GoogleCloudPlatform/python-docs-samples

- .travis.yml
- README.md
- bigquery/test/base_test.py
- resources/constants.json
- tox.ini
> Added GCLOUD_* and TEST_* envvar to passenv section.

- storage/README.md
- storage/compose_objects.py
- storage/list_objects.py
- storage/requirements.txt
- storage/tests/test_list_objects.py
- tests/__init__.py
* Added test for list_objects sample.
> Merging in storage samples.

- tox.ini
This also has the bonus of making the pep8 environment more lightweight.
> Slightly more readable tox.ini

- .coveragerc
- README.md
- bigquery/samples/utils.py
- bigquery/tests/test_async_query.py
- datastore/ndb/modeling/tests/test_structured_property_models.py
- discoverydoccaching/discovery_doc.py
- tests/__init__.py
> Fixing coverage, fixing pep8 issues

- bigquery/samples/export_data_to_cloud_storage.py
- bigquery/samples/load_data_by_post.py
- bigquery/samples/load_data_from_csv.py
- bigquery/samples/utils.py
> Added doc strings to functions with ambiguous args

- bigquery/samples/export_data_to_cloud_storage.py
- bigquery/tests/test_export_data_to_cloud_storage.py
> Added export format option

- bigquery/samples/appengine_auth/README.md
- bigquery/samples/appengine_auth/app.yaml
- bigquery/samples/appengine_auth/appengine_config.py
- bigquery/samples/appengine_auth/client_secrets.json
- bigquery/samples/appengine_auth/main.py
- bigquery/samples/appengine_auth/requirements.txt
- bigquery/tests/resources/datasets-list.json
- bigquery/tests/test_appengine_auth.py
Also, update it to use webapp2.
> Move bigquery 3lo sample on GAE to github.

- bigquery/samples/list_datasets_projects.py
- bigquery/tests/test_list_datasets_projects.py
The one used here:
https://cloud.google.com/bigquery/docs/managing_jobs_datasets_projects
> Add quick start sample.

- .coveragerc
- .gitignore
- tox.ini
@elibixby this fixes coverage and tests runs now that gae and py27 are separate environments.
> Fixing coverage

- README.md
> Updating readme with better testing instructions

- compute/autoscaler/demo/frontend.py
- compute/autoscaler/demo/tests/test_frontend.py
This application is a very simple web server, which responds to get requests by consuming some CPU cycles to demonstrate how Autoscaler can scale web frontends based on CPU utilization.
It is part of a tutorial video we've recently recorded. Link to the video will follow.
> Compute Autoscaler demo

- storage/list_objects.py
Also add comments for more explanation of what's going on with the service
construction.
> Add annotation for just the list_bucket part

- .gitignore
- README.md
- bigquery/samples/async_query.py
- bigquery/samples/export_data_to_cloud_storage.py
- bigquery/samples/list_datasets_projects.py
- bigquery/samples/load_data_by_post.py
- bigquery/samples/load_data_from_csv.py
- bigquery/samples/streaming.py
- bigquery/samples/sync_query.py
- bigquery/tests/test_async_query.py
- compute/autoscaler/demo/frontend.py
- monitoring/samples/auth.py
- storage/compose_objects.py
- storage/list_objects.py
- tests/__init__.py
- tests/utils.py
- tox.ini
> Enabling tests for python 3, fixing all python 3 incompatibilities.

- bigquery/samples/getting_started.py
- bigquery/samples/list_datasets_projects.py
- bigquery/tests/test_getting_started.py
This sample queries the shakespeare dataset via bigquery.
> Move bigquery 'getting started' sample into github.

- CONTRIBUTING.md
- README.md
> Moved Testing section to CONTRIBUTING.

- appengine/datastore_namespaces/README.md
- appengine/datastore_namespaces/app.yaml
- appengine/datastore_namespaces/appengine_config.py
- appengine/datastore_namespaces/guestbook.py
- appengine/datastore_namespaces/index.html
- appengine/datastore_namespaces/index.yaml
- appengine/datastore_namespaces/stylesheets/main.css
[this one](https://github.com/GoogleCloudPlatform/appengine-guestbook-namespaces-python)
> Move sample from appengine-guestbook-namespaces-python

- .travis.yml
> Making travis only test master branch to reduce thrashing.

- bigquery/api/load_data_by_post.py
Should fix #126, kind of incidentally.
> Update sample to use native sdk functionality.

- bigquery/api/load_data_by_post.py
> Specify source format, so json uploads work.

- bigquery/api/export_data_to_cloud_storage.py
Makes all the difference in downloading :)
> Allow gzip exported bigquery CSV with -z flag

- appengine/bigquery/README.md
- appengine/blobstore/README.md
- appengine/images/README.md
- appengine/localtesting/README.md
- appengine/memcache/guestbook/README.md
- appengine/multitenancy/README.md
- appengine/ndb/overview/README.md
- appengine/ndb/transactions/README.md
- bigquery/api/README.md
- compute/api/README.md
- monitoring/api/README.md
- scripts/README.md
- scripts/auto_link_to_docs.py
- scripts/docs-links.json
- storage/api/README.md
- storage/transfer_service/README.md
@waprin not quite ready to merge, but wanted to get your thoughts on this.
> Adding auto doc links for READMEs.

- appengine/logging/reading_logs/app.yaml
- appengine/logging/reading_logs/main.py
- appengine/logging/reading_logs/main_test.py
- appengine/logging/writing_logs/app.yaml
- appengine/logging/writing_logs/main.py
- appengine/logging/writing_logs/main_test.py
- managed_vms/hello_world_custom/requirements.txt
- tests/utils.py
> Moving logging example.

- bigquery/api/load_data_from_csv.py
Changing pydoc argument from `source_csv` to `source_path` to align with the argument name.
> Small discrepancy between argument and pydoc

- managed_vms/cloudsql/main.py
- managed_vms/datastore/main.py
> Using only the first 2 octets of IP addresses.

- blog/introduction_to_data_models_in_cloud_datastore/blog_test.py
- blog/introduction_to_data_models_in_cloud_datastore/wiki_test.py
- datastore/api/README.md
- datastore/api/index.yaml
- datastore/api/snippets.py
- datastore/api/snippets_test.py
- datastore/api/tasks.py
- datastore/api/tasks_test.py
- requirements-dev.txt
- tox.ini
@waprin this is missing tests, but ready for initial review. I will add tests. It's just a ton to write. :|
@pcostell Please verify that all of the relevant snippets are here. These are based on the node.js snippets, not the ndb ones.
@dhermes if you have a chance, please take a quick look and make sure I'm not using `gcloud-python` like a moron.
> Adding datastore samples.

- datastore/api/snippets_test.py
- datastore/api/tasks_test.py
- tests/__init__.py
- tests/utils.py
- tox.ini
@waprin PTAL, there's some stuff in here I'm not proud of.
> Trying to improve datastore flaky tests.

- bigquery/api/sync_query.py
> BQ: Empty array when no results

- managed_vms/kinto/Dockerfile
- managed_vms/kinto/README.md
- managed_vms/kinto/app.yaml
- managed_vms/kinto/requirements.txt
This is the basic Kinto setup, it's using a memory backend rather than it's preferred backend (Postgres, Redis) so I'll look into that next.
> Basic Kinto Example

- tox.ini
This is to fix travis in the interim between and and when we merge #185.
> Removing reqcheck from travis tests

- conftest.py
- storage/api/compose_objects_test.py
- storage/api/list_objects_test.py
- testing/cloud.py
@jerjou - there was also a slight refactor to the resource thingy in `cloud.py`. Once this repository stabilizes, I'll like move a lot of this over to `gcp-python-repo-tools`.
> Moving storage samples to py.test

- monitoring/api/auth_test.py
> Moving monitoring samples to py.test

- compute/api/create_instance_test.py
- compute/autoscaler/demo/frontend.py
- compute/autoscaler/demo/frontend_test.py
- tox.ini
> Moving compute engine samples to py.test

- bigquery/api/async_query_test.py
- bigquery/api/export_data_to_cloud_storage_test.py
- bigquery/api/getting_started_test.py
- bigquery/api/list_datasets_projects_test.py
- bigquery/api/load_data_by_post_test.py
- bigquery/api/load_data_from_csv_test.py
- bigquery/api/streaming_test.py
- bigquery/api/sync_query_test.py
> Moving bigquery samples to py.test

- .gitignore
- bigquery/api/installed_app.py
- bigquery/api/installed_app_test.py
Needed for this page: https://cloud.google.com/bigquery/authentication
Fixes google/oauth2client#435.
> Adding bigquery installed app auth sample.

- compute/api/startup-script.sh
We are deprecating the use of the X-Google-Metadata-Request header in favor
of the latest header, Metadata-Flavor.
The transition is explained here:
https://cloud.google.com/compute/docs/metadata#transitioning
> Deprecate X-Google-Metadata-Request in favor new Metadata-Flavor header

- monitoring/api/labeled_custom_metric.py
Fixed up reading the sample python code for reading a custom labeled timeseries.
> Fix copy/paste error for reading timeseries

- cloud_logging/api/list_logs.py
Script was throwing "KeyError: 'logs'" when the project does not have any logs.
> Fix KeyError exception when project has no logs

- cloud_logging/api/list_logs.py
- container_engine/django_tutorial/mysite/urls.py
- managed_vms/django_cloudsql/mysite/urls.py
Managed VMs tutorial should serve the polls app from the index.
Container Engine url should also have a dollar sign (not technically necessary but good for consistency).
> Fix up Django URLs

- datastore/api/tasks.py
In https://cloud.google.com/datastore/docs/datastore-api-tutorial#storing_data, `build_service` block starts with `import gcloud` so calling create_client() throws an error that `datastore` is undefined.
> Typo fix in samples/datastore/api/tasks.py

- storage/api/crud_object.py
- storage/api/crud_object_test.py
> Add sample for CRUD on GCS.

- container_engine/django_tutorial/mysite/urls.py
- container_engine/django_tutorial/polls/urls.py
- managed_vms/django_cloudsql/mysite/urls.py
Sorry, last PR for this wasn't quite this right, this should be right.
> Get rid of Django URL warnings

- monitoring/api/v3/list_resources.py
All the filters should be metric.type (API
change, name is now the fully qualified
REST resource).
> Fix metric.name

- monitoring/api/v3/README.md
Just a README change so I think we should merge.
This recommends the new gcloud ADC command.
> Monitoring Doc Fixups

- monitoring/api/v3/custom_metric.py
- monitoring/api/v3/custom_metric_test.py
- monitoring/api/v3/list_resources_test.py
Now use main integration test project because it can be whitelisted.
Fix all variables names of metric name to metric type. 
Even though I was experimenting with flaky, the custom metric tests now seem less flaky so I think for now we can run them as default.
> Use Main Project (now whitelisted)

- datastore/api/snippets.py
Replace `priority` with `percent_complete` in `projection_query` example.
> Fix property name in projection_query

- appengine/app_identity/asserting/app.yaml
- appengine/app_identity/asserting/main.py
- appengine/app_identity/asserting/main_test.py
- appengine/app_identity/incoming/app.yaml
- appengine/app_identity/incoming/main.py
- appengine/app_identity/incoming/main_test.py
- appengine/app_identity/signing/main.py
> Adding additional app identity samples.

- appengine/ndb/modeling/README.md
> Fix minor typo: appengine/ndb/modeling/README.md

- speech/api/speech_streaming_test.py
speech api is apparently variable in its response time.
> Comment out speech api test

- compute/metadata/main.py
- compute/metadata/main_test.py
We need to include "wait_for_change" in order to perform a hanging get. In
addition, we should deal with possible errors (like too many hanging gets).
Finally, this change allows for any of the maintenance event supported by
the metadata server.
> Update compute metadata hanging get example to use "wait_for_change".

- datastore/api/snippets.py
* Using Query.key_filter(), fixes #198
* Using Query.distinct_on instead of group_by.
> Updating datastore snippets

- compute/encryption/generate_wrapped_rsa_key_test.py
> Adding test for customer-supplied disk encryption key. Fixes #281

- dns/api/main.py
> Updating DNS samples to use newer gcloud features.

- nox.py
Travis is dying after a PR merge - I believe because TRAVIS_COMMIT_RANGE is empty after a merge. This is my guess as to how to fix it - feel free to educate me if there's a way to test this out..
> TRAVIS_COMMIT_RANGE isn't set on non-PRs

- managed_vms/twilio/main.py
- managed_vms/twilio/main_test.py
> Adding tests for the twilio sample. Fixes #183

- TESTING.md
- scripts/prepare-testing-project.sh
Adds missing sections to script and environment variables needed when running `nox -s tests` on a new project.
> Add missing instructions for test project setup.

- appengine/standard/ndb/entities/snippets.py
- appengine/standard/ndb/entities/snippets_test.py
Models are the class, entities are the datastore
instantiations of this class, so this change
is more conceptually accurate.
> Rename model usage to entity

- cloud_logging/README.md
- logging/api/export_logs_api.py
- logging/api/logs_api.py
1) Bug fix, wasn’t passing in token to pagination
2) Rearrange region tags to include more
3) Have v1 samples recommend v2 samples
> Logging Fixups

- bigtable/hello/main.py
- bigtable/hello/main_test.py
Also, change the sample to use sequential keys (with a disclaimer) to
match the Java sample. I had forgotten to add a sample usage to get a
specific row, so add that, too.
> Add region tags to bigtable/hello sample.

- appengine/standard/ndb/queries/snippets.py
- appengine/standard/ndb/queries/snippets_test.py
Maybe a flake8 upgrade? Either way it’s 
suddenly unhappy
> Use Explicit Imports

- bigtable/hello/main.py
I noticed that the `bigtable/hello` sample was not quitting when I sent
a `Ctrl-C` this should fix that problem.
> Close HappyBase connection in bigtable/hello sample.

- nox.py
These samples are being excluded from the plain `tests` target, since
they require the gRPC libraries (which are not compatible with Python
3, yet). This means they are not running on Jenkins or Travis.
By adding another session, we will be able to run the tests for these
samples on Jenkins.
> Add session for gRPC samples.

- bigtable/hello/README.md
- bigtable/hello/main.py
- bigtable/hello/main_test.py
- bigtable/hello/requirements.txt
- bigtable/hello_happybase/README.md
- bigtable/hello_happybase/main.py
- bigtable/hello_happybase/main_test.py
- bigtable/hello_happybase/requirements.txt
- conftest.py
- scripts/prepare-testing-project.sh
- scripts/resources/docs-links.json
Table of Contents generated with:
doctoc --title '**Table of Contents**' bigtable
Needs to wait for next gcloud-python launch so that https://github.com/GoogleCloudPlatform/gcloud-python/pull/1932 can go in. Tested locally on the bigtable-v2 branch of gcloud-python with a
previous version of grpcio.
> Update Bigtable samples to v2.

- storage/gcloud/customer_supplied_keys.py
- storage/gcloud/customer_supplied_keys_test.py
Simple upload and download samples using python gcloud.
> Add google cloud storage samples using gcloud.

- speech/api/requirements-speech_grpc.txt
- speech/api/speech_gcs.py
- speech/api/speech_gcs_test.py
- speech/api/speech_rest.py
- speech/api/speech_streaming.py
This is adapted from alpha samples in speech/api.
> Changing cloud speech code samples to work with v1beta1

- appengine/flexible/README.md
- appengine/flexible/django_cloudsql/README.md
- appengine/flexible/endpoints/README.md
- appengine/flexible/extending_runtime_compat/README.md
- appengine/flexible/hello_world_compat/README.md
- scripts/prepare-testing-project.sh
> Updating all references to gcloud preview app to gcloud app

- speech/api/README.md
> Virtual env inst

- appengine/flexible/endpoints/README.md
Endpoints applications require use of "gcloud beta app deploy" to be deployed correctly.
> Use gcloud beta app deploy for Endpoints

- appengine/standard/memcache/guestbook/main.py
- speech/api/speech_async_grpc.py
- speech/api/speech_async_rest.py
- speech/api/speech_grpc.py
- speech/api/speech_rest.py
- speech/api/speech_streaming.py
- vision/api/face_detection/faces.py
- vision/api/face_detection/faces_test.py
Some folks were tripping up on this.
Addresses #424
> Add comments for config options.

- appengine/flexible/endpoints/README.md
- appengine/flexible/endpoints/clients/service_to_service_gae_default/app.yaml
- appengine/flexible/endpoints/clients/service_to_service_gae_default/main.py
- appengine/flexible/endpoints/clients/service_to_service_google_id_token/app.yaml
- appengine/flexible/endpoints/clients/service_to_service_google_id_token/main.py
- appengine/flexible/endpoints/clients/service_to_service_non_default/app.yaml
- appengine/flexible/endpoints/clients/service_to_service_non_default/appengine_config.py
- appengine/flexible/endpoints/clients/service_to_service_non_default/main.py
- appengine/flexible/endpoints/requirements.txt
- appengine/flexible/endpoints/swagger.yaml
Added three samples:
1. Use App Engine default service account client (without key file).
2. Use non-default service account client (without key file).
3. Use Google ID token client (without key file)
> Auth samples for Endpoints.

- appengine/standard/localtesting/runner.py
Fixes discovery pattern
Adds some more import path hacks
> Fix local unit test sample

- appengine/standard/endpoints-v1.1/backend/app.yaml
- appengine/standard/endpoints-v1.1/backend/appengine_config.py
- appengine/standard/endpoints-v1.1/backend/echo-v1_swagger.json
- appengine/standard/endpoints-v1.1/backend/main.py
- appengine/standard/endpoints-v1.1/backend/main_test.py
Uses the Endpoints 1.1 Python client with configuration options for
service management and service control.
> Add Endpoints 1.1 sample

- bigquery/api/async_query.py
- bigquery/api/async_query_test.py
- bigquery/api/sync_query.py
- bigquery/api/sync_query_test.py
The useLegacySQL parameter must be explicitly set in order to use
standard SQL syntax. This adds usage of that parameter to the query
samples.
I plan to also include this code in the table at
https://cloud.google.com/bigquery/sql-reference/enabling-standard-sql
> Document usage of useLegacySQL parameter in BigQuery samples.

- datastore/api/index.yaml
- datastore/api/snippets.py
Uses 'category' instead of 'type' as a property name.
'type' could cause confusion with data types.
> Changes property name

- appengine/flexible/django_cloudsql/README.md
Some suggestions to reflect the requirements described [here](https://cloud.google.com/sql/docs/app-engine-connect#gaev2-csqlv2) but not referenced.
> edits to flexible django_cloud sql README

- CONTRIBUTING.md
Rather than use https://github.com/GoogleCloudPlatform/Template/wiki/style.html I want to have that page link to the appropriate repos.
> Add style guide information to CONTRIBUTING.md.

- storage/cloud-client/acl.py
- storage/cloud-client/acl_test.py
> Add storage acl samples

- appengine/flexible/endpoints/README.md
* Use three back-ticks to indicate code block (It seems indentation-based code block doesn't work if it's right after a list)
* Fix IAM link
* Avoid surrounding project id placeholders with angle brackets
> Fix various issuers in appengine/flexible/endpoints/README.md

- speech/grpc/transcribe_streaming.py
> Continuously transcribe in streaming.

- speech/grpc/transcribe.py
- speech/grpc/transcribe_async.py
The `--sample_rate` argument in `speech/grpc/transcribe.py` and `speech/grpc/transcribe_async.py` did not specify a type, which meant the value would be treated as a string, resulting in an exception during protobuf conversion:
```bash
$ python transcribe.py --encoding FLAC --sample_rate 16000 gs://path/to/my.flac
Traceback (most recent call last):
File "transcribe.py", line 95, in <module>
main(args.input_uri, args.encoding, args.sample_rate)
File "transcribe.py", line 66, in main
language_code='en-US',  # a BCP-47 language tag
File "/Users/zackse/code/python/contrib/python-docs-samples/speech/api-client/env/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 535, in init
_ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
File …
```
> grpc samples: specify type on --sample_rate to prevent TypeError

- speech/grpc/requirements.txt
- speech/grpc/transcribe_streaming.py
- speech/grpc/transcribe_streaming_test.py
This is to avoid timing issues where the request thread doesn't poll the
generator fast enough to consume all the incoming audio data from the input
device. In that case, the audio device buffer overflows, leading to lost data
and exceptions and other nastiness.
Address #515
> Speech api: Fill audio buffer in a separate thread.

- bigquery/api/async_query.py
- bigquery/api/async_query_test.py
- bigquery/api/sync_query.py
- bigquery/api/sync_query_test.py
The parameter is useLegacySql not useLegacySQL. See:
https://code.google.com/p/google-bigquery/issues/detail?id=701
I also update the tests to use a query that only works with standard SQL
for those tests.
> Typo in BQ Standard SQL samples.

- appengine/standard/endpoints-frameworks-v2/echo/README.md
Local running does not yet work with dev_appserver.py. Removing those instructions from the README.
> Remove local deployment from README

- appengine/flexible/endpoints/README.md
Since index.html has been removed, going to / is no longer a valid step.
Instead, the user should jump straight to calling the echo method.
> Remove mention of going to / for the Endpoints sample.

- .coveragerc
- translate/cloud-client/README.md
- translate/cloud-client/snippets.py
- translate/cloud-client/snippets_test.py
**NOTE**: This has #569 as a diffbase, please only review the latest commit.
> Translate samples

- appengine/flexible/endpoints/main.py
Currently the value of the "X-Endpoint-API-UserInfo" header does not
contain paddings. This causes incorrect padding error when doing
base64.b64decode(). This commit fixes the behavior by manually adding
paddings when necessary.
> Manually add required padding before base64.b64decode.

- speech/api-client/transcribe.py
- speech/api-client/transcribe_async.py
Print entire response, since may not have result.
> Update stale shortlink.

- speech/grpc/transcribe.py
- speech/grpc/transcribe_async.py
Printing out the grpc-generated objects results in `str`s with escape sequences
for unicode results, instead of the unicode characters themselves.
> Print out transcripts directly.

- appengine/standard/localtesting/env_vars_test.py
- appengine/standard/localtesting/login_test.py
- appengine/standard/localtesting/task_queue_test.py
While inside a class that inherits from unittest.TestCase it makes sense to use provided by TestCase assertion methods instead of pure Python's assertion()
> Use unittest.TestCase assertions

- compute/xmpp_wikibot/README.md
> Fix invocation for xmpp in README

- endpoints/getting-started/container-engine.yaml
> Update endpoints gke config to not use secrets.

- speech/grpc/transcribe_streaming.py
> streaming code used to hang when it was asked to "exit" - fixed now

- speech/grpc/transcribe_streaming.py
- speech/grpc/transcribe_streaming_test.py
I discovered, while reviewing #635, that pyaudio has an async api.
This lets us avoid spinning up our own thread, and saves some LOC.
Also - since the callback thread will automatically be closed by pyaudio when the stream is closed, we don't have to check `stopaudio` in it any longer, which saves us a control object being passed around.
Tested in OSX and linux.
> Use pyaudio's built-in async api.

- language/api/analyze.py
- language/movie_nl/main.py
> fixed discovery build by removing http

- translate/cloud-client/quickstart.py
- translate/cloud-client/snippets.py
@jonparrott Please review. Current sample breaks if someone uses the sample and project not WL. Fixed so that it works for non-WL folks. @sgreenberg
> added with and without model separate functions

- endpoints/getting-started/Dockerfile.custom
- endpoints/getting-started/container-engine.yaml
Need to switch ports for GKE config to match other languages.
`gcr.io/google-samples/echo-python:1.0` is updated.
> Update Endpoints sample container ports.

- translate/cloud-client/quickstart.py
- translate/cloud-client/quickstart_test.py
- translate/cloud-client/snippets.py
- translate/cloud-client/snippets_test.py
See 
- GoogleCloudPlatform/php-docs-samples#248
- GoogleCloudPlatform/ruby-docs-samples#113
> Translate API no longer requires an API key.

- vision/api/label/snippets.py
- vision/api/label/snippets_test.py
@jonparrott @tswast Please review. Alpha 1.1 changes.
> Vision a11 - adding crop hints and web annotation

- appengine/flexible/cloudsql/app.yaml
We've moved away from concatenating project:region:instance and towards using the instance connection name, which is now available not only from the console but also from gcloud. I'm in the process of adding the text to go along with this change, but already the proxy invocation uses this so we're no worse off if we publish this change.
Thanks!
> Update app.yaml to use connection name

- endpoints/kubernetes/grpc-bookstore.yaml
This makes our Quickstarts consistent such that port 80 is used in both
examples on GCE and GKE.
> Change the listening port from 9000 to 80

- appengine/standard/endpoints-frameworks-v2/echo/main.py
echo_api_key was not implemented correctly (looks like a cut and paste bug).
I discover this when trying to follow the[ instructions  on how to implement cloud endpoints on AppEngine standard](https://cloud.google.com/endpoints/docs/frameworks/python/quickstart-frameworks-python). and the following command failed:
`python lib/endpoints/endpointscfg.py get_swagger_spec main.EchoApi --hostname your-service.appspot.com`
with:
`endpoints.api_exceptions.ApiConfigurationError: POST path "echo" used multiple times, in classes EchoApi and EchoApi`
> fix echo_api_key

- bigquery/cloud-client/load_data_from_gcs.py
Adjusted error handling for BigQuery sample based on Googler feedback. Job.errors gives you the actual error(s), unlike job.error_result.
Bug #33164873
> Adjusted error handling based on Googler feedback

- bigquery/cloud-client/sync_query_params.py
- bigquery/cloud-client/sync_query_params_test.py
- bigquery/dml/requirements.txt
This query syntax is supported in the not-yet-released version of google-cloud-python in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2776.
I've added the do not merge label, since we should wait for the next google-cloud-python release, but the sample should be ready to review.
> BigQuery samples using query parameters.

- appengine/flexible/django_cloudsql/mysite/settings.py
Tweaked a few placeholder names for variables users should change before testing/deploying. The tutorial is now going to ask them to create a non-root username/password. Also updated environment variable that changed because of flex beta 2.
> Django_cloudsql config edits

- endpoints/bookstore-grpc/api_config.yaml
This simplifies our quickstart such that reader does not need to go
through an extra step to create an API key before calling this API.
> Allow ListShelves method to be called without API key

- storage/api/crud_object.py
> Compare files manually.

- appengine/standard/endpoints-frameworks-v2/echo/README.md
- appengine/standard/endpoints-frameworks-v2/echo/app.yaml
- appengine/standard/endpoints-frameworks-v2/quickstart/app.yaml
- endpoints/bookstore-grpc/api_config.yaml
- endpoints/getting-started/app.yaml
- endpoints/getting-started/openapi.yaml
1. Change default service names to the new cloud.goog format.
2. Change app.yaml beta_settings to endpoints_api_service.
> Update Endpoints samples:

- language/sentiment/requirements.txt
- language/sentiment/sentiment_analysis.py
- language/sentiment/sentiment_analysis_test.py
Blocked by GoogleCloudPlatform/google-cloud-python#2858
> Refactored the Sentiment Analysis tutorial to use the Cloud Client Lib

- speech/grpc/requirements.txt
- speech/grpc/transcribe.py
- speech/grpc/transcribe_async.py
- speech/grpc/transcribe_streaming.py
> Update speech grpc samples to use new auth and grpc interfaces

- endpoints/bookstore-grpc/api_config_auth.yaml
> Update grpc-blookstore sample api_config_auth.yaml

- language/tutorial/README.rst.in
- language/tutorial/requirements.txt
- language/tutorial/reviews/bladerunner-mixed.txt
- language/tutorial/reviews/bladerunner-neg.txt
- language/tutorial/reviews/bladerunner-neutral.txt
- language/tutorial/reviews/bladerunner-pos.txt
- language/tutorial/tutorial.py
- language/tutorial/tutorial_test.py
Adds code to back up documentation. Note that on my machine, there are issues with generating the documentation so that still should be added before merging.
> Adds snippets and tests for documentation tutorial.

- appengine/standard/memcache/guestbook/app.yaml
- appengine/standard/memcache/guestbook/main.py
See bug #33780149 on buganizer.
For some reason memcache.add throws an exception for objects larger than 1 MB rather than simpling returning False. Thus, I changed the sample code to use try/except around memcache.add, while preserving the check to see if memcache.add returned True or False. The boolean returned does seem to be necessary since it is False when memcache already has an entry for a given key.
Also got rid of 'version: 1' from the app.yaml so that 'gcloud app deploy' works.
> Updated memcache error checking to handle large object exception

- kms/api/quickstart.py
* Use camelCase when accessing the fields.
* Rename zone -> location, and fix an incorrect statement about how "global" works.
> A few fixes in the quickstart

- monitoring/api/v3/custom_metric.py
> Add region tags for writing time series

- appengine/flexible/endpoints/README.md
- appengine/standard/endpoints-frameworks-v2/echo/README.md
Updated the command gcloud beta app deploy to be gcloud app deploy, since the command is no longer in beta.
> Updated README.md

- endpoints/getting-started/openapi.yaml
Incorporate new prefix for x-issuer and x-jwks_uri flags. Stops gcloud throwing warnings when sample openapi.yaml is deployed.
> Update sample to avoid gcloud deprecation warnings

- speech/api-client/README.rst
- speech/api-client/transcribe.py
- speech/api-client/transcribe_async.py
- speech/cloud-client/README.rst
- speech/cloud-client/transcribe.py
Also fixes and fixes copy/paste error in cloud-client/transcribe.py usage.
> Adds usage examples to api-client samples

- speech/cloud-client/README.rst
- speech/cloud-client/transcribe.py
- speech/cloud-client/transcribe_async.py
- speech/cloud-client/transcribe_async_test.py
- speech/cloud-client/transcribe_test.py
Adds examples showing transcription from a GCS URI.
> Speech GCS

- appengine/standard/mailgun/main.py
I was getting the following issue: 
`RuntimeError: Mailgun API error: 400 b'{\n  "message": "\'from\' parameter is missing"\n}'`,
Providing custom header for `Content-Type` was the solution.
> Added headers manually to override error

- monitoring/api/v3/cloud-client/quickstart.py
- monitoring/api/v3/cloud-client/snippets.py
- monitoring/api/v3/cloud-client/snippets_test.py
Custom metric created doesn’t have a label.
> Fix monitoring tests

- endpoints/getting-started/openapi.yaml
We need to do this so that we can update https://cloud.google.com/endpoints/docs/restricting-api-access-with-api-keys-openapi to point to the endpoints/getting-started sample rather than the soon-to-be-deprecated appengine/flexible/endpoints sample.
> Added securityDef region tag to openapi.yaml for documentation purposes

- spanner/cloud-client/snippets.py
Fixing bug.
Documentation says we should only transfer if the second album budget has a minimum value of $300,000.
> Changed read_write_transaction minimum amount to 300,000

- vision/cloud-client/README.rst
- vision/cloud-client/README.rst.in
- vision/cloud-client/detect.py
- vision/cloud-client/detect_test.py
- vision/cloud-client/requirements.txt
Adds vision 1.1 features to the sample.
> Vision 1.1

- language/cloud-client/quickstart.py
- language/cloud-client/requirements.txt
- language/cloud-client/snippets.py
Updates for out of band release of language client library.
> Updates client library to version 0.23.0

- ml_engine/online_prediction/predict.py
- ml_engine/online_prediction/predict_test.py
* Rename tf_records -> examples everywhere, since TFRecords is technically a misnomer (or rather the name for the file container format for a number of tf.train.Example proto [or really any proto])
* Move both JSON and EXAMPLE tests to a new model, so that they share a common expected output
* Hopefully fix python 3 compat
> Fix ml_engine tests

- ml_engine/online_prediction/predict.py
Coerce string to bytes in py2-3 compat way
tf.Examples only have support for Bytes fields rather than pure string fields.
> Fix ML Engine Py 3 tests

- appengine/standard/flask/tutorial/appengine_config.py
- appengine/standard/flask/tutorial/main.py
Adding region tag so I can update the GAE Standard w/Flask tutorial to reference GitHub code
> Added a few region tags

- video/cloud-client/analyze.py
Operations count towards quota of 1qps, reduces frequency to avoid issues.
> Changes polling frequency

- spanner/cloud-client/snippets.py
> Update spanner sample to use bind parameters

- appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
google-endpoints 2.0.5 does not work with new version google-cloud-sdk
on mac, by upgrading to 2.0.6 fixes this sample.
> fix endpoint echo sample

- appengine/standard/ndb/overview/main.py
Make the response writing more readable by pulling the HTML into a format string.
> Refactor HTML response code

- endpoints/bookstore-grpc/jwt_token_gen.py
See title and [this](http://google-auth.readthedocs.io/en/latest/reference/google.auth.crypt.html#google.auth.crypt.Signer) docs page.
Note: I haven't tested the output of this script to see if the JWT is correct.
> 'Signer' is abstract, use 'RSASigner' instead.

- auth/api-client/snippets.py
- auth/api-client/snippets_test.py
- auth/cloud-client/snippets.py
- auth/cloud-client/snippets_test.py
Add samples for explicitly using compute and app engine credentials.
> Add more auth samples

- iap/iap_test.py
- iap/make_iap_request.py
Client ID is the preferred thing to use for the aud claim.
--msachs@, IAP TLM
> make_iap_request: Replace base URL with client ID

- speech/cloud-client/README.rst
- speech/cloud-client/README.rst.in
- speech/cloud-client/quickstart.py
- speech/cloud-client/requirements.txt
- speech/cloud-client/transcribe.py
- speech/cloud-client/transcribe_async.py
- speech/cloud-client/transcribe_streaming.py
- speech/cloud-client/transcribe_streaming_mic.py
Updating python code samples to use the GAPIC python client library for Speech API.
Merge only after the client library is released.
> Speech gapic client library

- dataproc/README.md
- dataproc/list_clusters.py
The `region` parameter is asked to the user but never used. This PR aims to properly forward the region argument to the other functions when this is provided and to set `global` as a default when it isn't provided. The `README` has been updated consequently to match with the required and optional arguments actually asked via `argparse`.
> Properly forwarding the "region" parameter provided as an input argument in list_cluster.py

- vision/cloud-client/crop_hints/README.rst
- vision/cloud-client/crop_hints/README.rst.in
- vision/cloud-client/crop_hints/crop_hints.py
- vision/cloud-client/crop_hints/requirements.txt
- vision/cloud-client/detect/README.rst
- vision/cloud-client/detect/README.rst.in
- vision/cloud-client/detect/detect.py
- vision/cloud-client/detect/detect_test.py
- vision/cloud-client/detect/requirements.txt
- vision/cloud-client/document_text/README.rst
- vision/cloud-client/document_text/README.rst.in
- vision/cloud-client/document_text/doctext.py
- vision/cloud-client/document_text/requirements.txt
- vision/cloud-client/face_detection/README.rst
- vision/cloud-client/face_detection/README.rst.in
- vision/cloud-client/face_detection/faces.py
- vision/cloud-client/face_detection/requirements.txt
- vision/cloud-client/quickstart/README.rst
- vision/cloud-client/quickstart/README.rst.in
- vision/cloud-client/quickstart/quickstart.py
- vision/cloud-client/quickstart/requirements.txt
- vision/cloud-client/web/README.rst
- vision/cloud-client/web/README.rst.in
- vision/cloud-client/web/requirements.txt
- vision/cloud-client/web/web_detect.py
Updating the sample codes to use the GAPIC client library.
Merge only after the client library has been released.
> Vision GAPIC client library

- speech/cloud-client/requirements.txt
- speech/cloud-client/transcribe_async.py
- speech/cloud-client/transcribe_async_test.py
This PR updated the async recognize example to show how to modify the recognition config so that the API response includes the additional information of word-level time offsets.
> add word time offsets to async sample

- bigquery/cloud-client/simple_app.py
- Original query returned a single nested row (instead of 10 rows as apparently expected in section print_results)
- Standard SQL specified directly in query
- Removed parameter max_results to avoid redundancy w/ query
> Fix SQL query to return 10 rows & simplify

- speech/cloud-client/transcribe_async.py
enable_word_time_offsets=True was present for an older version of this sample.
This sample no longer processes word time offsets in the recognize response.
> Remove old parameter enable_word_time_offsets

- dataproc/README.md
- dataproc/dataproc_e2e_test.py
- dataproc/submit_job_to_cluster.py
This PR is related to [PR#1029](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1029): forwarding the region `global` to all the possible operations (list clusters, create clusters,...) doesn't work anymore. Since the `zone` parameter is required, the region is inferred from the `zone` and properly forwarded to all the dependent functions. This change also adds the chance to use directly an existing cluster when the `--create_new_cluster` flag is missing. Given the option of using an existing cluster, the script `create_cluster_and_submit_job.py` has been renamed to `submit_job_to_cluster.py`.
> Fix region handling and allow to use an existing cluster.

- language/cloud-client/v1/snippets.py
- language/cloud-client/v1beta2/snippets.py
This PR updates the analyze entities samples to show the names of entity types (as opposed to just the enums).
before:
```
name            : Golden Gate Bridge
type            : 2
```
after:
```
name            : Golden Gate Bridge
type            : LOCATION
```
> show entity type name

- kms/api-client/snippets.py
The use of base64 is essentially an implementation detail of the Cloud KMS REST
API: it is required only so that arbitrary binary data can be included in a JSON
string, which only allows Unicode characters. Therefore, the "encrypt" sample
function should decode the base64-encoded ciphertext before writing the
file. Similarly, "decrypt" should not assume that an input file is
base64-encoded, but should perform the base64-encoding itself before sending the
encrypted data to KMS.
This aligns with how the "gcloud kms encrypt" and "gcloud kms decrypt" commands
behave. See https://stackoverflow.com/q/45699472 for an example of user
confusion caused by the mismatch.
> KMS: Clean up base64 logic in the encrypt and decrypt functions.

- appengine/flexible/mailjet/README.md
- appengine/flexible/mailjet/main.py
- appengine/standard/mailjet/main.py
Mailjet Send API v3.1 is being released, so updating the code samples to match the new Send API v3.1 configuration. Reference can be found [here](https://dev.mailjet.com/beta/).
Also readme.md edited to change references from Mailgun to Mailjet.
> updating Mailjet code samples for Send API v3.1

- kms/api-client/README.rst
- kms/api-client/snippets.py
- kms/api-client/snippets_test.py
In particular, this change:
- changes to use a consistent "_id" suffix for resource name components
- uses "data" instead of "text", since encryption is not restricted to text
- substitutes "ciphertext" for "encrypted {text, data}"
- cases "cryptoKey" and "keyRing" consistently with the API
Tracking bug: http://b/64758639
> KMS: Make the encrypt/decrypt samples consistent with the other languages

- endpoints/getting-started/clients/service_to_service_gae_default/main.py
It's been over a year now since they renamed this. We can move to use OpenAPI consistently.
> Change 'swagger' to OpenAPI

- appengine/standard/firebase/firenotes/frontend/index.html
I spent a lot of time messing with this example code, trying to disable account chooser. Finally I realized that `firebaseui.auth.CredentialHelper` was added later. This would have saved me a couple of hours and a lot of frustration.
> updates firebaseui version

- appengine/standard/bigquery/app.yaml
Removes the application and version fields from the app.yaml to make the project compatible with the newer preferred gcloud based tooling.
> Remove application and version from app.yaml

- iot/api-client/manager/manager.py
* Removes START / END blocks
* Separates create / get 
* Adds missing registry list / get methods.
> Changes for snippets

- language/cloud-client/v1/snippets.py
- language/cloud-client/v1/snippets_test.py
- language/cloud-client/v1beta2/resources/android_text.txt
- language/cloud-client/v1beta2/snippets.py
- language/cloud-client/v1beta2/snippets_test.py
Do not merge until the updated client library has been published and tested.
> Language classify

- video/cloud-client/analyze/README.rst
- video/cloud-client/analyze/analyze.py
- video/cloud-client/analyze/analyze_test.py
- video/cloud-client/analyze/requirements.txt
- video/cloud-client/faces/faces.py
- video/cloud-client/faces/faces_test.py
- video/cloud-client/faces/requirements.txt
- video/cloud-client/labels/labels.py
- video/cloud-client/labels/labels_test.py
- video/cloud-client/labels/requirements.txt
- video/cloud-client/quickstart/quickstart.py
- video/cloud-client/quickstart/quickstart_test.py
- video/cloud-client/quickstart/requirements.txt
- video/cloud-client/shotchange/requirements.txt
- video/cloud-client/shotchange/shotchange.py
- video/cloud-client/shotchange/shotchange_test.py
This PR updates the sample codes to support video intelligence v1beta2.
> Video v1beta2

- appengine/standard/endpoints-frameworks-v2/echo/README.md
- appengine/standard/endpoints-frameworks-v2/echo/app.yaml
Endpoints Frameworks apps on GAE standard must use the appspot.com domain name; users will have to change the line anyway, but this way fewer changes are required.
Reopened version of #1021
> Create better service name template in app.yaml

- appengine/flexible/tasks/create_app_engine_queue_task.py
- appengine/flexible/tasks/main.py
- tasks/pull_queue_snippets.py
- Now that the discovery doc is published, remove discoveryServiceUrl from the client constructor.
- Move imports of the discovery command into the functions in preparation for adding region tags.
- Use flask's get_data() getter to process the payload bytes into unicode.
- Switch to using a print statement instead of logging.warn to avoid confusion over the term "warning".
- Update the JSON keys to reflect the newest version of the API.
> Update Task Queue samples for beta

- iot/api-client/http_example/README.md
- iot/api-client/http_example/cloudiot_http_example.py
- iot/api-client/http_example/requirements.txt
- iot/api-client/manager/manager.py
- iot/api-client/manager/manager_test.py
- iot/api-client/mqtt_example/README.md
- iot/api-client/mqtt_example/cloudiot_mqtt_example.py
Holding PR for private beta additions
> Final additions in private beta

- iot/api-client/mqtt_example/cloudiot_mqtt_example.py
Fixes [this issue](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1141).
> Add type to port argument

- appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
Given that users may go on to make real apps from this sample, we should keep to the latest known-good versions.
> Require latest Endpoints Framework version

- video/cloud-client/faces/faces.py
- video/cloud-client/faces/faces_test.py
- video/cloud-client/labels/labels.py
- video/cloud-client/labels/labels_test.py
- video/cloud-client/quickstart/quickstart.py
- video/cloud-client/shotchange/shotchange.py
I noticed the faces.py example had a copy/paste doc string form the shotchanges.py example. That lead to correcting/tweaking the other doc/help strings for the other python examples.
> Tweak doc/help strings for sample tools 

- iot/api-client/mqtt_example/cloudiot_mqtt_example.py
* Remove required flag from --message_type flag
* Add 443 port as option for --mqtt_bridge_port flag
> Changes to running the Python MQTT example

- appengine/standard/endpoints-frameworks-v2/echo/app.yaml
When people following this doc [1], they will run into this error because of the extra square bracket in the app.yaml file.
```sh
python lib/endpoints/endpointscfg.py get_openapi_spec main.EchoApi --hostname xxx.appspot.com
```
```sh
No handlers could be found for logger "oauth2client.contrib.multistore_file"
Traceback (most recent call last):
File "lib/endpoints/endpointscfg.py", line 633, in <module>
main(sys.argv)
File "lib/endpoints/endpointscfg.py", line 629, in main
args.callback(args)
File "lib/endpoints/endpointscfg.py", line 487, in _GenOpenApiSpecCallback
application_path=args.application)
File "lib/endpoints/endpointscfg.py", line 332, in _GenOpenApiSpec
runtime: python27
application_path=application_path)
File "lib/endpoints/endpointscfg.py", line 200, in GenApiConfig …
```
> The square bracket in app.yaml upsets the YAML parser

- appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
google-endpoints 2.4.1 contained a bug which made it impossible to complete the tutorial. We want everyone to be using 2.4.2 as soon as possible.
> Update requirements.txt due to broken dependency

- appengine/standard/endpoints-frameworks-v2/echo/README.md
- appengine/standard/endpoints-frameworks-v2/echo/app.yaml
- appengine/standard/endpoints-frameworks-v2/quickstart/app.yaml
- codelabs/flex_and_vision/README.md
- endpoints/getting-started-grpc/README.md
- endpoints/getting-started/app.yaml
@inklesspen 
- `gcloud service-management deploy` becomes `gcloud endpoints deploy`
- `gcloud service-management enable` becomes `gcloud services enable`
- `gcloud service-management configs` becomes `gcloud endpoints configs`
> Update deprecated commands for `gcloud service-management`

- spanner/cloud-client/snippets.py
- spanner/cloud-client/snippets_test.py
At the request of the spanner team.
> Bump spanner stale read from 10 to 15 seconds.

- language/cloud-client/v1/requirements.txt
- language/cloud-client/v1/snippets.py
- language/cloud-client/v1/snippets_test.py
copy classify_text samples and tests to v1
> Language v1

- language/classify_text/classify_text_tutorial.py
Update the tutorial to use v1 client.  Sample tests passed.
> update to use v1 client

- appengine/flexible/tasks/README.md
Queue routing override is not recommended for simple use cases, it's an advanced option.
> Remove instructions regarding queue routing override

- appengine/flexible/hello_world/app.yaml
A few people have found painfully if they left the sample running with the default settings they incurred an unexpected charge. This keeps costs low for those kicking the tires on App Engine.
> Keeping user's costs low when using the hello world

- video/cloud-client/analyze/analyze.py
Protobuf handles the base64 encoding for you, and so the content was being base64 encoded twice.
> Do not base64 encode the input content.

- video/cloud-client/analyze/analyze.py
The client library was updated to make the `input_uri` optional.
> remove empty input_uri

- bigquery/cloud-client/auth_snippets.py
I'm also updating the links at https://cloud.google.com/bigquery/docs/authentication/service-account-file#bigquery-authentication-service-account-file-python
> Fix broken link to core Client service account helper.

- iot/api-client/end_to_end_example/cloudiot_pubsub_example_server_test.py
Also add a bit more output in the check for the test_config_turn_off test to make it consistent with the test_config_turn_on output check.
> Temperature data load should be a bytes object, not str.

- appengine/standard/flask/tutorial/requirements.txt
The latest version of Werkzeug (0.13) released on December 7th raises an ImportError when Flask is imported on app engine.
```ImportError: cannot import name SpooledTemporaryFile```
App engine standard does not support SpooledTemporaryFile, so we should explicitly instruct users to install Werkzeug==0.12.2 (last working version).
> Latest version of Werkzeug raises ImportError

- bigquery/cloud-client/requirements.txt
- bigquery/cloud-client/simple_app.py
- bigquery/cloud-client/simple_app_test.py
- Add region tags for needed dependencies.
- Use more relevant query from public datasets.
> BigQuery: rewrite simple app tutorial.

- bigquery/transfer/cloud-client/quickstart.py
- bigquery/transfer/cloud-client/quickstart_test.py
- bigquery/transfer/cloud-client/requirements.txt
- scripts/prepare-testing-project.sh
Client library docs:
https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery_datatransfer/index.html
> BigQuery: Add Data Transfer Service quickstart.

- pubsub/cloud-client/subscriber.py
Current code [1] will make subscription.open get called twice:
1- https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/subscriber/client.py
2- https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/pubsub/cloud-client/subscriber.py
[1] https://cloud.google.com/pubsub/docs/pull#listening-for-errors
To fix this, it should use subscription.future instead of calling open()...
> Fix subscription.open get called twice in the client libraries

- iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py
The API version should be v1, not v1beta1. Also remove the unnecessary 'data' field from the body and just use 'binary_data'.
> Update API version and body.

- appengine/flexible/django_cloudsql/mysite/settings.py
- appengine/flexible/hello_world_django/project_name/settings.py
MIDDLEWARE_CLASSES are removed in Django 2.0.
> Fixed settings.py incompatible with Django 2.0

- appengine/standard/endpoints-frameworks-v2/echo/README.md
Sample URLs were replaced with correct ones, the sample filename is
corrected, and some terminology is also corrected (Swagger is now
OpenAPI).
> Corrections to Endpoints Frameworks echo README

- pubsub/cloud-client/subscriber.py
Using ack_deadline_seconds as the example. Tests coming in next PR.
> Add sample for updating a subscription.

- endpoints/bookstore-grpc/Dockerfile
- endpoints/bookstore-grpc/status.py
Adds the `-p python3.5` flag to virtualenv creation step, as currently the flag is being added to an env var (a typo I believe) and the python binary ends up being `python 2.7`. 
Fixes a bad import in status context manager.
> Fixes python version flag & bad import in context manager

- iot/api-client/end_to_end_example/cloudiot_pubsub_example_mqtt_device.py
Env: Python 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
cloudiot_pubsub_example_mqtt_device.py.py in iot end_to_end_example contains wrong str casting.
json.loads takes byte parameter, so you don't have to cast for using it.
If you really want to convert byte to string, it should be 
```python3
payload = message.payload.decode()
```
current version produces an error
`
File "cloudiot_pubsub_example_mqtt_device.py", line 136, in on_message
data = json.loads(payload)
File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
return _default_decoder.decode(s)
File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/ …
> fix message.payload str casting.

- iot/api-client/http_example/cloudiot_http_example.py
- iot/api-client/manager/manager.py
- iot/api-client/mqtt_example/cloudiot_mqtt_example.py
Related:
* GoogleCloudPlatform/dotnet-docs-samples#451
* GoogleCloudPlatform/ruby-docs-samples#243
* GoogleCloudPlatform/java-docs-samples#1041
> Cleanup Cloud IoT region tags.

- spanner/cloud-client/snippets.py
Related:
* ~~googleapis/nodejs-spanner#136~~ merged
* GoogleCloudPlatform/ruby-docs-samples#244
* ~~GoogleCloudPlatform/java-docs-samples#1045~~ merged
* GoogleCloudPlatform/dotnet-docs-samples#454
* GoogleCloudPlatform/php-docs-samples#562
* GoogleCloudPlatform/golang-samples#403
> Add Spanner region tags.

- endpoints/getting-started/openapi.yaml
From the OpenAPI 2 spec:
* basePath: "If it is not included, the API is served directly under the host. The value MUST start with a leading slash (/). "
* Paths for methods: "A relative path to an individual endpoint. The field name MUST begin with a slash. The path is appended to the basePath in order to construct the full URL."
This OpenAPI getting-started sample have basePath="/", which (per strict spec interpretation) means all the paths start with double-slashes. (e.g "//v1/shelves" rather than "/v1/shelves"). Removing basepath="/" fixes that.
> Removing basePath = "\" from openApi spec file

- AUTHORING_GUIDE.md
Add requirements for python interpreters, including an example command to install with apt-get.
> Add interpreter requirements to Authoring Guide

- dlp/quickstart.py
- dlp/quickstart_test.py
Likelihood, in the findings protobuf, is stored as a number. This converts the likelihood score to the string representation, ie likely, very likely, unlikely... Tests have also been updated for new info types.
> updated Quickstart terminal print out and tests

- video/cloud-client/analyze/beta_snippets.py
- video/cloud-client/analyze/beta_snippets_test.py
- video/cloud-client/analyze/requirements.txt
This PR adds samples for the following beta features: 
- face bounding boxes
- face emotions
- speech transcription
> Face detection beta features

- vision/cloud-client/detect/detect.py
the strings to be formatted were missing the place holders.
> vision API: fix landmark sample

- endpoints/getting-started-grpc/README.md
- endpoints/getting-started-grpc/deployment.yaml
- endpoints/getting-started/app.yaml
- endpoints/getting-started/deployment.yaml
- endpoints/kubernetes/grpc-bookstore.yaml
We introduce a new feature where we can specify in YAML that service configuration for Endpoints is going to be managed. This means that the service will pull latest deployed service configuration automatically, rather than requiring customer to specify specific version of service configuration.
New flag:
**--rollout_strategy=managed**
Previously the only way to specify a version was using the following flag:
**--version=SERVICE_CONFIG_ID**
> Change to endpoints managed rollout

- video/cloud-client/analyze/beta_snippets.py
- video/cloud-client/analyze/beta_snippets_test.py
remove beta samples with face detection features.
> [DO NOT MERGE] remove face detection samples

- iot/api-client/manager/manager.py
See the python snippet for https://cloud.google.com/iot/docs/samples/registry-management-samples#list_registries
> Fixes iot_list_registries closing region tag

- speech/cloud-client/transcribe.py
- speech/cloud-client/transcribe_async.py
- speech/cloud-client/transcribe_model_selection.py
- speech/cloud-client/transcribe_streaming.py
- speech/cloud-client/transcribe_word_time_offsets.py
sample currently gives ascii errors for non-english use cases in python 2.
did not change transcribe_streaming_mic.py.
> use unicode

- .gitignore
- datastore/cloud-client/snippets_test.py
When there are only 6 entities being retrieved, and the page size is 5,
then the second page will not have a next cursor because all entities
have been retrieved.
Also, ignore *sponge_log.xml which are test log files.
> Fix broken datastore test_cursor_paging.

- composer/workflows/requirements.txt
- composer/workflows/simple.py
- composer/workflows/simple_test.py
The `composer_simple` sample is intended to demonstrate the concepts of
constructing Apache Airflow DAGs rather than any specific set of
operators.
By using the 1.10beta instead of git for the dependency, we have a
stabler package than building on master. Also, this will be easier for
Travis to cache.
CC @wwlian (Adding this sample per your request in CL 194867947)
> Composer: add simple workflow example. Use 1.10beta instead of git.

- appengine/standard/endpoints-frameworks-v2/echo/main.py
Add missing annotation parameter to require API key.
@inklesspen @wmwong
> Fix AppEngine Endpoints example.

- bigquery/cloud-client/natality_tutorial.py
- bigquery/cloud-client/natality_tutorial_test.py
Adds BigQuery portion of [Dataproc tutorial](https://cloud.google.com/dataproc/docs/tutorials/bigquery-sparkml) to this repo so it can be regularly tested (previously hard coded in the docs).
> BigQuery: Moves BigQuery tutorial for Dataproc to python-docs-samples

- appengine/standard/firebase/firenotes/frontend/main.js
RE: https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine#adding_the_firebase_authentication_user_interface
This fails because the projectId and messagingSenderId are missing. I have also added snippet anchors to include snippet in the doc.
> Fixed Initialize Firebase section and add snippet

- composer/workflows/simple.py
Without a schedule this DAG gets scheduled way too often when I upload it to a Cloud Composer environment.
> Composer: Add schedule to simple workflow.

- datastore/cloud-client/snippets.py
- datastore/cloud-client/snippets_test.py
- datastore/cloud-client/tasks.py
These samples/region tags aren't used on cloud.google.com, so I'm deleting them.
Related:
- googleapis/nodejs-datastore#110
- GoogleCloudPlatform/java-docs-samples#1138
- GoogleCloudPlatform/php-docs-samples#631
- GoogleCloudPlatform/dotnet-docs-samples#569
- GoogleCloudPlatform/ruby-docs-samples#292
- GoogleCloudPlatform/golang-samples#516
> Delete unused Datastore region tags / samples.

- bigquery/cloud-client/authorized_view_tutorial.py
- bigquery/cloud-client/authorized_view_tutorial_test.py
- bigquery/cloud-client/requirements.txt
Python version of [authorized view tutorial](https://cloud.google.com/bigquery/docs/share-access-views)
I'm open to ideas on phrasing region tags. My intent was to have sections to match up with the tutorial, but also have a region tag that encompassed the whole thing so I could show it at the end of the tutorial.
> BigQuery: Adds authorized view tutorial

- .github/CODEOWNERS
Starting with just Tim's and my sections; others can add themselves as owners when desired.
> Adds code owners for bigquery, bigquery data transfer, and composer

- appengine/standard/endpoints-frameworks-v2/echo/main.py
- appengine/standard/endpoints-frameworks-v2/echo/main_test.py
- appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
- appengine/standard/endpoints-frameworks-v2/iata/main.py
- appengine/standard/endpoints-frameworks-v2/iata/requirements.txt
- appengine/standard/endpoints-frameworks-v2/quickstart/main.py
- appengine/standard/endpoints-frameworks-v2/quickstart/main_test.py
Instead of importing from `protorpc`, import from `endpoints`.
Additionally, I updated the requirements.txt files because dpebot stopped doing it for some reason.
> Change Endpoints Frameworks samples to import from endpoints

- appengine/standard/firebase/firenotes/frontend/main.js
- dlp/inspect_content.py
- dlp/inspect_content_test.py
- monitoring/api/v3/uptime-check-client/snippets.py
- monitoring/api/v3/uptime-check-client/snippets_test.py
The DLP team is in the process of expanding code samples to include features that we have launched since the initial samples were written.
In this pull request, I updated inspect_content.py to include dictionary and regex based custom info types, and added some tests in inspect_content_test.java. Also updated deid.py and deid_test.py to fix issues with the tests since launching the V2 API.
> Add DLP code samples for custom info types

- speech/cloud-client/README.rst
- speech/cloud-client/beta_snippets.py
- speech/cloud-client/beta_snippets_test.py
Implemented the multi channel sample
> Multi Channel

- appengine/flexible/tasks/requirements.txt
Require gunicorn since it is used in the entrypoint.
> require gunicorn for GAE flex Cloud Tasks example

- translate/automl/automl_translation_predict.py
- translate/automl/predict_test.py
> remove translate prediction fallback

- vision/cloud-client/web/web_detect_test.py
The original image no longer appears on cloud.google.com/vision
> Update vision web_detect test image

- language/automl/model_test.py
- translate/automl/model_test.py
- vision/automl/model_test.py
skipping tests for now as they may create multiple models.
> skip automl model create/delete test

- appengine/standard/endpoints-frameworks-v2/echo/main.py
Currently none of the Endpoints Frameworks docs are using the "echo_api" region tag in this sample. I would like to show just a small snippet of code, so I added the "echo_api_method" region tag. In case we want to show the entire class in the docs, I've renamed the "echo_api" region tag to "echo_api_class".
> Changed region tags in sample

- codelabs/flex_and_vision/main.py
I do not believe this region tag is used in the repo or on cloud.google.com, but let me know if I am missing something. I am removing the unused region tag to clean up our sample tracking, which is done by region tag.
> Remove unused region tag

- CONTRIBUTING.md
- MAC_SETUP.md
This guide recommends `pyenv` and `pyenv-virtualenv`. I know there are many options, but this is what works for me.
> Add guide on using multiple Python versions for local development

- functions/helloworld/sample_pubsub_test_system.py
- functions/helloworld/sample_storage_test_system.py
The document at https://cloud.google.com/functions/docs/env-var suggests using `env['GCP_PROJECT']` for current project ID, as `env['GCLOUD_PROJECT']` is deprecated/legacy.
> Functions: Use the documented way to fetch current GCP project ID.

- vision/api/label/label.py
- vision/cloud-client/detect/detect.py
- vision/cloud-client/document_text/doctext.py
Removes region tags that are not used on cloud.google.com (plus typo fix)
> Vision - remove unused region tags

- pubsub/cloud-client/publisher.py
- pubsub/cloud-client/subscriber.py
Highlights the timeout feature - if not specified, Pub/Sub will try to publish or subscribe indefinitely.
>  Added timeout in error handling

- vision/cloud-client/crop_hints/crop_hints.py
- vision/cloud-client/detect/beta_snippets.py
- vision/cloud-client/detect/detect.py
- vision/cloud-client/detect/detect_pdf.py
- vision/cloud-client/document_text/doctext.py
- vision/cloud-client/face_detection/faces.py
- vision/cloud-client/product_search/import_product_sets.py
- vision/cloud-client/product_search/product_in_product_set_management.py
- vision/cloud-client/product_search/product_management.py
- vision/cloud-client/product_search/product_search.py
- vision/cloud-client/product_search/product_set_management.py
- vision/cloud-client/product_search/reference_image_management.py
- vision/cloud-client/quickstart/quickstart.py
- vision/cloud-client/web/web_detect.py
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Vision region tag update

- kms/api-client/asymmetric.py
- kms/api-client/asymmetric_test.py
- kms/api-client/requirements.txt
Added samples for the KMS Asymmetric Keys launch
> KMS: add asymmetric keys samples

- video/cloud-client/analyze/analyze.py
- video/cloud-client/analyze/beta_snippets.py
- video/cloud-client/labels/labels.py
- video/cloud-client/quickstart/quickstart.py
- video/cloud-client/shotchange/shotchange.py
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Video Intelligence region tag update

- spanner/cloud-client/requirements.txt
- spanner/cloud-client/snippets.py
- spanner/cloud-client/snippets_test.py
Clean and update spanner tests. They are now more consistent and will match the [Java](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java) and [Golang](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/spanner/spanner_snippets/snippet_test.go) tests/snippets more closely.
> Cleanup spanner tests.

- language/classify_text/classify_text_tutorial.py
- language/cloud-client/v1/quickstart.py
- language/cloud-client/v1/snippets.py
- language/sentiment/sentiment_analysis.py
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Language region tag update

- texttospeech/cloud-client/audio_profile.py
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> TTS region tag update

- kms/api-client/asymmetric.py
- kms/api-client/asymmetric_test.py
Addresses issues in the documentation of the last KMS PR:
- clarifies which RSA key algorithm is used for encrypt/decrypt
- makes a note that signAsymmetric will need changes for certain key algorithms
- changed EC_SIGN_P224_SHA256 to EC_SIGN_P256_SHA256
> KMS Asymmetric Text Fixes

- composer/rest/get_client_id.py
- composer/rest/get_client_id_test.py
- composer/rest/requirements.txt
- composer/workflows/trigger_response_dag.py
- composer/workflows/trigger_response_dag_test.py
Sample originally was posted at https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf#wzxhzdk15gcs_response_dagpywzxhzdk16
> Composer: Move trigger response DAG to GitHub.

- appengine/flexible/cloudsql_postgresql/requirements.txt
Manually updated requirements for appengine/flexible/cloudsql_postgresql. The test seemed to fail the first time because it ran out of space.
> Updated appengine/flexible/cloudsql_postgresql samples.

- composer/workflows/simple.py
This allows Airflow to surface the 'Hello World!' output, as PythonOperator does not include STDOUT in its logs.
[Fix #1662]
> Use logging on the PythonOperator in simple.py

- language/automl/automl_natural_language_dataset.py
- language/automl/automl_natural_language_model.py
- language/automl/automl_natural_language_predict.py
- translate/automl/automl_translation_dataset.py
- translate/automl/automl_translation_model.py
- translate/automl/automl_translation_predict.py
automl_natural_language => automl_language
automl_translation => automl_translate
This update is to be consistent with the Natural Language and Translation region tags.
> Update AutoML region tags to use standard product prefixes

- pubsub/cloud-client/subscriber.py
- pubsub/cloud-client/subscriber_test.py
> Added sample for synchronous pull

- bigquery/cloud-client/requirements.txt
If ipython has tagged their packages correctly, then the modifier is not necessary. Sending a PR to check. Bug 113341391.
> Remove ipython Python 2 modifier from requirements.txt

- pubsub/cloud-client/subscriber.py
Our January [update](https://github.com/GoogleCloudPlatform/python-docs-samples/commit/1bfa44503843ab921c5c2bd7f552d784c5bfee3e#diff-7ff914278985719ef067729ad18ee87c) to this line of code seems to have missed this.
> Fixed return object from `subscriber.subscribe()`

- .kokoro/presubmit_tests_composer.cfg
- .travis.yml
- composer/workflows/use_local_deps_test.py
- nox.py
- testing/test-env.tmpl.sh
Note: I had to skip the use_local_deps workflow sample because of a
change in relative versus absolute imports between Python 2 and Python
3. I have not yet checked the workflow within Airflow to see if it runs
under Python 3.
@TrevorEdwards please review
> Test Composer samples on Python 3

- pubsub/cloud-client/requirements.txt
- pubsub/cloud-client/subscriber.py
- pubsub/cloud-client/subscriber_test.py
For very long-running tasks, we can reset the ack deadline every once in a while by calling `modify_ack_deadline` on the Subscriber API Client in separate processes.
> Pub/Sub: synchronous pull with lease management

- functions/imagemagick/README.md
- functions/imagemagick/main.py
- functions/imagemagick/main_test.py
- functions/imagemagick/requirements.txt
~~**TODO** - add Kokoro test config. (@andrewsg this is good to review though.)~~
**EDIT:** Kokoro configs need to be added for GCF separately. We should do this in a separate PR.
> Add GCF imagemagick samples

- functions/sql/mysql_sample.py
- functions/sql/postgres_sample.py
(Missed a spot in #1655)
Replace `SUPERVISOR_HOSTNAME` with something more stable
@jasonpolites please review (and tell me if there's a better way)
> GCF SQL: Use proper environment variables

- kms/api-client/asymmetric.py
- kms/api-client/asymmetric_test.py
implements changes suggested in b/113025362 and b/113025156
> KMS changes

- video/cloud-client/analyze/analyze_test.py
- video/cloud-client/analyze/beta_snippets_test.py
- video/cloud-client/labels/labels_test.py
- video/cloud-client/shotchange/shotchange_test.py
Resolves contributor friction that Rebecca identified when writing https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1738
Currently, in order to run the tests, a contributor needs to find and download certain files, upload them to their bucket, and set an environment variable to point to their bucket. This PR updates the tests use public GCS URIs, so future contributors will not need to figure out and follow these confusing set-up steps.
> Use explicit URIs for Video Intelligence sample tests

- iot/api-client/end_to_end_example/requirements.txt
Seems like `oauth2client` is not a dependency of `google-auth`,`google-auth-httplib2`, nor `cryptography` (with the specified versions). For now, I'm adding oauth2client to `requirements.txt`, but alternatively we could update one of the aforementioned packages to a version that has oauth as a dependency.
> update requirements.txt with oauth2client

- appengine/standard_python37/django/app.yaml
Django collectstatic adds files to ``static/`` folder rather than ``static_files/``.
> Fix serving static files on production

- appengine/standard_python37/django/mysite/settings.py
While looking into the cause of an exception:
ModuleNotFoundError: No module named 'MySQLdb'
I noticed the pymysql initialisation was missing, yet it was [done for the python2 tutorial settings.py counterpart](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/django/mysite/settings.py#L95-L103)..
Note that this was noticed even when running the app in ["production" on GAE](https://console.cloud.google.com/errors/CIv9orry98OZRw?time=PT1H&project=expanded-talon-217815) (link for my own error in case it's accessible by Google employees). 
So worth looking into if this is the case here:
...This is a convenience feature for developers who cannot install
> Fix for error when missing MySQLdb

- bigquery/bqml/ncaa_tutorial_test.py
Tracked internally as 118618672.
This is one possible remedy for the test failure.  The other is to specify all the necessary data split options.
> Address broken test by updating CREATE MODEL options.

- dataproc/list_clusters.py
- dataproc/pyspark_sort.py
- dataproc/pyspark_sort_gcs.py
- dataproc/submit_job_to_cluster.py
The docs have already been frozen to the latest commit in preparation for this change, so the links will not break. I will update the docs once this is merged.
> Update Dataproc region tags to standard format

- cloud-sql/mysql/sqlalchemy/README.md
- cloud-sql/mysql/sqlalchemy/app.yaml
- cloud-sql/mysql/sqlalchemy/main.py
- cloud-sql/mysql/sqlalchemy/requirements.txt
- cloud-sql/mysql/sqlalchemy/templates/index.html
New sample app in a series of samples designed to highlight connection best practices. The app is a simple web app that allows voting between two different groups ("Tabs" vs "Spaces") and records the votes in a MySQL backend. 
Java equivalent is [here](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1231).
> Add Cloud SQL MySQL connectivity samples for SQLAlchemy. 

- dialogflow/cloud-client/detect_intent_audio.py
- dialogflow/cloud-client/detect_intent_stream.py
- dialogflow/cloud-client/detect_intent_texts.py
- dialogflow/cloud-client/detect_intent_with_model_selection.py
- dialogflow/cloud-client/detect_intent_with_sentiment_analysis.py
- dialogflow/cloud-client/detect_intent_with_texttospeech_response.py
Fix spelling of word "Conversation" in multiple files
> Fix typos in dialogflow cloud client comments

- appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
Needed to update google-endpoints to 4.8.0 to avoid the 'audiences must be a dict when third-party issuers are in use'  that was introduced in 4.7.0. See https://github.com/cloudendpoints/endpoints-python/issues/184
Signed-off-by: Nancy Avinger <navinger@google.com>
> Update google-endpoints to version 4.8.0.

- iot/api-client/beta-features/gateway/gateway_demo.py
Mike found out that `gateway_demo.py` was still using the old function name `listen_for_config_messages` instead of `listen_for_config_and_error_messages` which prevented the demo from running
> iot: update misnamed function in gateway_demo

- iot/api-client/end_to_end_example/cloudiot_pubsub_example_mqtt_device.py
- iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py
It throws an exception when trying to parse to JSON. Could use a second opinion on this solution. Original Codelab instructions available [here](https://codelabs.developers.google.com/codelabs/cloud-iot-core-overview/index.html?index=..%2F..index#0).
> Possible fix to message encoding issue

- healthcare/api-client/datasets/datasets.py
Only backwards-incompatible change is deidentify operation. Tests are unaffected.
> Update datasets.py from v1alpha to v1alpha2

- vision/cloud-client/detect/README.rst
- vision/cloud-client/detect/beta_snippets.py
- vision/cloud-client/detect/beta_snippets_test.py
I added the sample for async image batch annotation. I also renamed the function names and region tags for the previous two samples in my last PR.
> Added the sample for async image batch annotation

- cloud-sql/postgres/sqlalchemy/main.py
Using CHAR was bringing extra spaces on the frontend for comparison and leading to display wrong information.
> Changes from CHAR to VARCHAR on Cloud SQL example

- asset/cloud-client/quickstart_batchgetassetshistory_test.py
There's some latency between bucket creation and when it's reflected in
the backend. Need to delay in order to make the API call successfully.
> [CloudAsset] Test: Delay seconds between bucket creation and API call.

- bigquery_storage/to_dataframe/main_test.py
- bigquery_storage/to_dataframe/requirements.txt
As of google-cloud-bigquery version 1.11.1, the `to_dataframe` method
will fallback to the tabledata.list API when the BigQuery Storage API
fails to read the query results.
> Remove temporary dataset from bqstorage pandas tutorial

- bigquery_storage/to_dataframe/jupyter_test.py
- bigquery_storage/to_dataframe/requirements.txt
This is a notebooks tutorial, modeled after the Jupyter notebook example
code for BigQuery. Use some caution when running these tests, as they
run some large-ish (5 GB processed) queries and download about 500 MB
worth of data. This is intentional, as the BigQuery Storage API is most
useful for downloading large results.
> Add magics tutorial with BigQuery Storage API integration.

- appengine/standard_python37/pubsub/main.py
- appengine/standard_python37/pubsub/main_test.py
- appengine/standard_python37/pubsub/templates/index.html
The Google Auth Python library's `verify_oauth2_token()` function doesn't verify the iss claim. The same function in Node.js/Java/PHP does. (More detail: https://developers.google.com/identity/sign-in/web/backend-auth)
> Authenticated Push: must also verify the `iss` claim

- ml_engine/online_prediction/predict.py
- ml_engine/online_prediction/scikit-xg-predict.py
- notebooks/tutorials/cloud-ml-engine/Training and prediction with scikit-learn.ipynb
Renames all instances of the following terms in strings and other text:
* Cloud Machine Learning Engine
* Cloud ML Engine
* ML Engine
To be cautious about broken links, this change doesn't rename any files
or change any URLs. (The ml_engine directory may be renamed later, after
a sweep to find all the places where this code is included or linked
to.)
> Rename Cloud ML Engine to AI Platform

- datacatalog/cloud-client/lookup_entry.py
Minor changes to support Data Catalog docs, according to issue https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2168.
> Add region tags to support Data Catalog docs

- video/cloud-client/analyze/beta_snippets.py
label and entity descriptions from the service are in unicode, and printing with string formatting in python2 could result in errors such as
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 1: ordinal not in range(128)
```
> fix python2 print unicode issue

- cloud-sql/mysql/sqlalchemy/app.yaml
- cloud-sql/postgres/sqlalchemy/app.yaml
Previously, in the mysql example for cloud sql, there was a discrepancy between the naming of an environment variable in main.py and app.yaml. This PR changes the env var to "CLOUD_SQL_CONNECTION_NAME," matching the naming convention the [Java library uses](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java).
> Changed env var to match between app.yaml and main.py in cloud_sql/mysql

- dlp/deid.py
- dlp/inspect_content.py
- dlp/redact.py
- dlp/templates.py
- dlp/triggers.py
Fixing bug where "FIRST_NAME", "LAST_NAME", "EMAIL_ADDRESS" are still present even when user 
specifies info_types. To fix I have converted action='append' to nargs='+' which will preserve defaults but allow user to override rather than append to the default list.
> DLP: Several python example scripts have badly behaved info_types parameter

- video/cloud-client/analyze/beta_snippets.py
* label_annotations and object_annotations could be empty
* annotation.frames[0].time_offset may vary between annotations
> update videointelligence streaming samples

- speech/cloud-client/transcribe.py
Makes code copy-pastable runnable
> Place import inside the function

- appengine/flexible/django_cloudsql/mysite/settings.py
- appengine/flexible/django_cloudsql/requirements.txt
This addresses customer feedback that mysql vs postgres is confusing and that when using postgres, mysqlclient is required (and installation fails locally because mysql libs are not installed) by default.
> Change Django sample so that mysqlclient is not installed by default

- kms/api-client/snippets.py
So they will show up in context on web pages.
> Move import statements into tagged regions

- bigtable/metricscaler/metricscaler_test.py
- spanner/cloud-client/snippets_test.py
* Spanner doesn't actually promise the order of the results, so make the assertion work regardless of ordering.
* Bigtable might need some more time to scale, so retry the assertion up to 10 times.
> Deflake bigtable and spanner tests.

- pubsub/cloud-client/publisher.py
Added a few comments to clarify what the code does.
> Pub/Sub: add comments to publish with error-handling sample

- spanner/cloud-client/snippets.py
- spanner/cloud-client/snippets_test.py
The samples that transfer part of an album's marketing budget had some issues:
+ `read_write_transaction`: Compared `second_album_budget` with an arbitrary integer, rather than explicitly checking against `transfer_amount`.
+ `write_with_dml_transaction`: Moved money from album 1 to album 2, even though `read_write_transaction` was the other way around. Also retrieved album 1's budget where it should have retrieved album 2's budget.
This change fixes those issues and updates the tests accordingly.
@jsimonweb PTAL
> Improve and fix Cloud Spanner samples that transfer marketing budget

- monitoring/api/v3/cloud-client/snippets.py
Associated documentation and a majority of languages standardize to 20 minute intervals instead of 5. https://cloud.google.com/monitoring/custom-metrics/reading-metrics
> monitoring/metrics: update from 5 to 20 minutes

- pubsub/cloud-client/publisher.py
- pubsub/cloud-client/publisher_test.py
- pubsub/cloud-client/subscriber_test.py
- add `future.result()` to resolve futures to ensure publish success
- update publish with error handler example some more
> Pub/Sub: fix all publisher examples

- .kokoro/presubmit_tests_kubernetes_engine.cfg
- .kokoro/system_tests_kubernetes_engine.cfg
I recently submitted a PR renaming container_engine to kubernetes_engine (https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2205). It looks like some kokoro configs were missed in the renaming process
> Renamed container_engine kokoro configs

- dataflow/run_template/README.md
- dataflow/run_template/main.py
- dataflow/run_template/main_test.py
- dataflow/run_template/requirements.txt
This adds a helper script to run a Dataflow template from the command line, from Python, or from a Cloud Function HTTP endpoint.
> Add Dataflow script to run templates

- .kokoro/presubmit_tests_run.cfg
- run/README.md
- run/pubsub/.dockerignore
- run/pubsub/.gcloudignore
- run/pubsub/.gitignore
- run/pubsub/Dockerfile
- run/pubsub/README.md
- run/pubsub/main.py
- run/pubsub/main_test.py
- run/pubsub/requirements.txt
* Adds a Cloud Run section to the samples
* Introduces the Cloud Run + Cloud Pub/Sub sample app
* Adds Kokoro Presubmit checks for Cloud Run
Note: The Pub/Sub sample itself was written by @ace-n and I reviewed for product alignment.
> Add Cloud Run to Python Samples

- bigquery_storage/to_dataframe/main_test.py
- bigquery_storage/to_dataframe/requirements.txt
Requires `google-cloud-bigquery` 1.17.0.
> BigQuery Storage: Update to use faster Arrow data format.

- speech/microphone/transcribe_streaming_indefinite.py
Speech is getting support for 5 minutes of streaming
> Increase timeout to 5 mins

- vision/cloud-client/detect/beta_snippets.py
- vision/cloud-client/detect/beta_snippets_test.py
- vision/cloud-client/detect/detect.py
Reverts GoogleCloudPlatform/python-docs-samples#2174
The change breaks our tests. I'm guessing the original issue was that the bucket path was passed incorrectly.
> Revert "Update detect.py"

- firestore/cloud-client/snippets.py
Fixing these deprecations (since 1.2.0 ?) when running pytest with `google-cloud-firestore==1.2.0`
```
snippets_test.py::test_quickstart_get_collection
/Users/peter_v/data/projects/secretjobs/git/scraping/code/development/firestore/cloud-client/snippets.py:62: DeprecationWarning: 'Collection.get' is deprecated:  please use 'Collection.stream' instead.
docs = users_ref.get()
```
> Use `Collection.stream` instead of deprecated `Collection.get` in firestore

- monitoring/api/v3/alerts-client/snippets.py
- monitoring/api/v3/alerts-client/snippets_test.py
Hard coding could confuse readers.
> Make backup/restore file name a parameter

- pubsub/cloud-client/iam.py
- pubsub/cloud-client/iam_test.py
- pubsub/cloud-client/publisher.py
- pubsub/cloud-client/publisher_test.py
- pubsub/cloud-client/quickstart.py
- pubsub/cloud-client/quickstart_test.py
- pubsub/cloud-client/subscriber.py
- pubsub/cloud-client/subscriber_test.py
This is a new sample that will go on [here](https://cloud.google.com/pubsub/docs/publisher#retry), next to the Java and Node samples.
> Pub/Sub: add publish retry sample

- opencensus/metrics_quickstart.py
In current sample, no steps is written to register Stackdriver exporter to view manager. This is misleading sample in real world, and like [OpenCensus' document](http://localhost:1313/quickstart/python/metrics/#exporting-to-prometheus) it should show the step to register the exporter to reduce confusion.
> Add exporter registration step in OpenCensus Stats quick start

- storage/cloud-client/snippets_test.py
The Python client was fixed in https://github.com/googleapis/google-cloud-python/issues/3711 so the test now passes.
> Drop xfail for passing test_remove_bucket_label

- appengine/standard/firebase/firenotes/frontend/main.js
Changes the document location to not cut off the final curly bracket and parenthesis which is required to get the script to properly run.
> Documentation location for onAuthStateChanged

- iam/api-client/access.py
Initializes a `cloudresourcemanager` client in each snippet.
Reason: received a bug report where a user tried to call these functions on an IAM API client, not a ResourceManager client. This sample code lives in the IAM docs, so not being clear about which API is used here could be confusing.
> [IAM] Add client initialization to each access.py sample  

- trace/main.py
The tracer won't always send traces unless a sampler is specified. This one sends every trace.
> Add needed parameter

- monitoring/api/v3/cloud-client/snippets.py
The document says the example gathers 20 minutes of data, but only 5 minutes (300 seconds) were shown here.
> Match web documentation

- firestore/cloud-client/snippets.py
Some readers were tripping over how to resolve the import of ArrayUnion and ArrayRemove, see:
https://github.com/googleapis/google-cloud-python/issues/8792
https://stackoverflow.com/questions/57219705/unable-to-import-fieldvalue-arrayunion/57226431#57226431
> Adjust Cloud Firestore update_doc_array snippet to not require an extra import

- compute/managed-instances/demo/app.py
- compute/managed-instances/demo/requirements.txt
The previous design did not correctly close running Processes meant for CPU loading.  Once CPU loading was started, it would not be able to be stopped.
This design only creates one Process and never closes it.  Instead, it simply sleeps when CPU loading is turned off.
> Fix managed instances demo web server to correctly start/stop CPU loading

- translate/cloud-client/beta_snippets.py
- translate/cloud-client/beta_snippets_test.py
@beccasaurus 
now: translate-with-glossary prints the translations that use a glossary
previously: translate-with-glossary printed translations that didn't use a glossary
> fixing translate-with-glossary bug

- translate/cloud-client/beta_snippets.py
- translate/cloud-client/beta_snippets_test.py
- translate/cloud-client/snippets_test.py
Temporary solution to failing tests due to ASCII printing errors and ML variability.
Non-temporary fixes to translate_text_with_glossary function and test_translate_text
@nnegrey @beccasaurus
> Translate beta samples fix

- pubsub/cloud-client/subscriber.py
The samples for pulling from Cloud Pub/Sub now prints the actual number of messages received instead of `max_messages` for the request.
> Print actual number of messages pulled

- iam/api-client/access.py
- iam/api-client/access_test.py
- iam/api-client/grantable_roles.py
- iam/api-client/quickstart.py
Example code for removing a member in IAM policy.
> IAM: added snippet for remove member

- firestore/cloud-client/requirements.txt
- firestore/cloud-client/snippets.py
* bump google-cloud-firestore to v1.4.0
> Add `fs_update_document_increment` snippet

- appengine/standard/i18n/i18n_utils.py
- appengine/standard/mail/header.py
- appengine/standard/ndb/properties/snippets.py
- appengine/standard/ndb/queries/snippets_test.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
> Use print() function in both Python 2 and Python 3

- vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
The tests in the vision/automl repo have various strings that are formatted past the 80 column limit.
> Fix style in tests

- asset/cloud-client/quickstart_createfeed.py
- asset/cloud-client/quickstart_createfeed_test.py
- asset/cloud-client/quickstart_deletefeed.py
- asset/cloud-client/quickstart_deletefeed_test.py
- asset/cloud-client/quickstart_getfeed.py
- asset/cloud-client/quickstart_getfeed_test.py
- asset/cloud-client/quickstart_listfeeds.py
- asset/cloud-client/quickstart_listfeeds_test.py
- asset/cloud-client/quickstart_updatefeed.py
- asset/cloud-client/quickstart_updatefeed_test.py
- asset/cloud-client/requirements.txt
Cloud Asset Inventory is launching a series of Beta Apis:
Create Feed
Delete Feed
Get Feed
Update Feed
List Feeds
In this PR, we added all the quick starts as well as their tests.
> Asset: Add Real Time Feed API Sample Code

- endpoints/kubernetes/grpc-bookstore.yaml
Otherwise, many users still using very old ESP image 1.16.0
Tag "1" is always points to the latest ESP image
> Use latest esp docker image with tag 1

- tables/automl/notebooks/census_income_prediction/README.md
to approve with the updated notebook supporting jupyter
> updated readme for support Jupyter

- spanner/cloud-client/snippets.py
Summary:
This code used to be correct, when the Spanner Python API had a typo in
the parameter name, but that typo was fixed in an upstream pull request:
<https://github.com/googleapis/google-cloud-python/pull/7295>
Test Plan:
Running `git grep BOOE` now returns no results.
wchargin-branch: bool-not-booe
> Fix Spanner `BOOL` example after upstream typo fix

- iam/api-client/service_accounts.py
One set of the "iam_create_service_accounts" region tag is missing the "s" at the end.
> Add "s" to "iam_create_service_account" region tag

- pubsub/cloud-client/quickstart/pub.py
Continuously prints out "Published x messages" when `pub.py` is running. This would give the user some indication that the program is running / the publisher is retrying publish / and not hanging. 
@kir-titievsky does this look like a reasonable solution? 
Open Question: 
The client library doesn't throw a Service Unavailable error until total RPC timeout is reached (default to 600s/10mins). We need to update the client library so it can fail fast in that scenario.
> Pub/Sub: improve pub.py

- .gitignore
Add the commonly used Python virtualenv directory `env/` to the gitignore.
> Add Python virtual environment directory

- vision/cloud-client/product_search/product_in_product_set_management.py
- vision/cloud-client/product_search/product_in_product_set_management_test.py
- vision/cloud-client/product_search/product_management.py
- vision/cloud-client/product_search/product_management_test.py
- vision/cloud-client/product_search/requirements.txt
samples for new features:
* delete all products in a product set
* delete all products not in any product sets
> Purge products

- bigquery/pandas-gbq-migration/requirements.txt
- bigquery/pandas-gbq-migration/samples_test.py
- bigquery_storage/to_dataframe/jupyter_test.py
- bigquery_storage/to_dataframe/requirements.txt
- noxfile.py
* Show how to use BQ Storage API with pandas-gbq and magics.
* Update tests to actually run BQ Storage API on smaller IRS 990 table.
> BigQuery: Update pandas/bqstorage samples to latest library changes.

- iam/api-client/service_accounts.py
There were a few extra spaces after the [START iam_enable_service_account] region tag.
> iam: remove extra spaces after region tag

- iot/api-client/http_example/cloudiot_http_example_test.py
- iot/api-client/http_example/requirements.txt
- iot/api-client/manager/manager.py
- iot/api-client/manager/manager_test.py
- iot/api-client/manager/requirements.txt
- iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
- iot/api-client/mqtt_example/requirements.txt
Probably a good time to start migrating to the Cloud client for the Python samples.  This change adds a few of the initial updates that are most likely to affect tests across the HTTP/MQTT/manager samples.
> iot: switch to Cloud Client

- pubsub/streaming-analytics/PubSubToGCS.py
- pubsub/streaming-analytics/PubSubToGCS_test.py
- pubsub/streaming-analytics/README.md
- pubsub/streaming-analytics/requirements.txt
~~Unable to merge until Apache Beam supports TextIO for Python/Streaming. Currently, only Pub/Sub to BigQuery is supported in Python. Check out their Build-in I/O Transforms table [here](https://beam.apache.org/documentation/io/built-in/).~~
_(Sorry @kir-titievsky I was wrong about this!)_
Streaming Pub/Sub to GCS using Dataflow Python Tutorial. 
~~@davidcavazos I have got lots of string encoding and decoding operations in the code. If you see a way to reduce redundancy, please let me know.~~
I will work on a separate PR to add Stream Pub/Sub to BigQuery using Dataflow.
> Pub/Sub to GCS using Dataflow Tutorial

- firestore/cloud-client/snippets.py
PR as requested in https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2261#issuecomment-537086484
There are no more exceptions when no document found in DocumentReference.get() call.
If the document does not exist at the time of the snapshot is taken, the snapshot’s reference, data, update_time, and create_time attributes will all be None and its exists attribute will be False.
https://googleapis.github.io/google-cloud-python/latest/firestore/document.html#google.cloud.firestore_v1.document.DocumentReference.get
Now issues googleapis/google-cloud-python#4530 and googleapis/google-cloud-python#4531 are resolved
> Fix wrong get_check_exists sample. No exception handling is required anymore

- tables/automl/notebooks/music_recommendation/music_recommendation.ipynb
Updates the notebook to emphasize restarting the python kernel to be able to import automl-tables and fixes a typo.
> fix users bug and emphasize kernel restart

- functions/sql/mysql_sample.py
Based on this code example I have created and deployed a cloud function, which connects over a socket to the Cloud SQL Instance.
I however noticed that it wasn't behaving correctly: after a while I was getting back the Exception `pymysql.err.InterfaceError: (0, '')` on each request.
Scrolling back in the logs of my cloud function I noticed that the Exception started getting thrown after the connection the MySQL server got lost:
Note this error in the logs, after which the `pymysql.err.InterfaceError: (0, '')` Exceptions pop up:
```
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
```
When redeploying the function everything worked fine again, but a day later the same issue occurred again.
I narrowed down the problem to the …
> Correctly restore connection if MySQL server has gone away

- speech/microphone/transcribe_streaming_infinite.py
- storage/cloud-client/snippets.py
- translate/cloud-client/hybrid_glossaries/hybrid_tutorial.py
Adding changes to samples to stage for viewing tutorial
> Merging samples code

- cloud-sql/mysql/sqlalchemy/.dockerignore
- cloud-sql/mysql/sqlalchemy/.gitignore
- cloud-sql/mysql/sqlalchemy/Dockerfile
- cloud-sql/mysql/sqlalchemy/README.md
- run/README.md
Add Cloud Run support to the Cloud SQL (MySQL) sample.
> cloud-sql: add Cloud Run support to sqlalchemy sample

- dataflow/run_template/README.md
- dataflow/run_template/main.py
- dataflow/run_template/main_test.py
- dataflow/run_template/requirements.txt
- testing/requirements.txt
* Use client libraries instead of `subprocess`
* Updated README formatting
* Updated requirements
> Dataflow client library

- firestore/cloud-client/snippets.py
> fix: typo in fs_update_document_increment sample

- iot/api-client/manager/manager.py
- iot/api-client/manager/manager_test.py
After this, we will only have the configuration, state, and command APIs remaining for migration.
> Cloud client library migration for registry management features

- storage/signed_urls/generate_signed_urls.py
Per the docs, the "/" character should not be escaped in the object name
portion of the signed URL.  Also, Python 2 and 3 differ on whether the
tilde character should be escaped by the url library's `quote` method,
so in order for our sample to work on both Python2 and Python3, we
should always specify the tilde as a "safe" character. For reference, we
already fixed this same bug in gsutil a few months ago:
https://github.com/GoogleCloudPlatform/gsutil/blob/4531874e3a3d45ca642fc9c9fa438ba58c8f1494/gslib/commands/signurl.py#L543
> Fix encoding of object names.

- functions/sql/mysql_sample.py
> Update functions/sql example to use more clear connection logic.

- storage/signed_urls/generate_signed_urls.py
> Update V4 Signature snippet

- bigquery/bqml/requirements.txt
The BQML dependency on pytest is redundant with the central testing
dependencies. Removing this dependency resolves a `TypeError: attrib()
got an unexpected keyword argument 'convert'` test failure caused by
incompatible versions.
> chore(bigquery): remove redundant dependency on pytest

- composer/workflows/kubernetes_pod_operator.py
Ping me for internal bug reference
> Add to comment to clarify kubernetespodoperator

- compute/metadata/detect_legacy_usage.py
- compute/metadata/detect_legacy_usage_test.py
Adding a sample showing how to use the new legacy-endpoint-access endpoint to detect usage of the legacy metadata endpoints.
> Adding legacy-endpoint-access sample

- appengine/standard_python37/django/requirements.txt
Django 2.2.5 checks the version number that PyMySql reports and does not accept it. The 2.1.14 version is up-to-date and does not have this problem.
> Use latest 2.1.x Django to avoid PyMySql issue

- healthcare/api-client/dicom/dicom_stores.py
Apparently the patch API tolerated a bad format name until a few weeks ago, so this error was uncaught until now.
> Fix pubsub topic name format

- kubernetes_engine/django_tutorial/polls.yaml
Bumps the version to the latest Cloud SQL Proxy Docker Image to the latest version to be compatible with Postgres.
Resolves https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/328
> Update Cloud SQL Proxy Docker Image.

- container_registry/container_analysis/requirements.txt
- functions/imagemagick/requirements-dev.txt
- run/image-processing/requirements.txt
- run/logging-manual/requirements.txt
- run/pubsub/requirements.txt
- testing/requirements.txt
Fix #2556 by providing a valid pytest version for python2.
> fix: Use different versions of pytest for python 2 and python3

- noxfile-template.py
- noxfile.py
Fixes #2571 by adding black target.
Also addresses creating a template noxfile that can be copied to each subproject.
```
$cd speech                                                                                                                                                          
$cp ../noxfile-template.py noxfile.py                                                                                                                        
$nox -l                                                                                                                                                      
Sessions defined in /Users/crwilcox/workspace/python-docs-samples/speech/noxfile.py:
* gae -> A no-op session for patemetrized sessions with no available params.
* py27(sample='./cloud-client') -> …
```
> Add Black and Create Noxfile template

- dlp/deid.py
- dlp/deid_test.py
- dlp/inspect_content.py
- dlp/inspect_content_test.py
- dlp/jobs.py
- dlp/jobs_test.py
- dlp/metadata.py
- dlp/metadata_test.py
- dlp/quickstart.py
- dlp/quickstart_test.py
- dlp/redact.py
- dlp/redact_test.py
- dlp/risk.py
- dlp/risk_test.py
- dlp/templates.py
- dlp/templates_test.py
- dlp/triggers.py
- dlp/triggers_test.py
Per b/143006235, update doc samples to use dlp_v2 client. Requirements specify 0.12.1 but code samples seem to be using old client. We want to upgrade to keep consistency with Source: https://googleapis.dev/python/dlp/latest/index.html.
> Update DLP samples to use dlp_v2 client.

- noxfile-template.py
- noxfile.py
- run/system-package/.dockerignore
- run/system-package/Dockerfile
- run/system-package/README.md
- run/system-package/main.py
- run/system-package/main_test.py
- run/system-package/requirements.txt
Creating python sample for https://cloud.google.com/run/docs/tutorials/system-packages.
This sample Cloud Run service demonstrates using a customized Dockerfile to configure system packages whose command-line utilities are used as part of serving HTTP requests.
> Adding Cloud run system package sample

- pubsub/cloud-client/publisher_test.py
- pubsub/cloud-client/subscriber.py
- pubsub/cloud-client/subscriber_test.py
The infinite while loops in the subscriber examples suppress errors such as `403 User not authorized to perform this action`. This PR 1). updates all `subscriber.subscribe(...)` by explicitly resolving the streaming pull future:
```python
streaming_pull_future = subscriber.subscribe(...)
streaming_pull_future.result()
```
2). adds teardown code after `yield` for test fixtures.
> Pub/Sub: remove infinite while loops in subscriber examples

- asset/cloud-client/quickstart_createfeed.py
- asset/cloud-client/quickstart_deletefeed.py
- asset/cloud-client/quickstart_getfeed.py
- asset/cloud-client/quickstart_listfeeds.py
- asset/cloud-client/quickstart_updatefeed.py
- asset/cloud-client/requirements.txt
With the new python package released, we need to update the sample code too.
> Asset: Update Real Time Feed Sample Code with newest version

- .kokoro/python2.7/common.cfg
- bigquery/pandas-gbq-migration/samples_test.py
So long as NULLs are not present, the pandas dtype to
BigQuery data type auto conversion should work as
intended.
Closes internal issue 140645939.
> add TIMESTAMP column to pandas upload example

- pubsub/cloud-client/subscriber.py
Fixed #2633. 
To receive messages without timeout: 
`python subscriber.py <project_id> receive <subscription_name> `
To receive message with a timeout of `10` seconds:
`python subscriber.py <project_id> receive <subscription_name> --timeout 10`
> Pubsub: add timeout in argparser

- .kokoro/tests/run_tests.sh
- datalabeling/create_annotation_spec_set.py
- datalabeling/create_annotation_spec_set_test.py
- datalabeling/create_instruction.py
- datalabeling/create_instruction_test.py
- datalabeling/export_data.py
- datalabeling/import_data.py
- datalabeling/label_image.py
- datalabeling/label_image_test.py
- datalabeling/label_text.py
- datalabeling/label_text_test.py
- datalabeling/label_video.py
- datalabeling/label_video_test.py
- datalabeling/manage_dataset.py
Update datalabeling samples to use test endpoint. These samples trigger real human action, so we want to use the test endpoint to avoid that from happening.
> Update datalabeling samples to use test endpoint.

- appengine/standard_python37/pubsub/README.md
- appengine/standard_python37/pubsub/main.py
- appengine/standard_python37/pubsub/main_test.py
- codelabs/functions/python_powered/main.py
`_ah` is not necessary when setting up Cloud Pub/Sub authenticated push subscriptions in App Engine Standard's Python3 runtime.
> Pub/Sub: remove `_ah` in AppEngine Python3 sample

- secretmanager/api-client/requirements.txt
This bumps to the version that doesn't have a bunch of deprecation
warnings.
> Bump secretmanager version

- pytest.ini
- testing/requirements.txt
Bumps pytest to the latest versions of 4 and 5, and sets the [`junit_family`](https://docs.pytest.org/en/latest/reference.html#confval-junit_family).
> chore: update pytest version

- noxfile-template.py
- noxfile.py
Makes `nox -s lint` compatible with `nox -s blacken`'s defaults.
> Add max-line-length to nox lint.

- translate/cloud-client/translate_v3_create_glossary.py
- translate/cloud-client/translate_v3_list_glossary.py
Adds a comment; removes extraneous field access in Translation glossary samples.
Affected region tags / code snippets:
- translate_v3_create_glossary
- translate_v3_list_glossary
> fix: changes fields printed in list glossary sample; some minor fixes

- dataproc/quickstart/quickstart.py
- dataproc/quickstart/quickstart_test.py
The region tag is intentionally placed to include the CLI logic.
> fix: added cli functionality to dataproc quickstart example

- functions/spanner/main.py
The Cloud Functions Python example creates a database object each time the function is run. This means that a new session pool is created and destroyed at each run of the function.
The example has been modified to reuse the same database object.
Closes #2762
> Fix: Reuse same Spanner database in Cloud Function

- translate/cloud-client/translate_v3_list_glossary.py
- translate/cloud-client/translate_v3_list_glossary_test.py
Migrate from tmp-generated-samples branch fef998b
Remove boilerplate
Update copyright date
Blacken
Remove unused imports
Shorten docstrings
Remove CLI
> Translate: migrate published glossaries samples

- functions/composer/composer_storage_trigger.py
The configuration to send composer needs to be inside the data block rather than the JSON body itself
> Fix incorrect data submission

- dlp/inspect_content_test.py
[This doc](https://cloud.google.com/dlp/docs/inspecting-storage#reduce_latency) suggests that `FIRST_NAME` can really slow things down. Since we're not looking for it in out, and we're having test timeout issues, I want to try removing it from the problem tests.
Closes #2809 
Closes #2811 
Closes #2812
> Remove param to reduce latency (per docs)

- bigquery/bqml/data_scientist_tutorial_test.py
- bigquery/bqml/ncaa_tutorial_test.py
- bigquery/bqml/requirements.txt
- bigquery/bqml/resources/feature_input_query.sql
- bigquery/bqml/resources/training_data_query.sql
The BQML tests use a non-unique dataset ID for multiple examples and
testing currently triggers a lot of concurrent creation/deletions of
said dataset. Switch to a dataset that leverages uuid to avoid
invocations stomping on one another, which also necessitates
parameterizing much of the SQL.
There's also an issue with the pandas import currently, possibly due to
recent changes in panda. This change also pins pandas to 0.22 and
doesn't rely on the dependency being expressed as an extra through
google-cloud-bigquery.
> fix: address bigquery/bqml test failures 

- .kokoro/tests/run_tests.sh
The `buildcop.sh` is included in the Trampoline GCS directory.
> .kokoro: use buildcop.sh script to publish logs

- .kokoro/tests/run_tests.sh
The script sometimes runs into shell limits passing arguments to gcloud.
> .kokoro/testing: use buildcop binary to publish logs

- pubsub/cloud-client/README.rst
- pubsub/cloud-client/publisher.py
- pubsub/cloud-client/publisher_test.py
Publish concurrency control isn't supported by the Pub/Sub publisher client. After I dereference this sample on [Cloud Pub/Sub docs](https://cloud.google.com/pubsub/docs/publisher#concurrency), I will remove this sample from the repo.
> Pub/Sub: remove publish concurrency control sample

- opencensus/metrics_quickstart.py
- opencensus/metrics_quickstart_test.py
Slim down the opencensus tests to only check that the snippet runs successfully, and avoid testing the library / api.
Fixes #2903
> Simplify opencensus quickstart tests.

- dataproc/quickstart/quickstart_test.py
This test did not properly clean up the buckets after running the dataproc quickstart tests. Now it will :)
> fix: dataproc quickstart test to properly clean up gcs bucket during teardown

- appengine/standard/django/requirements.txt
another part of splitting up #2651
> Pin django to a specific version 

- automl/cloud-client/batch_predict_test.py
fix: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3052
> automl: fix batch test due to error message change

- iot/api-client/manager/manager_test.py
- iot/api-client/manager/requirements.txt
- iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
- iot/api-client/mqtt_example/cloudiot_mqtt_image_test.py
Replaces DevRel tools Flaky with [Flaky](https://github.com/box/flaky).
> Iot flaky tests

- pubsub/cloud-client/publisher.py
The previous sample resolves each publish future as each message is published, effectively skipping batching. 
The new sample uses the non-blocking function `add_done_callback()` on publish futures instead of `result()` in the main thread.
> Pub/Sub: update publish with batch settings sample

- noxfile-template.py
#3116 had a whitespace error that snuck in - Idk why lint didn't fail there, but it's failing on other PRs now because of it 🤷‍♀ this should hopefully fix that
> fix whitespace error that snuck in

- appengine/standard_python37/django/mysite/settings.py
- appengine/standard_python37/django/requirements.txt
Alternative to #3244 to continue PyMySQL support
> Bump Django version to 3.0 and set PyMySQL version

- healthcare/api-client/fhir/fhir_resources_test.py
- healthcare/api-client/fhir/fhir_stores_test.py
fixes #3072
fixes #3073
It might not fix it, but I'd like to see the test results.
> [healthcare] fix: use uuid for resource names

- healthcare/api-client/hl7v2/hl7v2_messages.py
- healthcare/api-client/hl7v2/hl7v2_messages_test.py
- healthcare/api-client/hl7v2/hl7v2_stores_test.py
- healthcare/api-client/hl7v2/requirements-test.txt
> [healthcare] fix: fix broken tests for healthcare API

- AUTHORING_GUIDE.md
Note that because many sections were added or completely re-written, the diff view is not helpful. This PR adds topics covered in the Java guide (for consistency), adds links to Google Cloud documentation where appropriate, and links to specific examples in existing samples where appropriate. Some sections have been removed to avoid duplication and simplify maintenance - for example, instead of showing the license header to use, it now links to the instructions in the LICENSE file for how to insert a license header.
Feedback welcome!
> re-write authoring guide, add links to other documentation

- appengine/flexible/pubsub/main.py
> appengine/flexible/pubsub: init publisher client globally

- iam/api-client/access_test.py
- iam/api-client/requirements-test.txt
fixes #3292
* use `uuid.uuid4()` instead of random
* retry write operations in the tests
> [iam] fix: reduce flakiness

- monitoring/api/v3/alerts-client/requirements-test.txt
- monitoring/api/v3/alerts-client/snippets_test.py
> [monitoring] testing: mitigate 409 conflicts

- .kokoro/lint/presubmit.cfg
- .kokoro/python2.7/continuous.cfg
- .kokoro/python2.7/presubmit.cfg
- .kokoro/python3.6/continuous.cfg
- .kokoro/python3.6/presubmit.cfg
- .kokoro/python3.7/continuous.cfg
- .kokoro/python3.7/presubmit.cfg
- .kokoro/python3.8/continuous.cfg
- .kokoro/python3.8/presubmit.cfg
- .kokoro/tests/run_tests.sh
- .kokoro/tests/run_tests_diff_head.sh
- .kokoro/tests/run_tests_diff_master.sh
- Switches continuous tests to only test files changed from the last commit 
- Switches buildcop to only report fails from the periodic build
Fixes #3314
> Switch continuous tests to only test changed files.

- datastore/cloud-ndb/flask_app_test.py
- datastore/cloud-ndb/quickstart_test.py
- datastore/cloud-ndb/requirements-test.txt
> [datastore] fix: handle datastore eventual consistency

- functions/slack/main.py
- functions/slack/main_test.py
- third_party/apache-airflow/plugins/gcs_plugin/hooks/gcs_hook.py
`googleapiclient` is the recommended import
> fix: import from googleapiclient, not apiclient

- datalabeling/create_annotation_spec_set_test.py
- datalabeling/create_instruction.py
- datalabeling/create_instruction_test.py
- datalabeling/import_data_test.py
- datalabeling/label_image_test.py
- datalabeling/label_text_test.py
- datalabeling/label_video_test.py
- datalabeling/manage_dataset_test.py
- datalabeling/requirements-test.txt
- datalabeling/testing_lib.py
fixes #3438 
fixes #3439 
We have been seeing flaky test results with the datalabeling test backends. This PR is wrapping all the rpc calls with `backoff` with `max_time=60`.
I believe this will significantly reduce the test flakiness. Here is an explanation.
If a test consists of multiple consecutive flaky rpc calls, the success rate of the test will become exponentially small as number of rpc grows.
Here is an example:
Let's say the success rate of a single rpc is always 0.9 (for simplicity) and
there is a test which has 8 consecutive rpc calls.
The success rate of the test as a whole:
0.9^8=~0.43
If we wrap this test with `pytest.mark.flaky(max_runs=3)`, the success rate of it:
1 - 0.57^3 = 0.81
If we wrap each rpc calls with retries, the success rate will be significantly higher. …
> [datalabeling] testing: wrap rpcs with backoff

- iot/api-client/mqtt_example/requirements-test.txt
- iot/api-client/mqtt_example/requirements.txt
- pubsub/cloud-client/publisher_test.py
- pubsub/cloud-client/requirements-test.txt
- pubsub/cloud-client/subscriber_test.py
> chore: remove gcp-devrel-py-tools from iot and pubsub

- logging/cloud-client/export_test.py
- logging/cloud-client/requirements-test.txt
- logging/cloud-client/snippets_test.py
> [logging] chore: remove gcp-devrel-py-tools

- monitoring/api/v3/api-client/custom_metric_test.py
- monitoring/api/v3/api-client/requirements-test.txt
- monitoring/api/v3/cloud-client/quickstart_test.py
- monitoring/api/v3/cloud-client/requirements-test.txt
- monitoring/api/v3/cloud-client/snippets_test.py
fixes #3347 
fixes #3348 
I'm having trouble running the test locally. I'll let Kokoro run the tests.
> [monitoring] chore: remove gcp-devrel-py-tools

- .kokoro/python3.6/periodic.cfg
- .kokoro/python3.7/periodic.cfg
- .kokoro/python3.8/periodic.cfg
Reverts GoogleCloudPlatform/python-docs-samples#3413
I don't think we need 7 hours any more.
> Revert "testing: bump the timeout for periodic builds"

- kms/api-client/snippets_test.py
fixes #3554
fixes #3555
It might fix the above issues.
> [kms] fix: use unique ids for test

- storage/cloud-client/storage_generate_signed_post_policy_v4.py
If name='submit' is specified for the input type='submit' the endpoint returns the following error:
<Error>
<Code>InvalidPolicyDocument</Code>
<Message>
The content of the form does not meet the conditions specified in the policy document.
</Message>
<Details>Policy did not reference these fields: submit</Details>
</Error>
> Remove name attribute from the input

- run/hello-broken/Dockerfile
- run/logging-manual/Dockerfile
- run/markdown-preview/editor/Dockerfile
- run/markdown-preview/renderer/Dockerfile
- run/system-package/Dockerfile
One of the Dockerfile sample practices we attempt on Cloud Run is to use `./` as the default destination of Dockerfile `COPY` statements.
It doesn't really change the behaviors we expect:
`COPY . .` = `COPY . ./`
`COPY README.md .` = `COPY README.md ./` = `COPY README.md README.md`
However, it matters when developers try to use the multi-source arguments option with COPY:
`COPY README.md main.py .` = ERROR!!
`COPY README.md main.py ./` = Happy Dance 👯 
By using `./` wherever just a `.` appears, it adds a little more noise to the Dockerfile but in exchange there's one less source of friction if developers iterate on top of the Dockerfiles we provide.
I'm working on standardizing this further, but for now sending a little PR to nudge Cloud Run Python alignment.
> run: Dockerfile COPY to ./

- vision/cloud-client/detect/vision_async_batch_annotate_images.py
- vision/cloud-client/detect/vision_async_batch_annotate_images_test.py
> [vision] fix: add timeout for LRO result and mark it as flaky

- healthcare/api-client/v1/fhir/requirements.txt
Remove unused oauth2client in healthcare samples.
Part of #2648
> chore: remove unused oauth2client in healthcare

- healthcare/api-client/v1/hl7v2/hl7v2_messages_test.py
Closes #3714
Test failed on `googleapiclient.HttpError`
```
Traceback (most recent call last):
File "/tmpfs/src/github/python-docs-samples/healthcare/api-client/v1/hl7v2/hl7v2_messages_test.py", line 209, in test_patch_hl7v2_message
hl7v2_message_id = run_eventually_consistent_test()
File "/tmpfs/src/github/python-docs-samples/healthcare/api-client/v1/hl7v2/.nox/py-3-7/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
ret = target(*args, **kwargs)
File "/tmpfs/src/github/python-docs-samples/healthcare/api-client/v1/hl7v2/hl7v2_messages_test.py", line 199, in run_eventually_consistent_test
project_id, cloud_region, dataset_id, hl7v2_store_id
File "/tmpfs/src/github/python-docs-samples/healthcare/api-client/v1/hl7v2/hl7v2_messages.py", line 184, in list_hl7v2_messages …
```
> Retry HttpErrors for test_patch_hl7v2_message

- datalabeling/create_annotation_spec_set.py
- datalabeling/export_data.py
- datalabeling/import_data.py
- datalabeling/label_image.py
- datalabeling/label_text.py
- datalabeling/label_text_test.py
- datalabeling/label_video.py
- datalabeling/manage_dataset.py
- datalabeling/manage_dataset_test.py
- datalabeling/testing_lib.py
> [datalabeling] fix: clean up old datasets before the test

- healthcare/api-client/dicom/dicom_stores_test.py
- healthcare/api-client/dicom/requirements.txt
- healthcare/api-client/v1/dicom/dicom_stores_test.py
- healthcare/api-client/v1/dicom/requirements.txt
> [healthcare] fix: create/delete the Pub/Sub topic

- container_registry/container_analysis/samples_test.py
> [container-registry] fix: mark a flaky test

- media-translation/cloud-client/README.rst
- media-translation/cloud-client/README.rst.in
- scripts/readme-gen/templates/README.tmpl.rst
> [media-translation] docs: hide cloud shell button for mic sample

- .kokoro/python3.6/common.cfg
- .kokoro/python3.7/common.cfg
- .kokoro/python3.8/common.cfg
- monitoring/api/v3/alerts-client/README.rst
- monitoring/api/v3/alerts-client/README.rst.in
- scripts/readme-gen/templates/README.tmpl.rst
Also added `required_api_url` and `required_role` field in `README.rst.in`.
A part of #3310 
Note: Now the service account has permission only on the project for py36 build, so py37 build should fail.
> [monitoring] testing: start using build specific projects

- .kokoro/tests/run_tests.sh
- scripts/decrypt-secrets.sh
- scripts/encrypt-secrets.sh
* activate the secret service account only when the key is there
* merge automl_secrets.txt into test-env.sh
* if .kokoro/docker or .kokoro/tests have changes, test everything
* remove stale apt-get command
* use SECRET_MANAGER_PROJECT envvar for secret manager command,
fallback to cloud-devrel-kokoro-resources
fixes #3820
> testing: various cleanups

- bigquery/cloud-client/README.rst
- bigquery/cloud-client/README.rst.in
- bigquery/cloud-client/noxfile_config.py
> [bigquery] opt in to use the build specific projects

- monitoring/api/v3/api-client/custom_metric.py
- monitoring/api/v3/api-client/custom_metric_test.py
> [monitoring] fix: use the same random value for retry

- .kokoro/docker/Dockerfile
- .kokoro/lint/common.cfg
- .kokoro/lint/continuous.cfg
- .kokoro/lint/periodic.cfg
- .kokoro/lint/presubmit.cfg
- .kokoro/python2.7/common.cfg
- .kokoro/python2.7/continuous.cfg
- .kokoro/python2.7/periodic.cfg
- .kokoro/python2.7/presubmit.cfg
- .kokoro/python3.6/common.cfg
- .kokoro/python3.6/continuous.cfg
- .kokoro/python3.6/periodic.cfg
- .kokoro/python3.6/presubmit.cfg
- .kokoro/python3.7/common.cfg
- .kokoro/python3.7/continuous.cfg
- .kokoro/python3.7/periodic.cfg
- .kokoro/python3.7/presubmit.cfg
- .kokoro/python3.8/common.cfg
- .kokoro/python3.8/continuous.cfg
- .kokoro/python3.8/periodic.cfg
- .kokoro/python3.8/presubmit.cfg
- .kokoro/tests/run_tests.sh
- .kokoro/trampoline_v2.sh
- .trampolinerc
- .trampolinerc_tmpl
- scripts/decrypt-secrets.sh
- scripts/run_tests_local.sh
This PR changes the build file to `trampoline_v2.sh` for all the jobs.
`trampoline_v2.sh` does 3 things.
1. Prepare the Docker image for the test
2. Run the Docker with appropriate flags to run the test
3. Upload the newly built Docker image
in a way that is somewhat compatible with trampoline_v1.
It also behaves better in many ways.
1. It uses the same uid as the caller, use the same gid as docker group on the host.
2. No permission change required upon cleanup.
3. It's bit more portable so that much easier to run somewhere other than Kokoro including local env.
4. It can optionally build the docker image from the source then use the built image for the test, so that you can have a single PR for changing the Dockerfile and tests.
5. Logging with timestamp. Easier to determine the …
> testing: migrate to trampoline_v2

- .kokoro/tests/run_tests.sh
This change allows us to only run necessary tests for Pull Requests.
> testing: diff against the common commit on the master

- dlp/conftest.py
- dlp/risk_test.py
* changed the Pub/Sub fixtures to `function` level
* shorten the timeout for the tests from 300 secs to 30 secs
* retrying all the tests in risk_test.py  just one time with 20 mins (!) delay
* total time of retry delay is limited to 1 hour
fixes #3921
fixes #3897
fixes #3896
fixes #3895
fixes #3894
fixes #3893
fixes #3892
fixes #3890
fixes #3889
> [dlp] fix: mitigate flakiness

- pubsub/cloud-client/subscriber.py
Use `nargs='?'` for a positional argument to make it optional. 
Old behavior: 
1. `python subscriber.py $PROJECT receive $SUBSCRIPTION_NAME` complains about `timeout` not set, and one has to add `--timeout`.
1. `python subscriber.py $PROJECT receive $SUBSCRIPTION_NAME --timeout=5` runs with a `timeout` value of 5 seconds.
New behavior: 
1. `python subscriber.py $PROJECT receive $SUBSCRIPTION_NAME` will run with a default `timeout` value, which is `None`.
1. `python subscriber.py $PROJECT receive $SUBSCRIPTION_NAME 5` will run with a `timeout` value of 5 seconds.
> fix: make timeout an optional positional arg

- spanner/cloud-client/snippets.py
The [Deleting rows in a table](https://cloud.google.com/spanner/docs/modify-mutation-api#deleting_rows_in_a_table) section gives four different delete methods but only two methods were demonstrated.
This PR adds the missing methods.
> Improve Spanner delete_data sample coverage

- pubsub/cloud-client/iam.py
- pubsub/cloud-client/iam_test.py
- pubsub/cloud-client/publisher.py
- pubsub/cloud-client/quickstart/pub.py
- pubsub/cloud-client/quickstart/sub.py
- pubsub/cloud-client/quickstart/sub_test.py
- pubsub/cloud-client/subscriber.py
Users have pointed out that when we say topic name and subscription name in the samples, we actually mean topic id and subscription id. Updating the samples to reflect this.
> Pub/Sub: replace name with id in samples

- cloud-sql/mysql/sqlalchemy/README.md
- cloud-sql/mysql/sqlalchemy/app.flexible.yaml
- cloud-sql/mysql/sqlalchemy/app.standard.yaml
- cloud-sql/mysql/sqlalchemy/main.py
- cloud-sql/postgres/sqlalchemy/README.md
- cloud-sql/postgres/sqlalchemy/app.flexible.yaml
- cloud-sql/postgres/sqlalchemy/app.standard.yaml
- cloud-sql/postgres/sqlalchemy/main.py
- cloud-sql/sql-server/sqlalchemy/README.md
- cloud-sql/sql-server/sqlalchemy/app.yaml
- cloud-sql/sql-server/sqlalchemy/main.py
* Rename environment variable DB_SOCKET_PATH to  DB_SOCKET_DIR for better description of its contents
* Move region tags and refactor code so as to give users a better sample experience
> refactor Cloud SQL samples

- firestore/cloud-client/snippets.py
f-strings is the preferred way to format strings in Python 3
> Change string format to f-strings

- datastore/cloud-client/snippets.py
This snippet shows up here:
https://cloud.google.com/datastore/docs/concepts/structuring_for_strong_consistency#datastore-datastore-eventual-consistent-query-python
The eventual parameter is specified in the docs:
https://googleapis.dev/python/datastore/latest/queries.html
To check this, I ran the snippet:
```
>>> from google.cloud import datastore
>>> client = datastore.Client()
>>> query = client.query(kind='Task')
>>> query.fetch(eventual=True)
<google.cloud.datastore.query.Iterator object at 0x1023a2860>
>>> query.fetch()
<google.cloud.datastore.query.Iterator object at 0x1023a28d0>
```
> Add Datastore eventual consistency read example

- firestore/cloud-client/snippets.py
This snippet is used in these docs:
https://cloud.google.com/firestore/docs/query-data/queries#python_3
Which say:
> After creating a query object, use the get() function to retrieve the results:
That's true for the other languages, but not for Python, which has deprecated get() and replaced it with stream(), based on these docs:
https://googleapis.dev/python/firestore/latest/collection.html#google.cloud.firestore_v1.collection.CollectionReference.get
> chore: add note about preference of stream() to get()

- dlp/README.rst
- dlp/redact.py
- dlp/redact_test.py
The sample shows how to remove all text found in an image with DLP.
The sample is integrated into the existing redact.py CLI application.
> Add DLP sample for redacting all image text

- appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
- appengine/standard/endpoints-frameworks-v2/quickstart/requirements.txt
- appengine/standard/migration/ndb/overview/main_test.py
fixes #4072
I also needed to disable one failing test at appengine/standard/migration/ndb/overview.
The failing test is reported at #4076
> [appengine] pin rsa to 4.0

- .kokoro/python2.7/common.cfg
- .kokoro/python3.6/common.cfg
- .kokoro/python3.7/common.cfg
- .kokoro/python3.8/common.cfg
- .kokoro/tests/run_tests.sh
Experimenting with different number of workers.
lint, py-2.7, py-3.6:
default (I think it's 6 on Kokoro)
py-3.7:
12
py-3.8:
20
> [btlr] testing: use NUM_TEST_WORKERS env var

- dlp/custom_infotype.py
- dlp/custom_infotype_test.py
Add DLP code sample and test for medical number custom detector with hotwords, meant for https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#increase_the_likelihood_of_a_person_name_match_if_there_is_the_hotword_patient_nearby
Add corresponding unit tests.
> Add DLP code sample and test for person_name detector with hotwords

- dlp/inspect_content.py
- dlp/inspect_content_test.py
Add a basic DLP code sample that just inspects with an infotype. This sample will be linked to the documentation at http://cloud/dlp/docs/concepts-infotypes#how_to_use_infotypes.
Please merge this PR after approving.
> Add a simplified inspect string example to DLP code samples

- dlp/deid.py
- dlp/deid_test.py
Add DLP code sample for reid w/ fpe using surrogate type and unwrapped security key, meant for https://cloud.google.com/dlp/docs/pseudonymization#re-identification_in_free_text_code_example
Add corresponding unit test.
Note: The added function deviates in terms of style from other functions in the same file. This is necessary because as a documentation snippet it has to be more specific to fit in the particular narrative of the documentation linked above. It is not integrated as part of the commandline tool in deid.py for the same reason.
Please automerge upon approval
> Add DLP sample code for reid w/ fpe using surrogate type and unwrapped security key

- video/cloud-client/analyze/beta_snippets.py
[Another PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4041) is blocked due to the use of positional arguments in the Video Intelligence samples. This PR changes one sample to use named arguments.
This fix updates the following region tags:
+ `video_speech_transcription_gcs_beta`
> fix: changes a positional to named arg

- iam/api-client/service_accounts_test.py
Fixes #4087
It turned out that looking up by e-mail is eventual consistent (although normally few seconds, but it can be up to few minutes in the worst case). If we use the uniqueId, the lookup should be strong consistent.
> [iam] testing: use uniqueId instead of email

- .kokoro/docker/Dockerfile
- .kokoro/python3.8/periodic.cfg
also enable the Docker image upload in python 3.8 periodic build.
fixes #4126
> testing: update the python versions in the Dockerfile

- AUTHORING_GUIDE.md
Use f-strings in the Authoring Guide to encourage new samples to use this style of string formatting.
> Use f-strings in the Authoring Guide

- .kokoro/tests/run_tests.sh
- .kokoro/trampoline_v2.sh
- scripts/decrypt-secrets.sh
We should be able to use Compute Engine default service account on Kokoro builds.
> testing: use default service account

- monitoring/api/v3/uptime-check-client/requirements-test.txt
- monitoring/api/v3/uptime-check-client/snippets_test.py
> [monitoring] fix: mitigate flake

- .kokoro/docker/Dockerfile
fixes #4155
Now we're using trampoline_v2.sh to run the test, so this change will be also tested in the presubmit builds.
> testing: upgrade the base image to Ubuntu 18.04

- AUTHORING_GUIDE.md
> add a section for installing coreutils on MacOS

- .kokoro/docker/Dockerfile
- .kokoro/docker/fetch_gpg_keys.sh
- .kokoro/trampoline_v2.sh
- vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
fixes #4162
fixes #4173 
Also copied the latest `trampoline_v2.sh`, which suppress docker build logs on CI systems.
> testing: reliablly fetch gpg keys

- tables/automl/dataset_test.py
fixes #4177
fixes #4178
I needed to modify the csv file to only have positive values in the `Balance` column. I don't have a permission on the `cloud-ml-tables-data`, so I created a new bucket and uploaded the file there. Here is a throw-away python script to modify the csv:
```python
from tempfile import NamedTemporaryFile
import shutil
import csv
filename = 'bank-marketing.csv'
tempfile = NamedTemporaryFile(mode='w', delete=False)
fields = ['Age','Job','MaritalStatus','Education','Default','Balance','Housing','Loan','Contact','Day','Month','Duration','Campaign','PDays','Previous','POutcome','Deposit']
with open(filename, 'r') as csvfile, tempfile:
reader = csv.DictReader(csvfile, fieldnames=fields)
writer = csv.DictWriter(tempfile, fieldnames=fields)
for row in reader:
if row['Age'] != …
```
> [tables/automl] fix: update the csv file and the dataset name

- spanner/cloud-client/backup_sample_test.py
- spanner/cloud-client/snippets_test.py
> fix(spanner): use uuid for unique id

- vision/cloud-client/product_search/product_in_product_set_management_test.py
> testing(vision): use different ids for test functions

- translate/cloud-client/translate_v3_batch_translate_text.py
- translate/cloud-client/translate_v3_batch_translate_text_with_glossary.py
- translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py
- translate/cloud-client/translate_v3_create_glossary.py
- translate/cloud-client/translate_v3_delete_glossary.py
fixes #4239
(by specifying a longer timeout)
> testing(translate): parameterize the timeout

- .kokoro/trampoline_v2.sh
- scripts/run_tests_local.sh
Upgrade to Trampoline 2.0.3.
This version has a nice cleanup. It makes the script `run_tests_local.sh` cleaner and faster for most cases.
Note:
The changes in `trampoline_v2.sh` is reviewed (and tested) in [another repo](https://github.com/GoogleCloudPlatform/docker-ci-helper). We're copying the script into this repo.
> chore: upgrade to trampoline 2.0.3

- appengine/standard_python3/pubsub/main.py
The latest https://github.com/googleapis/google-auth-library-python/releases/tag/v1.19.0 checks the issuer claim automatically via `verify_oauth_token2`. Remove code in the sample that does this check manually. See [PR #500](https://github.com/googleapis/google-auth-library-python/pull/500).
> Pub/Sub: no need to verify issuer in JWT

- renovate.json
> experiment: only update pytest major/minor version

- appengine/standard/firebase/firenotes/backend/app.yaml
- appengine/standard/firebase/firenotes/backend/main.py
Fixes #4268, undoes PR #4311 
Problem seemed to be inclusion of an unneeded environment variable. Actual problem was that the environment variable wasn't being used where it was optional, but important. Also, used a unique name for variable instead of standard GOOGLE_CLOUD_PROJECT.
- [ X] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ X] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ X] **Lint** pass:   `nox -s lint` (see [Test Enviroment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ X] …
> Fix audience

- .kokoro/tests/run_tests_orig.sh
This allows users to use `scripts/run_tests_local.sh` without having
secret files.
A typical use case is to run readmegen or lint locally without preparing
their own secrets.
@rebeccawshaw FYI
> testing: allow missing secrets

- translate/cloud-client/translate_v3_batch_translate_text_test.py
- translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py
This PR increases the timeout for the `translate_v3_batch_translate_text_test` from 240 to 300.
Fixes #4221
Fixes #4239
> fix: increase batch translation timeout to 300

- video/cloud-client/analyze/beta_snippets_test.py
- video/cloud-client/analyze/requirements-test.txt
> testing(videointelligence): retry harder upon 409s

- translate/automl/dataset_test.py
- translate/automl/model_test.py
> fix(translate): fix a broken test
