- bigquery/tests/test_async_query.py
> Fixed broken travis build.

- README.md
Signed-off-by: Peng Xiao <xiaoquwl@gmail.com>
> modify the url link address in README.md

- .coveragerc
- cloud_logging/README.md
- cloud_logging/api/list_logs.py
- cloud_logging/api/list_logs_test.py
- storage/api/list_objects.py
/cc @sharbison3, note the new file names and region tags.
> Adding cloud logging api sample.

- compute/api/create_instance.py
- compute/api/create_instance_test.py
- compute/api/startup-script.sh
/cc @waprin @jerjou.
Original repository: https://github.com/GoogleCloudPlatform/compute-getting-started-python
> Moving compute engine getting started example to this repository.

- appengine/storage/README.md
- appengine/storage/app.yaml
- appengine/storage/index.html
- appengine/storage/listing.html
- appengine/storage/main.py
Original from: https://github.com/GoogleCloudPlatform/storage-appengine-bucket-lister-python
Bugs will be created to bring this up to standards.
> Migrating sample.

- appengine/cloudsql/README.md
- appengine/cloudsql/app.yaml
- appengine/cloudsql/main.py
Original sample: https://github.com/GoogleCloudPlatform/appengine-cloudsql-native-mysql-demo-python
> Moving sample

- bigquery/api/export_data_to_cloud_storage_test.py
- bigquery/api/load_data_from_csv_test.py
- compute/api/create_instance_test.py
- requirements-dev.txt
- tox.ini
> Annotating slower tests and excluding them from travis.

- appengine/angular/README.md
- appengine/angular/app.yaml
- appengine/angular/app/css/app.css
- appengine/angular/app/index.html
- appengine/angular/app/js/app.js
- appengine/angular/app/partials/insert.html
- appengine/angular/app/partials/main.html
- appengine/angular/app/partials/update.html
- appengine/angular/main.py
- appengine/angular/model.py
- appengine/angular/scripts/deploy.sh
- appengine/angular/scripts/run.sh
From [this repo](https://github.com/GoogleCloudPlatform/appengine-angular-hello-world-python)
> Move over appengine-angular-hello-world-python

- bigquery/api/streaming.py
> insertId is within the row, not the request.

- .travis.yml
https://bitbucket.org/hpk42/tox/issues/285/tox-220-breaks-some-toxini-config-files
> Temoprarily Pin Tox Until Bug Is Fixed

- appengine/app_identity/signing/main.py
- appengine/bigquery/main.py
- appengine/blobstore/main.py
- appengine/cloudsql/main.py
- appengine/i18n/main.py
- appengine/images/main.py
- appengine/mailgun/main.py
- appengine/memcache/guestbook/main.py
- appengine/multitenancy/datastore.py
- appengine/multitenancy/memcache.py
- appengine/multitenancy/taskqueue.py
- appengine/ndb/modeling/contact_with_group_models.py
- appengine/ndb/modeling/keyproperty_models.py
- appengine/ndb/modeling/naive_models.py
- appengine/ndb/modeling/parent_child_models.py
- appengine/ndb/modeling/relation_model_models.py
- appengine/ndb/modeling/structured_property_models.py
- appengine/ndb/overview/main.py
> Cleaning up docstrings

- cloud_logging/api/list_logs_test.py
> Moving logging samples to py.test

- container_engine/django_tutorial/mysite/settings.py
Accidentally committed specific settings.
@jonparrott FYI, I think this is an auto-merge.
> Remove database settings

- speech/api/speechrest.py
- speech/api/speechrest_test.py
> Add test for speech sample.

- appengine/taskqueue/counter/README.md
- appengine/taskqueue/counter/app.yaml
- appengine/taskqueue/counter/counter.html
- appengine/taskqueue/counter/main.py
- appengine/taskqueue/counter/main_test.py
- appengine/taskqueue/counter/queue.yaml
Counter app. Copied from: https://github.com/GoogleCloudPlatform/appengine-taskqueue-counter
Added tests.
> App Engine Task Queue Sample.

- compute/auth/access_token.py
- compute/auth/access_token_test.py
- compute/auth/application_default.py
- compute/auth/application_default_test.py
- compute/auth/requirements.txt
> Adding compute auth examples

- appengine/ndb/entities/snippets_test.py
- appengine/ndb/properties/snippets_test.py
- appengine/ndb/property_subclasses/README.md
- appengine/ndb/property_subclasses/my_models.py
- appengine/ndb/property_subclasses/snippets.py
- appengine/ndb/property_subclasses/snippets_test.py
Also clean up an unnecessary fixture
> Move ndb property subclasses snippets from cloudsite

- speech/api/README.md
> Add missing -r flag to pip install.

- monitoring/api/v3/custom_metric.py
> Don’t send name in create custom metric

- appengine/mailjet/requirements.txt
- compute/encryption/requirements.txt
- managed_vms/mailjet/requirements.txt
@jonparrott fyi, forgot it stops checking on first failure
> More req updates

- managed_vms/sendgrid/main.py
- managed_vms/sendgrid/main_test.py
> Adding sendgrid tests, fixes #182

- appengine/flexible/endpoints/main.py
- appengine/flexible/endpoints/main_test.py
- appengine/flexible/endpoints/requirements.txt
- appengine/flexible/endpoints/swagger.yaml
Also adding test to the endpoint sample, which I somehow forgot to do.
> Adding firebase auth to endpoints sample, fixes #396

- speech/api/README.md
> Documentation fix

- appengine/flexible/hello_world_django/README.md
Fix typo with Flask CloudSQL link in README.md
> Fix Flask CloudSQL link

- bigquery/api/list_datasets_projects.py
(This comment looks like it doesn't belong here.)
> Remove stray comment

- nox.py
@waprin fyi, trying this out to see if it fixes stuff.
> Add workaround for travis commit being wrong.

- appengine/standard/endpoints-frameworks-v2/echo/app.yaml
- appengine/standard/endpoints-frameworks-v2/quickstart/app.yaml
Causes an error in `gcloud beta app deploy`
> Ignore bad file in endpoints lib

- appengine/standard/localtesting/runner.py
> Fixup GAE standard test runner sample

- monitoring/README.md
- monitoring/api/v2/README.md
- monitoring/api/v2/auth.py
- monitoring/api/v2/labeled_custom_metric.py
- monitoring/api/v2/lightweight_custom_metric.py
- monitoring/api/v3/README.md
- monitoring/api/v3/custom_metric.py
- monitoring/api/v3/list_resources.py
Renaming some APIs to Stackdriver brand
> Stackdriver product rename

- bigquery/cloud-client/async_query.py
This method was added in
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2083.
I can remove my hack now.
> BigQuery - use new QueryJob.results() method.

- appengine/standard/README.md
- appengine/standard/firebase/firetactoe/README.md
- appengine/standard/firebase/firetactoe/app.yaml
- appengine/standard/firebase/firetactoe/appengine_config.py
- appengine/standard/firebase/firetactoe/credentials.json
- appengine/standard/firebase/firetactoe/firetactoe.py
- appengine/standard/firebase/firetactoe/requirements.txt
- appengine/standard/firebase/firetactoe/static/main.css
- appengine/standard/firebase/firetactoe/static/main.js
- appengine/standard/firebase/firetactoe/templates/_firebase_config.html
- appengine/standard/firebase/firetactoe/templates/fire_index.html
Mostly a refactor of stuff from @mogar1980 #558
> Add firebase-based tic-tac-toe sample.

- bigtable/hello_happybase/README.md
> Fix link to bigtable happybase package.

- appengine/standard/firebase/firetactoe/creds.json
- appengine/standard/firebase/firetactoe/firetactoe.py
- appengine/standard/firebase/firetactoe/rest_api.py
Also - remove unnecssary region tags.
> Re-add firebase rest_api examples.

- appengine/flexible/memcache/README.md
- appengine/flexible/memcache/app.yaml
- appengine/flexible/memcache/main.py
- appengine/flexible/memcache/requirements.txt
R: @justinbeckwith
/cc @jmdobry @bshaffer @broady @tmatsuo @lesv @remi
> Add support for third-party memcache

- compute/xmpp_wikibot/requirements.txt
- compute/xmpp_wikibot/wikibot.py
> Simplify xmpp wikibot a bit

- appengine/standard/firebase/firetactoe/appengine_config.py
> Add appengine workaround for oauth

- ISSUE_TEMPLATE.md
This should help us triage issues, for people who don't realize that this repo
contains multiple apis with multiple samples.
> Add issue template.

- endpoints/getting-started/Dockerfile.custom
Need to link to source of Docker image
> Add comment about python runtime to Dockerfile

- storage/cloud-client/encryption.py
Changed upload/download functions to initialize blob using constructor, allowing encryption to work.
Also fixed a few typos in parser construction
> Edited upload/download to perform encryption properly

- storage/cloud-client/encryption.py
- storage/cloud-client/encryption_test.py
Cloud Storage encryption key rotation sample in veneer:
- Implemented rotate_encryption_key
- Added test_rotate_encryption_key and made another minor fix to test file
- Verified that all tests pass both programmatically and from command line
Feature Request 32908100 in Buganizer
> Storage Encryption Key Rotation Sample using Veneer + Tests

- appengine/standard/angular/app.yaml
Bug #33145347
Tested locally/deployed
> Fixed broken app.yaml for angular sample

- bigquery/cloud-client/async_query.py
- bigquery/cloud-client/export_data_to_gcs.py
- bigquery/cloud-client/load_data_from_file.py
- bigquery/cloud-client/snippets.py
Reviewed all other BigQuery samples and found that bug #33164873 's solution could also be applied to these files.
> Changed error handling for all other BigQuery samples as well

- endpoints/bookstore-grpc/http_bookstore.proto
This is for  gRPC transcoding tutorial document.
> Added http_bookstore.proto for grpc transcoding.

- appengine/flexible/multiple_services/gateway-service/app.yaml
- appengine/flexible/multiple_services/static-service/app.yaml
- endpoints/getting-started/app.yaml
> Replace 'vm: true' with 'env: flex' in yaml files.

- translate/cloud-client/snippets.py
The snippet is for sample code using the premium (NMT) model, this changes the default parameter to match.
> Changes default model to premium

- appengine/flexible/memcache/README.md
- appengine/flexible/memcache/main.py
This is just for people who are browsing on Github and might not be aware (I made this 
mistake). Addresses #752.
> Add note about memcache whitelist

- appengine/flexible/endpoints/README.md
- appengine/flexible/endpoints/openapi.yaml
- endpoints/getting-started/README.md
- endpoints/getting-started/openapi.yaml
* Use 'security' directive instead of 'x-security'
* Replace x-issuer, x-jwks_uri, audiences with x-google-issuer, x-google-jwks_uri, x-google-audiences.
> Update auth config and README

- endpoints/getting-started/openapi.yaml
In order to allow for includes
> Add region tags for firebase auth to openapi.yaml

- speech/grpc/requirements.txt
- speech/grpc/transcribe.py
- speech/grpc/transcribe_async.py
- speech/grpc/transcribe_streaming.py
Per @lukesneeringer's comment in #811, update grpc speech lib.
> Update grpc python lib for speech.

- monitoring/api/v3/cloud-client/quickstart.py
This makes quickstart more copy-pasteable.
> Update monitoring region tags

- appengine/flexible/django_cloudsql/app.yaml
- appengine/flexible/django_cloudsql/mysite/settings.py
- appengine/flexible/django_cloudsql/requirements.txt
Corresponding tutorial changes coming very soon
> Django flex sample: mysql -> postgres

- video/cloud-client/analyze/analyze.py
updated the gcs files used in Usage to use public ones. Hopefully the readme will be updated
> updated the gcs files used in Usage

- video/cloud-client/faces/faces.py
since the file does not exist. Propose to use the same one as the tutorial: demomaker/gbikes_dinosaur.mp4
Note: hopefully this will automatically update the readme too
> change the usage file as it does not exist

- video/cloud-client/shotchange/shotchange.py
since the file does not exist. Propose to use the same one as the tutorial: demomaker/gbikes_dinosaur.mp4
Note: hopefully this will automatically update the readme too
> change the usage file sample

- storage/transfer_service/aws_request.py
- storage/transfer_service/nearline_request.py
The sample positions of date parameters (year, month, day) aren't in the correct order that's expected.
> [Storage] Fix for transfer storage sample

- iot/api-client/mqtt_example/cloudiot_mqtt_example.py
Fixes for python3 compatibility.
> Print is a function.

- video/cloud-client/analyze/analyze.py
Addresses https://github.com/GoogleCloudPlatform/python-docs-samples/issues/990
> Places format calls inside print function calls.

- appengine/standard/channel/app.yaml
- appengine/standard/modules/backend.yaml
- appengine/standard/taskqueue/counter/app.yaml
- appengine/standard/taskqueue/counter/worker.yaml
- appengine/standard/taskqueue/pull-counter/worker.yaml
> module -> service in app.yamls

- speech/cloud-client/transcribe.py
- speech/cloud-client/transcribe_async.py
- speech/cloud-client/transcribe_streaming.py
This updates python doc samples for Speech API so the included samples can be correctly formatted in documentations.
> Use region tags for Speech API samples

- bigquery/cloud-client/.gitignore
- bigquery/cloud-client/auth_snippets.py
- bigquery/cloud-client/auth_snippets_test.py
For inclusion on https://cloud.google.com/bigquery/authentication
> BigQuery: add auth samples for service accounts.

- language/cloud-client/v1beta2/quickstart.py
- language/cloud-client/v1beta2/snippets.py
move region tags so that the beta page only include codes from the relevant file (snippets.py) which contains the entity_sentiment method.
> language beta move region tags

- appengine/flexible/django_cloudsql/mysite/settings.py
> Make port explicit in configuration so it is clear how to change to MySQL

- bigquery/cloud-client/snippets.py
Also, running a query is not "preferred" if you do want all the data. If you do run a query, you end up reading data from the destination table anyway.
> BigQuery : max_results changes page size not full list size

- endpoints/bookstore-grpc/README.md
> Add message about transcoding to Endpoints Bookstore README.

- appengine/flexible/pubsub/main.py
- appengine/flexible/pubsub/requirements.txt
- pubsub/cloud-client/iam.py
- pubsub/cloud-client/iam_test.py
- pubsub/cloud-client/publisher.py
- pubsub/cloud-client/publisher_test.py
- pubsub/cloud-client/quickstart.py
- pubsub/cloud-client/quickstart_test.py
- pubsub/cloud-client/requirements.txt
- pubsub/cloud-client/subscriber.py
- pubsub/cloud-client/subscriber_test.py
> Update pubsub samples

- language/cloud-client/v1/requirements.txt
- language/cloud-client/v1beta2/requirements.txt
- language/sentiment/requirements.txt
> Client version update

- bigquery/cloud-client/query.py
- bigquery/cloud-client/query_test.py
See: https://cloud.google.com/bigquery/docs/writing-results
> BigQuery : add sample for writing query results to a destination table.

- iot/api-client/README.md
1. gcloud alpha should be gcloud beta
2. --pubsub-topic should be --event-pubsub-topic 
3. Updated the link to the docs
4. Added info about the Publisher role for the Pub/Sub topic
> Small fixes to README.md

- storage/cloud-client/notification_polling.py
Adds support for displaying GCS overwrite-related attributes.
Also fixes a formatting bug for output.
> Add support for overwrite attributes

- storage/cloud-client/notification_polling.py
Fixes error in previous pull request, #1142
> Fix storage notification_puller example when generation unset

- bigtable/metricscaler/metricscaler.py
> Bigtable autoscaler: use size variable

- iot/api-client/http_example/cloudiot_http_example.py
Also refactors message sending code from main
> Adds cache control header and HTTP/2 headers

- kms/api-client/snippets.py
- kms/api-client/snippets_test.py
To use for documentation purposes.
> Adds snippets for enabling and restoring a key version

- appengine/flexible/hello_world/app.yaml
For consistency with the other quickstarts, adjust this one to use manual scaling as well.
> Consistency with other quickstarts

- video/cloud-client/analyze/analyze.py
- video/cloud-client/analyze/analyze_test.py
- video/cloud-client/analyze/requirements.txt
- video/cloud-client/faces/faces.py
- video/cloud-client/faces/faces_test.py
- video/cloud-client/faces/requirements.txt
- video/cloud-client/labels/labels.py
- video/cloud-client/labels/labels_test.py
- video/cloud-client/labels/requirements.txt
- video/cloud-client/quickstart/quickstart.py
- video/cloud-client/quickstart/requirements.txt
- video/cloud-client/shotchange/requirements.txt
- video/cloud-client/shotchange/shotchange.py
Update samples to use videointelligence v1 client library.
DO NOT MERGE until tested against the released client library.
> update samples to v1

- bigquery/cloud-client/auth_snippets.py
> buckets -> datasets in BigQuery auth sample

- vision/cloud-client/detect/beta_snippets.py
remove `unicode` which caused errors in python3.
> remove unicode

- video/cloud-client/faces/faces_test.py
Will update when the feature FACE_DETECTION is enabled in the test project.
> Temporarily Disabled the Test

- endpoints/getting-started/app.yaml
Deleted a space before the END region tag.
> Region tag must start in column 1

- appengine/standard/firebase/firenotes/README.md
The URL to test in localhost it was wrong.
> Fix URL to test in localhost

- iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py
Changed the API version to v1 and fixed the modifyCloudToDeviceConfig REST API payload.
> Fix the api version and payload for iot end to end example

- pubsub/cloud-client/subscriber_test.py
This is a separate PR from actually adding the sample, which is in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1331.
> Add tests for creating push subscription.

- pubsub/cloud-client/subscriber.py
The documentation specifies that the update subscription commands show how to update an endpoint URL: https://cloud.google.com/pubsub/docs/admin#update_a_subscription.
> Change update_subscription to change endpoint URL.

- iot/api-client/http_example/cloudiot_http_example.py
- iot/api-client/http_example/cloudiot_http_example_test.py
- iot/api-client/mqtt_example/cloudiot_mqtt_example.py
Updates endpoint for HTTP and correctly sets TLS to 1.2 for MQTT.
> Device samples changes

- monitoring/api/v3/api-client/custom_metric.py
> Fix client instantiation

- auth/api-client/snippets.py
- auth/cloud-client/snippets.py
- auth/http-client/snippets.py
Related:
* GoogleCloudPlatform/ruby-docs-samples#255
* GoogleCloudPlatform/google-cloud-java#3066
> Clean up Auth region tags.

- video/cloud-client/analyze/requirements.txt
Update requirements.txt to the most recent client library version.
> Videointelligence API: update client library version

- cdn/snippets.py
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
> cdn: replace BEGIN with START in region tag

- vision/cloud-client/detect/detect_pdf_test.py
- vision/cloud-client/detect/requirements.txt
Update client library version, and update the test.
> detect-pdf update

- vision/cloud-client/detect/detect_test.py
Sometimes, Vision sees Zepra.  Othertimes, it sees Electra Tower.
> Fix the vision geo test.

- pubsub/cloud-client/publisher.py
- pubsub/cloud-client/publisher_test.py
- pubsub/cloud-client/requirements.txt
Replaced `concurrent.futures.wait()` with `while True: time.sleep()`. Added the new publisher function in __main__. Cleaned up `requirements.txt`.
> Modified publisher with error handling

- functions/helloworld/sample_pubsub_test_system.py
- functions/helloworld/sample_storage_test_system.py
These were accidentally removed in the initial merge.
> Add system tests for pubsub and storage GCF

- composer/workflows/bq_notify.py
- composer/workflows/connections.py
- composer/workflows/connections_test.py
- composer/workflows/kubernetes_pod_operator.py
- composer/workflows/quickstart.py
- composer/workflows/simple.py
- composer/workflows/use_local_deps.py
@fenglu-g please take a look. These samples will appear in the docs in my CL 205007055.
> Add samples for using GCP connections in an Airflow DAG

- language/automl/dataset_test.py
> use lcm instead of vcm

- composer/workflows/kubernetes_pod_operator.py
I believe this will make it clearer what the actual value should be for the affinity label.
@noremac201 please review.
> Use example node pool names for affinity argument

- appengine/standard_python37/building-an-app/building-an-app-3/main.py
Added region tags around import statements for use in documentation.
> Added region tags

- appengine/standard_python37/building-an-app/building-an-app-3/static/script.js
Edited region tags for use in documentation
> Edit region tags in script.js

- nox.py
Directory-specific linting (e.g. `nox -s "lint(sample='./functions/tips')"`) is not working, which is in turn breaking CI. This PR restores this functionality.
> Fix nox not recognizing directories

- vision/cloud-client/detect/beta_snippets.py
These samples need to be tracked separately from GA, so we are changing the tags
> Udpate Beta Vision samples to use beta tags

- functions/concepts/main.py
- functions/helloworld/main.py
- functions/tips/main.py
> Add Request doc links

- storage/cloud-client/requirements.txt
Removing the leftover merge conflict that's tripping DPEbot up.
> Remove leftover merge conflict.

- storage/cloud-client/snippets.py
Adding a region tag so it can be included on cloud.google.com/python instead of the currently hardcoded snippet
> Add region tag to upload_blob snippet

- functions/firebase/main.py
- functions/firebase/main_test.py
> Add firebase trigger samples

- memorystore/redis/gce_deployment/deploy.sh
- memorystore/redis/gce_deployment/startup-script.sh
Note: GCS_APP_LOCATION prone to user error , simplifying to GCS_BUCKET_NAME param
> Memorystore GCE : Replace  GCS_APP_LOCATION with GCS_BUCKET_NAME

- kms/api-client/asymmetric_test.py
> KMS test fix

- composer/tools/copy_environment.py
- composer/tools/copy_environment_test.py
- composer/tools/requirements.txt
Add a script for creating a clone of an existing Cloud Composer
Environment using the latest Composer image version.
CC @janczak10
> Add Composer Environment Migration script

- composer/data/python2_script.py
- composer/workflows/bashoperator_python2.py
- composer/workflows/bashoperator_python2_test.py
- composer/workflows/pythonvirtualenvoperator_python2.py
- composer/workflows/pythonvirtualenvoperator_python2_test.py
> Add Composer samples that explicitly call python2

- endpoints/getting-started/k8s/esp_echo_http.yaml
Copied the k8s config file used in the Endpoints Kubernetes tutorial from the endpoints-samples repo. This way the sample code and the config files are all in the same repo.
> Added k8s config file from endpoints-samples/k8s

- composer/workflows/pythonvirtualenvoperator_python2_test.py
> Test pythonvirtualenvoperator sample in Python 3.

- functions/log/main.py
- functions/log/main_test.py
~~**DO NOT MERGE** until we confirm a BigQuery-only sample is appropriate.~~
Current sample is product-agnostic.
@mogar1980 @stew-r FYI
> GCF: Add Stackdriver triggers sample

- .travis.yml
Parse error in `.travis.yml` has stopped Travis CI from running on PRs.
> Attempt to kickstart Travis CI.

- storage/cloud-client/bucket_lock.py
> [Storage] Add spacing in sample code.

- firestore/cloud-client/requirements.txt
- firestore/cloud-client/snippets.py
> Remove CreateIfMissingOption

- appengine/standard/endpoints-frameworks-v2/echo/main.py
- appengine/standard/endpoints-frameworks-v2/echo/main_test.py
Changed the surface of the echo API to match the Java version. I've made the changes in the docs. To minimize time when the sample and docs are out of sync, I'll wait to publish the updated docs until this PR is reviewed and merged to master.
Signed-off-by: Nancy Avinger <navinger@google.com>
> Changed surface of echo API to match the Java version

- vision/cloud-client/crop_hints/crop_hints.py
We got reports that folks would run the Crop Hints tutorial but say "it did nothing, it's broken"
Printing output so folks know to check for `output-crop.jpg` where the output file is written
> Add print statements

- functions/helloworld/main.py
- functions/helloworld/main_test.py
(Omitting this fix from non-HTTP functions.)
> Fix XSS issue

- vision/cloud-client/product_search/import_product_sets_test.py
- vision/cloud-client/product_search/product_search_test.py
- vision/cloud-client/product_search/reference_image_management_test.py
- vision/cloud-client/product_search/resources/indexed_product_sets.csv
- vision/cloud-client/product_search/resources/product_sets.csv
use test data hosted on `gs://cloud-samples-data/vision/product_search`
> use shared sample data bucket

- endpoints/bookstore-grpc/api_config_http.yaml
addressing this issue: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1129#issuecomment-444635180
> Fix Endpoints Bookstore YAML

- endpoints/getting-started/clients/service_to_service_gae_default/main.py
Attempted to clarify the comment about the aud claim.
> Updated comment about the aud claim.

- bigquery/cloud-client/user_credentials.py
- bigquery/cloud-client/user_credentials_test.py
Also add comments for the needed values and use a concrete value where
possible according to the sample rubric.
For internal bug 122251632.
> Refactor BQ user credentials sample to use region tags

- bigquery/cloud-client/user_credentials.py
Describe the variables to set explicitly (rather than "this"), as
suggested in internal CL 227863277.
> Make TODO clearer what action to take.

- iot/api-client/manager/manager.py
- iot/api-client/manager/manager_test.py
This adds the gateway manager features and tests for the first of 2 PRs merging the beta feature into the main sample location.
> Migrates manager samples for Gateways from beta folder

- appengine/standard/endpoints/multiapi/main.py
I'm in the process of updating the Endpoints Frameworks Python doc that explains the path argument. I made some changes to the sample code to go along with the doc changes.
Signed-off-by: Nancy Avinger <navinger@google.com>
> Changes to help clarify path argument in the docs.

- storage/signed_urls/generate_signed_urls.py
Short PR to modify a value used to be consistent with gsutil. 
gcs -> storage
> storage: Update signed url sample

- profiler/quickstart/main.py
- profiler/quickstart/requirements.txt
Add code samples for https://cloud.google.com/profiler.
> Add Profiler code samples

- storage/signed_urls/generate_signed_urls.py
Hi @kurtisvg, this is a change to fix a typo in casing. Could you help review?
> storage: fix typo in Signed URL sample

- tables/automl/notebooks/retail_product_stockout_prediction/retail_product_stockout_prediction.ipynb
as the bug has been fixed in the public client lib
> remove the reference to a bug

- ml_engine/custom-prediction-routines/README.md
- ml_engine/custom-prediction-routines/predictor-interface.py
- ml_engine/custom-prediction-routines/preprocess.py
- ml_engine/custom-prediction-routines/scikit-predictor.py
- ml_engine/custom-prediction-routines/setup.py
- ml_engine/custom-prediction-routines/tensorflow-predictor.py
Change-Id: I734bebd77970a3ab627b0cbffdcb8fef320c2de4
> Add custom prediction routine samples for AI Platform

- firestore/cloud-client/requirements.txt
- firestore/cloud-client/snippets.py
- firestore/cloud-client/snippets_test.py
* Bump `google-cloud-firestore` to 1.1.0 which includes
the new functionality
> Add snippet for Collection Group Query

- functions/log/main.py
> Logging: remove extraneous GCP_PROJECT env var

- compute/managed-instances/demo/app.py
- compute/managed-instances/demo/templates/index.html
Add functionality to the minfra demo to simulate high CPU load on the demo webserver
> Minfra demo

- functions/http/main.py
Update Python sample to match [its Node.js counterpart](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/http/index.js#L195-L233)
> Use request parameter for bucket name

- container_registry/container_analysis/samples.py
> Container Analysis typo fix

- endpoints/getting-started/clients/google-jwt-client.py
related to https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1958
> Endpoints: decode jwt string

- functions/helloworld/main.py
- functions/helloworld/main_test.py
- functions/helloworld/sample_pubsub_test.py
- functions/helloworld/sample_pubsub_test_system.py
This addresses user feedback that compares our current Hello World [example](https://cloud.google.com/functions/docs/calling/pubsub#functions_calling_pubsub-python) for Cloud Function with Cloud Pub/Sub with that of [Firebase with Cloud Pub/Sub](https://firebase.google.com/docs/functions/pubsub-events). 
~1. `else` clause actually outputs something _else_.~
2. Show how users can access message attributes, publish time, and message IDs.
> Functions: improve existing sample

- firestore/cloud-client/snippets.py
> Update delete_full_collection sample to use batch_size as the limit

- storage/cloud-client/README.rst
- storage/cloud-client/snippets.py
- storage/cloud-client/snippets_test.py
> storage: add list buckets

- vision/cloud-client/crop_hints/crop_hints.py
Comment should reflect real filename.
> Fix comment.

- speech/cloud-client/beta_snippets.py
/cc @telpirion @GoogleCloudPlatform/ml-apis
> Data logging opt-in is no longer required for enhanced models

- endpoints/getting-started/deployment.yaml
The old docker image was crashed all the time.  Build a new docker image
> Update the docker image for python echo app

- vision/cloud-client/detect/detect.py
Make the code snippet on the doc site runnable.
> move import re

- storage/cloud-client/snippets.py
Short PR to add a comment to sample.
> [Storage] Add comment to clarify which package version is necessary

- iot/api-client/manager/manager.py
* Make `gateway_id` an optional parameter
> Fix IoT parameters

- iot/api-client/manager/manager.py
Removes unused logic when listing devices
> Fix list devices in IoT sample

- pubsub/cloud-client/subscriber.py
> Pub/Sub: fix region tag mistake

- datastore/cloud-ndb/flask_app.py
- datastore/cloud-ndb/flask_app_test.py
- datastore/cloud-ndb/middleware.py
- datastore/cloud-ndb/middleware_test.py
- datastore/cloud-ndb/quickstart.py
- datastore/cloud-ndb/quickstart_test.py
- datastore/cloud-ndb/requirements.txt
This is the first sample code I've done in some time, so please double-check any sample-specific style issues, especially region tags.
> Initial samples for google-cloud-ndb datastore client

- functions/helloworld/main.py
Consistently use the term `event` for events:
b/139649933
> refactor: Rename data to event

- tables/automl/notebooks/retail_product_stockout_prediction/retail_product_stockout_prediction.ipynb
> conversion to jupyter/colab

- tables/automl/notebooks/purchase_prediction/purchase_prediction.ipynb
> conversion to jupyer/colab

- tables/automl/notebooks/census_income_prediction/getting_started_notebook.ipynb
conversion of the notebook to support both Jupyter and Colab + bug fixes
> conversion of notebook for jupyter/Colab

- iot/api-client/mqtt_example/cloudiot_mqtt_example.py
Addresses [this reported issue](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1985).
> Adds explicit decode for Python 3

- tables/automl/automl_tables_dataset.py
- tables/automl/automl_tables_model.py
- tables/automl/automl_tables_predict.py
- tables/automl/dataset_test.py
- tables/automl/model_test.py
- tables/automl/predict_test.py
> [BLOCKED] AutoML Tables: Docs samples updated to use new (pending) client

- functions/billing/main.py
Fixed the code sample tags to be correct and added some very small error checking.
> Updating functions/billing/main.py - Code sample references

- functions/helloworld/main.py
Removes unused and not useful region tag: `functions_tips_terminate`
devrel/samples/604
> fix: Remove functions_tips_terminate

- storage/cloud-client/hmac.py
Fix data printed to match canonical sample.
> Fixup sample for list_hmac_keys

- dataflow/README.md
- dataflow/encryption-keys/README.md
- dataflow/encryption-keys/bigquery_kms_key.py
- dataflow/encryption-keys/requirements.txt
Creating a Dataflow sample to show how to use Customer-Managed Encryption Keys (CMEK) for the [Using customer-managed encryption keys](https://cloud.google.com/dataflow/docs/guides/customer-managed-encryption-keys) docs page.
> Add bigquery_kms_key Dataflow sample

- notebooks/tutorials/bigquery/Getting started with BigQuery ML Feature Engineering.ipynb
Create a new Notebook showing Feature Engineering for Census Dataset.
It uses Public Dataset Census and BQML using Python Big Query client. (from google.cloud import bigquery )
This notebook is compatible with both AI Platform Notebooks and Colab.
> BQML Tutorial for Feature Engineering

- notebooks/tutorials/cloud-ml-engine/Training and prediction with scikit-learn.ipynb
Update gcloud sdk command to ai-platform
> Update gcloud sdk command to ai-platform

- testing/requirements.txt
attr released a new release that was incompatibly with pytest v4.
> Update PyTest to v5.x to avoid attr incompatibility.

- iam/api-client/access.py
- iam/api-client/access_test.py
Added test_permissions function and tests for this doc: https://cloud.google.com/iam/docs/testing-permissions
> IAM: Added test_permissions function and tests

- functions/tips/main.py
- functions/tips/main_test.py
Add a serverless scope sample.
http://b/142060621
```
nox -s "lint(sample='./functions/tips')"
```
> feat: Add serverless scope sample

- composer/workflows/kubernetes_pod_operator.py
- composer/workflows/requirements.txt
> Fix kubernetespodoperator resources param

- storage/cloud-client/uniform_bucket_level_access.py
Region tag fix will merge on approval.
> Storage: fix region tag

- run/logging-manual/.dockerignore
- run/logging-manual/Dockerfile
- run/logging-manual/README.md
- run/logging-manual/main.py
- run/logging-manual/main_test.py
- run/logging-manual/requirements.txt
Adding python sample for [cloud run logging docs](https://cloud.google.com/run/docs/logging) for http://devrel/snippets/run_manual_logging
> Run logging manual

- spanner/cloud-client/bulk_load_csv/batch_import.py
fixes https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2532
> update filenames to match the CSV files

- functions/helloworld/main_test.py
- renovate.json
> Fix failing functions test

- noxfile-template.py
Removing black from lint check until we've had more discussion on what we'd like our style guide to be.
> Remove black from noxfile-template

- language/automl/automl_natural_language_sentiment_dataset.py
- language/automl/automl_natural_language_sentiment_model.py
Add filter defaults for list_datasets and list_models
Remove unnecessary filter from list_model_evaluations and
display_evaluation
b/130171300
/cc @andrewferlitsch
> Add filter defaults for language/automl

- MAC_SETUP.md
Note that verifying pyenv Python shim requires installing a Python version through pyenv to be completed first.
Add helper to refine list of available versions to a subset of minor releases, per crwilcox.
Add resource for latest Python versions (python.org/doc/versions/)
Update list of latest versions.
> Update MAC_SETUP.md with minor revisions

- .github/CODEOWNERS
Add myself as a code owner for Pub/Sub.
> Add anguillanneuf  as codeowner for Pub/Sub

- run/hello-broken/Dockerfile
Adding region tags for the [local troubleshooting tutorial](https://cloud.google.com/run/docs/tutorials/local-troubleshooting)
> Adding region tags to Dockerfile

- AUTHORING_GUIDE.md
> Add note in authoring guide about testing

- appengine/standard_python37/django/requirements.txt
> Revert appengine django dependency

- appengine/flexible/datastore/main.py
> catch potential error retrieving datastore results

- MAC_SETUP.md
Fixes #2693
Add instructions for Catalina
Move installation verification after installation of specific versions
Update latest python versions and add commands for each
Add console label to code blocks
> Update Mac setup guide

- appengine/standard_python37/cloud_debugger/main.py
- iam/api-client/access.py
- iam/api-client/access_test.py
- iam/api-client/custom_roles_test.py
Separated out logic into separate tests, added fixtures, fixed policy version error and query test permissions error. Fixes #2680
> Cleanup iam tests

- vision/cloud-client/document_text/doctext.py
> fix: get bounds for blocks instead of pages

- run/hello-broken/README.md
- run/image-processing/README.md
- run/logging-manual/README.md
- run/pubsub/README.md
- run/system-package/README.md
To run locally, the PORT environment variable needs to be set.
> Adding environment port variable

- translate/cloud-client/translate_v3_detect_language.py
- translate/cloud-client/translate_v3_detect_language_test.py
- translate/cloud-client/translate_v3_get_supported_languages.py
- translate/cloud-client/translate_v3_get_supported_languages_test.py
Migrate from tmp-generated-samples branch 615c08e
Remove boilerplate
Update copyright date
Blacken
Remove unused imports
> Translate: migrate published samples

- cloud-sql/mysql/sqlalchemy/README.md
* Made service name consistent in steps 1, 2, and 3 of README
* Removed beta command
* Removed whitespace from step 3 so that it can be copy-pasted easily
Tested all commands locally to confirm that they work!
> Updated commands for Cloud Run

- dataflow/run_template/main_test.py
Was looking into #2804 and made the tests to wait for the job to be in running state before cancelling, instead of a hardcoded sleep.
> dataflow: wait for jobs to be cancellable in tests for run_template.

- AUTHORING_GUIDE.md
> fix authoring guide bug

- translate/cloud-client/beta_snippets.py
Fix: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2875
> translate: increase timeout

- datastore/cloud-ndb/requirements.txt
> Update NDB version to 1.0.1

- vision/cloud-client/detect/detect_test.py
Fix: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2984
Fix: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2985
> vision: fix flaky test

- vision/cloud-client/web/web_detect_test.py
Fix: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2910
> vision: fix flaky tests to be more generic in the results

- storage/cloud-client/iam_test.py
- storage/cloud-client/uniform_bucket_level_access_test.py
Addresses flakes seen in IAM and UBLA tests.
> fix: harden storage test fixtures

- renovate.json
https://docs.renovatebot.com/configuration-options/#rebasewhen
> Replace deprecated renovate command

- .github/CODEOWNERS
Adding @nnegrey @telpirion @sirtorry  as owners for all the ML API and AutoML repos so the team can review each others' code more easily
> updating owners for ML APIs / AutoML

- storage/api/crud_object_test.py
> fix: create fixture with random file name for test

- vision/cloud-client/web/web_detect_test.py
Fix: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2880
> vision: remove redundant flaky web test

- endpoints/bookstore-grpc-transcoding/bookstore_server.py
- endpoints/bookstore-grpc/bookstore_server.py
> Correct book title by Neal Stephenson

- .github/blunderbuss.yml
Doug's taking a break from python-docs-samples for a bit.
> blunderbuss: Remove dmahugh

- appengine/flexible/pubsub/requirements.txt
- appengine/standard_python37/pubsub/requirements.txt
> Update dependency google-cloud-pubsub to v1.4.2

- .kokoro/python3.6/periodic.cfg
- .kokoro/python3.7/periodic.cfg
- .kokoro/python3.8/periodic.cfg
I think we can override the values.
> testing: bump the timeout for periodic builds

- appengine/standard/analytics/requirements-test.txt
- appengine/standard/appengine_helper.py
- appengine/standard/blobstore/blobreader/requirements-test.txt
- appengine/standard/blobstore/gcs/requirements-test.txt
- appengine/standard/conftest.py
- appengine/standard/django/requirements-test.txt
- appengine/standard/download-appengine-sdk.py
- appengine/standard/endpoints-frameworks-v2/echo/requirements-test.txt
- appengine/standard/endpoints-frameworks-v2/iata/requirements-test.txt
- appengine/standard/endpoints-frameworks-v2/quickstart/requirements-test.txt
- appengine/standard/firebase/firenotes/backend/requirements-test.txt
- appengine/standard/flask/tutorial/requirements-test.txt
- appengine/standard/iap/requirements-test.txt
- appengine/standard/mailgun/requirements-test.txt
- appengine/standard/mailjet/requirements-test.txt
- appengine/standard/ndb/transactions/requirements-test.txt
- appengine/standard/noxfile-template.py
- appengine/standard/pubsub/requirements-test.txt
- appengine/standard/sendgrid/requirements-test.txt
- appengine/standard/storage/api-client/requirements-test.txt
- appengine/standard/storage/appengine-client/requirements-test.txt
- appengine/standard/urlfetch/requests/requirements-test.txt
fixes #3353 
fixes #3354 
fixes #3355 
fixes #3356 
fixes #3357 
fixes #3358 
fixes #3359 
fixes #3360 
fixes #3361 
fixes #3362 
fixes #3363
fixes #3364 
fixes #3365 
fixes #3366 
fixes #3367 
fixes #3368 
fixes #3369 
fixes #3370 
fixes #3371
> [appengine] chore: remove gcp-devrel-py-tools

- healthcare/api-client/hl7v2/hl7v2_messages_test.py
- healthcare/api-client/hl7v2/requirements-test.txt
> [healthcare] chore: remove gcp-devrel-py-tools

- container_registry/container_analysis/samples.py
- container_registry/container_analysis/samples_test.py
Use new effective_severity field
fixes b/142836422
> [container analysis] effective severity

- jobs/v3/api_client/auto_complete_sample_test.py
- jobs/v3/api_client/commute_search_sample_test.py
- jobs/v3/api_client/custom_attribute_sample_test.py
- jobs/v3/api_client/email_alert_search_sample_test.py
- jobs/v3/api_client/featured_job_search_sample_test.py
- jobs/v3/api_client/general_search_sample_test.py
- jobs/v3/api_client/histogram_sample_test.py
- jobs/v3/api_client/location_search_sample_test.py
- jobs/v3/api_client/requirements-test.txt
> [jobs] chore: remove gcp-devrel-py-tools

- compute/encryption/generate_wrapped_rsa_key_test.py
> [compute] fix: use unique disk name

- iam/api-client/service_accounts_test.py
> [iam] fix: use uuid4's first part for test

- bigquery/datalab-migration/requirements.txt
Fixes: #3658
Fixes: #3659
Fixes: #3660
> fix: bump ipython version to address compilation issues with py3.8

- dlp/risk_test.py
> [dlp] fix: increase the number of retries for some tests

- appengine/flexible/memcache/noxfile.py
- dataflow/encryption-keys/noxfile.py
- dataflow/flex-templates/streaming_beam/noxfile.py
- ml_engine/online_prediction/noxfile.py
- pubsub/streaming-analytics/noxfile.py
fixes #3677
Just copied the template, and added "3.8" to the ignore list.
> testing: disable py-3.8 build for some tests

- spanner/cloud-client/requirements.txt
Resolves #3237
Resolves #3240 
Resolves #3241 
Resolves #3242
> chore: pin new Cloud Spanner release

- README.md
fixes #3556
also removed the stale coverage badge.
> chore: add build badges to README

- iap/requirements.txt
update google-auth version to pick up the fix
> fix: update google-auth version for issue #3712

- noxfile-template.py
These are added in:
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1770
> testing: remove I100 and I201 from the ignore list

- .kokoro/tests/run_tests.sh
> cleanup: remove stale code block

- appengine/flexible/datastore/main_test.py
> [appengine] testing: relax datastore test

- vision/automl/edge_container_predict/Dockerfile
- vision/automl/edge_container_predict/README.md
- vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
> [vision] fix: move the Docker image

- vision/automl/edge_container_predict/Dockerfile
- vision/automl/edge_container_predict/README.md
- vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
- vision/automl/edge_container_predict/cloudbuild.yaml
also update README with how to build and upload the images.
@genquan9 
Now the images are little bit more maintenable. Potentially we can parameterize the version number too.
> [vision] chore: parameterized FROM, add cloudbuild.yaml

- iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
- iot/api-client/mqtt_example/pytest.ini
> [iot] testing: verbose log output, adding a new assert

- scripts/encrypt-secrets.sh
> testing: fix encrypt-secrets.sh

- run/hello-broken/Dockerfile
- run/hello-broken/main.py
- run/image-processing/Dockerfile
- run/image-processing/main.py
- run/logging-manual/Dockerfile
- run/logging-manual/main.py
- run/markdown-preview/editor/Dockerfile
- run/markdown-preview/renderer/Dockerfile
- run/pubsub/Dockerfile
- run/pubsub/main.py
- run/system-package/Dockerfile
- run/system-package/main.py
Internal issue id: b/156748422
Updating all Cloud Run Dockerfiles with: 
`ENV PYTHONUNBUFFERED TRUE`
Removing all the unnecessary `sys.stdout.flush()`
> Using pythonunbuffered instead of flushing the sys.stdout

- appengine/standard/i18n/app.yaml
- appengine/standard/multitenancy/app.yaml
- appengine/standard/ndb/overview/app.yaml
- appengine/standard/ndb/transactions/app.yaml
Removed deprecated "version: 1" line.
> Fix app yamls

- storage/cloud-client/acl_test.py
- storage/cloud-client/hmac_samples_test.py
- storage/cloud-client/iam_test.py
- storage/cloud-client/noxfile_config.py
- storage/cloud-client/snippets_test.py
- storage/cloud-client/uniform_bucket_level_access_test.py
We still need to use the old project for some tests.
fixes #4033
fixes #4029
> [storage] testing: use multiple projects

- run/events-gcs/Dockerfile
- run/events-gcs/main.py
Fixes `run_events_gcs_*` region tags.
Detected from Samples Tracker.
R: @cumason123
> fix: fixes run events gcs sample region tags

- healthcare/api-client/v1/fhir/fhir_resources.py
Add comment that supplied sample body only works with Patient resource.
Fixes b/159116240
> healthcare API: add comment on update/patch FHIR resource

- jobs/v3/api_client/email_alert_search_sample_test.py
> test(jobs): increase max test time to 300

- dlp/risk_test.py
> [dlp] fix: add retry count to mitigate the flake

- tasks/create_http_task_with_token.py
service_account_email property is missing from inline sample documentation.
> docs(tasks): service_account_email parameter example

- asset/cloud-client/quickstart_searchallresources_test.py
> [asset] fix: bump the timeout

- functions/slack/main_test.py
> fix(functions): only check if there is a result

- .github/blunderbuss.yml
> remove kurtis while he's on leave

- translate/cloud-client/beta_snippets.py
- translate/cloud-client/translate_v3_batch_translate_text_test.py
> testing(translate): bump the timeout for operations

- appengine/standard/firebase/firenotes/backend/app.yaml
> Remove no longer used environment variable

- .github/blunderbuss.yml
> add charlie as an owner

- automl/cloud-client/list_operation_status_test.py
> testing(automl): retry upon InternalServerError

- asset/cloud-client/quickstart_searchalliampolicies.py
- asset/cloud-client/quickstart_searchallresources.py
> Add commented variables to make samples more friendly to copy and use

- AUTHORING_GUIDE.md
- appengine/flexible/memcache/noxfile.py
- dataflow/encryption-keys/noxfile.py
- dataflow/flex-templates/streaming_beam/noxfile.py
- ml_engine/online_prediction/noxfile.py
- noxfile-template.py
- pubsub/streaming-analytics/noxfile.py
- run/markdown-preview/editor/noxfile.py
- run/markdown-preview/renderer/noxfile.py
> feat: add blacken nox session

- run/events-storage/main.py
Delete Region tag run_events_gcs_server_setup. Not needed.
> Delete Region tag run_events_gcs_server_setup

- .github/blunderbuss.yml
> re-add kurtis

- .github/PULL_REQUEST_TEMPLATE.md
Fixes typo on PULL_REQUEST_TEMPLATE.md (no issue recorded for this)
> Fixes typo on PULL_REQUEST_TEMPLATE.md

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
> add new codeowner, update pull request template

- run/hello-broken/noxfile_config.py
- run/helloworld/noxfile_config.py
there are some GCLOUD_PROJECT leftovers
fixes #4449
> testing(run): use correct envvars

- spanner/cloud-client/snippets.py
- spanner/cloud-client/snippets_test.py
> fix(spanner): use future date to avoid time drift

- iam/api-client/service_accounts.py
- iam/api-client/service_accounts_test.py
> testing(iam): fix failing cleanup code

- MAC_SETUP.md
Adding troubleshooting instructions for some errors when trying to install a python version.
> Add troubleshooting instructions

- .github/blunderbuss.yml
We're planning to start using blunderbuss's `assign_issues_by` feature, and here is the first pass of the config file changes.
> chore: first pass of assign_issues_by

- iam/api-client/quickstartv2.py
Adjust region tag to match the quickstart v2 samples in other languages
> Adjust region tag

- appengine/standard_python3/building-an-app/building-an-app-1/main.py
- iam/api-client/service_accounts.py
- spanner/cloud-client/snippets.py
> chore: fix some unmatched region tags

- appengine/standard/firebase/firenotes/frontend/main.js
- appengine/standard/multitenancy/taskqueue.py
- appengine/standard/xmpp/xmpp.py
- storage/cloud-client/storage_disable_versioning.py
- storage/cloud-client/storage_set_metadata.py
> chore: fix some more unmatched region tags

- iap/iap_test.py
> fix(iap): add sleep to avoid test failures

- composer/workflows/requirements-composer.txt
> remove comment because composer doesn't like it

- AUTHORING_GUIDE.md
Added general guidance about `list` methods based on code changes in #4630.
> docs: add note about filtering for list methods

- .github/blunderbuss.yml
> chore: blunderbuss update

- MAC_SETUP.md
I was going through these instructions again and thought it would be a good idea to update the Python versions :)
> Update python versions

- appengine/flexible/tasks/create_app_engine_queue_task.py
- appengine/flexible/tasks/snippets.py
Closes #4653 #4652 #4651 #4650 #4649
> fix: use enums instead of str for task creation

- auth/end-user/web/main_test.py
- composer/workflows/bashoperator_python2_test.py
- composer/workflows/bq_copy_across_locations_test.py
- composer/workflows/bq_notify_test.py
- composer/workflows/connections_test.py
- composer/workflows/dataflowtemplateoperator_tutorial_test.py
- composer/workflows/dataproc_workflow_template_instantiate_operator_tutorial_test.py
- composer/workflows/hadoop_tutorial_test.py
- composer/workflows/kubernetes_pod_operator_test.py
- composer/workflows/pythonvirtualenvoperator_python2_test.py
- composer/workflows/quickstart_test.py
- composer/workflows/simple_test.py
- composer/workflows/trigger_response_dag_test.py
- composer/workflows/use_local_deps_test.py
> cleanup: replace sanity check with confidence check

- iam/api-client/custom_roles_test.py
fixes #4770
I think it's sufficient to check if there's a newline.
> fix(iam): fix a broken test

- video/cloud-client/analyze/video_detect_faces_beta_test.py
- video/cloud-client/analyze/video_detect_faces_gcs_beta_test.py
> chore: fixes flaky test

- .github/sync-repo-settings.yaml
> Add sync-repo-bot config

- cloud-sql/sql-server/sqlalchemy/main.py
> Add new updated SQL Server sample region tags.

- cloud-sql/postgres/sqlalchemy/requirements.txt
> Downgrade dependency for pg8000

- functions/tips/main.py
> Add missed region tags

- run/logging-manual/main.py
> chore (run/logging): Use actual product names

- composer/workflows/airflow_db_cleanup.py
Add a region tag so we can refer to this dag in the docs
> add region tags

- run/django/cloudmigrate.yaml
- run/django/mysite/migrations/0001_createsuperuser.py
- run/django/mysite/settings.py
* Ensure tags unique with added django token
* Tag two new files to remove licence headers rendering in tutorial
> Fix region tags for run/django

- AUTHORING_GUIDE.md
> update region tag guidance

- appengine/standard/migration/ndb/overview/main_test.py
Added needed index to project's datastore
Fixes #4076
> Don't skip test_app any more

- functions/helloworld/sample_pubsub_test_system.py
> chore(functions): use consistent env var names

- pubsub/streaming-analytics/README.md
> Pub/Sub: add region to command to run Dataflow job

- run/deployment-previews/README.md
> Correct tutorial URL in README

- healthcare/api-client/v1/datasets/datasets_test.py
- healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
fixes #5211
fixes #5210
fixes #5209
fixes #5205
> fix(healthcare): add more retries for mitigating flakes

- healthcare/api-client/v1/dicom/dicom_stores_test.py
> fix(healthcare): retry flaky test

- appengine/standard_python3/pubsub/templates/index.html
Add the missing `ul` elements.
> fix: update index.html

- eventarc/audit-storage/README.md
- eventarc/pubsub/README.md
> docs(eventarc): update ReadMes

- run/django/Dockerfile
- run/hello-broken/Dockerfile
- run/helloworld/Dockerfile
- run/image-processing/Dockerfile
- run/logging-manual/Dockerfile
- run/markdown-preview/editor/Dockerfile
- run/markdown-preview/renderer/Dockerfile
- run/pubsub/Dockerfile
- run/system-package/Dockerfile
> feat(run): Add timeout comment to Dockerfiles

- data-science-onramp/data-ingestion/README.md
- data-science-onramp/data-ingestion/holidays.csv
The Kaggle dataset we originally used for this tutorial is no longer available, so we now are including it with the code for users to download.
> add holidays dataset and readme about it

- run/markdown-preview/editor/main.py
- run/markdown-preview/editor/main_test.py
- run/markdown-preview/editor/render.py
> Remove unused code in Markdown sample

- data-science-onramp/feature-engineering/README.md
- data-science-onramp/feature-engineering/feature_engineering.ipynb
> update feature engineering to use new holidays dataset

- media/transcoder/job_test.py
- media/transcoder/requirements-test.txt
> fix(media): increase max retries

- data-science-onramp/data-ingestion/setup.py
> add missing region tags

- appengine/standard/endpoints-frameworks-v2/iata/requirements.txt
fixes #5390
Amusingly the directory has no tests.
> fix(appengine): pin rsa to 4.5

- healthcare/api-client/v1/fhir/fhir_resources_test.py
- healthcare/api-client/v1/fhir/fhir_stores_test.py
- healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
- healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
> fix(healthcare): bump backoff timeouts to 240

- datastore/cloud-client/admin_test.py
> fix(datastore): properly retry the test

- datastore/cloud-client/admin_test.py
- datastore/cloud-client/snippets_test.py
> fix(datastore): properly retry a flaky test

- .github/blunderbuss.yml
- [] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
> chore: add dandhlee to blunderbuss

- jobs/v3/api_client/custom_attribute_sample_test.py
> fix(jobs): mark a test as flaky

- storage/cloud-client/storage_upload_file.py
* following Java's example https://github.com/googleapis/google-cloud-java/blob/b36db6a957bcfb7b6ccdb77fb12b4cc7fa22b807/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/objects/UploadObject.java#L33-L40
> docs: update description of parameters in storage_upload_file

- .github/blunderbuss.yml
> chore: tmatsuo out

- cloud-sql/mysql/client-side-encryption/snippets/cloud_sql_connection_pool.py
- cloud-sql/mysql/sqlalchemy/README.md
- cloud-sql/mysql/sqlalchemy/main.py
- cloud-sql/postgres/client-side-encryption/snippets/cloud_sql_connection_pool.py
- cloud-sql/postgres/sqlalchemy/README.md
- cloud-sql/sql-server/sqlalchemy/main.py
- run/idp-sql/database.py
> fix deprecation warnings and update documentation in SQL samples

- renovate.json
This file is pulled directly from Airflow so we shouldn't be changing it
> ignore composer constraints file

- .github/snippet-bot.yml
This config will for consolidating snippet-bot's checks into one.
> chore: update snippet-bot config

- .github/sync-repo-settings.yaml
This is the first step to consolidate snippet-bot's checks.
> chore: update sync-repo-settings config

- .github/blunderbuss.yml
Switch assignees to only @cojenco and @andrewsg, who focus
specifically on python.
Updates #5906
> chore(.github): update storage blunderbus config

- trace/cloud-trace-demo-app-opentelemetry/app/app.py
- trace/cloud-trace-demo-app-opentelemetry/app/requirements.txt
- trace/trace-python-sample-opentelemetry/main.py
- trace/trace-python-sample-opentelemetry/main_test.py
- trace/trace-python-sample-opentelemetry/requirements.txt
> trace: Update OpenTelemetry library versions

- healthcare/api-client/v1/fhir/fhir_resources_test.py
- healthcare/api-client/v1/fhir/fhir_stores_test.py
- healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
- healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
Fixes #6119
This PR attempts to reduce flakiness by increasing the timeout 240s to 500s.
Googlers see b/189121491
> chore(healthcare): increased timeout to reduce flakiness

- appengine/flexible/tasks/create_app_engine_queue_task.py
> fix: Update todo variables

- compute/metadata/README.md
Adding a new link to README pointing to documentation that uses samples from this folder.
> chore: Updating list of documents

- .github/CODEOWNERS
- .github/blunderbuss.yml
Please let me know if a different person (or a GitHub team) should be added instead. 
CC @tequilarista  @rsamborski @m-strzelczyk
> Add m-strzelczyk@ as codeowner for compute

- composer/tools/README.md
> Update composer readme

- renovate.json
I believe this is obsolete because of the PR @dandhlee made earlier anyway
> remove package pattern throwing a warning

- run/idp-sql/test/e2e_test.py
> feat: add retry to test

- run/idp-sql/README.md
- run/idp-sql/credentials.py
- run/idp-sql/postcreate.sh
- run/idp-sql/requirements.txt
- run/idp-sql/test/e2e_test_setup.yaml
> feat(run): Update sample to use Secret Manager Integration

- composer/workflows/hadoop_tutorial.py
https://airflow.apache.org/code.html#default-variables returns a 404
n/a
> Update documentation link

- data-science-onramp/feature-engineering/feature_engineering.ipynb
- data-science-onramp/vertex-ai/modules/setup.py
- data-science-onramp/vertex-ai/modules/trainer/sklearn_model/model.py
- data-science-onramp/vertex-ai/modules/trainer/sklearn_model/task.py
- data-science-onramp/vertex-ai/modules/trainer/tfkeras_model/model.py
- data-science-onramp/vertex-ai/modules/trainer/tfkeras_model/task.py
- data-science-onramp/vertex-ai/modules/trainer/utils.py
> Ai platform -> vertex ai

- composer/airflow_1_samples/bq_copy_across_locations.py
- composer/airflow_1_samples/bq_notify.py
- composer/airflow_1_samples/dataflowtemplateoperator_tutorial.py
- composer/airflow_1_samples/dataproc_workflow_template_instantiate_operator_tutorial.py
- composer/airflow_1_samples/hadoop_tutorial.py
- composer/airflow_1_samples/kubernetes_pod_operator.py
- composer/workflows/bq_copy_across_locations.py
- composer/workflows/bq_notify.py
- composer/workflows/dataflowtemplateoperator_tutorial.py
- composer/workflows/dataproc_workflow_template_instantiate_operator_tutorial.py
- composer/workflows/kubernetes_pod_operator.py
This is a continuation of #6276 which was raised by an external contributor - thank you @sjsyz !
> update airflow docs links

- functions/http/main.py
> chore(functions): fix typo

- run/logging-manual/e2e_test.py
- run/pubsub/e2e_test.py
> fix: Update logging library

- auth/service-to-service/auth.py
> chore: Update region tag for Cloud Run

- appengine/flexible/tasks/create_app_engine_queue_task.py
> Add back timestamp protobuf

- .github/CODEOWNERS
> chore: update Dataproc codeowners

- .github/CODEOWNERS
- .github/blunderbuss.yml
add sijunliu and silvano as co-owners of the auth samples
> chore: update CODEOWNERS

- storage/cloud-client/storage_download_file.py
Update description of parameters and print statement to improve clarity and consistency. The samples in such other languages as Java and Node.js have clear comments. Followed above-mentioned examples and comments from Listnr.  
https://cloud.google.com/storage/docs/downloading-objects?hl=en#code-samples
> docs(storage): update description in storage_download_file

- appengine/standard_python3/building-an-app/building-an-app-3/templates/index.html
> Add dependency to HTML

- composer/airflow_1_samples/dataproc_workflow_template_instantiate_operator_tutorial.py
- composer/workflows/dataflowtemplateoperator_tutorial.py
> add info about Dataflow region availability

- storage/cloud-client/snippets_test.py
- storage/cloud-client/storage_move_file.py
- storage/cloud-client/storage_rename_file.py
Fixes issue with not having a move sample, and the rename sample being improperly labeled as `move` internally.
> Add storage move_blob sample and fix confusion with rename

- AUTHORING_GUIDE.md
> clarify samples noxfile instructions

- .github/blunderbuss.yml
> Add Nick to blunderbuss

- .kokoro/python3.10/common.cfg
- .kokoro/python3.10/continuous.cfg
- .kokoro/python3.10/periodic.cfg
- .kokoro/python3.10/presubmit.cfg
- appengine/standard/noxfile-template.py
- noxfile-template.py
Accompanying CL - 398765942
Add 3.10 as an optional check for now, do googleapis after.
> Add kokoro 3.10 configs as an optional check

- storage/cloud-client/acl_test.py
Add backoff to retry flaky tests in acl_test
Fixes #6736
> fix(storage): add backoff to retry flaky test

- memorystore/redis/gce_deployment/startup-script.sh
> fix(redis): Update comment in config file

- dataflow/gpu-examples/pytorch-minimal/Dockerfile
- dataflow/gpu-examples/pytorch-minimal/requirements.txt
- dataflow/gpu-examples/tensorflow-landsat/Dockerfile
- dataflow/gpu-examples/tensorflow-landsat/requirements.txt
- dataflow/gpu-examples/tensorflow-minimal/Dockerfile
- dataflow/gpu-examples/tensorflow-minimal/requirements.txt
Group dependency updates since we have so many in the pipeline and they're having test failures from other products
> group dataflow dependency updates

- servicedirectory/snippets_test.py
> samples: fix flaky test teardown in servicedirectory

- run/logging-manual/e2e_test.py
> Update Cloud Run logging test

- composer/tools/composer_db_transfer.py
Mirrors cl/411490264 which has links to passing builds
> Private Service Connect integration

- appengine/flexible/numpy/requirements.txt
- appengine/flexible/scipy/requirements.txt
- composer/workflows/requirements.txt
I'm pretending to be renovate 🤖
> Bump numpy/scipy in appengine/flexible

- data-science-onramp/data-processing/README.md
- data-science-onramp/data-processing/process.py
Doing some cleanup for data-cleaning to be renamed to data-processing 🧹
> chore: clean up data cleaning residue

- cloud-sql/postgres/sqlalchemy/main.py
Adding comment to code sample to clear up key name for psycopg2 driver/library.
> chore: add comment to cloudsql unix socket sample

- functions/v2/label_gce_instance/main.py
- functions/v2/label_gce_instance/requirements.txt
> chore(functions/label_gce_instance): update GCE library

- renovate.json
> exempt constraint file

- .github/CODEOWNERS
- AUTHORING_GUIDE.md
I accidentally made a push directly to the `main` branch. This reverts that commit. https://github.com/GoogleCloudPlatform/python-docs-samples/commit/dd2f027cfaa7a4898812d4ee2d1eb98eb1768f39
> Revert "chore: reference python-samples-reviewers "

- composer/airflow_1_samples/gke_operator.py
- composer/workflows/gke_operator.py
Thanks @adlersantos for noticing that these comments are relevant for the kuberenetesPodOperator but not the GKE operator!!
> remove irrelevant comment

- cloud-sql/sql-server/sqlalchemy/Dockerfile
- cloud-sql/sql-server/sqlalchemy/main.py
- cloud-sql/sql-server/sqlalchemy/requirements.txt
> Add SQL Server to Cloud SQL Cloud Run quickstart.

- bigquery/datalab-migration/noxfile_config.py
- bigquery/datalab-migration/requirements.txt
> Drop 3.6 from datalab migration

- composer/airflow_1_samples/quickstart.py
- composer/workflows/quickstart.py
Fixes  b/203682194
[Successful Airflow 1 run](https://screenshot.googleplex.com/NFD8U8veAMz84Ce)
[Successful Airflow 2 run](https://screenshot.googleplex.com/BmHDd2YG8TpP76f)
> Fix b/203682194

- healthcare/api-client/v1/fhir/fhir_resources_test.py
- healthcare/api-client/v1/fhir/fhir_stores_test.py
- healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
- healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
fixes #7433
fixes #7384
fixes #7385
fixes #7386
> test: fix flaky healthcare samples

- composer/cicd_sample/utils/add_dags_to_composer.py
I was uploading a string to the file instead of the file contents 🤦🏻‍♀️
Before: https://screenshot.googleplex.com/A6aruDwPrtVUmFK
After: https://screenshot.googleplex.com/3MCx6BYqKYj7g8n
> fix:  update GCS method

- functions/v2/pubsub/main.py
- functions/v2/pubsub/main_test.py
Fixes #217464630
- [ X ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ N/A ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [  X ] **Tests** pass:   `nox -s py-3.8` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ X ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ NO ] These samples need a new **API enabled** in testing projects to pass (let us know …
> Make Python PubSub sample match other language ones

- notebooks/tutorials/bigquery/BigQuery basics.ipynb
Ran into the same issue mentioned in this buganizer while using the tutorial notebooks for big-query
Fixes #<ISSUE-NUMBER> https://b.corp.google.com/issues/187995655
> Update BigQuery basics.ipynb

- .github/CODEOWNERS
- .github/blunderbuss.yml
> chore: remove silvolu from blunderbuss/codeowners

- appengine/flexible/websockets/requirements.txt
- composer/airflow_1_samples/requirements.txt
- trace/cloud-trace-demo-app-opentelemetry/app/requirements.txt
- trace/cloud-trace-demo-app/app/requirements.txt
Fixes #7478 
Fusion: https://source.cloud.google.com/results/invocations/dd66b6e0-62fb-40c6-b05a-1301c18ebbbd/targets
*Steps to re-create error:*
Using `appengine` as an example, but should apply to other affected samples.
1) Use locally or cloud shell and navigate to the sample folder and simply install requirements
```
pip3 install -r requirements.txt
pip3 install -r requirements-test.txt
```
2) You should see the same error logs like so after executing the following:
```
python3 main.py
```
Error:
3) Verify this PR no longer produces those missing module errors and for `appengine` - verify the tests are passing locally.
Note: You'll see varying versions for `markupsafe` are being installed. This is due to the varying `Flask` versions per sample
ref: …
> fix(issue-7478): resolving missing modules & versions

- media-translation/README.md
> docs: add README for media-translation

- auth/service-to-service/auth.py
- auth/service-to-service/auth_test.py
> Fix: Make test var name match code

- functions/helloworld/main.py
> chore(functions/helloworld): update product names

- auth/service-to-service/auth.py
> chore(auth): document Cloud Run URL structure

- appengine/flexible/multiple_services/gateway-service/services_config.py
> Fix OS environ variable

- .github/CODEOWNERS
Updating CODEOWNERS to include all files under the directory, not just `*.py` files.
> chore: update CODEOWNERS to all files under directory

- composer/2022_airflow_summit/README.md
- composer/2022_airflow_summit/parallel_work.py
- composer/2022_airflow_summit/parallel_work_test.py
- composer/2022_airflow_summit/requirements-test.txt
- composer/2022_airflow_summit/requirements.txt
- composer/README.md
Added DAG file for Airflow Summit 2022.
The DAG will showcase autoscaling in Cloud Composer.
> Added DAG file for Airflow Summit 2022

- composer/workflows/dataproc_batch_operators.py
> docs: update variable comment

- composer/2022_airflow_summit/constraints.txt
Reverts GoogleCloudPlatform/python-docs-samples#7930
Reverts #8005 
Reverts #7940 
Reverts #7968
Fixes #7987
> fix broken build: Revert constraints changes

- functions/helloworld/sample_http_test_integration.py
> fix: update post so retries are actually performed

- composer/rest/get_client_id_test.py
> chore: address codeql

- composer/airflow_1_samples/kubernetes_pod_operator.py
- composer/workflows/kubernetes_pod_operator.py
> docs(composer): clarify optional parameter

- functions/v2/http_logging/main.py
> chore(functions): Update import location

- pubsublite/spark-connector/README.md
- pubsublite/spark-connector/spark_streaming_test.py
> fix: upgrade dataproc image version for spark connector

- storagetransfer/aws_request_test.py
Fixes https://github.com/GoogleCloudPlatform/python-docs-samples/issues/8097
> test: retry ServiceUnavailable

- healthcare/api-client/v1beta1/fhir/fhir_resources.py
- healthcare/api-client/v1beta1/fhir/fhir_stores.py
Fixes [#7963](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/7963)
> (healthcare API):update v1beta1 samples to use R4 store to fix flakiness

- run/jobs/main_test.py
> feat(run/jobs): make tests more robust

- dataflow/gpu-examples/tensorflow-minimal/Dockerfile
- dataflow/gpu-examples/tensorflow-minimal/requirements.txt
> dataflow/gpu: use compatible nvidia image

- appengine/standard_python3/custom-server/app.yaml
> fix(appengine): hardcoded PORT -> env var

- dataflow/flex-templates/streaming_beam/README.md
This is a small update to a single README file only.
The Dataflow Flex Template example has a list of limitations in its README file. That list is out-of-date. Specifically, it says that Flex Template streaming jobs cannot be updated and FlexRS cannot be used. These restriction have been lifted with the base image version `20210120_RC00` ([Source](https://cloud.google.com/dataflow/docs/concepts/dataflow-templates#comparing-templated-jobs)). Specifically, Note 2 under the table.
There is no need to keep a list of limitations in this README file because it will eventually get out of sync with the authoritative source for this information.
The authoritative source is this: [Using Flex Templates](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates#limitations).
So, I …
> Update Dataflow Flex Template README

- composer/workflows/azureblobstoretogcsoperator_tutorial.py
- composer/workflows/s3togcsoperator_tutorial.py
teeny PR to add some region tags
> add region tags for aws + azure tutorials

- storagetransfer/posix_download_test.py
> test: retry ServiceUnavailable posix_download_test

- appengine/standard_python3/bundled-services/blobstore/django/main.py
- appengine/standard_python3/bundled-services/blobstore/flask/main.py
- appengine/standard_python3/bundled-services/blobstore/wsgi/main.py
- appengine/standard_python3/bundled-services/deferred/django/main.py
- appengine/standard_python3/bundled-services/deferred/flask/main.py
- appengine/standard_python3/bundled-services/deferred/wsgi/main.py
- appengine/standard_python3/bundled-services/mail/django/main.py
- appengine/standard_python3/bundled-services/mail/flask/main.py
- appengine/standard_python3/bundled-services/mail/wsgi/main.py
> Fix: add region tags

- run/django/e2e_test_setup.yaml
- run/idp-sql/e2e_test_setup.yaml
> Fix SQL creation conflict

- compute/api/create_instance.py
- memorystore/redis/gce_deployment/deploy.sh
> chore(samples): Updating debian version from 9 to 11

- cloud-sql/mysql/sqlalchemy/connect_tcp.py
- cloud-sql/postgres/sqlalchemy/connect_tcp.py
- cloud-sql/sql-server/sqlalchemy/connect_tcp.py
This commit adds region tags that match the other languages. A future
commit will remove the old region tags.
> chore(cloudsql): add consistent region tags

- healthcare/api-client/v1/fhir/README.rst
- healthcare/api-client/v1/fhir/fhir_resources.py
- healthcare/api-client/v1/fhir/fhir_resources_test.py
- healthcare/api-client/v1/fhir/resources/CodeSystemExample.json
- healthcare/api-client/v1/fhir/resources/ImplementationGuideExample.json
- healthcare/api-client/v1/fhir/resources/StructureDefinitionExample.json
- healthcare/api-client/v1/fhir/resources/StructureDefinitionProfileUrlExample.json
> samples(healthcare API): add samples and tests for v1 FHIR profiles

- appengine/flexible/tasks/main.py
- appengine/flexible/tasks/templates/index.html
External text is now sanitized automatically via templates before returning to the user.
> Fix: Sanitize text response

- run/idp-sql/e2e_test.py
> Extend test retry period

- appengine/standard_python3/bundled-services/deferred/django/main.py
- appengine/standard_python3/bundled-services/deferred/django/main_test.py
- appengine/standard_python3/bundled-services/deferred/flask/main.py
- appengine/standard_python3/bundled-services/deferred/flask/main_test.py
- appengine/standard_python3/bundled-services/deferred/wsgi/main.py
- appengine/standard_python3/bundled-services/deferred/wsgi/main_test.py
> fix: longer waits to reduce flaky

- .github/header-checker-lint.yml
> Update header checker

- run/deployment-previews/Dockerfile
I'm having a horrible time with timeouts in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/7491 and figured I'd try splitting it up by product to find the culprit
> 7491 - run

- trace/cloud-trace-demo-app/app/Dockerfile
I'm having a horrible time with timeouts in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/7491 and figured I'd try splitting it up by product to find the culprit
> 7491 - trace

- dataflow/gpu-examples/tensorflow-landsat-prime/requirements.txt
- dataflow/gpu-examples/tensorflow-landsat/requirements.txt
- dataflow/gpu-examples/tensorflow-minimal/requirements.txt
split #8310 up into 3 - dataflow edition
> update tf in dataflow

- composer/2022_airflow_summit/data_analytics_process_expansion.py
Fixed runtime JVM error by moving Spark code back into __main__.
> fixed jvm error

- ml_engine/online_prediction/requirements.txt
Splitting up #8310 into multiple PRs
> ML Engine TF bump

- compute/oslogin/service_account_ssh_test.py
> fix: due to response format change

- pubsub/streaming-analytics/requirements.txt
Not sure why this version wasn't updated.
> deps: update dataflow version in pubsub tutorial

- run/idp-sql/main.py
> chore: update region tags

- jobs/v3/api_client/general_search_sample.py
cl/490049441 removed usage in documentation; this can be merged once snippet-bot is happy (since that means the changes will have been successfully published/indexed).
> chore(jobs): remove obsolete region tags

- functions/pubsub/main.py
Addressing customer feedback.
(The Java sample has a [similar note](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/HEAD/functions/pubsub/publish-message/src/main/java/functions/PublishMessage.java#L37) already.)
> chore(functions/pubsub): clarify env var must be specified manually

- run/markdown-preview/e2e_test.py
- run/markdown-preview/requirements-test.txt
> fix(run/markdown-preview): make tests more robust

- appengine/standard_python3/bundled-services/mail/flask/main_test.py
> fix(appengine): add retries to log assertion

- .kokoro/lint/common.cfg
- .kokoro/python2.7/common.cfg
- .kokoro/python3.10/common.cfg
- .kokoro/python3.7/common.cfg
- .kokoro/python3.8/common.cfg
- .kokoro/python3.9/common.cfg
- .kokoro/tests/run_tests.sh
> testing: remove btlr binary

- functions/concepts-filesystem/main.py
- functions/concepts-filesystem/requirements.txt
Update [file system concept sample](https://cloud.google.com/functions/docs/samples/functions-concepts-filesystem#functions_concepts_filesystem-python) to use functions framework.
Tested by:
* Running local tests
* Deploying and invoking using curl
stdout:
> chore(functions/concept-filesystem): Update function signature using functions framework

- functions/tips-connection-pooling/main.py
- functions/tips-connection-pooling/requirements.txt
Update https://cloud.google.com/functions/docs/samples/functions-tips-connection-pooling#functions_tips_connection_pooling-python signature to gen2 using functions framework
Tested by:
* Running Locally
* Running pytest
* Deploying and invoking using curl
stdout: ```Success!```
> chore(functions/connection_pooling): Update function signature to use functions framework

- functions/helloworld/main.py
- functions/helloworld/requirements-test.txt
- functions/helloworld/requirements.txt
> chore: update HelloWorld error samples

- CONTRIBUTING.md
> I found a typo on the CONTRIBUTING document

- composer/tools/composer_db_transfer.md
- composer/tools/composer_db_transfer.py
> Deprecation notice for composer_db_transfer.py

- .github/CODEOWNERS
Updates the GH codeowners to include a teamsync team of folks who can be the Composer approver in addition to me and Rachael
> update GH owners for composer to include teamsync team

- functions/concepts-after-timeout/main.py
- functions/concepts-after-timeout/requirements.txt
Update [Execution after timeout sample](https://cloud.google.com/functions/docs/samples/functions-concepts-after-timeout) function signature using functions framework
Tested by:
Deploying and invoking using curl
> chore(functions/concepts-after-timeout): Update sample signature using functions framework

- functions/tips-lazy-globals/main.py
- functions/tips-lazy-globals/requirements.txt
Update [Lazy globals sample](http://cloud/functions/docs/samples/functions-tips-lazy-globals) to use functions framework.
Tested by:
Running local tests
Deploying and invoking using curl
> chore(functions/tips-lazy-globals): Update sample signature using functions framework

- functions/tips-scopes/main.py
- functions/tips-scopes/requirements.txt
Update [Global versus function scope sample](http://cloud/functions/docs/samples/functions-tips-scopes) function signature using functions framework
Tested by:
Running local tests
Deploying and invoking using curl
> chore(functions/tips-scopes): Update sample signature using functions framework

- functions/tips-gcp-apis/main.py
- functions/tips-gcp-apis/requirements.txt
Update python sample https://cloud.google.com/functions/docs/samples/functions-tips-gcp-apis to use declarative function framework signature.
Tested by:
1. Running local tests
2. Deploying function and creating a pubsub topic for testing. Messages arrived as expected.
> chore(functions/tips-gcp-apis):update sample to use functions framework declarative signature

- people-and-planet-ai/README.md
- people-and-planet-ai/weather-forecasting/README.md
- people-and-planet-ai/weather-forecasting/notebooks/1-overview.ipynb
- people-and-planet-ai/weather-forecasting/notebooks/2-dataset.ipynb
- people-and-planet-ai/weather-forecasting/notebooks/3-training.ipynb
* Add links to video
* Fixes relative paths to source files
* Fixes broken links
* Add titles to notebooks
> ppai/weather-forecasting: add video link + fix links

- run/filesystem/cloudbuild.yaml
- run/filesystem/e2e_test.py
> chore: update the filesystem sample tests

- firestore/cloud-client/snippets.py
Pending cl/509567007 to update docs; do not merge until SnippetBot is happy.
> chore(firestore): removing obsolete region tags

- recaptchaenterprise/samples/demosite/docker-compose.yaml
This can be helpful such that files get created by the same user that is running docker
> Add an optional DOCKER_COMPOSE_USER environment variable. 

- .kokoro/python3.11/common.cfg
- .kokoro/python3.11/continuous.cfg
- .kokoro/python3.11/periodic.cfg
- .kokoro/python3.11/presubmit.cfg
Towards https://github.com/GoogleCloudPlatform/python-docs-samples/issues/8873
> fix: add kokoro config files for python 3.11

- media_cdn/dualtoken.py
- media_cdn/snippets.py
No new code changes, except for minor cosmetic changes for CGC pages.
- Update copyright year
- Add new region tag for `sign_url_prefix` function
> Minor updates for Media CDN snippets

- translate/samples/snippets/hybrid_glossaries/hybrid_tutorial_test.py
> fix: update translate test string

- .kokoro/docker/Dockerfile
Prepare docker image for testing of Recaptcha Enterprise samples migrated in PR #8532.
> chore: Prepare Dockerfile for Recaptcha tests

- dlp/snippets/README.md
Add README for DLP. Testing the CODEOWNERS and notifications workflow for the DLP team.
> chore: add Readme for DLP
