testing/test-env.tmpl.sh

Made some cleanups in the test-env.tmpl.sh. I also synced with the current secret.

chore: clean up the test-env template and sync to the current secret

---

appengine/standard/firebase/firenotes/frontend/index.html
appengine/standard_python3/building-an-app/building-an-app-4/templates/index.html
appengine/standard_python37/building-an-app/building-an-app-3/templates/index.html
appengine/standard_python37/building-an-app/building-an-app-4/templates/index.html

Fixes #4421
Script and stylesheet references pointed to no longer used URLs for Firebase.

Fix firebase source URLs

---

iap/example_gce_backend.py

Fixes #4260
The method signature for validate_iap changed with 41c173 but the
call to validate_iap from example_gce_backend.py was not changed

Fix the call to validate_iap (#4260)

---

container_registry/container_analysis/README.md

Fix link to container analysis samples

---

dataflow/flex-templates/streaming_beam/streaming_beam_test.py

fixes #4492
I know this is a terrible workaround, but this test has been failing for
a week. I'd like to make our builds green first.

fix(dataflow): use gcloud for teardown

---

run/logging-manual/e2e_test.py

fixes #4609
Now the test finishes in a couple of minutes. The test used to take 30 minutes or so without this change.

fix(run): add timestamp filter for faster test

---

functions/firebase/main.py
functions/firebase/main_test.py

N.B: this doesn't actually fail on Cloud Functions (since Firebase doesn't emit `update` events for documents that don't change) - but it _does_ rely on undocumented (and thus, not necessarily guaranteed!) behavior.

chore(functions/firebase): add guard against infinite loops

---

dataflow/run_template/main_test.py

Fixes #4686
It should be an uncommon occurrence that a job hangs in queue for more than 4 minutes (and therefore unable to cancel), probably because many tests were triggered at a similar time.
I'm slightly increasing the max retry time to 5 minutes to leave more room for jobs to be cancelled, but most of the time it will be cancelled much quicker.

dataflow/run_template: slightly increase max retry time in test

---

spanner/cloud-client/backup_sample.py
spanner/cloud-client/backup_sample_test.py
spanner/cloud-client/requirements-test.txt

test(spanner): fix flaky restore_database() sample test

---

.kokoro/python3.6/periodic.cfg
.kokoro/python3.7/periodic.cfg

Now we only upload the Docker image after a successful py38 periodic builds. Unfortunately, recently we have been having red py38 periodic builds, our Docker image is becoming old thus all our presubmit builds needs to build the Docker image from scratch.
By allowing other periodic builds to upload the Docker image, we'll have a higher chance of the Docker image being updated.

chore: also upload the Docker image in py36 and py37 builds

---

dataflow/README.md
dataflow/encryption-keys/README.md
dataflow/flex-templates/streaming_beam/README.md
dataflow/run_template/README.md

Updating the "Open in Cloud Shell" links to clone the repo and open the correct README file.

dataflow: update "Open in Cloud Shell" links

---

.github/sync-repo-settings.yaml

chore(sync-repo-settings): disable admin enforced

---

functions/ocr/app/main.py

* Fixes the problem with incorrect parameter name
Fixes #4905 
> File "/user_code/main.py", line 42, in detect_text text_detection_response = vision_client.text_detection(source=image) TypeError: inner() missing 1 required positional argument: 'image'
I got this error message when I followed the tutorial
https://cloud.google.com/functions/docs/tutorials/ocr#functions-clone-sample-repository-python
`
/functions/ocr/app/main.py, line 42 
`
```
text_detection_response = vision_client.text_detection(image=image)  
```
change parameter name "source" => "image"

Fix incorrect parameter name

---

ml_engine/online_prediction/predict_test.py

Fixes #4915
I am pretty sure this test output should be deterministic, so I was a bit surprised by this. However, the issue is some floating point error, so I updated the text to check that the `confidence` is close rather than exactly identical.
- [N/A] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [N/A] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [N/A] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [N/A] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNER …

Make predict test more lenient

---

storage/cloud-client/storage_set_metadata.py

I believe a call to `blob.patch()` is necessary to actually save the metadata back to GCS.

Add patch call

---

storage/cloud-client/storage_download_file.py
storage/cloud-client/storage_get_metadata.py

There have been reports that perhaps `blob` and `get_blob` and there differences can be confusing to users. This attempts to bring in some context to popular samples to help clarify.

fix: add a comment to draw attention to using get_blob, not blob

---

storage/cloud-client/storage_list_files_with_prefix.py

The comment doesn't specify that a prefix should end in the delimiter if using a delimiter.

fix(storage): Update comment, prefix should include delimiter

---

dataflow/README.md

Many of the APIs are already enabled or are automatically added by the `dataflow` API.

dataflow: simplify enabled APIs list

---

run/deployment-previews/check_status.py

Based off conversation in PR #5212, stripping the extra spaces/newlines from the secret can help prevent any issues

Strip spaces and newlines from secret

---

.github/CODEOWNERS

Add iot team as code owner

---

run/logging-manual/main.py

Responding to developer feedback that it is confusing to come from the docs to the main.py and see `GOOGLE_CLOUD_PROJECT` environment variable. This adds the missing context. For more discussion of this feedback, see b/178792002 (internal).
This applies to both Cloud Run and Cloud Functions, let's see what the bot thinks about my tagging both on the PR.

fix(run): Clarify the source of GOOGLE_CLOUD_PROJECT var

---

run/django/cloudmigrate.yaml

Correct default settings name for django settings (underscore, not hyphen)
b/178553088

fix(django): correct default secret name

---

.kokoro/docker/Dockerfile
.kokoro/tests/run_single_test.sh
.kokoro/tests/run_tests.sh

This migrates the `python-docs-samples` repo off the Python-only `v1` AST parser architecture and onto the more language-agnostic `v2` (or "polyglot parser") architecture.

feat(AST parser): use v2 parser architecture

---

.kokoro/docker/Dockerfile

Workaround for the docker authentication issue.

fix: use temporary ubuntu image from gcr.io

---

.kokoro/docker/Dockerfile

It also uses the latest version of python.

fix: use cached image from mirror.gcr.io

---

data-science-onramp/data-cleaning/clean.py
data-science-onramp/data-cleaning/clean_test.py

fixes #5312
It won't fix the issue, but will allow us to debug better.

testing(data-science-onramp): add debug output

---

datastore/cloud-client/admin.py
datastore/cloud-client/admin_test.py
datastore/cloud-client/snippets.py
datastore/cloud-client/snippets_test.py
datastore/cloud-client/tasks.py
datastore/cloud-client/tasks_test.py

fixes #5250
also remove unnecessarily long `max_time`.

fix(datastore): longer LRO timeout

---

.kokoro/docker/Dockerfile

gcr.io/cloud-devrel-kokoro-resources/python-samples-testing-docker
will be updated once one of our continuous builds passes. This image is
also reused by sample tests in Python libraries.

testing: upgrade the test docker image to ubuntu 20.04

---

run/django/mysite/settings.py

`env_file` declared on line 32 and hardcoded `.env` on line 37th refers to same file. But still, both have been rewritten separately which may lead to inconsistency if the filename is changed in any single place, or if someone run the program from a different directory other than `run/django`.
Fixes #5491

fixed inconsistency of dotenv in run/django project

---

composer/blog/README.md
composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/README.md

Adds links to now published blog posts for cloud Composer. README-only changes

chore(composer): readme-only changes

---

jobs/v3/api_client/email_alert_search_sample_test.py

fixes #5490
My usage of retry_delay was wrong. It only retries 2 times.
I think using `backoff.expo` is just fine and we can reduce the
`max_time` too.

fix(jobs): switch to backoff.expo, shorter timeout

---

composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/requirements.txt
composer/workflows/requirements.txt

Unblocks #5515 and #5521
I merged a PR this morning that bumped sqlalchemy dependencies in other samples to 1.4. It seems like we're using the cached version of that dependency by the time we get to Composer samples, and Airflow does not play well with SQLalchemy 1.4, so we need to explicitly pin to the latest 1.3.* version until at least Airflow 2.0.

Explicitly pin SQLAlchemy for composer samples

---

eventarc/audit-storage/Dockerfile
eventarc/audit-storage/main.py

Updates region tags to use `audit_storage`, not `gcs`.
These aren't in the docs, please merge this when approved.

chore(eventarc): update region tags

---

testing/test-env.tmpl.sh

feat: add environment variables for dialogflow samples.

---

.github/CODEOWNERS

chore: Add Yoshi to trace codeowners

---

composer/rest/get_client_id.py
composer/rest/get_dag_prefix.py

chore: fix typos

---

composer/dag_test_utils/README.md
composer/dag_test_utils/pyproject.toml
composer/dag_test_utils/setup.py

I redid the setup.py with a better, more descriptive name, and added a pyproject.toml. I haven't added it to PyPI yet in case we wanted to do something like change the name, but to test locally, you can
- Change to this branch and to `composer/dag_test_utils`
- Build with `python3 -m build` (you might have to `pip install build`)
- Change to `../workflows`
- `pip install ../dag_test_utils/dist/cloud_composer_dag_test_utils-0.0.1.tar.gz`
- Open a python editor and try `import internal_unit_testing` - you may see some deprecation warnings, and those are okay. They're part of underlying Airflow and will be resolved in the next release. If you see any `ModuleNotFoundError` errors, we should talk because I probably got something wrong. 
- (alternative path) go to the `requirements-test.txt` …

prepare utils for pypi distribution

---

functions/helloworld/main.py
functions/helloworld/sample_pubsub_test.py

Improve the Pub/Sub Cloud Functions example by describing what `event` and `context` are. 
Show a way to extract topic name from `context` in the sample as well. 
Tested that it indeed works in a demo I published in my personal repo: https://github.com/anguillanneuf/buganizer/tree/main/177311703

docs: describe event and context in Pub/Sub example

---

renovate.json

The problem with RenovateBot currently is that it actually treats `minor` and `patch` releases to be the same. See [separateMinorPatch](https://docs.renovatebot.com/configuration-options/#separateminorpatch) docs for more detail.
To mitigate this, we first include a rule to tell RenovateBot to separate and recognize between `minor` and `patch` releases. Then, we create a second rule to disable `patch` updates. This should now successfully let RenovateBot to only update on `major` and `minor` patches.
Fixes #5873 

chore(deps): update Renovate to ignore patches

---

appengine/standard_python3/django/polls/templates/polls/detail.html
appengine/standard_python3/django/polls/templates/polls/index.html
appengine/standard_python3/django/polls/templates/polls/results.html

Additional to #5784 
Fixes rendering on templates due to incorrect comment style in context
before/after: 

(minor) Correct comment format for licence on templates

---

storage/s3-sdk/s3_sdk_test.py

I realized that the tests weren't actually running as I wrote them
previously. Whoops! With this change they should be running as
expected.

test(storage): fix S3 SDK tests (again)

---

compute/metadata/vm_identity.py
compute/metadata/vm_identity_test.py

+ Adding a docstring to the sample.
While updating the [public documentation](https://cloud.google.com/compute/docs/instances/verifying-instance-identity) page, I notices that I included unnecessary `import pprint` in one of the regions. So I want to fix this + add a docstring the the sample.

chore: Cleaning up the vm identity sample.

---

renovate.json

fixes #6178
Regex is the same that we use in the [synth template](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/renovate.json)

ignore composer blog constraints

---

people-and-planet-ai/image-classification/README.ipynb
people-and-planet-ai/image-classification/requirements.txt

In pip 21 with Beam 2.30 and AI Platform 1.1.1, there is a dependency version conflict causing pip to hang for a really long time. Pinning `google-cloud-bigquery==2.18.0`, which is required by both libraries, seems to resolve this conflict.
The notebook also now needs to restart the runtime due to dependency updates, so I'm also updating that.

ppai/image-classification: fix dependency conflicts

---

run/django/mysite/settings.py

* Configures `STATIC_URL`, required for local development in debug mode
* Fixes imported error name
cc @averikitsch

Minor fixes to django cloud run tutorial

---

run/markdown-preview/editor/templates/index.html

This is a fix propagating from https://github.com/GoogleCloudPlatform/golang-samples/pull/2149
* Pin material to v11
* Use new fullwidth guide "width: 100%"

fix(run/markdown-preview): full width input form

---

.github/CODEOWNERS

Adds @glasnt as a codeowner for the django samples

Add glasnt as */django/* codeowner

---

compute/encryption/generate_wrapped_rsa_key.py
compute/encryption/requirements.txt

Fixes the code that was failing with new version of requests library, as evident in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/6422

fix: Encryption samples no logner break with new requests library version

---

appengine/flexible/django_cloudsql/mysite/settings.py
kubernetes_engine/django_tutorial/mysite/settings.py
run/django/mysite/settings.py

Removes old tags, cleans up a newer tag to confirm with format (underscore separated names)

chore: clean up django region tags

---

appengine/flexible/django_cloudsql/mysite/settings.py
kubernetes_engine/django_tutorial/mysite/settings.py
run/django/mysite/settings.py

chore: Remove deprecated region tag

---

storage/cloud-client/acl_test.py
storage/cloud-client/noxfile_config.py

Previous service account email used by the storage acl tests no longer exist in the project. 
Update to use an existing service account email that has storage admin permissions
Fixes #6518, Fixes #6519, Fixes #6520, Fixes #6521
Fixes #6522, Fixes #6523, Fixes #6524, Fixes #6525

fix(storage): update service account email for acl tests

---

run/helloworld/Dockerfile

Use requirements.txt instead of hard-coded install

---

healthcare/api-client/v1beta1/fhir/fhir_resources.py
healthcare/api-client/v1beta1/fhir/fhir_stores.py

The `v1` healthcare region tags collide with the `v1beta1` region tags.

fix(samples): v1 and v1beta1 region tags collide

---

iap/requirements.txt

chore: Use latest google-auth to avoid a utility function deprecation

---

composer/airflow_1_samples/kubernetes_pod_operator.py
composer/workflows/kubernetes_pod_operator.py

I was going through [this tutorial](https://cloud.google.com/composer/docs/how-to/using/using-kubernetes-pod-operator#secret-config) earlier and found that the environment variable set here throws TemplateNotFound errors. It's because of a stupid quirk of Airflow and adding a space after the filename fixes it. 🙄 (found in [common pitfalls](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=62694614))

Two character update to Airflow DAG

---

storage/cloud-client/public_access_prevention_test.py

This temporary skips failing test until we get the PAP changes for #6751  fully merged in.
GCS is changing the `unspecified` public access prevention value to `inherited`
Please see nodejs example here: https://github.com/googleapis/nodejs-storage/pull/1614/files

fix(storage): skip test temporarily before pap changes release

---

storage/cloud-client/bucket_lock_test.py

Although changes to the bucket (enabling `default_event_based_hold`) will be readable immediately after writing, configuration changes may take time to propagate. This adds time to allow the bucket configurations to propagate. 
Fixes #6733

fix(storage): add time for bucket config changes to propagate

---

appengine/flexible/storage/main.py
appengine/flexible/storage/main_test.py
appengine/flexible/storage/noxfile_config.py
appengine/flexible/storage/requirements-test.txt
iot/api-client/gcs_file_to_device/gcs_send_to_device_test.py

Fixes #6725, #6724
I disabled public access on the `python-docs-samples-tests` bucket and these were the two tests that failed. 
For the AppEngine sample it felt a bit awkward to create the bucket _before_ the app is imported (`main.py` references the bucket through an env var) so I stood up a new, separate bucket with public access enabled.
For IoT, I modified the test to create its own bucket.

fix: create separate bucket for iot gcs_file_to_device test

---

noxfile-template.py

By default nox skips the session if the interpreter is missing.
This asks it to error instead.

fix: fail nox session if python version is missing

---

appengine/standard/django/README.md

Fix link to external Django tutorial

---

composer/airflow_1_samples/constraints.txt
composer/airflow_1_samples/noxfile_config.py
composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/constraints.txt

Fixes #7045
Fixes #7046
Fixes #7047
Fixes #7048
Fixes #7049
Fixes #7050
Fixes #7051
Fixes #7052 
Fixes #7053

add constraint on WTForms

---

memorystore/redis/cloud_run_deployment/e2e_test.py
run/django/test/e2e_test.py
run/filesystem/e2e_test.py
run/hello-broken/e2e_test.py
run/helloworld/e2e_test.py
run/idp-sql/test/e2e_test.py
run/image-processing/e2e_test.py
run/logging-manual/e2e_test.py
run/markdown-preview/e2e_test.py
run/pubsub/e2e_test.py
run/system-package/e2e_test.py

Changed `subprocess.run` to `subprocess.check_call` whenever we're running a command and not saving the stdout.  This bubbles up the error message.  
We had some flaky tests failing on subprocess.run (eg [hello-broken](https://source.cloud.google.com/results/invocations/31e5fdd2-bcc3-4012-a153-1fd81271dba6/targets/github%2Fpython-docs-samples%2Frun%2Fhello-broken/tests)), so this should help us debug it in the future.

Using check_call to expose underlying error messages

---

composer/rest/composer2/composer2_airflow_rest_api.py

Add region tags, so that this example can be used on a different documentation page.

Add region tags for the Composer 2 Airflow REST API example

---

run/deployment-previews/Dockerfile
run/deployment-previews/check_status.py
run/deployment-previews/cloudbuild-configurations/cloudbuild-cleanup.yaml
run/deployment-previews/cloudbuild-configurations/cloudbuild-preview.yaml
run/deployment-previews/requirements.txt
run/deployment-previews/test_app.py

Fixes #5009
* Migrates from secret manager API to built-in secrets for Cloud Build 
* Removes `gcloud` dependency and uses discovery API for service updating/tag removing.

refactor: Update deployment preview to support built-in secrets, discovery API

---

people-and-planet-ai/timeseries-classification/e2e_test.py

Helps to debug: #7024 (similar to #7140)
Use subprocess.check_call instead of subprocess.run to have better error messages.
Subprocesses where we capture output were left the same.

ppai/timeseries-classification: use check_call instead of run

---

auth/service-to-service/auth_test.py

Remove invalid --async flag from functions command.
Fixes #7111
I meant to add this flag to the Cloud Run commands to fix the flaky test, but accidentally also added it to a functions command.

fix: Remove invalid --async flag from functions command

---

bigquery/bqml/requirements.txt
bigquery/pandas-gbq-migration/requirements.txt

Upgrade pandas in BQ samples lagging in python 3.10

---

data-science-onramp/data-ingestion/ingestion.py
data-science-onramp/data-ingestion/ingestion_test.py
data-science-onramp/data-processing/process.py
data-science-onramp/data-processing/process_test.py

We currently are having problems with dataproc clusters in our test environment (see b/211687420 if you're internal) and I figured out that these tests had leftovers if the dataproc fixtures failed which meant we were hitting quotas. This cleans up the leftovers if theres an error creating the cluster and still raises the error.

Cleanup cluster if error during creation

---

noxfile-template.py

This adds a check to the noxfile to see if there are tests in the directory. To test, use the noxfile-template in any directory with tests. Then try it on a directory like [this one](https://github.com/nikitamaia/python-docs-samples/tree/geospatial-sandbox/people-and-planet-ai/geospatial-classification/serving_app) which is found in PR #7291. This does assume that all tests are of the format `*_test.py` - if we want, I can also include a check for `test_*.py`, because I know that's a common Python pattern even though it's not the one we use. 
Corresponding PR in synthtool https://github.com/googleapis/synthtool/pull/1321
cc @davidcavazos - this will hopefully remove the need for your workaround

Noxfile check for tests

---

AUTHORING_GUIDE.md

The correct value to be changed in `testing/test-env.sh` is `GOOGLE_CLOUD_PROJECT`
instead of `GCLOUD_PROJECT`.
Source:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/1d6736bd49778b2440e348890ec444d785c4fb60/testing/test-env.tmpl.sh#L16

doc: Update env variable mentioned in Authoring Guide

---

people-and-planet-ai/geospatial-classification/requirements.txt

this sample omits 3.6 anyway, so we can remove this vulnerable version of numpy as a requirement

remove numpy version for 3.6

---

datastore/cloud-client/snippets.py
datastore/cloud-client/snippets_test.py

The examples in other client libraries are all using `sampleTask`.
Additionally, the doc says: 
> The following example creates a key with kind Task using a key name, "sampleTask", as the identifier:
Closes internal bug 210583283

docs: Change Python client examples from sample_task to sampleTask

---

composer/airflow_1_samples/dataflowtemplateoperator_tutorial.py
composer/airflow_1_samples/dataflowtemplateoperator_tutorial_test.py

Removes a redundant parameter to match with the [Airflow 2 sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/composer/workflows/dataflowtemplateoperator_tutorial.py)
Fixes b/209830375 along with https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/2531
Dataflow job success: [job](https://pantheon.corp.google.com/dataflow/jobs/us-central1/2022-02-08_11_45_36-18254988095377204925?project=leah-playground) [screenshot](https://screenshot.googleplex.com/4FYdXpwAnkFFBSB)
DAG run success: [screenshot](https://screenshot.googleplex.com/6dxJuW55ZvyoNv9)
Note: It's a good idea to open an issue first for discussion. [airflow logs](https://de34b6bb073e6fc6cp-tp.appspot.com/admin/airflow/log?task_id=dataflow_operator_transform_csv_to_bq&dag_id=composer_dataflow_dag …

fix: remove redundant Airflow variable

---

iam/api-client/quickstart.py
iam/api-client/quickstart_test.py

ADC allows users to authenticate with methods other than a service account key—for example, with credentials for a Google Account created via `gcloud auth application-default login`.

feat(iam): use Application Default Credentials (ADC) in IAM quickstart

---

dataflow/custom-containers/README.md
dataflow/custom-containers/minimal/Dockerfile
dataflow/custom-containers/minimal/e2e_test.py
dataflow/custom-containers/minimal/main.py
dataflow/custom-containers/minimal/noxfile_config.py
dataflow/custom-containers/minimal/requirements-test.txt
dataflow/custom-containers/minimal/requirements.txt

Add samples for Dataflow custom containers.

dataflow: add custom container minimal sample

---

compute/api/create_instance.py
compute/api/create_instance_test.py

Fixes #7461 
I figure the `us-central1` is a bit overused, so there might be more race conditions when tests are running. Going away to Europe should reduce the risk of the race conditions/resource exhaustion.

chore(compute): Changing the default zone for compute api tests

---

composer/airflow_1_samples/requirements.txt
trace/cloud-trace-demo-app-opentelemetry/app/requirements.txt
trace/cloud-trace-demo-app/app/requirements.txt

Pinning markupsafe version to prevent imports failing.
Fixes #7479.

chore(deps): pin markupsafe version

---

healthcare/api-client/v1/fhir/fhir_resources_test.py
healthcare/api-client/v1/fhir/fhir_stores_test.py
healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
healthcare/api-client/v1beta1/fhir/fhir_stores_test.py

For #7433.
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/7433#issuecomment-1053561512 These tests failed with a `KeyError` yesterday in the 3.7 periodic build last night:
```
Traceback (most recent call last):
File "/workspace/healthcare/api-client/v1beta1/fhir/fhir_stores_test.py", line 62, in test_dataset
wait_for_operation(operation["name"])
File "/workspace/healthcare/api-client/v1beta1/fhir/.nox/py-3-10/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
return retry_target(
File "/workspace/healthcare/api-client/v1beta1/fhir/.nox/py-3-10/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
return target()
File "/workspace/healthcare/api-client/v1beta1/fhir/fhir_stores_test.py", line 51, in …
```

test(healthcare): include full operation in exception message

---

.github/blunderbuss.yml

Updating Blunderbuss to sync with the CODEOWNERS file, see #7520 for reference.
Also updating Blunderbuss to use GH teams whenever applicable, especially for sample owners.
Fixes #7262.

chore: update blunderbuss to use GH teams

---

composer/airflow_1_samples/airflow_db_cleanup.py

Fixes b/223364117 
The DAG is now able to perform cleanup operation on airflow databases with larger data in a single table.
More context : http://docs/document/d/1eWydWjGXqqQ4lvACOMs5o7qQtnuuyo_0jzwWXJ3_YfY?resourcekey=0-TBb9afCO5cWD5hhW_sRZgQ

Fix airflow_db_cleanup script

---

auth/service-to-service/auth.py

b/224052838
Listener report showed confusion with variable name, which isn't used in any other languages but Python and isn't consistent with comments.

Fix: Change variable name for consistency

---

run/deployment-previews/test_app.py

A fix for #7787, more to come. 
Borrows solution from #7788 regarding Any types.

fix: type linting issue

---

people-and-planet-ai/image-classification/e2e_test.py
people-and-planet-ai/image-classification/requirements.txt
people-and-planet-ai/image-classification/train_model.py
people-and-planet-ai/timeseries-classification/create_datasets.py
people-and-planet-ai/timeseries-classification/trainer.py

ppai: fix lint errors

---

composer/workflows/gke_operator.py

Companion to cl/439518578 - we recommend using regional clusters not zonal clusters
[Airflow success](https://screenshot.googleplex.com/BbGYiKnWMgzuweC)
Airflow 1 sample will not be updated to match due to the way the `location` functionality is implemented in Airflow 1. If customer want to use regional clusters, we recommend they upgrade to Airflow 2.

chore: Update Airflow 2 GKE sample to use regional clusters

---

dataflow/custom-containers/ubuntu/Dockerfile

Fixes #7822
It looks like they upgraded the Python version to 3.10 on the newly released `ubuntu:jammy` changed. Recently `ubuntu:latest` now points to `ubuntu:jammy` ([Python per Ubuntu releases](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python3-dev&searchon=names)). Even though Apache Beam is available in Python 3.10 through `pip`, unfortunately there is no "official" support for it so there is no `apache/beam_python3.10_sdk` image (to pull the worker boot files from).
We're pinning to `ubuntu:impish` which is the latest ubuntu image with Python 3.9 support.

dataflow (fix): pin in to ubuntu:impish

---

pubsublite/spark-connector/spark_streaming_test.py

Schedule Dataproc clusters for deletion during cluster creation time. Clusters will get deleted even if tests fail, freeing up resources.
Tests are no longer flaky:
fixes #7928 
fixes #7927

pubsublite: lifecycle config during cluster creation

---

healthcare/api-client/v1/consent/README.rst

Caused by Nox README generator.

Manually fix formatting issue in README

---

composer/2022_airflow_summit/data_analytics_process_test.py
composer/2022_airflow_summit/requirements-test.txt

add backoff to fix flaky test

---

run/idp-sql/app.json

chore(run/idp-sql): Fix cloud run button

---

pubsublite/spark-connector/noxfile_config.py

Fixes #8123 
Fixes #8124 
The flaky test was caused by parallel test runs in different Python version: `StatusCode.ALREADY_EXISTS`. There's really no need to test both Python 3.7 and 3.8 for this sample. Proposing that we just run tests in one Python version.

pubsublite: limit tests in python 3.8

---

.kokoro/docker/Dockerfile

Dockerfile build fails with:
```
Step #0: [0mERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
Step #0: The command '/bin/sh -c wget --no-check-certificate -O /tmp/get-pip.py 'https://bootstrap.pypa.io/get-pip.py'     && python3.6 /tmp/get-pip.py "pip==$PYTHON_PIP_VERSION"     && pip3 install --no-cache-dir --upgrade --force-reinstall "pip==$PYTHON_PIP_VERSION"     && [ "$(pip list |tac|tac| awk -F '[ ()]+' '$1 == "pip" { print $2; exit }')" = "$PYTHON_PIP_VERSION" ]' returned a non-zero code: 1
Finished Step #0
ERROR
```

Updated Dockerfile from using Python 3.6 to 3.10

---

.kokoro/docker/Dockerfile

Make sure that every version of Python gets PIP installed.

chore(docker): Update Dockerfile to install pip for every Python3 version

---

cloud-sql/sql-server/sqlalchemy/requirements.txt

Updates pyodbc dependency in sqlalchemy sample to fix failing test:
```
------------------------------------------------------------
- testing /workspace/cloud-sql/sql-server/sqlalchemy
------------------------------------------------------------
Using noxfile-template from parent folder (/workspace).
nox > Running session py-3.9
nox > Creating virtual environment (virtualenv) using python3.9 in .nox/py-3-9
No user noxfile_config found: detail: No module named 'noxfile_config'
nox > python -m pip install -r requirements.txt
nox > Command python -m pip install -r requirements.txt failed with exit code 1:
Collecting Flask==2.1.0
Using cached Flask-2.1.0-py3-none-any.whl (95 kB)
Collecting gunicorn==20.1.0
Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting python-tds==1.11.0 …
```

fix: update pyodbc dependency to fix sqlalchemy test

---

README.md

Removes 3.6 status from the main README, 3.6 tests have been removed previously.

chore: remove 3.6 status from the README

---

AUTHORING_GUIDE.md

chore: add link to Google Cloud Samples Style Guide

---

dataflow/custom-containers/ubuntu/Dockerfile
dataflow/custom-containers/ubuntu/requirements.txt

It looks like Ubuntu Impish was not an LTS version and is no longer supported. Since Apache Beam still does not "officially" support Python 3.10 we can't move towards latest (Jammy), so I'm "downgrading" to Focal which is the previous LTS version. It uses Python 3.8 by default, so I also changed the Beam image to pull the boot files from.
I also updated the Beam version as a side effect :)
Fixes #8206

dataflow/ubuntu-container: use LTS ubuntu version

---

datastore/cloud-client/admin_test.py

Fix: Datastore client: Mark test as flaky

---

appengine/standard/appengine_helper.py
datastore/cloud-client/snippets_test.py
datastore/cloud-client/tasks_test.py
dns/api/main_test.py

Replace the deprecated `pytest.yield_fixture` with `pytest.fixture`
Fixes #8232

Fix: replace pytest.yield_fixture with pytest.fixture

---

compute/oslogin/requirements-test.txt
compute/oslogin/service_account_ssh_test.py

The current retry is making tests fail out. Instead of indefinitely waiting, retrying with a specific number should help determine whether test passes / fails. 
Unfortunately I can't get the test to pass, but happy to incorporate ideas to help get this test passing. For now, they no longer will be timing out after ~5 hours, instead they'll fail or pass immediately.
Fixes #8219. Towards #7277.

fix: use backoff exception to gracefully exit and fail

---

composer/2022_airflow_summit/data_analytics_process_test.py
composer/2022_airflow_summit/noxfile_config.py

#8021 was similar but was throwing the `Aborted` error, this is giving a 409 `AlreadyExists` which was happening when it would retry but already find a batch there. I've added teardown logic to hopefully reduce the likelihood that an `AlreadyExists` happens.
Fixes #8254 

fix: add fixture for dataproc batch and better test cleanup

---

composer/2022_airflow_summit/requirements.txt

explicitly add google providers dependency

---

appengine/standard_python3/bundled-services/blobstore/django/main.py
appengine/standard_python3/bundled-services/blobstore/flask/main.py
appengine/standard_python3/bundled-services/deferred/flask/main.py
appengine/standard_python3/bundled-services/mail/django/main.py
appengine/standard_python3/bundled-services/mail/django/main_test.py
appengine/standard_python3/bundled-services/mail/flask/main.py
appengine/standard_python3/bundled-services/mail/flask/main_test.py
appengine/standard_python3/bundled-services/mail/wsgi/main.py
appengine/standard_python3/bundled-services/mail/wsgi/main_test.py

Fix: wait time and exception checks

---

dataflow/conftest.py
dataflow/extensible-templates/dataflow_udf_transform.js
dataflow/extensible-templates/e2e_test.py
dataflow/extensible-templates/noxfile_config.py
dataflow/extensible-templates/requirements-test.txt
dataflow/extensible-templates/requirements.txt

Toward internal b/238353202 and b/244173472 (region tags are created on Monday, Aug 29)

dataflow: extensible template with javascript udf

---

dataflow/flex-templates/streaming_beam/requirements.txt

Fixes #8297
Bumping the `apache-beam[gcp]` version to (indirectly) bump the `google-cloud-pubsub` version to accept the keyword argument `request` on `create_topic()`

dataflow: update apache-beam version

---

dataflow/run_template/main_test.py

Fixes #8298
It looks like Dataflow no longer accepts underscores in the job names. Replacing them with hyphens should work.

dataflow: replace job name underscores with hyphens

---

appengine/standard_python3/cloud_debugger/main.py
appengine/standard_python3/cloud_debugger/templates/index.html

fix: unsanitized output

---

composer/airflow_1_samples/conftest.py

should fix lint issue for #8319

fix lint in conftest

---

composer/airflow_1_samples/kubernetes_pod_operator.py
composer/workflows/kubernetes_pod_operator.py

Pin perl version to 5.34.0 for Airflow Kubernetes Pod Operator example

---

cloud-sql/sql-server/sqlalchemy/Dockerfile
cloud-sql/sql-server/sqlalchemy/connect_tcp.py
cloud-sql/sql-server/sqlalchemy/requirements.txt

Consolidating SQL Server samples to [`pytds`](https://python-tds.readthedocs.io/en/latest/index.html) driver for all paths. 
Enables Private IP + SSL TCP connection with App Engine.

chore: update SQL Server samples to use pytds

---

composer/2022_airflow_summit/data_analytics_process_expansion.py

Patching https://github.com/GoogleCloudPlatform/python-docs-samples/pull/8290.
- Removed extra imports
- Removed need to collect data before final processing
- Simplified distance weight algorithm

Bmiro kaiyang edit

---

composer/2022_airflow_summit/data_analytics_process_expansion.py

Add UDF type hinting

---

run/filesystem/cloudbuild.yaml

Fixes #8294 
TLDR: This PR changes `cloudbuild.yaml` used in `run/filesystem/`. The goal is to reduce flakiness caused by the initial cloud build timing out waiting for the subsequent cloud build to finish building, pushing, and deploying. It will help centralize troubleshooting for the build associated with this test into one build job instead of 2.
This PR will:
- in `cloudbuild.yaml`, replace the `gcloud alpha run deploy` with 3 separate steps (`docker build`, `docker push`, `gcloud alpha run deploy`). 
- Originally, this single step created a separate build job that build the image, uploaded it to a default Artifact Registry repo, and deployed to Cloud Run in one shot. 
- make it so each build is pushed to the same folder in the `cloud-run-source-deploy` Artifact Registry repository …

Fix: filesystem e2e flakiness

---

.github/header-checker-lint.yml

Temporarily setting this to `true` while repo migrations are underway.

chore: Update license header config to ignore year

---

noxfile-template.py

Ignore `self` annotations for class methods. Typing them require `typing-extensions` to use the `Self` type, which is redundant and does not provide new information. Otherwise, the class name is not available when defining methods since it hasn't finished defining, so it requires further hacks to annotate.
Furthermore, [PEP 673](https://peps.python.org/pep-0673) has made self type annotations unnecessary, but is only available on Python 3.11+.

lint: ignore class self annotations

---

appengine/standard_python3/bundled-services/blobstore/wsgi/main_test.py

After the `gcloud app deploy` command returns, the instance may still need a few seconds before it is responsive. Add a short wait so that tests don't fail for that reason.
Fixes #8495

fix: May need slight wait before responsive

---

cloud_tasks/snippets/README.md
cloud_tasks/snippets/create_queue.py
cloud_tasks/snippets/create_queue_test.py
cloud_tasks/snippets/delete_queue.py
cloud_tasks/snippets/delete_queue_test.py
cloud_tasks/snippets/list_queues.py
cloud_tasks/snippets/list_queues_test.py

- docs: add samples from python-docs-samples/tasks (#36)
- feat!: migrate to use microgen (#38)
- chore(python): add nox session to sort python imports (#254)

migrate code from googleapis/python-tasks

---

.github/CODEOWNERS
.github/blunderbuss.yml

Sorting CODEOWNERS entry, removing `GoogleCloudPlatform/cloud-dpes` team and updating blunderbuss.

fix: update OWNERS and blunderbuss

---

jobs/v3/api_client/general_search_sample.py

Adding in standardized region tags with product prefix to enable tracking, sample browser. See companion PR here: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7442/files

chore(jobs): add normalized region tags with product prefix

---

.github/CODEOWNERS
.github/blunderbuss.yml

Blunderbuss assigned me https://github.com/GoogleCloudPlatform/python-docs-samples/issues/8697 . The Platform ops team doesn't maintain `texttospeech`. 🥲 

fix: remove dee-po team from texttospeech

---

auth/api-client/api_key_test.py

Fixes #8787 
The flakiness could be because the key creation wasn't completed before the tests started executing.

docs(api-key-samples): patch for flaky test, added sleep time

---

monitoring/snippets/v3/cloud-client/snippets_test.py

Monitoring tests failed a few weeks ago due to timeouts. This PR adds backoff support to retry these tests, reducing the chance of flakiness.
Fixes #8817 
Fixes #8818 
Fixes #8819

test: add retries to monitoring tests

---

appengine/flexible/scipy/requirements.txt
appengine/standard/firebase/firenotes/backend/requirements.txt
appengine/standard/migration/taskqueue/counter/requirements.txt
appengine/standard/migration/taskqueue/pull-counter/requirements.txt
bigquery/datalab-migration/requirements.txt
compute/oslogin/requirements-test.txt
iot/api-client/gcs_file_to_device/requirements.txt
language/snippets/classify_text/requirements.txt

Mend Renovate's [dashboard](https://app.renovatebot.com/dashboard#github/GoogleCloudPlatform/python-docs-samples/959440112) for our repo has been showing a warning because [arbitrary equality](https://peps.python.org/pep-0440/#arbitrary-equality) is not supported in requirements files. I think that it was inadvertently added by a different bot 🤖 . Given that it's considered not great practice and is throwing warnings, i've removed the few instances of it to quiet our robot friend. 
(alt text for image - screenshot of renovate bot job log showing "unexpected range error" and a message of "PEP440 arbitrary equality (===) not supported")

Remove arbitrary equals - not supported by MEND renovate

---

run/image-processing/cloudbuild.yaml
run/image-processing/e2e_test.py

Addresses #8832 
This PR makes a few changes to the e2e test for the `image-processing` sample:
- Uses a `cloudbuild.yaml` configuration to build and push image
- Retains image instead of deleting it
- Uses artifact registry instead of container registry
With this PR all images for image-processing e2e tests will be pushed to Artifact registry repo `cloud-run-source-deploy`

Updates to `run/image-processing/e2e_test.py`

---

retail/interactive-tutorials/README.md

There are missing spaces causing the headers not to render.
See https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/retail/interactive-tutorials

docs: Fix Retail README headers

---

appengine/standard_python3/bundled-services/blobstore/django/main_test.py
appengine/standard_python3/bundled-services/blobstore/flask/main_test.py
appengine/standard_python3/bundled-services/blobstore/wsgi/main_test.py
appengine/standard_python3/bundled-services/deferred/django/main_test.py
appengine/standard_python3/bundled-services/deferred/flask/main_test.py
appengine/standard_python3/bundled-services/deferred/wsgi/main_test.py
appengine/standard_python3/bundled-services/mail/django/main_test.py
appengine/standard_python3/bundled-services/mail/flask/main_test.py
appengine/standard_python3/bundled-services/mail/wsgi/main_test.py

Fixes #8852
@engelke I'd argue we should apply this change to other GAE Python 3 samples too, to prevent _future_ flakiness. **WDYT?**

chore(GAE Python3): add HTTP retries to flaky test

---

functions/http/main.py
functions/http/requirements.txt

Update the function signatures for the following samples using functions framework
https://cloud.google.com/functions/docs/samples/functions-http-form-data#functions_http_form_data-python
https://cloud.google.com/functions/docs/samples/functions-http-xml#functions_http_xml-python
https://cloud.google.com/functions/docs/samples/functions-http-cors#functions_http_cors-python
https://cloud.google.com/functions/docs/samples/functions-http-cors-auth#functions_http_cors_auth-python
Since they use a single file I decided to fix all of them :/.
Tested each of them by:
- Deploying a Gen2 function and sending sample `curl` requests
- Running tests

chore(functions/v2): Update sample signatures using functions framework

---

composer/workflows/requirements.txt

Reverts GoogleCloudPlatform/python-docs-samples#8867
This was merged without the 3.8 check running, which is the only check that's enabled for Composer - it ended up breaking in the periodic build because it clashes with the constraints. It'll get upraded when we bump the version of Airflow! 😄

Revert "chore(deps): update dependency apache-airflow-providers-cncf-kubernetes to v5.1.0"

---

.github/CODEOWNERS

The Cloud Retail team is supporting the retail samples, not the Data & AI team directly. Updating CODEOWNERS.

chore: Update Retail sample ownership

---

.kokoro/docker/Dockerfile

#8995 reverted 3.11 support, but it looks like it didn't remove 3.11 from the Docker build image. While testing this problem, I observed that the `docker build` step was responsible for the build freezing.

ci: remove 3.11 from Dockerfile

---

recaptchaenterprise/samples/demosite/docker-compose.yaml

This is to be consistent with the Java and NodeJS reCAPTCHA demos.

Change default port from 8000 to 8080.

---

appengine/standard_python3/bundled-services/mail/wsgi/main_test.py

fix: wait longer for incoming mail

---

.github/CODEOWNERS
.github/blunderbuss.yml
logging/redaction/Dockerfile
logging/redaction/README.md
logging/redaction/log_redaction.py
logging/redaction/log_redaction_final.py
logging/redaction/requirements.txt

Code to support an interactive tutorial that demonstrates log redaction using DLP at ingestion time.

Add log redaction tutorial sample code

---

run/markdown-preview/renderer/main.py
run/markdown-preview/renderer/requirements.txt

The list of allowed tags in bleach 6 is now a `frozenset` rather than a `list`. The existing logic tries to append an extra element, which now fails. This PR creates a new list from the frozenset instead.

fix: migrate run markdown-preview sample to bleach 6

---

batch/requirements.txt

Removing unnecessary `black` requirement for batch. As suggested in #9071

cleanup: Removing black from requirements

---

.github/auto-label.yaml

This PR updates `auto-label.yaml` to include  `people-and-planet-ai/` which is used in [blunderbuss configuration](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/54f19f06894940230ac1d6cd5e11547cc265c816/.github/blunderbuss.yml#L112).

include people-and-planet-ai in auto-label.yaml

---

appengine/standard_python3/bundled-services/mail/wsgi/main_test.py

Fixes lint issue in appengine/standard_python3/bundled-services/mail/wsgi/main_test.py

fix: lint issue in appengine wsgi sample

---

texttospeech/cloud-client/.gitignore
texttospeech/cloud-client/README.rst
vision/cloud-client/README.md

The `vision` and `texttospeech` directories had out-of-date redirect pages for the samples.

chore: removed obsolete redirects from Vision, TTS

---

recaptchaenterprise/samples/demosite/app/backend/create_recaptcha_assessment.py

Round score to the first decimal. Scores never have a second decimal anyway, and the way it is truncated in the frontend can lead to the wrong value displayed (0.8 instead of 0.9 for a value of 0.89999999)

Round score to the first decimal

---

people-and-planet-ai/timeseries-classification/requirements-test.txt
people-and-planet-ai/timeseries-classification/requirements.txt

Splitting out some PPAI dependency updates into a separate PR, because of timeouts. FYI @davidcavazos

chore: update PPAI time series dependencies

---

.kokoro/docker/Dockerfile
.kokoro/lint/common.cfg
.kokoro/python2.7/common.cfg
.kokoro/python3.10/common.cfg
.kokoro/python3.7/common.cfg
.kokoro/python3.8/common.cfg
.kokoro/python3.9/common.cfg
.trampolinerc

Use a prebuilt docker image in presubmits to solve the issue where presubmits fail during the docker build step. See [this log](https://source.cloud.google.com/results/invocations/ed14226d-09e7-431d-aeaa-2f9d8d3b15d6/log) for an example of the failure where the docker build step timed out.
Towards https://github.com/GoogleCloudPlatform/python-docs-samples/issues/8873

ci: use prebuilt docker image in presubmits

---

cloud-sql/sql-server/client-side-encryption/snippets/cloud_sql_connection_pool.py
cloud-sql/sql-server/sqlalchemy/connect_connector.py
cloud-sql/sql-server/sqlalchemy/connection_test.py

In latest version of `sqlalchemy-pytds` library #9145, the `host` param has become optional in the SQLAlchemy engine URL, our samples previously had a dummy value of `localhost` set to fulfill the required host param. Now that it is optional, we can remove `localhost` from the URL for simplicity and to avoid confusion.

chore: remove unused `host` from URL in SQL Server samples

---

cloud-sql/mysql/sqlalchemy/app.py
cloud-sql/postgres/sqlalchemy/app.py
cloud-sql/sql-server/sqlalchemy/app.py

SQLAlchemy v2 is now [commit as you go](https://docs.sqlalchemy.org/en/20/core/connections.html#commit-as-you-go) meaning `.execute` commands are no longer auto-commit and must be followed up with a `.commit` for the statement or query to be performed.
This was missed as part of #9087

fix(cloudsql): make connections commit as you go

---

jobs/v3/api_client/commute_search_sample_test.py

fix flaky test: add httperror to backoff check

---

kms/snippets/noxfile_config.py
kms/snippets/snippets_test.py

Fixes #9125
Updated sleep to have longer time outs (1-32 seconds) to avoid flackyness.

fix: Updated wait_for_ready to fix flacky tests

---

kms/snippets/README.md
kms/snippets/snippets_test.py

Issue #9125
Pull Request #9168 
Adding comments about required permissions for the service account running the tests. Had to figure it out manually for all the python version specific projects.

docs(kms): Adding notes about required roles for running tests

---

vision/AUTHORING_GUIDE.md
vision/CONTRIBUTING.md
vision/snippets/detect/detect_test.py

fix: vision test failures

---

compute/oslogin/oslogin_service_account_ssh.py
compute/oslogin/oslogin_service_account_ssh_test.py

Issue #8429 
Current theory is that the test sometimes fail, because the required firewall rule gets deleted by GCE Enforcer. If the test failas and the rule is still there, then we have a problem.

fix(oslogin_tests): Making the test check if the firewall rule got removed

---

privateca/snippets/requirements-test.txt
privateca/snippets/requirements.txt
privateca/snippets/test_certificate_authorities.py
privateca/snippets/test_subordinate_ca.py

Fixing flacky privateca tests (#9075, #9081)

---

people-and-planet-ai/weather-forecasting/tests/training_tests/test_training.py

Fixes #9272 and #9277 
Vertex AI issues causing failures in tests, not due to the sample. Mark as expected to fail, will remove the mark when the underlying issue is resolved.

fix: mark expected failure

---

cdn/snippets.py

Old region tags are replaced with product specific region tags. Please check b/272509882 for more details.
Region tags were added using https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9258

chore: cleanup un-wanted region tags

---

appengine/standard_python3/bundled-services/blobstore/django/requirements.txt

Python 3.11 tests for bundled services with Django are failing. The tests use an older library version for Python 3.7 compatibility that seems to cause the Python 3.11 problem.
This uses Python version conditions in requirements.txt to satisfy both platforms.

Fix: use current Django

---

people-and-planet-ai/weather-forecasting/notebooks/3-training.ipynb

Related to: #9272
Adds a notice to the sample for users following the sample to be aware that running the training job in Vertex AI will not work until the underlying issue is fixed.

ppai/weather: add notice of vertex issue

---

pubsublite/spark-connector/spark_streaming_test.py

fixes #9308 fixes #9309 
the pub/sub lite spark connector maintainer forgot to update the public gcs location of the connector jar (see b/275751052)
i removed the lifecycle rules in the test gcs bucket for now and will add it back and restore the test to the original state after the bug fix.

fix: pubsublite spark connector test

---

bigquery/datalab-migration/samples_test.py

Datalab has been been effectively frozen for years, and is deprecated. We're no longer investing in fixing these tests, but instead we'll skip them.
In Sept 2023, we'll be at the 1yr mark and can remove the tests and accompanying migration guide.
Fixes: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9458
Fixes: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9457
Fixes: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9456
Fixes: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9455
Fixes: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9372

testing(bigquery): skip all datalab tests

---

dialogflow/set_agent.py

set_agent is resetting from Essentials/Enterprise to Free tier when run in CI. This masks out "tier" so that it does not mutate.
This, combined with setting all test runner projects to Enterprise, should resolve #9404

fix: Add update_mask to SetAgentRequest in set_agent.py::set_agent

---

data-science-onramp/data-ingestion/ingestion_test.py
data-science-onramp/data-processing/process_test.py

retries for data-science-onramp

---

iot/api-client/README.md
iot/api-client/codelabs/noxfile_config.py
iot/api-client/end_to_end_example/noxfile_config.py
iot/api-client/gcs_file_to_device/noxfile_config.py
iot/api-client/http_example/noxfile_config.py
iot/api-client/mqtt_example/noxfile_config.py

I made an issue to track their upcoming removal #9495, but I want to propose skipping IoT tests until then. Some flakiness with those tests has been blocking merging of dependency PRs, and I don't think our time is best spent adding retries to something that is slated for removal later this year. I believe that they are hanging in 3.11, causing #9437 to timeout
If folks aren't ready for this though and think we should wait on this til August, that's fine, just let me know

Skip IoT tests, add deprecation notice to readme

---

noxfile-template.py
pubsublite/spark-connector/README.md

Fixes #9378 
The changes in `noxfile-template.py` effectively adds a `--use-pep517` flag to `pip install`. 
Copied from the text output:
```
nox > python -m pip install -r requirements.txt --use-pep517
```
This is required for pip≥23.1 as described in https://github.com/pypa/pip/issues/8559
Otherwise, we need to build the Spark Jar and install the source distribution as described in the Spark official documentation for this test: https://spark.apache.org/docs/latest/building-spark.html#pyspark-pip-installable

fix(pubsublite): pyspark pip install

---

dataproc/snippets/create_cluster_test.py
dataproc/snippets/submit_job_test.py
dataproc/snippets/update_cluster_test.py

Fixes #9513
Fixes #9461 
Fixes #9445 
Even though I used the native retries in #9496, I went with `backoff` here because it was already in use in the sample. If you prefer i retrofit all of it to the native retry though, I can! I also think this will help with #9437 

add retries for subnetwork not ready errors

---

iam/api-client/custom_roles_test.py

Fixes #9532 #9525 #9526 
There is a hard quota of 300 custom roles per project, and deleted custom roles still count against that quota for up to 14 days, so this test now creates and deletes only one custom role when run.

fix: minimize custom tests used

---

dlp/snippets/redact.py
dlp/snippets/redact_test.py

[DLP] Implemented dlp_redact_image_listed_infotypes with unit test cases. Java equivalent:
https://cloud.google.com/dlp/docs/redacting-sensitive-data-images#dlp-redact-image-listed-infotypes-java

[DLP] Implemented dlp_redact_image_listed_infotypes with unit test cases

---

secretmanager/snippets/snippets_test.py

Fixes flaky secretmanager test
There is a hard quota of 240 writes per second for the secret manager service. Adding one second delay to each test fixture that causes such a write to avoid occasionally exceeding quota.

fix: slow down secretmanager writes

---

dlp/snippets/deid.py
dlp/snippets/deid_test.py

[DLP] Implemented dlp_deidentify_table_bucketing with unit test cases. Java equivalent: https://cloud.google.com/dlp/docs/examples-deid-tables.md#dlp-deid-table-bucketing-java

[DLP] Implemented dlp_deidentify_table_bucketing

---

dlp/snippets/redact.py
dlp/snippets/redact_test.py

[DLP] Implemented dlp_redact_image_all_infotypes with unit test cases. Java equivalent:
https://cloud.google.com/dlp/docs/redacting-sensitive-data-images.md#dlp-redact-image-all-infotypes-java

[DLP] Implemented dlp_redact_image_all_infotypes with unit test cases

---

dataproc/snippets/create_cluster_test.py

Also switch to different subnetwork region
Fixes #9510

fix: rework teardown logic to work correctly with backoff strategy

---

dataproc/snippets/submit_job_test.py

Improves robustness for cluster setup in backoff/retry
Also requested IN_USE_ADDRESSES quota increase  IAM & Admin -> Quotas -> Service (Compute Engine API) -> Metric(In-use IP addresses) on us-central1 and europe-north1 because these quotas were exceeded during presubmit testing of this PR.
Fixes #9513

fix: Adds InvalidArgument as caught exception

---

functions/helloworld/main.py

This PR replaces `logging.warn` which is deprecated as of Python 3.3, in favor of `logging.warning`
- [ x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ x] Please **merge** this PR for me once it is approved

use `logging.warning` in helloworld

---

functions/v2/ocr/main.py
functions/v2/ocr/main_test.py

fix: Use .message.data key to extract data from cloud_event

---

cloud-sql/mysql/sqlalchemy/README.md
cloud-sql/mysql/sqlalchemy/app.flexible.yaml
cloud-sql/mysql/sqlalchemy/app.standard.yaml
cloud-sql/mysql/sqlalchemy/deployment.yaml
cloud-sql/mysql/sqlalchemy/main.py
cloud-sql/mysql/sqlalchemy/requirements.txt
cloud-sql/postgres/sqlalchemy/README.md
cloud-sql/postgres/sqlalchemy/app.flexible.yaml
cloud-sql/postgres/sqlalchemy/app.standard.yaml
cloud-sql/postgres/sqlalchemy/deployment.yaml
cloud-sql/postgres/sqlalchemy/main.py
cloud-sql/postgres/sqlalchemy/requirements.txt
cloud-sql/sql-server/sqlalchemy/README.md
cloud-sql/sql-server/sqlalchemy/app.flexible.yaml
cloud-sql/sql-server/sqlalchemy/app.standard.yaml
cloud-sql/sql-server/sqlalchemy/deployment.yaml
cloud-sql/sql-server/sqlalchemy/main.py
cloud-sql/sql-server/sqlalchemy/requirements.txt

Updating Cloud SQL samples to use gen2 Cloud Functions over gen1 and to use the v2 Cloud SQL Auth Proxy over v1.

chore(cloudsql): update samples to gen2 functions and v2 proxy

---

dataproc/snippets/quickstart/quickstart_test.py

Reduce stress on us-central1 default subnet and prevent failures. Uses a 100% carbon neutral cell
Fixes #9461

fix: Updating dataproc quickstart test region

---

run/idp-sql/requirements.txt

Fixes #9897
Error message `AttributeError: 'HTTPResponse' object has no attribute 'strict'` in the logs for the cloud run service that acts as a test fixture. Googling this lead to: https://stackoverflow.com/questions/76175361/firebase-authentication-httpresponse-object-has-no-attribute-strict-status
Suggested workaround:
urllib3<2.0.0

fix: pin urllib3 as a workaround

---

renovate.json

Previous attempt to enable pyproject.toml did not seemed to have worked. This _should_ work.
Fixes #9895 .

Fix pyproject.toml for Renovate

---

people-and-planet-ai/timeseries-classification/Dockerfile
people-and-planet-ai/timeseries-classification/create_datasets.py
people-and-planet-ai/timeseries-classification/e2e_test.py
people-and-planet-ai/timeseries-classification/local_test.py
people-and-planet-ai/timeseries-classification/main.py

Fixes #9891 and #9797
TensorFlow drastically increased its memory footprint, requiring to increase the available memory on Cloud Run.
Also, Dataflow has trouble pickling the main session when launching from an existing process. Launching the job from a subprocess is the recommended way to avoid pickling unwanted symbols.

ppai/timeseries: fix flaky tests

---

webrisk/snippets/compute_threatlist_diff.py
webrisk/snippets/search_hashes.py
webrisk/snippets/search_uri.py
webrisk/snippets/submit_uri.py
webrisk/snippets/test_basic_samples.py

b/280881593 : Fix typehints and return responses from samples to tests.

refactor: typehints and return for webrisk samples

---

servicedirectory/noxfile_config.py
servicedirectory/quickstart.py
servicedirectory/quickstart_test.py
servicedirectory/snippets.py
servicedirectory/snippets_test.py

b/280879439 : Update typehints for service directory samples.

refactor: update typehints for servicedirectory samples

---

dlp/snippets/inspect_content.py
dlp/snippets/inspect_content_test.py

Implemenetd dlp_inspect_image_listed_infotypes with unit test cases. Java equivalent: https://cloud.google.com/dlp/docs/samples/dlp-inspect-image-listed-infotypes#dlp_inspect_image_listed_infotypes-java

[DLP] Implemenetd dlp_inspect_image_listed_infotypes with unit test cases

---

dataflow/flex-templates/streaming_beam/Dockerfile

This has caused some confusion in the past, and is important to make our examples aligned with the instructions here: https://cloud.google.com/dataflow/docs/guides/templates/configuring-flex-templates#use_custom_container_images.

Update Python template Dockerfile to contain entrypoint

---

.github/blunderbuss.yml

Blunderbuss misassigned #9277 to the wrong team. This PR updates the blunderbuss yaml rule.

Update blunderbuss for people-and-planet-ai

---

scripts/readme-gen/readme_gen.py

Recommendation from https://pyyaml.org/wiki/PyYAMLDocumentation. Also generating README.rst using `nox` fails if safe_load isn't used.

Use yaml.safe_load() in readme-gen instead of yaml.load().

---

dlp/snippets/deid.py
dlp/snippets/deid_test.py

[DLP] Implemented dlp_deidentify_table_row_suppress with unit test cases. Java equivalent: https://cloud.google.com/dlp/docs/examples-deid-tables.md#dlp-deid-table-row-suppress-java

[DLP] Implemented dlp_deidentify_table_row_suppress with unit test cases

---

appengine/flexible_python37_and_earlier/disk/main.py
appengine/flexible_python37_and_earlier/disk/main_test.py

fixit: clean up appengine/flexible_python37_and_earlier/disk

---

appengine/flexible_python37_and_earlier/static_files/main.py
appengine/flexible_python37_and_earlier/static_files/main_test.py

fixit: clean up appengine/flexible_python37_and_earlier/static_files

---

discoveryengine/documents_sample_test.py
discoveryengine/get_operation_sample.py
discoveryengine/import_documents_sample.py
discoveryengine/list_documents_sample.py
discoveryengine/list_operations_sample.py
discoveryengine/operations_sample_test.py
discoveryengine/poll_operation_sample.py
discoveryengine/requirements.txt
discoveryengine/search_sample.py
discoveryengine/search_sample_test.py

Fixes #10066
- Update tests to use returned values instead of print output
- Switch to use `v1` GA endpoint
- Remove alias for library import

fixit: Update to Gen App Builder Tests

---

appengine/standard/iap/main.py
appengine/standard/iap/main_test.py
appengine/standard/migration/memorystore/main_test.py
blog/introduction_to_data_models_in_cloud_datastore/blog_test.py
blog/introduction_to_data_models_in_cloud_datastore/wiki_test.py
compute/auth/application_default_test.py
compute/autoscaler/demo/frontend_test.py
compute/managed-instances/demo/app.py
endpoints/getting-started-grpc/greeter_client.py
endpoints/getting-started-grpc/greeter_server.py
scripts/auto_link_to_docs.py
storage/api/compose_objects_test.py
storage/api/crud_object_test.py
storage/api/customer_supplied_keys_test.py
storage/api/list_objects.py
storage/api/list_objects_test.py

Updated to use standard template, keeping copyright year in place

chore: update license headers failing check

---

compute/client_library/requirements-test.txt

pytest-xdist library is well a supported and actively managed compared to pytest-parallel.
> pytest-parallel was built to run many Selenium tests in parallel. To achieve that, it patches several pytest internals. As pytest changes, these patches become ever more precarious
Source: https://github.com/kevlened/pytest-parallel/issues/104#issuecomment-1293941066

feat: use pytest-xdist for parallel testing

---

renovate.json

Update Renovate config so that minor PRs are submitted monthly, and patch PRs are submitted quarterly. Schedule can be updated at any time.

chore: update dependency update schedule

---

.github/.OwlBot.lock.yaml
.github/.OwlBot.yaml
.repo-metadata.json

- Add Owlbot config to repository to automatically format code using `blacken` on Pull Requests.
- Not sure if this was intentionally left out for some reason, feel free to reject if thats the case

chore: Add Owlbot config to repository

---

dlp/snippets/custom_infotype.py
dlp/snippets/custom_infotype_test.py
dlp/snippets/inspect_content.py
dlp/snippets/inspect_content_test.py
dlp/snippets/templates.py

Corrected Region tags for 6 DLP samples and made related code changes.

[DLP] Corrected Region tags for 6 DLP samples and made related code changes

---

auth/api-client/api_key_test.py

Fixes #8787 
Increase the wait time to 30 seconds before using the key to run tests. Re-added backoff.

chore: handle auth flakiness

---

video/transcoder/get_job_state.py
video/transcoder/job_test.py

There was a breaking change in python 3.11. See 
* https://github.com/python/cpython/issues/94763
* https://github.com/python/cpython/issues/100458
* https://docs.python.org/3/whatsnew/3.11.html#enum
```
Changed Enum.__format__() (the default for format(), str.format() and f-strings) to always produce the same result as Enum.__str__(): for enums inheriting from ReprEnum it will be the member’s value; for all other enums it will be the enum and member name (e.g. Color.RED)
```
Fixes #10241

fix: broken tests due to str(enum) changes in Python 3.11

---

dlp/snippets/inspect_content.py
dlp/snippets/inspect_content_test.py
dlp/snippets/stored_infotype_test.py

These tests compete for the same resource when there are multiple concurrent test runs.
This leads to flaky tests as seen on #10222

fix(dlp, testing): add unique string to dlp infotype tests

---

generative_ai/tuning_test.py

This frequently failing test is impacted by an internal bug. Adding a skip until it is resolved.

chore: add skip to flaky gen_ai test

---

appengine/flexible_python37_and_earlier/tasks/README.md

This PR reorders the two sections `Creating a queue` and `Deploying the App Engine App` of the README.md.
This sample is meant for creating a task queue for an App Engine app. Therefore creating an App Engine App before creating a Task Queue makes more sense.

Revise README.md

---

media-translation/README.md
media-translation/snippets/README.md
media-translation/snippets/translate_from_file_test.py

Adds README.md with the deprecation message 
Disables tests.
Fixes #10370

chore(cleanup): retire media translate samples

---

speech/snippets/transcribe_streaming.py
speech/snippets/transcribe_streaming_test.py

chore: remove return val from transcribe_streaming

---

.github/CODEOWNERS
bigquery-datatransfer/snippets/conftest.py
bigquery-datatransfer/snippets/manage_transfer_configs.py
bigquery-datatransfer/snippets/manage_transfer_configs_test.py
bigquery-datatransfer/snippets/noxfile_config.py
bigquery-datatransfer/snippets/requirements-test.txt
bigquery-datatransfer/snippets/requirements.txt
bigquery-datatransfer/snippets/run_notification_test.py

- BigQuery: Add Data Transfer Service quickstart. [(#1295)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1295)
- Auto-update dependencies. [(#1377)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1377)
- bigquery_datatransfer -> bigquerydatatransfer
- Auto-update dependencies. [(#1846)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1846)
- Auto-update dependencies. [(#1980)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1980)
- Adds updates including compute [(#2436)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2436)
- chore(deps): update dependency google-cloud-bigquery-datatransfer to v1 [(#3208)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3208)
- Simplify noxfile …

migrate code from googleapis/python-bigquery-datatransfer

---

.github/CODEOWNERS
bigquery-migration/snippets/__init__.py
bigquery-migration/snippets/create_migration_workflow.py
bigquery-migration/snippets/create_migration_workflow_test.py
bigquery-migration/snippets/noxfile_config.py
bigquery-migration/snippets/requirements-test.txt
bigquery-migration/snippets/requirements.txt

- docs(samples): add create_migration_workflow snippet (#71)
- chore(deps): update all dependencies (#73)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.4.2 (#74)
- chore(deps): update all dependencies (#93)
- chore(deps): update all dependencies (#111)
- chore(deps): update all dependencies (#113)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.7.0 (#120)
- chore(deps): update dependency google-api-core to v2.10.0 (#126)
- chore(deps): update dependency pytest to v7.1.3 (#130)
- chore(deps): update dependency google-api-core to v2.10.1 (#135)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.7.1 (#138)
- chore(deps): update dependency google-api-core to v2.10.2 (#141)
- chore(deps): update dependency …

migrate code from googleapis/python-bigquery-migration

---

firestore/cloud-async-client/snippets.py
firestore/cloud-client/aggregate_query_count.py
firestore/cloud-client/snippets.py

Update the samples which currently show the following warnings:
```
UserWarning: Detected filter using positional arguments. Prefer using the 'filter' keyword argument instead.
cities_ref.where("state", ">=", "CA").where("state", "<=", "IN")
```

fix(firestore): update query samples to use FieldFilter

---

vmwareengine/cloud-client/cancel_private_cloud_deletion.py
vmwareengine/cloud-client/create_cluster.py
vmwareengine/cloud-client/create_custom_cluster.py
vmwareengine/cloud-client/create_private_cloud.py
vmwareengine/cloud-client/delete_cluster.py
vmwareengine/cloud-client/update_cluster.py

Updating docstrings to better set expectations.

docs(vmware): Updating docstrings

---

dlp/snippets/deid.py
dlp/snippets/deid_test.py

Implemented dlp_deidentify_table_primitive_bucketing sample code. Json Equivalent: https://cloud.google.com/dlp/docs/concepts-bucketing#bucketing_scenario_1

[DLP] Implemented dlp_deidentify_table_primitive_bucketing sample code

---

speech/snippets/create_recognizer_test.py
speech/snippets/enable_cmek.py
speech/snippets/enable_cmek_test.py
speech/snippets/transcribe_batch_dynamic_batching_v2.py
speech/snippets/transcribe_batch_dynamic_batching_v2_test.py
speech/snippets/transcribe_batch_gcs_input_gcs_output_v2.py
speech/snippets/transcribe_batch_gcs_input_gcs_output_v2_test.py
speech/snippets/transcribe_batch_gcs_input_inline_output_v2.py
speech/snippets/transcribe_batch_gcs_input_inline_output_v2_test.py
speech/snippets/transcribe_batch_multiple_files_v2.py
speech/snippets/transcribe_batch_multiple_files_v2_test.py
speech/snippets/transcribe_feature_in_recognizer.py
speech/snippets/transcribe_feature_in_recognizer_test.py
speech/snippets/transcribe_multiple_languages_v2.py
speech/snippets/transcribe_multiple_languages_v2_test.py
speech/snippets/transcribe_override_recognizer.py
speech/snippets/transcribe_override_recognizer_test.py
speech/snippets/transcribe_reuse_recognizer.py
speech/snippets/transcribe_reuse_recognizer_test.py

Added samples for:
* Enabling CMEK
* BatchRecognize (GCS output, inline output, dynamic batching, multiple files)
* Multiple languages recognition
* Various recognizer features

docs(samples): More STT v2 samples

---

.kokoro/docker/Dockerfile

Partial revert of https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10453 which removed python 3.7 from the docker image used for samples testing. This is causing presubmits to fail downstream, for example in https://github.com/googleapis/python-logging/pull/770.

fix: restore python 3.7 in docker image used for samples testing

---

.kokoro/tests/run_tests.sh

Since version [20.22 virtualenv no longer supports Python 2.7](https://virtualenv.pypa.io/en/latest/changelog.html#v20-22-0-2023-04-19). We hardcode virtualenv version to keep Python 2.7 while we work on deprecating it from our repositories.

fix(docker): Hardcoding virtualenv version to keep Python 2.7 support

---

dlp/snippets/risk.py
dlp/snippets/risk_test.py

Implemented dlp_k_anonymity_with_entity_id. Json equivalent: https://cloud.google.com/dlp/docs/visualizing_re-id_risk#step_1_calculate_k-anonymity_on_the_dataset

[DLP] Implemented dlp_k_anonymity_with_entity_id

---

run/logging-manual/app.json

Fixes #10494 
Added "app.json" to get the "Run on Google Cloud" button to prompt for the environment variable the service needs.

fix: run button sets env variable

---

run/filesystem/e2e_test.py
run/filesystem/requirements-test.txt
run/hello-broken/e2e_test.py
run/hello-broken/requirements-test.txt
run/idp-sql/e2e_test.py
run/service-auth/receive_test.py
run/system-package/e2e_test.py
run/system-package/requirements-test.txt

fix: add retries to e2e Cloud Run tests

---

dlp/snippets/stored_infotype_test.py

solving the revert request: #10556

Fix: [DLP] bug fix #10556

---

kms/snippets/requirements.txt

Add missing requirement + bump up google-cloud-kms versions.
Fixes #10609 #10610 #10611 #10612 #10613 #10614

Fix(KMS): Fixing failling tests

---

kms/snippets/decrypt_asymmetric.py
kms/snippets/decrypt_symmetric.py
kms/snippets/encrypt_symmetric.py
kms/snippets/get_public_key.py
kms/snippets/get_public_key_jwk.py
kms/snippets/requirements.txt
kms/snippets/sign_asymmetric.py

Follow-up to previous fix - complete removal of `six` dependency as we no longer support Python 2.7.
Fixes #10614
Fixes #10613
Fixes #10612 
Fixes #10611 
Fixes #10610 
Fixes #10609 

chore(KMS): Remove six dependency

---

error_reporting/snippets/report_exception.py
error_reporting/snippets/report_exception_test.py

align code sample for error reporting with code in other languages (b/275730159):
- use the "same" exception type and message
- refactor the method name

fix: refactor error reporting code sample

---

logging/import-logs/main.py
logging/import-logs/main_test.py

Ensure that neither start nor end dates of the range are older than 29 days from now.
Fixes #10632

fix: add constraint to the age of import log range

---

datastore/cloud-ndb/requirements.txt

Running the sample tests currently fails due to a missing dependency on `six`. As a temporary measure, version 2.2.1 adds `six` as a dependency (see https://github.com/googleapis/python-ndb/issues/911)
1. [x] Please **merge** this PR for me once it is approved

chore(deps): Upgrade NDB version used in samples

---

run/filesystem/gcsfuse.Dockerfile

The URL for packages.cloud.google.com should be https instead of http.

Fix URL for GCS fuse example.

---

datastore/cloud-ndb/named_db.py
datastore/cloud-ndb/named_db_test.py
testing/test-env.tmpl.sh

New sample for Cloud NDB, demonstrating how to access a named database.
** DATASTORE_DATABASE, needs to be changed to the database ID of any Datastore-mode database (recommend "prod-database")

feat(ndb): New sample for named-database support in Cloud NDB

---

composer/workflows/airflow_db_cleanup.py

Update airflow_db_cleanup.py to also clean sessions table

---

dlp/snippets/Metadata/list_info_types.py
dlp/snippets/Metadata/list_info_types_test.py

Fix PR as part of the issue: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10601
This PR only splits metadata related samples into multiple files

feat(dlp): Split metadata samples into multiple files such that each region tag gets its own file

---

dlp/snippets/Inspect/inspect_augment_infotypes.py
dlp/snippets/Inspect/inspect_augment_infotypes_test.py
dlp/snippets/Inspect/inspect_column_values_w_custom_hotwords.py
dlp/snippets/Inspect/inspect_column_values_w_custom_hotwords_test.py
dlp/snippets/Inspect/inspect_file.py
dlp/snippets/Inspect/inspect_file_test.py
dlp/snippets/Inspect/inspect_image_all_infotypes.py
dlp/snippets/Inspect/inspect_image_all_infotypes_test.py
dlp/snippets/Inspect/inspect_image_file.py
dlp/snippets/Inspect/inspect_image_file_test.py
dlp/snippets/Inspect/inspect_image_listed_infotypes.py
dlp/snippets/Inspect/inspect_image_listed_infotypes_test.py
dlp/snippets/Inspect/inspect_phone_number.py
dlp/snippets/Inspect/inspect_phone_number_test.py
dlp/snippets/Inspect/inspect_string.py
dlp/snippets/Inspect/inspect_string_test.py
dlp/snippets/Inspect/inspect_table.py
dlp/snippets/Inspect/inspect_table_test.py

Fix PR as part of the issue: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10601
This PR only splits inspect related samples into multiple files - part 1

feat(dlp): Split inspect samples into multiple files such that each region tag gets its own file part -1

---

secretmanager/snippets/snippets_test.py

Note: This is WIP!
Add fix flaky bot issues in snippet's test file.
* https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10763
* https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10764

fix(secretmanager): Use retry-wrapper for function calls to avoid flaky bot issues

---

.github/flakybot.yaml

Following https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot#configuration to make the issues created by flaky bot as P2.

chore(flakybot): Changing default flaky issue priority to p2

---

cloud-sql/mysql/sqlalchemy/Dockerfile

The current base image 'python:3' takes the latest image available, which is 3.12 (recently released). All dependencies of the mySql sample are not yet compatible with 3.12. Thus, pinning the base version to 3.11 like all other samples in this repository.

Pin MySQL sample to Python 3.11

---

.github/auto-approve.yml

Adds auto-approve.yml for Renovate only.
ReadMe: https://github.com/googleapis/repo-automation-bots/tree/main/packages/auto-approve
SourceCode: https://github.com/googleapis/repo-automation-bots/blob/main/packages/auto-approve/src/process-checks/python/sample-dependency.ts

feat: Add Auto Approve bot config

---

recaptcha_enterprise/snippets/requirements-test.txt

The tests were failing with:
```
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/workspace/recaptcha_enterprise/snippets/.nox/py-3-8/lib/python3.8/site-packages/werkzeug/urls.py)
```

fix(recaptcha): Fixing Flask+Werkzeug versioning problem

---

dataflow/flex-templates/getting_started/README.md
dataflow/flex-templates/getting_started/getting_started.py
dataflow/flex-templates/getting_started/metadata.json
dataflow/flex-templates/getting_started/requirements.txt

Getting-started sample for the [Use Flex Templates](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates) docs
Doc bug: b/309158338

docs(samples): Add flex template "getting started" sample

---

.github/CODEOWNERS

There are now codelabs for learning to edit and submit new samples. Assign ownership of that file to restrict review requests.

fix: assign practice-folder CODEOWNER

---

.github/CODEOWNERS

Fixes CODEOWNERS for /practice-folder to avoid spamming other reviewers with training PRs

fix: practice-folder CODEOWNERS

---

appengine/standard_python3/bundled-services/mail/django/main.py
appengine/standard_python3/bundled-services/mail/django/requirements.txt

Removes deprecated usage of `url` in favor of `re_path`, updates Django versions.

fix: correct deprecated Django functionality, update Django deps

---

logging/import-logs/README.md
logging/import-logs/main.py
logging/import-logs/main_test.py

Patch logName of imported logs to use destination project.
Store original logName in user labels.
Refactor method comments.
Refactor handling partial errors of type WriteLogEntriesPartialErrors.

fix: import log to destination project

---

firestore/cloud-async-client/snippets.py
firestore/cloud-async-client/snippets_test.py

`update_document_increment()` in `firestore/cloud-async-client/snippets.py` does not work as expected. Add `await` to fix.

fix(firestore): Add await to the example

---

composer/workflows/airflow_moved_tables.py
composer/workflows/airflow_moved_tables_test.py
composer/workflows/requirements.txt

When upgrading Airflow to a newer version, sometimes certain rows from the metadata cannot be migrated.
Adds 2 DAGs, one to inspect the rows, the other to rename the table, so that the error message in the Airflow UI disappears.

Add DAGs to inspect moved tables after airflow upgrade

---

dataflow/snippets/batch_write_storage.py
dataflow/snippets/noxfile_config.py
dataflow/snippets/tests/test_batch_write_storage.py
dataflow/snippets/tests/test_write_pubsub.py
dataflow/snippets/write_pubsub.py

Adds a snippet that shows how to write messages to Pub/Sub from Dataflow.
Bug: b/310239684
Doc bug: b/318728052 (Parent doc bug for context: b/309130866)

docs(samples): Add Dataflow to Pub/Sub snippet

---

run/service-auth/receive_test.py

fix: run/service-auth - ensure token decoded before use

---

composer/workflows/airflow_db_cleanup.py

This fixes an issue where the python operator gets killed if the ssession table is large enough by using COUNT(*) instead of loading everything into memory

fix(airflow_db_cleanup): sessions cleanup

---

dataflow/snippets/tests/test_write_pubsub.py
dataflow/snippets/write_pubsub.py

Fixes two issues when running the `write_pubsub.py` snippet on the Dataflow runner: 
- The custom pipeline option named `pipeline` conflicts with the `DataflowRunner` pipeline options.
- The global namespace is not available inside the `Map` transform when running on the Dataflow worker. See [`NameError`](https://cloud.google.com/dataflow/docs/guides/common-errors#name-error) in the Dataflow troubleshooting guide.
(The current version of the snippet runs fine when using the DirectRunner; these issues are due to differences in the Dataflow
runtime environment.)

docs(samples): Fix Pub/Sub snippet for Dataflow runner

---

storage/cost-analysis/README.md
storage/cost-analysis/storage_soft_delete_relative_cost_analyzer.py

Identifies buckets with relative increase in cost on enabling the soft-delete. The relative increase in cost of using soft delete is calculated by combining the storage/v2/deleted_bytes metric with the existing storage/v2/total_byte_seconds metric.
Relative cost of each bucket = ('soft delete retention duration'
× 'deleted bytes' / 'total bytes seconds' )
x 'cost of storing in storage class'
x 'ratio of storage class'.
Fixes #11196 

feat(soft-delete-cost-analysis): Script to identify buckets with relative increase in cost on enabling the soft-delete.

---

generative_ai/function_calling.py
generative_ai/gemini_chat_example.py
generative_ai/gemini_count_token_example.py
generative_ai/gemini_guide_example.py
generative_ai/gemini_multi_image_example.py
generative_ai/gemini_pro_basic_example.py
generative_ai/gemini_pro_config_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_single_turn_video_example.py
generative_ai/requirements.txt
generative_ai/test_gemini_examples.py

Update Gemini VertexAI samples imports. No longer requires `preview`, to import models.
Fixes: [b/324397045](b/324397045)

feat: update gemini samples imports

---

firestore/cloud-client/snippets.py

Fixes https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10983
The sample is recursive, but it doesn't properly handle the case where batch_size is 0, which ends up in an infinite loop.

fix(firestore): failed recursive delete in snippet

---

discoveryengine/requirements.txt
discoveryengine/search_sample.py
discoveryengine/search_sample_test.py

Allows support for Blended Search https://cloud.google.com/generative-ai-app-builder/docs/create-data-store-es#multi-data-stores
b/329457260

fix(discoveryengine): Update Search Sample to use Engine/App ID

---

generative_ai/test_gemini_examples.py

fix: skip failing Gemini grounding test due to allowlist restrictions

---

generative_ai/embedding.py

Note: I am a Googler on a different team that noticed this sample was slightly confusing when I tried to use it so putting this PR up as a potential improvement. 
As a developer wanting to copy/paste this sample into my workload I would expect it to take in an input string and then get the embedding for it? This is what the notebook example for this already does... https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/generative_ai/text_embedding_new_api.ipynb

chore: update embedding sample to be more developer friendly

---

generative_ai/function_calling.py

Fixes #11323 to remove the role from the `FunctionResponse` turn since Gemini does not validate the `role` field nor use the `role` field.

Update `generative-ai/function-calling` code sample to remove role from FunctionResponse

---

compute/client_library/ingredients/disks/list.py
compute/client_library/snippets/disks/list.py

Fix list_disks() function docs. We are listing not deleting.

fix disk list.py

---

.kokoro/docker/Dockerfile

Python 3.12 removed distutils ([details](https://docs.python.org/3/whatsnew/3.12.html#distutils)).
As a result, several 3.12 sample tests are failing. Any time a dependency wheel is built (like `appengine/flexible_python37_and_earlier/scipy` [here](https://btx-internal.corp.google.com/invocations/09d254c0-1f60-4041-96fb-d0f9c9dcf6f0/targets/cloud-devrel%2Fpython-docs-samples%2Fpython3.12%2Fpresubmit/log)), we get an error.
The release note mentions distutils is still available through setuptools. This PR adds setuptools to the build image.

build: Add setuptools to Dockerfile

---

dataflow/flex-templates/pipeline_with_dependencies/Dockerfile

Fixes https://stackoverflow.com/questions/78218949/how-to-pre-build-worker-container-dataflow-insights-sdk-worker-container-imag 
- [x ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ x] **Lint** pass:   `nox -s lint` (see [Test …

Don't pass the --setup_file option when a package is already installed in the custom image.

---

generative_ai/embedding_model_tuning.py
generative_ai/embedding_model_tuning_test.py
generative_ai/function_calling.py
generative_ai/gemini_pdf_example.py
generative_ai/gemini_pro_config_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/test_gemini_examples.py

Add PDF Sample for https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/send-multimodal-prompts
- Change existing Gemini Samples to use `GenerationConfig` class instead of a generic dict.

feat: Add Gemini PDF Sample & Add Type for `GenerationConfig`

---

.github/CODEOWNERS
.github/blunderbuss.yml
storagecontrol/conftest.py
storagecontrol/noxfile_config.py
storagecontrol/quickstart.py
storagecontrol/quickstart_test.py
storagecontrol/requirements-test.txt
storagecontrol/requirements.txt

This adds a quickstart sample for the StorageControl API gapic library

feat: add storagecontrol quickstart sample

---

composer/workflows/bq_copy_across_locations.py

Correct the documentation of the function to correctly specify its return value, and update a locally scoped variable to not refer to its type but instead its semantic meaning.
Fixes #11427 

nitpick: Update documentation and naming in read_table_list function

---

contentwarehouse/snippets/create_folder_link_document_sample_test.py
contentwarehouse/snippets/create_get_delete_document_schema_test.py
contentwarehouse/snippets/create_get_update_delete_document_test.py
contentwarehouse/snippets/create_rule_set_sample_test.py
contentwarehouse/snippets/fetch_acl_sample_test.py
contentwarehouse/snippets/list_document_schema_test.py
contentwarehouse/snippets/noxfile_config.py
contentwarehouse/snippets/quickstart_sample_test.py
contentwarehouse/snippets/search_documents_sample_test.py
contentwarehouse/snippets/set_acl_sample_test.py
contentwarehouse/snippets/update_document_schema_sample_test.py

Remove tests due to Document AI Warehouse Deprecation
https://cloud.google.com/document-warehouse/docs/release-notes

tests: Skip Document AI Warehouse Tests due to deprecation/failures

---

cloud-sql/sql-server/sqlalchemy/requirements-test.txt
cloud-sql/sql-server/sqlalchemy/requirements.txt

These two deps are already part of `cloud-sql-python-connector` and not needed separately in requirements.
This is causing test failures in #11465 as it is overriding proper versions of `google-auth`

chore: update cloud-sql/sqlserver deps

---

generative_ai/function_calling.py
generative_ai/function_calling_chat.py
generative_ai/imagen/generate_image.py

Fixes #11366. (`generative_ai.function_calling_chat_test`)
Fixes #11367. (`generative_ai.function_calling_test`)
These code samples were referring to `gemini-1.0-pro`, which was leading to some flaky behavior (i.e., Function Calling was returning inaccurate function names) in these tests. This PR fixes that flakiness by pinning to `gemini-1.0-pro-001`.

fix: Pin Gemini Function Calling code samples to `gemini-1.0-pro-001`

---

secretmanager/snippets/create_secret.py
secretmanager/snippets/create_secret_with_user_managed_replication.py
secretmanager/snippets/snippets_test.py

[issue-9643 fix] added ttl to secrets tests and samples

---

dialogflow/participant_management.py
dialogflow/requirements.txt

Fixes #9505 
Samples haven't reflect, which exact import is needed to make it working. Refactoring to make it more precise

fix: moving imports inside functions

---

compute/client_library/requirements.txt
discoveryengine/requirements.txt
discoveryengine/standalone_apis_sample.py
discoveryengine/standalone_apis_sample_test.py
documentai/snippets/handle_response_sample_test.py
documentai/snippets/handle_response_sample_v1beta3.py
documentai/snippets/requirements.txt

- https://cloud.google.com/generative-ai-app-builder/docs/builder-apis

samples(documentai, discoveryengine): Add Samples for Vertex AI Search Standalone RAG APIs

---

generative_ai/embedding_model_tuning_test.py
generative_ai/gemini_count_token_example.py
generative_ai/test_gemini_examples.py

- Change to new format
- Add multimodal example
Replacement for #11632

fix(generative-ai): Update count tokens sample

---

iam/cloud-client/snippets/conftest.py

Making the deny-policy tests skip, when there is no permission to properly execute them. Deny policy is a organization-level policy and we definitely don't have and won't have permission to modify policies at org-level. 
This will silence problems with tests in this directory making life easier when working with other IAM stuff.

fix(iam.deny): Skipping test if we don't have permission to run it.

---

run/helloworld/main.py
run/pubsub/main.py

Manually searched docs and confirmed no references remain. Only removed comments, no code changes.
Removed these tags:
run_helloworld_service
run_pubsub_handler

chore(fixit): remove redundant region tags

---

generative_ai/gemini_reasoning_engine.py
generative_ai/gemini_reasoning_engine_test.py
generative_ai/requirements-test.txt
generative_ai/requirements.txt

For https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/reasoning-engine

samples(generative_ai): Create Reasoning engine samples

---

generative_ai/gemini_rapid_evaluation.py
generative_ai/gemini_rapid_evaluation_test.py
generative_ai/requirements.txt

- TODO: Replace with SDK examples once these metrics are supported.
- Replacement for https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11628
Add samples for rapid Eval API reference doc https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/evaluation#examples

samples(generative_ai): Add Rapid Evaluation Python Samples

---

generative_ai/gemini_tuning.py
generative_ai/gemini_tuning_test.py
generative_ai/inference/inference_api_test.py
generative_ai/inference/non_stream_multimodality_basic.py
generative_ai/inference/non_stream_text_basic.py
generative_ai/inference/stream_multimodality_basic.py
generative_ai/inference/stream_text_basic.py
generative_ai/multimodal_embedding_image.py
generative_ai/multimodal_embedding_image_test.py
generative_ai/multimodal_embedding_image_video_text.py
generative_ai/multimodal_embedding_image_video_text_test.py
generative_ai/multimodal_embedding_video.py
generative_ai/multimodal_embedding_video_test.py

- Sets location = "us-central1" while initializing vertex.
- Renames REGION to LOCATION.

Standardize the location parameter

---

generative_ai/embedding_model_tuning.py
generative_ai/requirements.txt

feat: Update embedding tuning sample to use new preview parameters.

---

composer/workflows/simple.py

The sample codes use the deprecated modules. For example,
```
from airflow.operators import bash_operator
from airflow.operators import python_operator
```
Those are [deprecated](https://airflow.apache.org/docs/apache-airflow/2.3.2/_api/airflow/operators/bash_operator/index.html).

Update example to update deprecated modules

---

Makefile

When running locally, if the noxfile already exists in the sample directory it will error out. This means that linting or testing will work only the first time, and if you try running them again you'll get an error.
The `-n` flag forces `cp` to not overwrite the file, but if it already exists it returns an error. Removing this flag and always copying the noxfile fixes this.

fix: copy noxfile even if it already exists

---

iam/cloud-client/snippets/test_project_policies.py
iam/cloud-client/snippets/test_service_account_key.py

fix: remove assertion for fixture ending

---

iam/cloud-client/snippets/test_roles.py
iam/cloud-client/snippets/test_service_account.py

fix: making tests more resistant to concurent running tests

---

firestore/cloud-client/snippets.py
firestore/cloud-client/snippets_test.py

[issue-1788] added firedbase tests

---

generative_ai/rag.py

Add user configurable embedding model and quota (LlamaIndex on Vertex AI for RAG)

---

endpoints/getting-started/deployment.yaml
endpoints/kubernetes/k8s-grpc-bookstore.yaml

Add endpoints product prefix to some regions that were missing it.

chore: Migrate region tags

---

appengine/flexible/datastore/app.yaml

Update the app.yaml to use newer runtimes for datastore.

Chore: Update datastore for GAE Flex to use new runtimes

---

compute/client_library/ingredients/instances/create_instance_from_template_with_overrides.py
compute/client_library/ingredients/instances/create_start_instance/create_from_public_image.py
compute/client_library/ingredients/instances/create_start_instance/create_with_additional_disk.py
compute/client_library/ingredients/instances/create_start_instance/create_with_local_ssd.py
compute/client_library/ingredients/instances/create_start_instance/create_with_snapshotted_data_disk.py
compute/client_library/ingredients/instances/create_with_subnet.py
compute/client_library/ingredients/instances/custom_machine_types/create_extra_mem_no_helper.py
compute/client_library/ingredients/instances/custom_machine_types/create_shared_with_helper.py
compute/client_library/ingredients/instances/custom_machine_types/create_with_helper.py
compute/client_library/ingredients/instances/custom_machine_types/create_without_helper.py
compute/client_library/ingredients/instances/ip_address/assign_static_external_ip_to_new_vm.py
compute/client_library/recipes/instances/create.py
compute/client_library/snippets/instances/create.py
compute/client_library/snippets/instances/create_start_instance/create_from_public_image.py
compute/client_library/snippets/instances/create_start_instance/create_with_additional_disk.py
compute/client_library/snippets/instances/create_start_instance/create_with_local_ssd.py
compute/client_library/snippets/instances/create_start_instance/create_with_snapshotted_data_disk.py
compute/client_library/snippets/instances/create_with_subnet.py
compute/client_library/snippets/instances/custom_machine_types/create_shared_with_helper.py
compute/client_library/snippets/instances/custom_machine_types/create_with_helper.py
compute/client_library/snippets/instances/custom_machine_types/create_without_helper.py
compute/client_library/snippets/instances/custom_machine_types/extra_mem_no_helper.py
compute/client_library/snippets/instances/from_instance_template/create_from_template_with_overrides.py
compute/client_library/snippets/instances/ip_address/assign_static_external_ip_to_new_vm.py
compute/client_library/snippets/tests/test_custom_types.py
compute/client_library/snippets/tests/test_instance_start_stop.py
compute/client_library/snippets/tests/test_ip_address.py

Fixes #11991
Fixes #11989
Fixes #11990 
Fixes #11988 
Fixes #11987 
Fixes #11986
Fixes #11985 
Fixes #11984
Fixes #11983
Fixes #11982
Fixes #11981
Fixes #11980
Fixes #11979
Fixes #11978
Fixes #11977
Fixes #11976
Fixes #11975
Fixes #11974
Debian 10 went poof, so it's time to move to newer version.

fix(compute): Updating Debian 10 to Debian 12 in samples

---

storagetransfer/conftest.py

Skip AWS test that hit bucket quota limit
Per team discussion, unblock periodic tests until aws bucket quota issue is resolved
Fixes #12009

fix(sts): skip aws test with bucket quota limit

---

generative_ai/anthropic_claude_3_streaming.py
generative_ai/anthropic_claude_3_tool_use.py
generative_ai/anthropic_claude_3_unary.py
generative_ai/chat.py
generative_ai/code_chat.py
generative_ai/code_completion_function.py
generative_ai/code_completion_function_test.py
generative_ai/code_generation_function.py
generative_ai/distillation.py
generative_ai/embedding.py
generative_ai/embedding_model_tuning.py
generative_ai/evaluate_model.py
generative_ai/grounding.py
generative_ai/ideation.py
generative_ai/ideation_test.py
generative_ai/list_tuned_models.py
generative_ai/multimodal_embedding_image.py
generative_ai/multimodal_embedding_image_video_text.py
generative_ai/multimodal_embedding_video.py
generative_ai/streaming_text.py
generative_ai/tune_code_generation_model.py
generative_ai/tuning.py

Using `generativeaionvertexai_` prefix for all code samples of Generative AI.
Fixes # [b/354932854](http://b/354932854)
No code changes. Using new prefix tag for genai code samples.
Going forward, we will be using `generativeaionvertexai` instead of `aiplatform`

docs(generativeai): Add new region tags for code samples.

---

generative_ai/count_token/count_token_example.py
generative_ai/count_token/count_token_example_test.py
generative_ai/requirements.txt

Fixes # [b356425456](http://b/356425456)

feat: Add local count token example

---

auth/api-client/api_key_test.py
auth/api-client/authenticate_with_api_key.py

Quota should be derived from the API key.
ETA:
based on documentation for the underlying API, the call authenticates with the API key and doesn't do anything associated with a passed in project ID. 
This will update https://cloud.google.com/docs/authentication/api-keys

chore: Remove quota project from API key auth sample.

---

kms/snippets/create_key_for_import.py

Replaces #12160 
As per #12160, @tdbhacks noted that for the other languages for this sample, https://cloud.google.com/kms/docs/importing-a-key#create_targets, this change ensures that all languages show the same functionality for the same sample.

fix(kms): align sample to other languages

---

appengine/flexible/django_cloudsql/mysite/settings.py
appengine/flexible/django_cloudsql/polls/urls.py
appengine/flexible/django_cloudsql/requirements.txt
appengine/flexible/hello_world_django/project_name/urls.py
appengine/flexible/hello_world_django/requirements.txt
appengine/flexible_python37_and_earlier/django_cloudsql/polls/urls.py
appengine/flexible_python37_and_earlier/django_cloudsql/requirements.txt
appengine/flexible_python37_and_earlier/hello_world_django/project_name/urls.py
appengine/flexible_python37_and_earlier/hello_world_django/requirements.txt
appengine/standard_python3/bundled-services/blobstore/django/requirements.txt
appengine/standard_python3/bundled-services/deferred/django/requirements.txt
appengine/standard_python3/bundled-services/mail/django/main.py
appengine/standard_python3/bundled-services/mail/django/requirements.txt
appengine/standard_python3/django/requirements.txt
kubernetes_engine/django_tutorial/requirements.txt
run/django/mysite/settings.py
run/django/requirements.txt

Replaces #12111, #12112, #12113, #12114, #12116, #12117
* Updates Django 5.x series to 5.1 for Python 3.10+ 
* Updates Django 4.x series to latest patch for Python 3.8+
* Updates Django 3.x series to latest patch for <Python 3.8
* Removes duplicate dependency declaration for Python 3.10 in some samples
* Applies `django-upgrade` targetting minimum supported version per sample (s/re_path/path, adds `STORAGES`)

chore: update Django samples to 5.1 (Python 3.10+)

---

securitycenter/snippets/snippets_mute_config.py
securitycenter/snippets/snippets_mute_config_test.py

docs: Create set_undefined_finding sample

---

.kokoro/tests/run_tests.sh
dataflow/conftest.py
dataflow/gemma-flex-template/Dockerfile
dataflow/gemma-flex-template/README.md
dataflow/gemma-flex-template/custom_model_gemma.py
dataflow/gemma-flex-template/e2e_test.py
dataflow/gemma-flex-template/metadata.json
dataflow/gemma-flex-template/noxfile_config.py
dataflow/gemma-flex-template/requirements-test.txt
dataflow/gemma-flex-template/requirements.txt

Adds a Gemma Flex Template example and an e2e test running on Dataflow. This code example is similar to #11284, but using a Pytorch model and deploying as a flex template. The e2e test will need model weights staged to GCS like the streaming Gemma example.

Add Gemma Flex Template example

---

.kokoro/python2.7/periodic.cfg
.kokoro/python3.10/periodic.cfg
.kokoro/python3.11/periodic.cfg
.kokoro/python3.12/periodic.cfg
.kokoro/python3.8/periodic.cfg
.kokoro/python3.9/periodic.cfg

Disable test log reporting to flaky-bot during testing. We recently removed the flaky-bot app, but the reporting appears to be causing many issues to be created as a side effect of normal test runs. (example: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/12434) 
Changing this config should disable that test reporting and stop the issue creation. If this works, it looks like the `REPORT_TO_BUILD_COP_BOT` env variable may no longer be used, and we should consider removing it entirely (from both config and the test runner scripts).

disable test log reporting to flaky-bot

---

firestore/cloud-client/requirements.txt
firestore/cloud-client/vector_search.py
firestore/cloud-client/vector_search_test.py

Add Firestore Python Vector Search query snippets.
NOTE: This needs an index setup on the test project that this runs the tests, but I'm not sure what project that is, it's unclear to me how the other tests have the FIRESTORE_PROJECT environment variable initialized in the CI environment.

Add Firestore vector search query snippets

---

datastore/cloud-client/index.yaml
datastore/cloud-client/query_filter_or.py
datastore/cloud-client/query_filter_or_test.py
datastore/cloud-client/query_multi_ineq.py
datastore/cloud-client/query_multi_ineq_test.py
firestore/cloud-client/query_filter_or.py
firestore/cloud-client/query_filter_or_test.py
firestore/cloud-client/snippets.py
firestore/cloud-client/snippets_test.py

touches the following region tags:
- firestore_query_filter_compound_multi_ineq
- firestore_query_indexing_considerations
- firestore_query_order_fields
- datastore_query_filter_compound_multi_ineq
- datastore_query_indexing_considerations
- datastore_query_order_fields
- firestore_query_filter_or
- firestore_query_filter_or_compound
- firestore_query_filter_not_eq
- firestore_query_filter_not_in
context: go/firestore_multiineq_sample_tracker

feat: add Firestore and datastore multiple inequality samples

---

firestore/cloud-client/requirements.txt
firestore/cloud-client/vector_search.py
firestore/cloud-client/vector_search_test.py

Add snippets for Firestore Vector Search distance parameters

Add snippets for Firestore Vector Search distance parameters

---

dataflow/gpu-examples/tensorflow-landsat-prime/Dockerfile
dataflow/gpu-examples/tensorflow-landsat-prime/main.py
dataflow/gpu-examples/tensorflow-landsat-prime/requirements.txt
dataflow/gpu-examples/tensorflow-landsat/Dockerfile
dataflow/gpu-examples/tensorflow-landsat/main.py
dataflow/gpu-examples/tensorflow-landsat/requirements.txt

Fixes b/361414289
Rasterio changed the way they read files. It seems like now they support [virtual filesystems](https://rasterio.readthedocs.io/en/latest/topics/vsi.html) and Cloud Storage seems to be supported out of the box.

fix: rasterio and update dependencies

---

generative_ai/batch_predict/batch_code_predict.py
generative_ai/batch_predict/batch_text_predict.py
generative_ai/batch_predict/test_batch_predict.py

I noticed that some samples were missing from our repository. This PR addresses this by adding 2 new samples (listed below) and introducing an extendable test structure.
|  File	|  Documentation Link	| Region_tag| 
|---	|---	|--- 
|  batch_code_predict.py	|  [Get batch code predictions](https://cloud.google.com/vertex-ai/generative-ai/docs/code/batch-prediction-genai-code)	|  `aiplatform_batch_code_predict` |
|  batch_text_predict.py	|  [Get batch text generations](https://cloud.google.com/vertex-ai/generative-ai/docs/text/batch-prediction-genai)	|   `aiplatform_batch_text_predict` |
For proper testing, please upload the 2 files to the test environment of the test project with the `.JSNOL` extension and provide the paths to the model prompts in the format …

feat: New text Generation Samples

---

appengine/flexible/websockets/requirements.txt
appengine/flexible_python37_and_earlier/websockets/requirements.txt
appengine/standard/endpoints-frameworks-v2/echo/requirements-test.txt
appengine/standard/endpoints-frameworks-v2/quickstart/requirements-test.txt
appengine/standard/firebase/firenotes/backend/requirements-test.txt
appengine/standard/firebase/firetactoe/firetactoe.py
appengine/standard/firebase/firetactoe/firetactoe_test.py
appengine/standard/firebase/firetactoe/requirements-test.txt
appengine/standard/firebase/firetactoe/rest_api.py
appengine/standard/iap/main_test.py
appengine/standard/iap/requirements-test.txt
appengine/standard/mailgun/requirements-test.txt
appengine/standard/migration/memorystore/appengine_config.py
appengine/standard/migration/memorystore/main.py
appengine/standard/migration/memorystore/main_test.py
appengine/standard/migration/memorystore/requirements-test.txt
appengine/standard/sendgrid/requirements-test.txt

Should help resolves errors while running renovate
Currently, #4745 reports "Unexpected range error"
Running `npx renovate --platform local` gives more details: 
```
WARN: Unexpected range error (repository=local)
"currentValue": "===2.0.1",
"err": {
"message": "PEP440 arbitrary equality (===) not supported",
"stack": "TypeError: PEP440 arbitrary equality (===) not supported [...]"
```
Checking all `requirements*.txt` files, I've removed all `===` references (markupsafe and mock)
While this is valid in [PEP440](https://peps.python.org/pep-0440/#arbitrary-equality), per the message it's not supported in Renovate. 
This may help unblock a number of pending dependency updates (e.g. https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12093#issuecomment-2327875438)

fix: remove arbitrary equality comparisons (not supported by renovate)

---

automl/snippets/requirements.txt
bigquery/remote-function/translate/requirements-test.txt
bigquery/remote-function/translate/requirements.txt
functions/ocr/app/requirements.txt
functions/v2/ocr/requirements.txt
translate/samples/snippets/hybrid_glossaries/requirements.txt
translate/samples/snippets/requirements.txt
translate/samples/snippets/snippets_test.py

Fixes #12560
Due to https://support.google.com/translate/answer/15139004, Afrikaans is no longer the alphabetically first language that's supported in Google Translate. 
This PR updates the validation to ensure this language is part of the results, rather than the first.

chore(deps): update google-cloud-translate to v3.16.0

---

texttospeech/snippets/audio_profile.py
texttospeech/snippets/audio_profile_test.py
texttospeech/snippets/long_audio_quickstart.py
texttospeech/snippets/long_audio_quickstart_test.py
texttospeech/snippets/ssml_addresses.py
texttospeech/snippets/ssml_addresses_test.py
texttospeech/snippets/synthesize_text.py
texttospeech/snippets/synthesize_text_test.py

Get rid of hidden variables in texttospeach samples

chore: refactored samples, to make them follow copy-paste-run approach

---

generative_ai/embedding.py
generative_ai/embedding_batch.py
generative_ai/embedding_batch_test.py
generative_ai/embedding_model_tuning.py
generative_ai/embedding_model_tuning_test.py
generative_ai/embedding_preview.py
generative_ai/embedding_test.py
generative_ai/embeddings/batch_example.py
generative_ai/embeddings/batch_example_test.py
generative_ai/embeddings/code_retrieval_example.py
generative_ai/embeddings/document_retrieval_example.py
generative_ai/embeddings/model_tuning_example.py
generative_ai/embeddings/model_tuning_test.py
generative_ai/embeddings/multimodal_example.py
generative_ai/embeddings/multimodal_image_example.py
generative_ai/embeddings/multimodal_test.py
generative_ai/embeddings/multimodal_video_example.py
generative_ai/embeddings/multimopdal_example.py
generative_ai/embeddings/retrievals_test.py
generative_ai/multimodal_embedding_image.py
generative_ai/multimodal_embedding_image_test.py
generative_ai/multimodal_embedding_image_video_text.py
generative_ai/multimodal_embedding_image_video_text_test.py
generative_ai/multimodal_embedding_video.py
generative_ai/multimodal_embedding_video_test.py

|  Region Tag	| Old file | New File  	| 
|---					|---			|---				|
|	generativeaionvertexai_embedding_batch |  embedding_batch.py | batch_example.py |
|	**generativeaionvertexai_embedding_model_tuning** |  embedding_model_tuning.py | model_tuning_example.py |
|	**generativeaionvertexai_embedding_code_retrieval** | embedding_preview.py  | code_retrieval_example.py |
|	**generativeaionvertexai_embedding** |  embeddings.py |  document_retrieval_example.py |
|	generativeaionvertexai_multimodal_embedding_image_video_text |  multimodal_embedding_image_video_text.py | multimodal_example.py |
|	generativeaionvertexai_multimodal_embedding_image | multimodal_embedding_image.py  | multimodal_image_example.py |
|	generativeaionvertexai_multimodal_embedding_video |  multimodal_embedding_video.py | …

refactor: (GenAI) Reorganized Embeddings Samples (Group A)

---

dataflow/snippets/Dockerfile
dataflow/snippets/read_kafka_multi_topic.py
dataflow/snippets/tests/test_read_kafka.py

Shows how to build a Dataflow pipeline that reads from multiple Kafka topics, filters based on the topic name, and performs different application logic per topic.
Snippet bug: b/362325397
Related doc bug: b/342015050

docs(samples): Add Dataflow snippet to read from multiple Kafka topics

---

generative_ai/gemini_guide_example.py
generative_ai/gemini_text_input_example.py
generative_ai/gemini_video_audio.py

Fixes: [b/362352967](https://b.corp.google.com/362352967)

docs(generativeai): update todo comments for quick start guide examples

---

datastore/cloud-client/snippets.py

Some of the datastore snippets are missing required imports. This change pulls the necessary imports into each sample in snippets.py

fix: (datastore) add imports to snippets

---

generative_ai/model_tuning/create_evaluation_task_example.py
generative_ai/model_tuning/create_evaluation_task_example_test.py
generative_ai/model_tuning/distillation_example.py
generative_ai/model_tuning/distillation_example_test.py
generative_ai/model_tuning/evaluate_model_example.py
generative_ai/model_tuning/evaluate_model_example_test.py
generative_ai/model_tuning/pretrained_codegen_example.py
generative_ai/model_tuning/pretrained_examples_test.py
generative_ai/model_tuning/pretrained_list_example.py
generative_ai/model_tuning/pretrained_textgen_example.py
generative_ai/model_tuning/supervised_advanced_example.py
generative_ai/model_tuning/supervised_cancel_example.py
generative_ai/model_tuning/supervised_example.py
generative_ai/model_tuning/supervised_get_example.py
generative_ai/model_tuning/supervised_list_example.py
generative_ai/model_tuning/supervised_tuning_examples_test.py
generative_ai/model_tuning/tune_code_generation_model.py
generative_ai/model_tuning/tuning.py

Created a new folder: `/generative_ai/model_tuning/`
| Region_tag                                            | New file                          |
|-------------------------------------------------------|-----------------------------------|
| generativeaionvertexai_evaluate_model                 | evaluate_model_example.py         |
| generativeaionvertexai_create_evaluation_task         | create_evaluation_task_example.py |
| generativeaionvertexai_cancel_tuning_job              | supervised_cancel_example.py      |
| generativeaionvertexai_list_tuning_jobs               | supervised_list_example.py        |
| generativeaionvertexai_tuning_basic                   | supervised_example.py             |
| generativeaionvertexai_tuning_advanced                | supervised_advanced_example.py …

refactor: (GenAI) Reorganized Model Tuning Samples (Group B)

---

generative_ai/model_garden/claude_3_streaming_example.py
generative_ai/model_garden/claude_3_tool_example.py
generative_ai/model_garden/claude_3_unary_example.py
generative_ai/model_garden/model_garden_test.py

| Region_tag                                | New file                                   |
|-------------------------------------------|--------------------------------------------|
| generativeaionvertexai_claude_3_streaming | model_garden/claude_3_streaming_example.py |
| generativeaionvertexai_claude_3_tool_use  | model_garden/claude_3_tool_example.py      |
| generativeaionvertexai_claude_3_unary     | model_garden/claude_3_unary_example.py     |
**File with all tests:** ->  `/model_garden/model_garden_test.py`
❗Files need to be deleted after approval:
- /generative_ai/anthropic_claude_3_streaming.py
- /generative_ai/anthropic_claude_3_streaming_test.py
- /generative_ai/anthropic_claude_3_tool_use.py
- /generative_ai/anthropic_claude_3_tool_use_test.py
- …

refactor: (GenAI) Reorganized Model Garden Samples (Group B)

---

.github/CODEOWNERS

Fixes b/368475655, parallels https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3870

chore(CODEOWNERS): Add cloud-samples-infra team to repo config ownership

---

.github/CODEOWNERS

Removes teams that are no long in active use. Any rows that would then be limited to inherited rules were removed, with the exception of the "pending clarification" section. Note this means I removed a collection of directories explicitly flagged as missing specific owners, with an expectation we'll track that another way across samples repos.
Fixes b/364335594 for python-docs-samples.
There is a pre-existing syntax error in the file: the @GoogleCloudPlatform/aml-ai is mentioned in CODEOWNERS but does not have repo access. This should be fixed via the admin UI.

chore(CODEOWNERS): Remove unused teams

---

generative_ai/batch_predict/gemini_batch_predict.py
generative_ai/batch_predict/test_batch_predict.py
generative_ai/prompts/prompt_optimizer.py
generative_ai/prompts/test_prompt_optimizer.py
generative_ai/prompts/test_resources/sample_configuration.json

Update samples and tests for Prompt Optimizer. The static resources have been moved to GCS buckets and the tests can now be made simpler.

fix(generativeai): update prompt optimizer sample and tests

---

generative_ai/batch_predict/gemini_batch_predict.py
generative_ai/controlled_generation/example_06.py
generative_ai/model_garden/claude_3_streaming_example.py
generative_ai/model_garden/model_garden_test.py
generative_ai/text_generation/gemini_describe_http_image_example.py
generative_ai/text_generation/gemini_describe_http_pdf_example.py
generative_ai/text_generation/test_text_generation_examples.py
generative_ai/video/gemini_describe_http_video_example.py
generative_ai/video/gemini_youtube_video_key_moments_example.py
generative_ai/video/gemini_youtube_video_summarization_example.py
generative_ai/video/test_video_examples.py

feat(generativeai): Add new sample for text generation(Youtube, Web support, Controlled Generations)
Fixes [b/369301403](http://b/369301403)
> This is a cleaner version of PR - https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12625

feat(generativeai): Add new sample for text generation

---

gemma2/gemma2_predict_gpu.py
gemma2/gemma2_predict_tpu.py

Fixes spelling.
Based on: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9527#discussion_r1777562836

fix(gemma2): Word fix in comments

---

generative_ai/test_gemini_examples.py
generative_ai/understand_audio/summarization_example.py
generative_ai/understand_audio/transcription_example.py
generative_ai/understand_audio/understand_audio_test.py

Created a new folder:  `/generative_ai/understand_audio`
| Region_tag                                        | New file                 |
|---------------------------------------------------|--------------------------|
| generativeaionvertexai_gemini_audio_summarization | summarization_example.py |
| generativeaionvertexai_gemini_audio_transcription | transcription_example.py |
**❗Files to be deleted after approval:**
- `/generative_ai/gemini_audio.py`
- Marked tests in `/generative_ai/test_gemini_examples.py` -> (`test_summarize_audio` and `test_transcript_audio` )

refactor: (GenAI) Reorganized Audio Samples (Group C)

---

generative_ai/rag/create_corpus_example.py
generative_ai/rag/delete_corpus_example.py
generative_ai/rag/delete_file_example.py
generative_ai/rag/generate_content_example.py
generative_ai/rag/get_corpus_example.py
generative_ai/rag/get_file_example.py
generative_ai/rag/import_files_async_example.py
generative_ai/rag/import_files_example.py
generative_ai/rag/list_corpora_example.py
generative_ai/rag/list_files_example.py
generative_ai/rag/quickstart_example.py
generative_ai/rag/retrieval_query_example.py
generative_ai/rag/test_file.txt
generative_ai/rag/test_rag.py
generative_ai/rag/upload_file_example.py

Created new `/generative_ai/rag` folder.
I left the `skip` mark on tests but I fixed them all.
| Region_tag                                    | New file                      |
|-----------------------------------------------|-------------------------------|
| generativeaionvertexai_rag_retrieval_query    | retrieval_query_example.py    |
| generativeaionvertexai_rag_generate_content   | generate_content_example.py   |
| generativeaionvertexai_rag_quickstart         | quickstart_example.py         |
| generativeaionvertexai_rag_import_files       | import_files_example.py       |
| generativeaionvertexai_rag_import_files_async | import_files_async_example.py |
| generativeaionvertexai_rag_get_file           | get_file_example.py           |
| generativeaionvertexai_rag_list_files …

refactor: (GenAI) Reorganized Rag Samples (Group С)

---

composer/workflows/kubernetes_pod_operator_c2.py

Fixes the template example and comments:
- Removed the templated `config_file` parameter (should point at the usual config with GKE credentials)
- Updated the Airflow templates reference link
- Added the comment about templated params
- Capitalize Kubernetes, Docker
- Mention namespace param usage for Composer 3
- Namespace param is not required

Remove templated config_file path, fix parameter comments

---

iam/cloud-client/snippets/get_policy.py
iam/cloud-client/snippets/test_service_account.py

providing an example to share with folks who worked on these samples, but there is a number of feedback items on samples of "this sample doesn't do anything". 
I think an underlying issue is that while the snippet does what it's documented to do, there is no output so the sample doesn't appear to do anything. i.e., output looks like 
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1727410693.815942    2970 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache 
For this sample 
With this update it will print out the policy to screen so folks can see that it's doing …

fix(iam): add a print for visibility

---

texttospeech/snippets/requirements.txt
texttospeech/snippets/streaming_tts_quickstart.py
texttospeech/snippets/streaming_tts_quickstart_test.py

Add quickstart documentation for new streaming synthesize API

feat(tts): add streaming synthesis sample

---

discoveryengine/import_documents_sample.py

fix: Update `discoveryengine.GcsSource` `data_schema` with more options.

---

.github/CODEOWNERS

Removed `/recaptcha_enterprise/demosite/**/*` assignment and moved the `reCAPTCHA Customer Obsession` team as owners of the parent folder `/recaptcha_enterprise`

chore(codeowners): Update CODEOWNERS for recaptcha/ folder

---

appengine/standard/iap/main_test.py
appengine/standard/iap/requirements-test.txt
appengine/standard/iap/requirements.txt

fix(gae): resolve linting issues in main_test.py

---

generative_ai/test_gemini_examples.py
generative_ai/understand_video/audio_video_example.py
generative_ai/understand_video/single_turn_video_example.py
generative_ai/understand_video/understand_video_test.py

Created new folder:  `/generative_ai/understand_video`
| Region_tag                                      | New file                     |
|-------------------------------------------------|------------------------------|
| generativeaionvertexai_gemini_single_turn_video | single_turn_video_example.py |
| generativeaionvertexai_gemini_video_with_audio  | audio_video_example.py       |
**❗Files to be deleted after approval:**
- `generative_ai/gemini_single_turn_video_example.py`
- `generative_ai/gemini_video_audio.py`
- Marked tests in `generative_ai/test_gemini_examples.py`:
- `generative_ai.test_gemini_examples.test_gemini_single_turn_video_example`
- `generative_ai.test_gemini_examples.test_analyze_video_with_audio`

refactor: (GenAI) Reorganized Video Samples (Group C)

---

.github/auto-label.yaml
tpu/list_tpu.py
tpu/start_tpu.py
tpu/stop_tpu.py
tpu/test_tpu.py

Created new Samples for TPU. **Start**, **Stop**, **List** operations.
Doc page -> [here](https://cloud.google.com/tpu/docs/managing-tpus-tpu-vm#gcloud)
| Region tag    | Sample                    |
|---------------|---------------------------|
|  tpu_vm_list |  `tpu/list_tpu.py` |
|  tpu_vm_start | `tpu/start_tpu.py`  |
|  tpu_vm_stop | `tpu/stop_tpu.py`  |
Updated tests in `tpu/test_tpu.py`

feat: New Samples for TPU: Start, Stop, List

---

securitycenter/snippets_v2/snippets_findings_v2.py

This PR aims to fix the incorrect import used in code samples, issue raised in https://github.com/GoogleCloudPlatform/python-docs-samples/issues/12713

fix incorrect import used in v2 code samples

---

.kokoro/tests/run_single_test.sh
.kokoro/tests/run_tests.sh

Fixes the error `ERROR: (gcloud.secrets.versions.access) PERMISSION_DENIED: Permission 'secretmanager.versions.access' denied...` which appears in presubmits

fix: activate service account needed for tests

---

generative_ai/evaluation/get_rouge_score.py

Fixes the sample for Vertex AI "Get Rouge Score" [section](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/evaluation#get_rouge_score).
The "prompt" column in the sample input dataset is misleading, as the SDK [will not use](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/evaluation/_evaluation.py#L424) this column if the `model` argument is not provided. Without `model`, providing only "response" and "reference" columns is [sufficient](https://github.com/googleapis/python-aiplatform/blob/main/vertexai/evaluation/_evaluation.py#L127).
As a follow up to this fix, I'm considering to update this sample to mention both options of computing these metrics, similarly how we did [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/gen …

chore(generative_ai): clean up & re-format code samples

---

managedkafka/snippets/clusters/create_cluster.py
managedkafka/snippets/clusters/delete_cluster.py
managedkafka/snippets/clusters/get_cluster.py
managedkafka/snippets/clusters/list_clusters.py
managedkafka/snippets/clusters/update_cluster.py
managedkafka/snippets/consumergroups/delete_consumer_group.py
managedkafka/snippets/consumergroups/get_consumer_group.py
managedkafka/snippets/consumergroups/list_consumer_groups.py
managedkafka/snippets/consumergroups/update_consumer_group.py
managedkafka/snippets/requirements.txt
managedkafka/snippets/topics/create_topic.py
managedkafka/snippets/topics/delete_topic.py
managedkafka/snippets/topics/get_topic.py
managedkafka/snippets/topics/list_topics.py
managedkafka/snippets/topics/update_topic.py

- [N/a] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [N/a] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [N/a] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [N/a] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample

feat: make samples self runnable by moving devrel tags

---

healthcare/api-client/v1/fhir/fhir_stores.py
healthcare/api-client/v1/fhir/fhir_stores_test.py

Fixes b/310269530
/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

fix: update deprecated notificationConfig in healthcare api

---

generative_ai/prompts/prompt_template.py
generative_ai/prompts/test_prompt_template.py

feat(genai): add prompt template example

---

managedkafka/snippets/clusters/create_cluster.py
managedkafka/snippets/clusters/delete_cluster.py
managedkafka/snippets/clusters/get_cluster.py
managedkafka/snippets/clusters/list_clusters.py
managedkafka/snippets/clusters/update_cluster.py
managedkafka/snippets/consumergroups/delete_consumer_group.py
managedkafka/snippets/consumergroups/get_consumer_group.py
managedkafka/snippets/consumergroups/list_consumer_groups.py
managedkafka/snippets/consumergroups/update_consumer_group.py
managedkafka/snippets/topics/create_topic.py
managedkafka/snippets/topics/delete_topic.py
managedkafka/snippets/topics/get_topic.py
managedkafka/snippets/topics/list_topics.py
managedkafka/snippets/topics/update_topic.py

- [n/a] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [n/a] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [n/a] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [n/a] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample

fix: log error message when exception is caught

---

.kokoro/docker/Dockerfile
.kokoro/python3.13/common.cfg
.kokoro/python3.13/continuous.cfg
.kokoro/python3.13/periodic.cfg
.kokoro/python3.13/presubmit.cfg

Towards https://github.com/GoogleCloudPlatform/python-docs-samples/issues/12728

feat: Add Python 3.13 to testing image

---

securitycenter/snippets_v2/snippets_create_client_v2.py
securitycenter/snippets_v2/snippets_create_client_v2_test.py

I changed the return type for `create_client_with_endpoint()` shortly before I merged https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12671, but I forgot to update the docstring.
Also formats the sample and its test with `black`.

fix(securitycenter): update docstring for create_client_with_endpoint()

---

tpu/test_tpu.py

**Switch tests to Mock-based approach for TPU sample operations**

refactor (TPU): Refactored tests to use Mocking for TPU sample operations

---

dataplex/quickstart/noxfile_config.py
dataplex/quickstart/quickstart.py
dataplex/quickstart/quickstart_test.py

feat(dataplex): add quickstart for dataplex

---

tpu/create_tpu_spot.py

feat: TPU Create with spot

---

firestore/cloud-client/vector_search.py
firestore/cloud-client/vector_search_test.py

Use more realistic text embeddings in Firestore vector search examples. eg: 
```query_vector=Vector([3.0, 1.0, 2.0])``` -> 
```query_vector=Vector([0.3416704, 0.18332680, 0.24160706])```
Fixes b/342654827

fix: more realistic text embeddings in Firestore vector search examples

---

privateca/snippets/monitor_certificate_authority.py
privateca/snippets/test_certificate_authorities.py

Resolves issues raised in #12896
Updates privateca_monitor_ca_expiry sample to delete created sample (outside the region tags)

test(privateca): cleanup policies created during testing

---

endpoints/getting-started/openapi.yaml

chore(endpoints): migrate regions step 1 - in openapi-appengine.yaml

---

kubernetes_engine/django_tutorial/polls.yaml

Fixes [b/347826199](http://b/347826199)
Associated all region_tags with an official product (gke) and suffix _python

chore(gke): migrate region step 1 - update regions adding gke_ prefix and _python suffix

---

jobs/v3/api_client/email_alert_search_sample.py
jobs/v3/api_client/featured_job_search_sample.py
jobs/v3/api_client/general_search_sample.py

Fixes region tag issues in the following files:
email_alert_search_sample.py
featured_job_search_sample.py
general_search_sample.py
b/347350460
b/347350477
b/347349708

chore(job): fix regions in files starting with 'e' to 'g' from folder 'jobs/v3/api_client/'

---

kubernetes_engine/django_tutorial/polls.yaml

Fixes [b/347826199](http://b/347826199)
Associated all region tags with an official product gke and suffix yaml_python.
The yaml word is added in order to respect the pattern mentioned in the [rename region tag](https://g3doc.corp.google.com/company/teams/cloud-devrel/egg/contributing/rename-region-tag.md?cl=head#craft-a-unique-name-for-the-region-tag)

chore(gke): migrate region step 1 - update regions adding gke_ prefix and _yaml_python suffix

---

endpoints/kubernetes/k8s-grpc-bookstore.yaml

Fixes Internal: b/388331748
Follow-up of #13039

chore(endpoints): migrate region tags step 1 & 3 - rename regions in k8s-grpc-bookstore.yaml

---

.kokoro/docker/cloudbuild.yaml

Towards b/388782093
Towards https://github.com/GoogleCloudPlatform/python-docs-samples/issues/12728

chore: Update cloud build triggers to use cloud logging only 

---

jobs/v3/api_client/base_job_sample.py

b/347349725
b/347825738
b/347825769
b/347350189

chore(job): migration step 3 - delete region tags in jobs/v3/api_client/base_job_sample.py

---

dataflow/flex-templates/getting_started/requirements.txt

This sample pinned the Beam SDK version number. However, the latest template base image always uses the latest Beam, so it's not needed and can cause errors;
More information: b/374216225

docs(samples): Remove Beam version from requirements.txt file

---

appengine/standard/mail/app.yaml

Fixes Internal: b/388587061
Documentation won't be updated as it refers to frozen samples: https://cloud.google.com/appengine/docs/standard/services/mail/receiving-mail-with-mail-api

chore(gae): migrate region tags step 1 & 3 - mail/app.yaml

---

endpoints/getting-started/k8s/esp_echo_http.yaml

b/347825510
b/384989786
b/347825503

chore(endpoints): rename region tags at endpoints/getting-started/k8s/esp_echo_http.yaml

---

endpoints/getting-started/openapi.yaml

b/347825628
b/347351150
Follow-up of #13016

chore(endpoints): region migration step 3 - remove regions in open-api.yaml

---

appengine/standard/multitenancy/datastore.py
appengine/standard/multitenancy/memcache.py
appengine/standard/multitenancy/taskqueue.py

chore(gae): rename regions in standard/multitenancy

---

secretmanager/snippets/noxfile_config.py
secretmanager/snippets/requirements.txt

Replaces #12930
Updates google-crc32c dependency, and updates minimum Python version tested from 3.8 (support dropped in google-crc32c 1.6.0) to Python 3.9

chore(deps): update dependency google-crc32c, update min python version

---

kubernetes_engine/django_tutorial/polls.yaml

Fixes [b/347826199](http://b/347826199)
Delete old region tag

fix(gke): delete old region "gke_kubernetes_deployment_python"

---

appengine/standard/storage/appengine-client/main.py
appengine/standard/storage/appengine-client/requirements-test.txt

b/347350771
b/347350870
b/347349966
b/347350558
b/347350538
b/347350224
b/347350515

chore(gae): rename regions in standard/storage/appengine-client/main.py

---

workflows/cloud-client/main.py
workflows/cloud-client/main_test.py

- Add `__main__` to call execute_workflow() when running `python main.py`
- Remove redundant default arguments LOCATION and WORKFLOW_ID (as we have them in main.py and main_test.py as constants)
- Apply style recommendations to pass linter check.
Fixes Internal: b/390011565 (Step 1, making the sample run as in README.md)

fix(workflows): Fix Quickstart for Cloud Client

---

appengine/standard/mailjet/requirements-test.txt
appengine/standard/mailjet/templates/index.html
appengine/standard/pubsub/requirements-test.txt
appengine/standard/pubsub/templates/index.html
appengine/standard_python3/pubsub/templates/index.html

b/347350411
b/347349898
b/347350194

chore(gae): remove region tag 'form' from HTML templates

---

jobs/v3/api_client/location_search_sample.py

b/384774431
b/347825997
b/384780822
b/347825791
b/347825792
b/347350338
Regions renaming in documentation was made in cl/648538021

chore(job): rename and delete tags at jobs/v3/api_client/location_search_sample.py

---

dataproc/README.md

these samples were moved to the API directory and then moved back. the readme is incorrect and points to an archived repo

fix: remove dataproc/README.md

---

video/cloud-client/README.rst

these samples moved to a different repo and then migrated back under the top level directory of videointelligence. The other directories should probably be examined and merged over to videointelligence as well (and potentially de-duplicated)

fix: remove invalid video/cloud-client directory

---

appengine/standard/migration/ndb/overview/README.md
appengine/standard/migration/ndb/overview/main.py
appengine/standard/migration/ndb/overview/requirements-test.txt
appengine/standard/migration/ndb/overview/templates/index.html

chore(gae): delete regions from migration/ndb/overview/main.py

---

appengine/standard/migration/incoming/main.py
appengine/standard/migration/storage/main.py
appengine/standard/migration/storage/main_test.py
appengine/standard/migration/taskqueue/pull-counter/appengine_config.py
appengine/standard/migration/taskqueue/pull-counter/main.py
appengine/standard/migration/taskqueue/pull-counter/main_test.py
appengine/standard/migration/urlfetch/async/main.py
appengine/standard/migration/urlfetch/async/main_test.py
appengine/standard/migration/urlfetch/requests/main_test.py

Identified in lint errors in #13065
Runs `isort --profile google` on samples that failed `lint` in the above PR

fix: isort --profile google

---

composer/workflows/kubernetes_pod_operator_c2.py

The `airflow.providers.cncf.kubernetes.operators.kubernetes_pod` module was deprecated and now was removed.
Update the example to use its up-to-date alternative, `airflow.providers.cncf.kubernetes.operators.pod`.

Fix KPO sample imports

---

cloud-sql/mysql/sqlalchemy/Dockerfile
cloud-sql/mysql/sqlalchemy/requirements.txt
cloud-sql/postgres/sqlalchemy/Dockerfile
cloud-sql/postgres/sqlalchemy/requirements.txt
cloud-sql/sql-server/sqlalchemy/Dockerfile
cloud-sql/sql-server/sqlalchemy/requirements.txt

SQLAlchemy v2.0.24 fails with Python 3.13 with error:
```
AssertionError: Class <class 'sqlalchemy.sql.elements.SQLCoreOperations'> directly inherits TypingOnly but has additional attributes {'__static_attributes__'}.
```
[see bug #11334](https://github.com/sqlalchemy/sqlalchemy/issues/11334)
Bumping version of SQLAlchemy and fixing Python to version 3.13 to avoid such problems in the future.

fix: sqlalchemy dependencies

---

appengine/standard/migration/urlfetch/async/README.md
appengine/standard/migration/urlfetch/async/main.py
appengine/standard/migration/urlfetch/async/requirements-test.txt
appengine/standard/migration/urlfetch/requests/README.md
appengine/standard/migration/urlfetch/requests/main.py
appengine/standard/migration/urlfetch/requests/requirements-test.txt

chore(gae): delete region tags from standard/migration/urlfetch and remove Python 2 refs

---

compute/api/startup-script.sh
compute/oslogin/service_account_ssh.py

b/347350498
b/347350381
b/347350813
b/347350512
b/347350262
b/347825229

chore(compute): delete region tags from 'api' and 'oslogin' folders

---

run/pubsub/Dockerfile
run/system-package/Dockerfile

b/347349975
b/347349649
Follow-up of #4951

chore(cloudrun): migrate region tags for dockerfiles and yaml from run folder - part 2

---

jobs/v3/api_client/auto_complete_sample.py

chore(job): migrate regions step 3 - remove regions in auto_complete_sample.py

---

genai/text_generation/noxfile_config.py
genai/text_generation/requirements-test.txt
genai/text_generation/requirements.txt
genai/text_generation/test_text_generation.py
genai/text_generation/textgen_chat_with_txt.py
genai/text_generation/textgen_chat_with_txt_stream.py
genai/text_generation/textgen_config_with_txt.py
genai/text_generation/textgen_sys_instr_with_txt.py
genai/text_generation/textgen_with_txt.py
genai/text_generation/textgen_with_txt_img.py
genai/text_generation/textgen_with_txt_stream.py

feat(genai): add python samples for text generation

---

kubernetes_engine/django_tutorial/Dockerfile
kubernetes_engine/django_tutorial/mysite/settings.py

chore(gke): delete old region tags from django_tutorial

---

endpoints/getting-started/openapi-appengine.yaml

chore(endpoints): migrate region tag step 1 - add new tag to open-appengine.yaml

---

iam/cloud-client/snippets/iam_modify_policy_add_role.py
iam/cloud-client/snippets/modify_policy_add_member.py
iam/cloud-client/snippets/modify_policy_remove_member.py
iam/cloud-client/snippets/quickstart.py
iam/cloud-client/snippets/quickstart_test.py
iam/cloud-client/snippets/test_project_policies.py
iam/cloud-client/snippets/test_service_account.py
iam/cloud-client/snippets/test_service_account_key.py

Follow-up of #13010 and #13097

docs(iam): update comments and terminology in IAM samples

---

kubernetes_engine/django_tutorial/polls.yaml

- Delete unused region tags 
- Start migrating region tag "service" 
Fixes
[b/347350469](https://b.corp.google.com/issues/347350469)
[b/347350500](https://b.corp.google.com/issues/347350500)
[b/347350953](https://b.corp.google.com/issues/347350953)
[b/393167940](https://b.corp.google.com/issues/393167940)

fix(gke): delete unused region tags and start migrating "service" region tag

---

kubernetes_engine/django_tutorial/polls.yaml

Delete old region tag "gke_kubernetes_service_python" from kubernetes_engine/django_tutorial/polls.yaml
Fixes
b/393167940

chore(gke): delete old region tag "gke_kubernetes_service_python"

---

run/pubsub/Dockerfile
run/system-package/Dockerfile

chore(cloudrun): migrate region tags for dockerfiles and yaml from run folder - part 2 - step 3

---

endpoints/getting-started/openapi-appengine.yaml

chore(endpoints): migrate region tag step 3 - delete old region tag in openapi-appengine.yaml

---

cloud-sql/mysql/sqlalchemy/connect_connector.py
cloud-sql/mysql/sqlalchemy/connect_connector_auto_iam_authn.py
cloud-sql/postgres/sqlalchemy/connect_connector.py
cloud-sql/postgres/sqlalchemy/connect_connector_auto_iam_authn.py
cloud-sql/sql-server/sqlalchemy/connect_connector.py

Enabled lazy refresh for the Python Cloud SQL connector (Postgres, MySQL, and SQL Server).

feat(cloud-sql): enable lazy refresh for postgres, mysql and sql server connectors

---

generative_ai/video/gemini_youtube_video_summarization_example.py

Fixes test failures for generative_ai/video (e.g. https://github.com/GoogleCloudPlatform/python-docs-samples/pull/13152)
Updates the sample video being used for summarization. The original video was marked private, this is another video of a similar type from the same channel (Made with Google).

fix: update suggested video for summarization

---

genai/text_generation/textgen_transcript_with_gcs_audio.py
genai/text_generation/textgen_with_gcs_audio.py

Required according to documentation: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/audio-understanding#audio_transcription
Audio timestamps are inaccurate without this parameter. I also removed references to timestamps from the audio summary sample to simplify it.

docs(genai): Add `audio_timestamp` parameter for Audio Understanding

---

genai/text_generation/textgen_with_local_video.py
genai/text_generation/textgen_with_mute_video.py
genai/text_generation/textgen_with_video.py
genai/text_generation/textgen_with_youtube_video.py

Fixes b/398821909
Best Practices: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/video-understanding#best-practices

docs(genai): Update Video Samples to follow recommended practices

---

bigquery/cloud-client/grant_access_to_dataset.py
bigquery/cloud-client/grant_access_to_table_or_view.py
bigquery/cloud-client/revoke_access_to_table_or_view.py
bigquery/cloud-client/revoke_access_to_table_or_view_test.py
bigquery/cloud-client/revoke_dataset_access.py
bigquery/cloud-client/view_dataset_access_policy.py
bigquery/cloud-client/view_table_or_view_access_policy.py
bigquery/cloud-client/view_table_or_view_access_policy_test.py

Part of b/394478489
Fixes typos, Python code style, and variable names to make it consistent across documentation and this tutorial [Control access to resources with IAM](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#python).

fix(bigquery): improve cloud-client samples

---

datastore/cloud-ndb/flask_app.py
datastore/cloud-ndb/quickstart.py
datastore/cloud-ndb/requirements.txt

b/347350603
b/347825351
b/347350340

chore(datastore): delete and migrate invalid region tags in the whole folder - step 1

---

appengine/standard/iap/js/poll.js

chore(gae): delete old region tags in iap/js/poll.js

---

tpu/create_tpu.py
tpu/create_tpu_spot.py
tpu/create_tpu_with_script.py
tpu/delete_tpu.py
tpu/get_tpu.py
tpu/list_tpu.py
tpu/queued_resources_create.py
tpu/queued_resources_create_network.py
tpu/queued_resources_create_spot.py
tpu/queued_resources_create_startup_script.py
tpu/queued_resources_create_time_bound.py
tpu/queued_resources_delete.py
tpu/queued_resources_delete_force.py
tpu/queued_resources_get.py
tpu/queued_resources_list.py
tpu/start_tpu.py
tpu/stop_tpu.py

Fixes b/400926465
Updating the samples to use TPU v5e, as requested by the TPU team.

feat(tpu): Updating TPU samples to feature TPUv5e

---

securitycenter/snippets/requirements-test.txt
securitycenter/snippets/requirements.txt
securitycenter/snippets/snippets_findings.py
securitycenter/snippets/snippets_findings_test.py
securitycenter/snippets/snippets_notification_receiver.py
securitycenter/snippets/snippets_notification_test.py
securitycenter/snippets/snippets_orgs_test.py

Fixes Internal: b/402176817
Fixes Issue: #13168
- securitycenter_group_findings_with_changes
- securitycenter_group_findings_at_time
- Update `requirements` to latest versions
- Fix test for `securitycenter_list_findings_at_time` sample
- Add backoff to `test_update_asset_discovery_org_settings`
- Change imports from `securitycenter` to `securitycenter_v1` to make explicit which version is being used
- Add an exception to `securitycenter_receive_notifications` as in the Java sample, reacting to a ParsingError
- Use the same importing style for all datetime objects across samples in `snippet_findings.py`
- Remove deprecation warning for `utcnow()`
- Use a timezone compatible with Python 3.9 (as datetime.UTC was added in Python 3.11)

fix(securitycenter): delete deprecated samples and fix failing samples

---

bigquery/cloud-client/conftest.py
bigquery/cloud-client/grant_access_to_dataset.py
bigquery/cloud-client/grant_access_to_table_or_view.py
bigquery/cloud-client/revoke_access_to_table_or_view.py
bigquery/cloud-client/revoke_dataset_access.py
bigquery/cloud-client/view_dataset_access_policy.py
bigquery/cloud-client/view_table_or_view_access_policy.py

Fixes b/403272595
- Fix comments (for example 'grant' instead of 'revoke', and found typos)
- Remove unnecessary comments (for example in imports at the start of the sample)
- Unify comments style

fix(bigquery): fix typos and comments in cloud-client samples

---

datastore/cloud-ndb/flask_app.py

chore(datastore): delete invalid region tag 'ndb_flask' - Region tag migration step 3

---

language/AUTHORING_GUIDE.md
language/CONTRIBUTING.md
language/README.md

- Delete Markdown files pointing to an archived repo which returned a "Not found 404".
- Delete files not required in this repo, as they already are in the root directory:
language/AUTHORING_GUIDE.md
language/CONTRIBUTING.md

chore(language): remove markdown files from migration

---

generative_ai/template_folder/noxfile_config.py

Resolves CI issues with #12851, #12861, #12865, #12947, #12952, #12959, #12975, #13152
The `generative_ai/` template folder contains valid tests, and is currently failing the above PRs due to requiring `pandas`, which as of pandas 2.2.3 does not support Python 3.13. 
All other samples within the folder don't test for Python 3.13, so update the template to match. 
cc @msampathkumar

fix(template): update template to not test 3.13

---

generative_ai/embeddings/requirements.txt

Resolves CI issues with #12851, #12861, #12865, #12947, #12952, #12959, #12975, #13152
Fixes #12995
Based on local testing, updating the pandas (#13152) and google-cloud-aiplatform (#12865) version to latest resolves the NoneType issue.

chore(deps): bump deps for generative_ai/embeddings

---

functions/v2/http_logging/main_test.py

Resolves testing errors on #12895
Updates the mockdata in this test to match the expected data format: 
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#FIELDS.span_id
> The span ID is expected to be a 16-character, hexadecimal encoding of an 8-byte array and should not be zero.
The original mock value was being formatted, and thus failing the assert.

fix: make mock span expected format

---

model_garden/anthropic/anthropic_batchpredict_with_bq.py

- [ x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#tes …

update to comment about model region availability

---

secretmanager/snippets/requirements.txt
secretmanager/snippets/snippets_test.py

test(secretmanager): add test_create_secret_without_ttl

---

texttospeech/snippets/streaming_tts_quickstart.py
texttospeech/snippets/synthesize_text.py

https://cloud.google.com/text-to-speech/docs/chirp3-hd

docs(texttospeech): Update TTS Samples to use Chirp 3 Model

---

documentai/snippets/quickstart_sample.py
documentai/snippets/quickstart_sample_test.py

b/393632125
- Move the sample inside the function so it's easier to read and run
- Rewrite comments
- Replace call to 'documentai' with 'documentai_v1', to make it easier to identify which version is being used
- Add type hints
- Replace checking stderr/out to assert returned objects

fix(documentai): refactor 'documentai_quickstart' sample for latest style guide

---

parametermanager/snippets/create_param_with_kms_key.py
parametermanager/snippets/regional_samples/create_regional_param_with_kms_key.py
parametermanager/snippets/regional_samples/remove_regional_param_kms_key.py
parametermanager/snippets/regional_samples/snippets_test.py
parametermanager/snippets/regional_samples/update_regional_param_kms_key.py
parametermanager/snippets/remove_param_kms_key.py
parametermanager/snippets/requirements-test.txt
parametermanager/snippets/requirements.txt
parametermanager/snippets/snippets_test.py
parametermanager/snippets/update_param_kms_key.py

Added samples for Global and Regional Parameter Manager API with CMEK key
- create_param_with_kms_key
- update_param_kms_key
- remove_param_kms_key
- create_regional_param_with_kms_key
- update_regional_param_kms_key
- remove_regional_param_kms_key
Added test cases for both global and regional parameter.
**Note: The KMS service needs to be enabled in the testing project to pass the integration tests.**

feat(parametermanager): added samples for handling cmek in parameter for global and regional

---

documentai/snippets/quickstart_sample.py
documentai/snippets/quickstart_sample_test.py

Fixes Internal: b/393632125
- Refactor sample to make it consistent with other languages in https://cloud.google.com/document-ai/docs/process-documents-client-libraries#using_the_client_library
- Move the creation and deletion of the Processor from the sample to a Test fixture as the Quickstart shows how to create the processor in the Web console, not by Python code
- Cleanup test workflow based on Cavazos' advice

fix(documentai): refactor 'quickstart' sample

---

dataflow/gemma-flex-template/Dockerfile

Without this change (failing build):
With this change (successful build):

Pytorch upgrade in `gemma-flex-template` docker image

---

translate/samples/AUTHORING_GUIDE.md
translate/samples/CONTRIBUTING.md
translate/samples/snippets/noxfile_config.py
translate/samples/snippets/requirements.txt
translate/samples/snippets/translate_v3_translate_text.py
translate/samples/snippets/translate_v3_translate_text_test.py

b/405384416
- Add region tag 'translate_v3_import_client_library'
- Remove remaining Markdown files from previous repos [1](https://github.com/googleapis/python-translate) and [2](https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-translate/samples)
- Fix styling of the sample and removed unnecessary dependencies
- Refactor to improve sample objective of showing how to translate a simple text.

feat(translate): add region tag 'import_client_library' and refactor sample

---

workflows/cloud-client/conftest.py
workflows/cloud-client/main.py
workflows/cloud-client/main_test.py
workflows/cloud-client/noxfile_config.py
workflows/cloud-client/requirements-test.txt
workflows/cloud-client/requirements.txt

Fixes Internal: b/391200147
- Cleanup the code inside the region tags, to make it easier for the developer to follow the quickstart
- Add `_id` suffix to project and workflow, to make more explicit what value is expected
- Take out unnecessary `os.getenvs` and the return from the region tags
- Move workflow creation to its own fixture, and create a `conftest.py` which will be reused for new samples in the same folder
- Update to latest dependencies
- Add exponential backoff as suggested in [AUTHORING_GUIDE.md#retry-rpcs](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#retry-rpcs)
- As the `__main__` entry points have been requested by 'glasnt' to stay in the scripts, but the Style guide suggests not to include them in the sample, it was adjusted …

fix(workflows): refactor sample 'workflows_api_quickstart' to comply with the Samples Style Guide and fix tests

---

functions/imagemagick/main.py
functions/imagemagick/main_test.py
functions/v2/imagemagick/main.py
functions/v2/imagemagick/main_test.py

Fixes #13292 
Updates sample to use the Wand equivalent to `-blur 0x8`, to match other samples. 
Potential root cause [comment in thread](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/13279/files#r2025722122).

fix: update blur function to match other samples

---

genai/text_generation/textgen_with_pdf.py

Update the code examples to use a different data sources that does not include Gemini 1.5 model. The previous pdf is about Gemini 1.5 model.
bugs: b/407554370

feat: update genai textgen_with_pdf.py example

---

genai/text_generation/model_optimizer_textgen_with_txt.py
genai/text_generation/test_text_generation_examples.py

Add a code sample for the model-optimizer-exp-04-09 endpoint using GenAI API.

feat: add code samples for model optimizer

---

composer/tools/composer_migrate.md
composer/tools/composer_migrate.py

Add script for migrating Composer 2 to Composer 3.

Add script for migrating environment from Composer 2 to Composer 3

---

dataflow/snippets/Dockerfile
dataflow/snippets/noxfile_config.py
dataflow/snippets/read_kafka.py
dataflow/snippets/requirements.txt

- Update the `dataflow_kafka_read` snippet to use [Managed I/O](https://cloud.google.com/dataflow/docs/guides/managed-io-kafka)
- Bump the Apache Beam version to 2.63 (required for Managed I/O)
- Update the Dockerfile to be compatible with Beam 2.63.

feat(Dataflow): Update Kafka snippet to use Managed I/O

---

generative_ai/rag/import_files_example.py

- [Yes] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [Yes ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [Yes ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [Yes] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE. …

Update import_files_example.py to optionally use import_result_sink to show import result status in a written GCS file.

---

secretmanager/snippets/create_secret_with_delayed_destroy.py
secretmanager/snippets/disable_secret_with_delayed_destroy.py
secretmanager/snippets/snippets_test.py
secretmanager/snippets/update_secret_with_delayed_destroy.py

chore(secretmanager): Add global samples for delayed destory

---

appengine/standard_python3/building-an-app/building-an-app-1/app.yaml
appengine/standard_python3/building-an-app/building-an-app-1/main.py

Bump up python runtime version to latest python 3.13

Bump up runtime version to python 3.13

---

workflows/cloud-client/README.md
workflows/cloud-client/conftest.py
workflows/cloud-client/main.py
workflows/cloud-client/myFirstWorkflow.workflows.yaml
workflows/cloud-client/pass_data_in_execution_request.py
workflows/cloud-client/pass_data_in_execution_request_test.py

Fixes b/391200147
- Update the Workflow YAML definition to receive optional arguments, and keep compatibility with the previous sample not sending arguments. The Copyright year was adjusted accordingly as it's a new file with the same name.
- Create a sample `workflows_execute_with_arguments` and start migration of `workflows_execute_without_arguments`
- Refactor previous tests and `conftest.py`
- Update README.py

feat(workflows): add sample 'execute_with_arguments' and update 'conftest.py'

---

workflows/cloud-client/execute_with_arguments.py
workflows/cloud-client/execute_with_arguments_test.py
workflows/cloud-client/execute_without_arguments.py
workflows/cloud-client/execute_without_arguments_test.py

Fixes Internal: b/414453548
- Copy main.py to execute_without_arguments.py
- Rename pass_data_in_execution_request.py to execute_with_arguments.py
`main.py` will be deleted in the next step after the references in documentation are migrated.

chore(workflows): migrate samples 'execute_without_arguments' and 'execute_with_arguments' - step 1

---

.kokoro/docker/Dockerfile

This PR fixes the issue where the `python-samples-testing` docker build is failing with the following error
```
ERROR: This script does not work on Python 3.8. The minimum supported Python version is 3.9. Please use https://bootstrap.pypa.io/pip/3.8/get-pip.py instead.
```
Towards b/414758499

chore: fix docker build for Python 3.8

---

genai/tuning/requirements.txt
genai/tuning/test_tuning_examples.py
genai/tuning/tuning_with_checkpoints_create.py
genai/tuning/tuning_with_checkpoints_get_model.py
genai/tuning/tuning_with_checkpoints_list_checkpoints.py
genai/tuning/tuning_with_checkpoints_set_default_checkpoint.py
genai/tuning/tuning_with_checkpoints_textgen_with_txt.py

feat: add code samples for tuning with intermediate checkpoints

---

secretmanager/snippets/regional_samples/create_regional_secret_with_delayed_destroy.py
secretmanager/snippets/regional_samples/disable_regional_secret_delayed_destroy.py
secretmanager/snippets/regional_samples/snippets_test.py
secretmanager/snippets/regional_samples/update_regional_secret_with_delayed_destroy.py

chore(secretmanager): Add regional samples for delayed destory

---

retail/interactive-tutorials/search/search_simple_query.py

replaces #13337
fixes b/415382524

chore(retail): add region tag to fix broken 404

---

firestore/cloud-client/snippets_test.py

Fixes Internal: b/239029690
The sample works well, but requires manual steps before running local tests.
- Add a note for future developers before running tests (Set env vars, and create a firestore DB for testing)
- Add asserts to validate the state before deleting the collection

fix(firestore): add a note for devs and asserts for `firestore_data_delete_collection`

---

generative_ai/embeddings/batch_example.py
generative_ai/embeddings/code_retrieval_example.py
generative_ai/embeddings/document_retrieval_example.py
generative_ai/embeddings/test_embeddings_examples.py

Update model name to gemini-embedding-001 in code snipets

---

.github/blunderbuss.yml

Disabling global blunderbuss assignments (the backup assignments after label based triage). 
Context reference: https://b.corp.google.com/issues/421202292

chore: disable global blunderbuss assignments

---

translate/samples/snippets/snippets.py
translate/samples/snippets/snippets_test.py

Fixes Internal: b/421210226
Note to reviewers: As using `from typing import Union, Optional` will break the linting if inserted inside the region tags, `from __future__ import annotations` is proposed instead to comply with Python 3.9.

fix(translate): update sample `translate_text` to unify across languages

---

generative_ai/embeddings/batch_example.py
generative_ai/embeddings/test_embeddings_examples.py

Addresess issues identified in #13393, #13396
The tests in #13388 all passed originally, but it appears the batch test was marked as a fixture, and was not being executed, thus the changes appeared to succeed. 
From https://btx.cloud.google.com/invocations/c57aafde-585e-490e-a9e2-384a1d47d7a1/log
```
============================= test session starts ==============================
platform linux -- Python 3.12.7, pytest-8.2.0, pluggy-1.6.0 -- /workspace/generative_ai/embeddings/.nox/py-3-12/bin/python
cachedir: .pytest_cache
rootdir: /workspace
configfile: pytest.ini
plugins: asyncio-0.23.6, anyio-4.9.0
asyncio: mode=Mode.STRICT
collecting ... collected 7 items
test_embeddings_examples.py::test_multimodal_embedding_image_video_text PASSED [ 14%] …
```

chore(generative_ai): unmark test as fixture

---

functions/billing/main.py

This region tag is in this sample https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/functions/billing_stop_on_notification/stop_billing.py which causes this duplicate to not surface this sample.

fix(functions): remove duplicate region tag

---

noxfile-template.py

Introduces explicit Python version for lint commands. 
Fixes b/425186923
A few samples (search for any noxfile-config.py files that have ignored_versions matching tested_versions, currently applies to appengine flex samples) have skipped tests by ignoring testsing all versions, so use a default, or set to earliest python that is tested.

feat: set specific linting version for tests, min tested or 3.10

---

genai/tuning/tuning_job_create.py
genai/tuning/tuning_with_checkpoints_create.py

fix(genai): Use TuningDataset to set training dataset gcs uri

---

discoveryengine/standalone_apis_sample.py

The naming convention for the ranking api changed to:
- semantic-ranker-default@latest
This PR updates the default model name.
For more information see:
https://cloud.google.com/generative-ai-app-builder/docs/ranking
Fixes #13471

fix: Update the default model name for the ranking api default name

---

composer/workflows/airflow_db_cleanup.py

We decided to change the way dag_runs triggered externally (not by schedule) are treated.
Previously they were skipped completely, but some customers are manually triggering DAGs and want to prune those informations too.
Now those dag_runs will get pruned the same way scheduled dag_runs are.

Change what we do with manually triggered dag_runs to being pruned too.

---

secretmanager/snippets/bind_tags_to_secret.py
secretmanager/snippets/create_secret_with_tags.py
secretmanager/snippets/regional_samples/bind_tags_to_regional_secret.py
secretmanager/snippets/regional_samples/create_regional_secret_with_tags.py
secretmanager/snippets/regional_samples/snippets_test.py
secretmanager/snippets/requirements.txt
secretmanager/snippets/snippets_test.py

Created samples for Global and Regional Secret Manager API
Samples (Global, Regional)
- Create Secret With Tags
- Bind Tags to Secret
Ref: https://cloud.google.com/secret-manager/docs/create-and-manage-tags

feat(secretmanager): Added samples for tags field

---

parametermanager/snippets/create_param_version_with_secret.py
parametermanager/snippets/regional_samples/create_regional_param_version_with_secret.py
parametermanager/snippets/regional_samples/remove_regional_param_kms_key.py
parametermanager/snippets/regional_samples/update_regional_param_kms_key.py

Fixed the examples in the Parameter Manager samples.

fix(parametermanager): fix examples in parameter manager docs sample

---

genai/batch_prediction/batchpredict_with_bq.py
genai/batch_prediction/batchpredict_with_gcs.py

Updates code samples to use new model gemini 2.5 flash.
Internal: b/432138567

chore(batch prediction) Updates code samples to use gemini 2.5 flash instead of gemini 2.0 flash

---

storage/hierarchical-namespace/README.md
storage/hierarchical-namespace/delete-empty-folders.py
storage/hierarchical-namespace/delete_empty_folders.py

Add script to efficiently delete a large number of nested empty folders in an HNS bucket.
See https://cloud.google.com/storage/docs/hns-buckets-best-practices#folder-management for additional context.

Add script to efficiently delete a large number of nested empty folders in an HNS bucket.

---

discoveryengine/answer_query_sample.py
discoveryengine/documents_sample_test.py

For documentation https://cloud.google.com/generative-ai-app-builder/docs/answer#search-answer-basic-python

feat(discoveryengine): Add user pseudo id to answer query sample

---

run/django/e2e_test_cleanup.yaml
run/django/e2e_test_setup.yaml

Updates the default bucket name for testing, to help identify assets in testing projects b/418598361

fix(ci): update default django static bucket name

---

discoveryengine/requirements.txt
discoveryengine/session_sample.py

feat: Update session sample with the new SessionServiceClient instead of ConversationalSearchServiceClient.
ConversationalSearchServiceClient will be deprecated soon and we would like to use SessionServiceClient instead. The new service has the exact same methods as the previous one.

feat: Update session sample with the new SessionServiceClient

---

composer/workflows/airflow_db_cleanup.py

A logic error in the final cleanup step is causing the incorrect deletion of past dag_runs.
During the last iteration when dag_id is None, the dag_id check is skipped entirely. This causes the system to delete any dag_run that is eligible for removal, not just the intended orphaned entries.
This error manifested when someone prepared a dag, which were scheduled with '@once' and start_date in the past.

Fix some dag_runs removed unintentionally 
