.github/blunderbuss.yml

Configure blunderbuss for DLP API.

chore: update blunderbuss for dlp

---

cloudbuild/snippets/quickstart_test.py

fix: Use SUCCESS value instead of name

---

recaptcha_enterprise/demosite/app/static/scripts/component.js
recaptcha_enterprise/demosite/docker-compose.yaml

- Remove unhelpful invalidReason from the response.
- Specify a container_name to simplify docker operations.

Restore changes lost to the merge into main

---

appengine/standard/migration/storage/main_test.py

fix: use default bucket name for tests

---

functions/ocr/app/requirements-test.txt
functions/ocr/app/requirements.txt

fix: new dependency versions for py-3.11

---

people-and-planet-ai/geospatial-classification/requirements-test.txt
people-and-planet-ai/geospatial-classification/requirements.txt

Refreshing PPAI dependencies separately due to the long build time.

chore: upgrade ppai geospatial dependencies

---

securitycenter/snippets/requirements-test.txt
securitycenter/snippets/snippets_bigquery_export_test.py

Addresses flaky failures in securitycenter/snippets

fix: backoff until service available

---

compute/oslogin/requirements-test.txt
compute/oslogin/requirements.txt

Fixes #8880 
We need to update couple of things at once, or there will be dependency problems.

chore(deps): Updating OSLogin dependencies

---

people-and-planet-ai/land-cover-classification/noxfile_config.py
people-and-planet-ai/weather-forecasting/tests/dataset_tests/noxfile_config.py

Tests need some refactoring work when team has time.

fix: temporarily disable testing

---

talent/job_search_commute_search_test.py

See b/277494438 for more information

fix: Adding temporary skipif while product team fixes server-side error

---

secretmanager/snippets/snippets_test.py

fix: try longer delay for quota

---

dataproc/snippets/update_cluster_test.py

fix: backoff on cancelled

---

iam/api-client/custom_roles_test.py

fix: parameter count

---

auth/api-client/api_key_test.py

fix: retry auth with delays

---

auth/api-client/api_key_test.py

fix: initialize in case of exceptions

---

dataproc/snippets/instantiate_inline_workflow_template_test.py

fix: Adds Aborted as retriable test error dataproc

---

vision/snippets/web/web_detect_test.py

Fixes web detection rare flakiness

fix: allow test to be a little flaky

---

appengine/standard/noxfile_config.py

Fixes test failures due to intermittent external module installation failures

fix: retry appengine/standard pip install

---

dialogflow/analyze_content_stream_test.py

fix: Adjusting test case to new behavior, upper case in response

---

data-science-onramp/data-processing/process_test.py

fix: changes default region for data-science test to us-west1

---

appengine/standard_python3/bundled-services/blobstore/django/main_test.py
appengine/standard_python3/bundled-services/blobstore/flask/main_test.py
appengine/standard_python3/bundled-services/blobstore/wsgi/main_test.py

Fixes flaky bundled service blobstore tests

fix: wait longer for bundled services

---

appengine/standard_python3/bundled-services/blobstore/django/main_test.py
appengine/standard_python3/bundled-services/blobstore/flask/main_test.py
appengine/standard_python3/bundled-services/blobstore/wsgi/main_test.py

Fixes rare case where new App Engine versions aren't deleted

fix: ensure cleanup even if exceptions

---

run/pubsub/e2e_test.py
run/pubsub/requirements-test.txt

fix: reorganize run pubsun e2e test fixtures with backoff

---

renovate.json

Include `pyproject.toml` files for dependency updates.
Some end-to-end samples require creating packages defined with a `pyproject.toml`
For more information: https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

Update dependencies on pyproject.toml

---

firestore/cloud-client/query_filter_or.py
firestore/cloud-client/query_filter_or_test.py
firestore/cloud-client/requirements-test.txt

explicitly use all fixtures, and add retry fixture components with backoff

chore: refactor test fixture logic

---

cloud-sql/mysql/sqlalchemy/connect_connector_auto_iam_authn.py

Updating DB_IAM_USER comment to showcase properly formatted service account name.

chore(cloudsql): update DB_IAM_USER comment

---

batch/requirements-test.txt
batch/tests/test_basics.py
batch/tests/test_bucket.py
batch/tests/test_template.py

fix: accept flaky behavior of service

---

workflows/cloud-client/main.py
workflows/cloud-client/main_test.py
workflows/cloud-client/myFirstWorkflow.workflows.yaml

fix: update Cloud Workflows sample

---

dlp/snippets/jobs.py
dlp/snippets/jobs_test.py

Implemented dlp_create_job with unit test cases; C# equivalent: https://cloud.google.com/dlp/docs/samples/dlp-create-job#dlp_create_job-csharp

[DLP] Implemented dlp_create_job with unit test cases

---

retail/interactive-tutorials/search/search_simple_query_test.py

Fixes search returning unexpected results

fix: just accept results, don't examine them

---

data-science-onramp/data-ingestion/ingestion_test.py
data-science-onramp/data-processing/process_test.py
dataproc/snippets/quickstart/quickstart.py
dataproc/snippets/submit_job.py
dataproc/snippets/submit_job_to_cluster.py
vision/snippets/detect/beta_snippets.py
vision/snippets/detect/detect.py

fix: migrate storage samples to use download_as_bytes()

---

noxfile-template.py

Forced pip to latest version unless specific version override has been defined.

fix: upgrade pip in each session

---

language/snippets/cloud-client/v1/quickstart.py

fix: update language_v1.Document to language_v1.types.Document

---

auth/api-client/api_key_test.py

fix: wait longer for retries

---

cloud-sql/postgres/sqlalchemy/connect_unix.py
cloud_tasks/snippets/create_http_task.py
cloud_tasks/snippets/create_http_task_with_token.py
cloud_tasks/snippets/create_queue.py
datastore/cloud-client/snippets.py
datastore/cloud-client/snippets_test.py
firestore/cloud-async-client/distributed_counters.py
firestore/cloud-async-client/snippets.py
firestore/cloud-async-client/snippets_test.py
firestore/cloud-client/distributed_counters.py
firestore/cloud-client/query_filter_or.py
firestore/cloud-client/query_filter_or_test.py
firestore/cloud-client/snippets.py
firestore/cloud-client/snippets_test.py
storage/api/compose_objects.py
storage/api/crud_object.py
storage/api/customer_supplied_keys.py
storage/s3-sdk/s3_sdk_test.py
storage/signed_urls/generate_signed_urls.py

Applied [pyupgrade](https://github.com/asottile/pyupgrade) to use f-strings and newer Python features.

feat: upgrade sample style (Cloud SDK)

---

run/pubsub/main.py

pair with @nicain; this is not typical usage of if __name__ == .. but
to make sure documentation and intent of the sample for atlas this
should work.

fix: add region tag, move code around for docs

---

noxfile-template.py

fixes: pip intermittently installing from source, and failing

fix: install only binary with pip

---

appengine/standard_python3/pubsub/main.py

Fixes b/281697343
this needs a new region tag, updating so I can submit an update to docs then can come back and remove the old region tag.

fix: add missing region tag

---

run/pubsub/main.py

region tag CLs have been merged; once the docs have been published this can be merged.

chore: remove unused region tag

---

composer/workflows/airflow_db_cleanup.py

Adding deletion of rows with NULL dag_id

---

run/hello-broken/main.py
run/helloworld/main.py
run/image-processing/image.py
run/image-processing/main.py
run/jobs/main.py
run/logging-manual/main.py
run/markdown-preview/editor/main.py
run/markdown-preview/editor/render.py
run/markdown-preview/renderer/main.py
run/service-auth/app.py
run/service-auth/receive.py
run/system-package/main.py

Also removes deprecate "run_" region tags

fixit: update docstrings for Cloud Run samples

---

cloud_tasks/snippets/create_http_task.py
cloud_tasks/snippets/create_http_task_test.py
cloud_tasks/snippets/create_http_task_with_token.py
cloud_tasks/snippets/create_http_task_with_token_test.py
cloud_tasks/snippets/create_queue.py
cloud_tasks/snippets/create_queue_test.py
cloud_tasks/snippets/delete_queue.py
cloud_tasks/snippets/delete_queue_test.py
cloud_tasks/snippets/list_queues.py
cloud_tasks/snippets/list_queues_test.py
cloud_tasks/snippets/noxfile_config.py

refactor: cleanup cloud_tasks samples

---

generative_ai/chat_test.py
generative_ai/classify_news_items_test.py
generative_ai/embedding_test.py
generative_ai/extraction_test.py
generative_ai/ideation_test.py
generative_ai/list_tuned_models_test.py
generative_ai/requirements-test.txt
generative_ai/sentiment_analysis_test.py
generative_ai/summarization_test.py

fix: Adding exponential backoff

---

logging/cloud-client/get_sink.py
logging/cloud-client/get_sink_test.py

feat(logging): add a sample for get_sink

---

AUTHORING_GUIDE.md
container/snippets/README.md
error_reporting/fluent_on_compute/README.md
kms/snippets/README.md
people-and-planet-ai/README.md
people-and-planet-ai/timeseries-classification/README.md
pubsublite/spark-connector/README.md

- AUTHORING_GUIDE.md
- container/snippets/README.md
- error_reporting/fluent_on_compute/README.md
- kms/snippets/README.md
- people-and-planet-ai/README.md
- people-and-planet-ai/timeseries-classification/README.md
- pubsublite/spark-connector/README.md

Updates to Authoring guide and multiple README

---

appengine/flexible/scipy/main.py
appengine/flexible/scipy/main_test.py

fixit: clean up appengine/flexible/scipy

---

appengine/flexible/hello_world/main.py
appengine/flexible/hello_world/main_test.py

fixit: clean up appengine/flexible/hello_world

---

vision/snippets/web/web_detect.py
vision/snippets/web/web_detect_test.py

Sample clean-up for Vision Web Detection.

chore(fixit): clean up vision web samples

---

run/filesystem/main.py
run/idp-sql/credentials.py
run/idp-sql/database.py
run/idp-sql/main.py
run/idp-sql/middleware.py
run/markdown-preview/editor/render.py
run/pubsub/main.py
run/service-auth/receive.py
run/system-package/main.py

fixit: clean up run samples

---

appengine/flexible_python37_and_earlier/numpy/main.py
appengine/flexible_python37_and_earlier/numpy/main_test.py

fixit: clean up appengine/flexible_python37_and_earlier/numpy

---

appengine/flexible/numpy/main.py
appengine/flexible/numpy/main_test.py

fixit: clean up appengine/flexible/numpy

---

appengine/flexible_python37_and_earlier/scipy/main.py
appengine/flexible_python37_and_earlier/scipy/main_test.py

fixit: clean up appengine/flexible_python37_and_earlier/scipy

---

appengine/flexible_python37_and_earlier/hello_world/main.py
appengine/flexible_python37_and_earlier/hello_world/main_test.py

fixit: clean up flexible_python37_and_earlier/hello_world

---

dlp/snippets/custom_infotype.py
dlp/snippets/custom_infotype_test.py
dlp/snippets/deid.py
dlp/snippets/deid_test.py
dlp/snippets/inspect_content.py
dlp/snippets/inspect_content_test.py
dlp/snippets/jobs.py
dlp/snippets/jobs_test.py
dlp/snippets/metadata.py
dlp/snippets/metadata_test.py
dlp/snippets/quickstart.py
dlp/snippets/quickstart_test.py
dlp/snippets/redact.py
dlp/snippets/redact_test.py
dlp/snippets/risk.py
dlp/snippets/risk_test.py
dlp/snippets/templates.py
dlp/snippets/templates_test.py
dlp/snippets/triggers.py
dlp/snippets/triggers_test.py

fix: Add typehints for DLP snippets

---

trace/cloud-trace-demo-app-opentelemetry/app/app.py
trace/cloud-trace-demo-app-opentelemetry/app/app_test.py

fixit: clean up trace/cloud-trace-demo-app-opentelemetry/app

---

trace/trace-python-sample-opentelemetry/main.py
trace/trace-python-sample-opentelemetry/main_test.py

fixit: clean up trace/trace-python-sample-opentelemetry

---

vision/snippets/crop_hints/crop_hints.py
vision/snippets/crop_hints/crop_hints_test.py

FixIt: Clean up Cloud Vision crop hints sample.

chore(fixit): sample clean up for vision crop hints

---

vision/snippets/document_text/doctext.py
vision/snippets/document_text/doctext_test.py

Clean up for Cloud Vision document text samples.

chore(fixit): vision document text sample clean-up

---

appengine/standard_python3/hello_world/main.py
appengine/standard_python3/hello_world/main_test.py

fixit: clean up appengine/hello_world

---

appengine/standard_python3/warmup/main.py
appengine/standard_python3/warmup/main_test.py

fixit: clean up appengine/standard_python3/warmup

---

appengine/flexible/disk/main.py
appengine/flexible/disk/main_test.py

fixit: clean up appengine/flexible/disk

---

appengine/flexible/static_files/main.py
appengine/flexible/static_files/main_test.py

fixit: clean up appengine/flexible/static_files

---

appengine/flexible/extending_runtime/main.py
appengine/flexible/extending_runtime/main_test.py

fixit: clean up appengine/flexible/extending_runtime

---

monitoring/snippets/v3/uptime-check-client/noxfile_config.py
monitoring/snippets/v3/uptime-check-client/snippets.py
monitoring/snippets/v3/uptime-check-client/snippets_test.py

fixit: clean up monitoring/snippets/v3/uptime-check-client

---

monitoring/snippets/v3/cloud-client/noxfile_config.py
monitoring/snippets/v3/cloud-client/quickstart.py
monitoring/snippets/v3/cloud-client/quickstart_test.py
monitoring/snippets/v3/cloud-client/snippets.py
monitoring/snippets/v3/cloud-client/snippets_test.py

fixit: clean up monitoring/snippets/v3/cloud-client

---

speech/microphone/transcribe_streaming_infinite.py
speech/microphone/transcribe_streaming_mic.py
speech/microphone/transcribe_streaming_mic_test.py

fixit: clean up transcribe/microphone

---

compute/load_balancing/create_certificate.py
compute/load_balancing/create_regional_certificate.py
compute/load_balancing/noxfile_config.py
compute/load_balancing/test_certificates.py

fixit: Clean up Python sample at compute/load_balancing

---

compute/encryption/generate_wrapped_rsa_key.py
compute/encryption/generate_wrapped_rsa_key_test.py
compute/encryption/noxfile_config.py

fixit:  Clean up Python sample at compute/encryption

---

compute/managed-instances/demo/app.py

fixit: Clean up Python sample at compute/managed-instances/demo

---

dialogflow/noxfile_config.py

chore: suspend some tests for now

---

appengine/standard_python3/bundled-services/mail/django/main_test.py

fix: more HTTP request retries

---

appengine/standard_python3/bundled-services/mail/wsgi/main_test.py

fix: more HTTP retries

---

.github/blunderbuss.yml

App Engine samples self-service team

fix: appengine assignments team change

---

dlp/snippets/deid.py
dlp/snippets/deid_test.py
people-and-planet-ai/land-cover-classification/README.md

This sample is not fully working, adding note for users while we work on it.

ppai/landcover: add note on current status

---

auth/api-client/api_key_test.py
auth/service-to-service/main.py
dlp/snippets/inspect_content.py
webrisk/snippets/submit_uri.py

Fixes user feedback report where no result was seen locally

fix: display result when run standalone

---

owlbot.py

- Prevents irrelevant file changes from occurring in PRs
- Tested locally
- Based on https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/b95c715c9b66fcb09ca9e30aa8280d027b169a76/owlbot.py#L36

chore: Update `owlbot.py` to only format changed files

---

dlp/snippets/inspect_content.py
dlp/snippets/inspect_content_test.py

This PR includes two region tags:
[dlp_inspect_image_file](https://cloud.google.com/dlp/docs/samples/dlp-inspect-image-file)
[dlp_inspect_column_values_w_custom_hotwords](https://cloud.google.com/dlp/docs/creating-custom-infotypes-likelihood.md#match-column-values)

[DLP] Implemented dlp_inspect_column_values_w_custom_hotwords and dlp_inspect_image_file

---

compute/client_library/ingredients/instances/create_instance.py
compute/client_library/snippets/instances/create.py
compute/client_library/snippets/instances/create_start_instance/create_from_custom_image.py
compute/client_library/snippets/instances/create_start_instance/create_from_public_image.py
compute/client_library/snippets/instances/create_start_instance/create_from_snapshot.py
compute/client_library/snippets/instances/create_start_instance/create_windows_instance.py
compute/client_library/snippets/instances/create_start_instance/create_with_additional_disk.py
compute/client_library/snippets/instances/create_start_instance/create_with_existing_disks.py
compute/client_library/snippets/instances/create_start_instance/create_with_local_ssd.py
compute/client_library/snippets/instances/create_start_instance/create_with_snapshotted_data_disk.py
compute/client_library/snippets/instances/create_with_subnet.py
compute/client_library/snippets/instances/custom_hostname/create.py
compute/client_library/snippets/instances/custom_machine_types/create_shared_with_helper.py
compute/client_library/snippets/instances/custom_machine_types/create_with_helper.py
compute/client_library/snippets/instances/custom_machine_types/create_without_helper.py
compute/client_library/snippets/instances/custom_machine_types/extra_mem_no_helper.py
compute/client_library/snippets/instances/delete_protection/create.py
compute/client_library/snippets/instances/preemptible/create_preemptible.py
compute/client_library/snippets/instances/spot/create.py

fix(compute): Properly configuring network for instance creation

---

cloud_tasks/snippets/README.md
cloud_tasks/snippets/create_http_task_test.py
cloud_tasks/snippets/create_http_task_with_token_test.py
cloud_tasks/snippets/create_queue_test.py
cloud_tasks/snippets/list_queues_test.py

Also included README cleanup (linting, line length warnings)
Fixes #10080

chore: add retries to cloud-tasks tests

---

appengine/standard_python3/bundled-services/mail/flask/main.py

FIx for arbitrary javascript injection

---

secretmanager/snippets/consume_event_notification.py

ref: b/286976386 & b/287752461
Fixes N/A

include import & print statement in python code snippet

---

speech/snippets/requirements.txt

chore: update STT client library

---

run/service-auth/receive_test.py

fix: remove debugging from test

---

speech/snippets/quickstart_v2.py
speech/snippets/quickstart_v2_test.py

fix: Update STT v2 quickstart to remove recognizer creation

---

appengine/standard_python3/bundled-services/deferred/django/main_test.py

fix: wait time instead of tries

---

.github/CODEOWNERS
.github/blunderbuss.yml

Update CODEOWNERS and Blunderbuss configs for speech team

chore: update CODEOWNERS and Blunderbuss configs for speech team

---

appengine/standard_python3/bundled-services/blobstore/flask/main_test.py
appengine/standard_python3/bundled-services/blobstore/wsgi/main_test.py
appengine/standard_python3/bundled-services/deferred/flask/main_test.py
appengine/standard_python3/bundled-services/deferred/wsgi/main_test.py
appengine/standard_python3/bundled-services/mail/django/main_test.py
appengine/standard_python3/bundled-services/mail/flask/main.py
appengine/standard_python3/bundled-services/mail/flask/main_test.py
appengine/standard_python3/bundled-services/mail/wsgi/main_test.py

Fixes #10236 #10178 #10159 #10180

fix: wait time instead of tries for flaky issues

---

composer/airflow_1_samples/airflow_db_cleanup.py
composer/workflows/airflow_db_cleanup.py

Add rendered task instances to cleanup dag

---

vision/snippets/quickstart/quickstart.py
vision/snippets/quickstart/quickstart_test.py

chore: clean up Vision quickstart

---

documentai/snippets/handle_response_sample.py
documentai/snippets/handle_response_sample_test.py
documentai/snippets/quickstart_sample.py
documentai/snippets/quickstart_sample_test.py

- Reduced function input parameters and hardcoded some values in to simplify sample.
- Response to internal issue 290362120

docs(samples): Updated Doc AI Quickstart sample based on user feedback

---

run/hello-broken/e2e_test.py

fix: wait to be sure fully ready

---

securitycenter/snippets/snippets_bigquery_export_test.py
securitycenter/snippets/snippets_mute_config_test.py
securitycenter/snippets/snippets_notification_test.py

Fixes #10439 
Fixes #10437 
Fixes #10414 
Fixes #10413

chore(scc): use backoff in tests

---

dlp/snippets/triggers.py
dlp/snippets/triggers_test.py

Implemented dlp_update_trigger sample code. Json Equivalent:
https://cloud.google.com/dlp/docs/creating-job-triggers#dlp-patch-trigger-protocol

[DLP] Implemented update trigger code sample

---

documentai/snippets/handle_response_sample.py
documentai/snippets/handle_response_sample_test.py
documentai/snippets/requirements.txt

- Update client library to `2.17` required for sample to work
- Add `processOptions` to OCR
- Add printing of Symbols and Text Styles (Not currently populated)
- Reordered Blocks/Paragraphs to indicate parent elements first
- Added generic entity extraction to Form Parser Sample
- Removed Document Quality Processor samples (Deprecated in favor of Doc OCR)
- Other minor updates for readability/Python conventions

docs(documentai): Update `handle_response` for OCR/Form Parser 2.0 GA

---

video/transcoder/create_job_from_ad_hoc.py
video/transcoder/create_job_from_preset.py
video/transcoder/create_job_from_preset_batch_mode.py
video/transcoder/create_job_from_template.py
video/transcoder/create_job_template.py
video/transcoder/create_job_with_animated_overlay.py
video/transcoder/create_job_with_concatenated_inputs.py
video/transcoder/create_job_with_embedded_captions.py
video/transcoder/create_job_with_periodic_images_spritesheet.py
video/transcoder/create_job_with_set_number_images_spritesheet.py
video/transcoder/create_job_with_standalone_captions.py
video/transcoder/create_job_with_static_overlay.py
video/transcoder/delete_job.py
video/transcoder/delete_job_template.py
video/transcoder/get_job.py
video/transcoder/get_job_state.py
video/transcoder/get_job_template.py
video/transcoder/job_template_test.py
video/transcoder/job_test.py
video/transcoder/list_job_templates.py
video/transcoder/list_jobs.py
video/transcoder/requirements.txt

b:288111390
Please merge on approval.

docs(samples): add batch mode sample and test

---

generative_ai/tuning.py

fix: Update default training steps to 300

---

.github/sync-repo-settings.yaml

Mark 3.11 as required test and turn off 3.7

chore: mark 3.11 as required test and turn off 3.7

---

.github/CODEOWNERS
.github/blunderbuss.yml

We're now the infra-db-sdk team. infra-db-dpes will be removed eventually

chore: use new team alias in CODEOWNERS

---

run/filesystem/gcsfuse_run.sh

Cleaned up version of #10476 - update cloud run script

chore: update cloud run script

---

retail/interactive-tutorials/product/add_fulfillment_places.py
retail/interactive-tutorials/product/remove_fulfillment_places.py
retail/interactive-tutorials/product/set_inventory.py

Fixes #10483
There were some recent backend changes making the LRO last longer than the deadline (120s). Update the code samples to wait in a loop.

fix(retail): fix retail fulfillment places tests

---

generative_ai/list_tuned_code_generation_models.py
generative_ai/list_tuned_code_generation_models_test.py
generative_ai/requirements.txt
generative_ai/tune_code_generation_model.py
generative_ai/tune_code_generation_model_test.py

Vertex SDK - LLM - Added tuning samples for the code generation models - `code-bison`

---

functions/v2/storage/main_test.py

chore: adding in region tag for cloud storage v2 unit test docs

---

.github/blunderbuss.yml

Update sample repo code owners to infra-db-sdk

chore: update code owners to infra-db-sdk

---

cloud-sql/mysql/sqlalchemy/main.py
cloud-sql/postgres/sqlalchemy/main.py
cloud-sql/sql-server/sqlalchemy/main.py

Follow-up PR from comment on https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10576

chore: update import statement

---

run/image-processing/e2e_test.py

fix: retries if needed

---

storagetransfer/conftest.py
storagetransfer/event_driven_aws_transfer.py
storagetransfer/event_driven_aws_transfer_test.py
storagetransfer/event_driven_gcs_transfer.py
storagetransfer/event_driven_gcs_transfer_test.py
storagetransfer/requirements-test.txt
storagetransfer/requirements.txt

Adds event driven transfer samples and tests

feat(storagetransfer): Adds event driven transfer samples

---

composer/workflows/airflow_db_cleanup.py
composer/workflows/kubernetes_pod_operator_c2.py

update comment in kpo

---

recaptcha_enterprise/snippets/requirements-test.txt

Updates webdriver-manager version. 
Fixes #10468 
Fixes #10469 
Fixes #10562
Fixes #10564

fix: recaptcha test failure

---

discoveryengine/documents_sample_test.py
discoveryengine/get_operation_sample.py
discoveryengine/import_documents_sample.py
discoveryengine/list_documents_sample.py
discoveryengine/list_operations_sample.py
discoveryengine/poll_operation_sample.py
discoveryengine/search_sample.py
discoveryengine/search_sample_test.py

- Add API Endpoint to Samples
- Change `search_engine_id` to `data_store_id`
Fixes Internal ticket [b/300400448](http://b/300400448)

fix(discoveryengine): Update the samples after GA Launch

---

jobs/v3/api_client/histogram_sample_test.py

fix: more retries

---

recaptcha_enterprise/demosite/app/requirements.txt

Update requirements file to add "Werkzeug==2.2.0"
b: 302855603

fix(recaptcha-demosite): add dependency - Werkzeug

---

run/image-processing/e2e_test.py

fix: use entire UUID for uniqueness

---

composer/blog/gcp-tech-blog/data-orchestration-with-composer/requirements.txt
composer/cicd_sample/requirements.txt

As noted in chat, dependabot made some Airflow changes we actually didn't want!

revert dependabot Airflow changes

---

generative_ai/chat.py
generative_ai/classify_news_items.py
generative_ai/code_chat.py
generative_ai/code_completion_function.py
generative_ai/code_completion_test_function.py
generative_ai/code_generation_function.py
generative_ai/code_generation_unittest.py
generative_ai/embedding.py
generative_ai/extraction.py
generative_ai/ideation.py
generative_ai/list_tuned_code_generation_models.py
generative_ai/list_tuned_models.py
generative_ai/sentiment_analysis.py
generative_ai/streaming_chat.py
generative_ai/streaming_code.py
generative_ai/streaming_codechat.py
generative_ai/streaming_text.py
generative_ai/summarization.py
generative_ai/tune_code_generation_model.py
generative_ai/tuning.py

fix: GenAI sample Copy-Paste Runnable

---

dataflow/run_template/main_test.py

fix(imports): Fixes #10608

---

appengine/standard_python3/bundled-services/deferred/django/main.py
appengine/standard_python3/bundled-services/deferred/django/main_test.py
appengine/standard_python3/bundled-services/deferred/flask/main.py
appengine/standard_python3/bundled-services/deferred/flask/main_test.py
appengine/standard_python3/bundled-services/deferred/wsgi/main.py
appengine/standard_python3/bundled-services/deferred/wsgi/main_test.py

fix: longer waits for deferred operations

---

discoveryengine/requirements.txt
discoveryengine/search_sample.py
discoveryengine/search_sample_test.py

- Include Content Search Spec, Query expansion, and spell correction
- Context: 
- https://cloud.google.com/generative-ai-app-builder/docs/snippets
- https://cloud.google.com/generative-ai-app-builder/docs/get-search-summaries

chore(discoveryengine): Update Search Sample with more options

---

.github/CODEOWNERS

See https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10743#issue-1929090031

chore: remove @justin-mp from CODEOWNERS

---

generative_ai/code_chat.py
generative_ai/code_completion_function.py
generative_ai/code_completion_test_function.py
generative_ai/code_generation_function.py
generative_ai/code_generation_unittest.py
notebooks/README.md
notebooks/samples/README.md
notebooks/tutorials/bigquery/Getting started with BigQuery ML Feature Engineering.ipynb

fix: Rebranding vertexai genai terms

---

generative_ai/tuning.py

feat: model tuning update with evaluation metrics

---

run/idp-sql/main.py
run/idp-sql/requirements.txt

fix(deps): update to Flask 3.0.0, update deprecated decorator

---

run/deployment-previews/README.md
run/deployment-previews/cloudbuild-configurations/cloudbuild-cleanup.yaml
run/deployment-previews/cloudbuild-configurations/cloudbuild-preview.yaml
run/deployment-previews/cloudbuild-configurations/cloudbuild.yaml

Fixes b/288825878
* Moves sample to use Artifact Registry
* Makes use of `REPO_FULL_NAME` substitution variable
* Uses dedicated service account 
* Uses python microservice template repo
* Updates for UI changes
* Replace `<figure>` with markdown images
* Misc spelling and grammar fixes.

Update deployment previews

---

discoveryengine/multi_turn_search_sample.py
discoveryengine/multi_turn_search_sample_test.py

- Add Sample for Multi-Turn Search (Conversational Search)
- https://cloud.google.com/generative-ai-app-builder/docs/multi-turn-search

docs(discoveryengine): Create Multi-Turn Search Sample

---

run/image-processing/requirements-test.txt
run/image-processing/requirements.txt

Fixes #10792
Need to specifically import Werkzeug now. Also updated dependencies.

fix: update and add requirements

---

run/jobs/README.md
run/jobs/e2e_test_cleanup.yaml
run/jobs/e2e_test_setup.yaml

chore(b-230113499): removes alpha references from jobs

---

appengine/standard/pubsub/requirements.txt

fix: add google-auth-httplib2 to pubsub sample

---

dlp/snippets/Deidentify/deidentify_cloud_storage.py
dlp/snippets/Deidentify/deidentify_date_shift.py
dlp/snippets/Deidentify/deidentify_deterministic.py
dlp/snippets/Deidentify/deidentify_dictionary_replacement.py
dlp/snippets/Deidentify/deidentify_exception_list.py
dlp/snippets/Deidentify/deidentify_fpe.py
dlp/snippets/Deidentify/deidentify_free_text_with_fpe_using_surrogate.py
dlp/snippets/Deidentify/deidentify_masking.py
dlp/snippets/Deidentify/deidentify_redact.py
dlp/snippets/Deidentify/deidentify_replace.py
dlp/snippets/Deidentify/deidentify_replace_infotype.py
dlp/snippets/Deidentify/deidentify_simple_word_list.py
dlp/snippets/Deidentify/deidentify_table_bucketing.py
dlp/snippets/Deidentify/deidentify_table_condition_infotypes.py
dlp/snippets/Deidentify/deidentify_table_condition_masking.py
dlp/snippets/Deidentify/deidentify_table_fpe.py
dlp/snippets/Deidentify/deidentify_table_infotypes.py
dlp/snippets/Deidentify/deidentify_table_primitive_bucketing.py
dlp/snippets/Deidentify/deidentify_table_row_suppress.py
dlp/snippets/Deidentify/deidentify_table_with_crypto_hash.py
dlp/snippets/Deidentify/deidentify_table_with_multiple_crypto_hash.py
dlp/snippets/Deidentify/deidentify_time_extract.py
dlp/snippets/Deidentify/reidentify_deterministic.py
dlp/snippets/Deidentify/reidentify_fpe.py
dlp/snippets/Deidentify/reidentify_free_text_with_fpe_using_surrogate.py
dlp/snippets/Deidentify/reidentify_table_fpe.py
dlp/snippets/Deidentify/reidentify_text_fpe.py
dlp/snippets/Triggers/delete_trigger.py

Included imports inside the region tag for deidentify related dlp samples. Rest samples required no change. 

fix(dlp): Included imports inside the region tag for dlp samples

---

AUTHORING_GUIDE.md
automl/tables/automl_tables_dataset.py
automl/tables/dataset_test.py

Adds dataset_name to the calls to ensure no resource collision on display name
Fixes #10925

fix flaky test, fix authoring guide typo

---

Makefile

This is a work in progress.
Create a Makefile that can be used to provide a consistent interface to running
samples, regardless of language.

feat: Makefile for consistent python testing interface

---

run/helloworld/Dockerfile

Users are looking for sample Dockerfiles. 
quickstarts in other languages also have Dockerfiles

Restore Dockerfile

---

generative_ai/code_completion_test_function_test.py

Updating test case for Generative AI
Fixes https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10943

fix(generative_ai): update testcase

---

logging/import-logs/README.md

Remove footnotes by:
* replacing "TBD" with the the valid container image URI.
* commenting the mentioning of documentation until the reference architecture documentation is released

fix: update import logs sample README.md

---

practice-folder/beginner-sample/hello.py
practice-folder/beginner-sample/hello_test.py

fix: correct last updated message

---

practice-folder/beginner-sample/hello.py
practice-folder/beginner-sample/hello_test.py

fix: Update hello.py timestamp message

---

logging/import-logs/README.md

add instructions about importing logs older than 30 days to the sample's README file.

chore(docs): update import log README

---

functions/billing/main_test.py

Fixes #10963
There were some problems with those tests, I don't know how they were passing in the first place.

fix: Fixing functions/billing tests

---

generative_ai/function_calling.py

Adds a code snippet to be used in documentation for function calling in Vertex AI.

feat(generative-ai): Add function calling example for multimodal snippet

---

generative_ai/gemini_chat_example.py
generative_ai/gemini_count_token_example.py
generative_ai/gemini_guide_example.py
generative_ai/gemini_multi_image_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_single_turn_video_example.py
generative_ai/requirements.txt
generative_ai/test_gemini_examples.py

Adding 5 samples for the new GenAI model
Fixes #11017
Update: CICD issues
* CICD project is not whitelisted
* [b/316007612](b/316007612)

feat(generative-ai): Add code samples for Gemini models

---

practice-folder/intermediate-sample/main.py
practice-folder/intermediate-sample/main_test.py
practice-folder/intermediate-sample/requirements-test.txt
practice-folder/intermediate-sample/requirements.txt

feat: intermediate codelab

---

generative_ai/gemini_guide_example.py
generative_ai/gemini_multi_image_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_single_turn_video_example.py

Updated the order of inputs given to GenAI model.
As per best practices mentioned, updated the `text` input to be last argument in the list of input items.

chore(generative_ai): update the order of items

---

generative_ai/gemini_guide_example.py
generative_ai/gemini_multi_image_example.py
generative_ai/gemini_pro_basic_example.py
generative_ai/gemini_pro_config_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/test_gemini_examples.py

Add two Gemini pro vision samples

feat(generative_ai): add gemini pro basic and config examples

---

composer/workflows/airflow_db_cleanup.py

Composer db cleanup dag

---

auth/service-to-service/auth_test.py

fix: update hello image reference to Artifact Registry hosted version

---

compute/client_library/ingredients/instances/create_instance.py
compute/client_library/snippets/tests/test_templates.py

fix: compute template test issue

---

generative_ai/distillation.py
generative_ai/distillation_test.py

feat: add code samples for distillation

---

monitoring/snippets/v3/cloud-client/snippets_test.py

fix(monitoring): Fixing flaky tests

---

storage/cost-analysis/README.md
storage/cost-analysis/storage_soft_delete_relative_cost_analyzer.py

The sample was already merged, this PR is to update the documentation. 
Fixes #11196
This was reviewed internally : cl/608673793

docs(samples): Updating readme for soft delete cost analyzer script

---

generative_ai/distillation.py
generative_ai/distillation_test.py

fix: distillation unit test fix

---

generative_ai/classify_news_items.py
generative_ai/evaluate_model.py
generative_ai/extraction.py
generative_ai/ideation.py
generative_ai/list_tuned_models.py
generative_ai/sentiment_analysis.py
generative_ai/summarization.py
generative_ai/tuning.py

Fixes b/318011653
Update the text-bison model stable version to 002.
001 will be deprecated.

fix(generative-ai): update text-bison stable version to 002

---

generative_ai/chat.py
generative_ai/classify_news_items.py
generative_ai/classify_news_items_test.py
generative_ai/code_chat.py
generative_ai/code_completion_function.py
generative_ai/code_completion_test_function.py
generative_ai/code_generation_function.py
generative_ai/distillation.py
generative_ai/embedding.py
generative_ai/evaluate_model.py
generative_ai/evaluate_model_test.py
generative_ai/extraction.py
generative_ai/extraction_test.py
generative_ai/function_calling.py
generative_ai/ideation.py
generative_ai/ideation_test.py
generative_ai/list_tuned_code_generation_models.py
generative_ai/list_tuned_models.py
generative_ai/sentiment_analysis.py
generative_ai/streaming_chat.py
generative_ai/streaming_code.py
generative_ai/streaming_codechat.py
generative_ai/streaming_text.py
generative_ai/summarization.py
generative_ai/tune_code_generation_model.py
generative_ai/tuning.py

1. Update region_tags to exclude command for script executions `if __name__ = ....` (one line updates for 20 samples)
2. Update test cases (No code changes to python script) (changes to 3 tests files)
Note:
* For updates please check [b/327042223](http://b/327042223)
* Report a newly discovered bug at https://github.com/GoogleCloudPlatform/python-docs-samples/issues/11264

bug fix: fix the function call for Gen AI samples

---

appengine/flexible/hello_world_django/requirements.txt
asset/snippets/quickstart_searchallresources.py
generative_ai/function_calling_chat.py
generative_ai/function_calling_chat_test.py

Fixes #11256.
Currently, the `generative-ai/function-calling` code sample uses the text modality of Gemini function calling. This PR adds sample code and tests for `generative-ai/function-calling-chat` that shows how to use the chat modality of Gemini function calling with a multi-turn conversation.

Add code sample for `generative-ai/function-calling-chat` that uses the chat modality

---

generative_ai/gemini_grounding_example.py
generative_ai/grounding.py
generative_ai/grounding_test.py
generative_ai/test_gemini_examples.py

Add samples for Vertex AI Grounding with PaLM and Gemini
https://cloud.google.com/vertex-ai/docs/generative-ai/grounding/ground-language-models
Gemini Grounding test is currently failing due to b/326448948#comment2

feat: Add Vertex AI Grounding samples

---

discoveryengine/requirements-test.txt
discoveryengine/requirements.txt
discoveryengine/search_sample.py

https://cloud.google.com/generative-ai-app-builder/docs/get-search-summaries#summary-model
Requested in b/327250330

samples(discoveryengine): Add Model Prompt Spec and Model Spec to `search_sample()`

---

recaptcha_enterprise/demosite/app/requirements.txt

Update google-cloud-recaptcha-enterprise client library dependency version

chore(deps): update google-cloud-recaptcha-enterprise client to 1.18.1

---

practice-folder/beginner-sample/hello.py
practice-folder/beginner-sample/hello_test.py

fix: update the last_updated string

---

generative_ai/multimodal_embedding_image.py

fix: dimension parameter not supported

---

composer/workflows/kubernetes_pod_operator_c2.py

Update comments: config_file must be specified explicitly

---

generative_ai/function_calling.py
generative_ai/function_calling_chat.py
generative_ai/gemini_chat_example.py
generative_ai/gemini_count_token_example.py
generative_ai/gemini_grounding_example.py
generative_ai/gemini_guide_example.py
generative_ai/gemini_multi_image_example.py
generative_ai/gemini_pro_basic_example.py
generative_ai/gemini_pro_config_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_single_turn_video_example.py

Fixes b/329641091
Update the region tags for Gemini code samples with the GenAI specific tag generativeaionvertexai.

refactor: change the region tags for Gemini samples

---

run/jobs/main.py

fix: update comment to reflect the required argument

---

generative_ai/embedding_model_tuning.py
generative_ai/embedding_model_tuning_test.py

Fixes: b/320696662
- [ X] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)

feat: Text-Embedding Model Tuning demo.

---

generative_ai/test_gemini_examples.py

Fix flaky test_gemini_examples.py

---

generative_ai/embedding.py
generative_ai/embedding_preview.py
generative_ai/embedding_test.py

feat: Elastic Text-Embedding Model demo.

---

generative_ai/imagen/generate_image.py

feat: update generate image sample to 006

---

generative_ai/imagen/edit_image_mask.py
generative_ai/imagen/edit_image_mask_free.py
generative_ai/imagen/get_short_form_image_captions.py
generative_ai/imagen/get_short_form_image_responses.py

feat: update region tags for existing Imagen samples

---

generative_ai/gemini_all_modalities.py
generative_ai/gemini_audio.py
generative_ai/gemini_system_instruction.py
generative_ai/gemini_video_audio.py
generative_ai/requirements.txt
generative_ai/test_gemini_examples.py

Add Gemini 1.5 Pro code samples:
- Audio
- Video/Audo
- All modalities
- System instruction

feat: Add Gemini 1.5 Pro code samples

---

generative_ai/embedding_model_tuning.py

fix: Tidy up text embedding model tuning demo.

---

generative_ai/gemini_pdf_example.py
generative_ai/test_gemini_examples.py

Update the Gemini PDF example with:
- New model ID
- New sample template

refactor: Update Gemini PDF example

---

generative_ai/test_gemini_examples.py

fix(generative-ai): Making test more accepting for AI answer.

---

.github/dependabot.yml

Should reduce the number of Pull Requests from Dependabot

chore: Change Dependabot to group dependencies

---

.kokoro/docker/Dockerfile
vision/snippets/detect/detect_test.py

Add explicit python3.12 pip install for setuptools
Follow-up to #11358

Update Dockerfile to fix Python 3.12 tests

---

generative_ai/imagen/generate_image.py
generative_ai/imagen/generate_image_test.py

feat: update Imagen 2 samples for usability

---

speech/microphone/README.rst
speech/snippets/README.rst

issue-10628 fix

---

functions/helloworld/sample_http_test_integration.py

[Issue 9129 fix] Improve integration tests

---

iap/requirements.txt

Update requirements.txt to include google cloud iam

---

generative_ai/README.md
generative_ai/function_calling.py
generative_ai/function_calling_chat.py
generative_ai/gemini_all_modalities.py
generative_ai/gemini_audio.py
generative_ai/gemini_chat_example.py
generative_ai/gemini_count_token_example.py
generative_ai/gemini_grounding_example.py
generative_ai/gemini_guide_example.py
generative_ai/gemini_multi_image_example.py
generative_ai/gemini_pdf_example.py
generative_ai/gemini_pro_basic_example.py
generative_ai/gemini_pro_config_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_single_turn_video_example.py
generative_ai/gemini_system_instruction.py
generative_ai/gemini_video_audio.py
generative_ai/rag.py

* Update samples to scripting format style. Tagging @gericdong for reviewing this item.
* Update Gemini model name for Gemini samples
* Code cleanup and code formatting updates.

feat: gemini code samples updates

---

generative_ai/classify_news_items.py
generative_ai/classify_news_items_test.py

Fixes b/336998539
Update the classification sample to the new style with -
- New copy-paste-runnable style
- New region tag

refactor(generative-ai): Update the classification sample to the new style

---

generative_ai/chat.py
generative_ai/chat_test.py

Fixes b/336998539
Update chat sample to the new style with -
- New copy-paste-runnable style
- Stable version
- New region tag

refactor(generative-ai): Update chat sample to the new style

---

generative_ai/list_tuned_code_generation_models.py

version bump for aiplatform_sdk_list_tuned_code_generation_models fix

---

generative_ai/tune_code_generation_model.py
generative_ai/tune_code_generation_model_test.py

Fixes b/336998539
Update code tuning sample to the new style with -
- New copy-paste-runnable style
- New region tag
- New stable version

refactor(generative-ai): Update code tuning sample to the new style

---

generative_ai/tuning.py
generative_ai/tuning_test.py

Fixes b/336998539
Update the text model tuning sample to the new style with -
- New copy-paste-runnable style
- New region tag

refactor(generative-ai): Update text model tuning sample to the new style

---

iam/cloud-client/snippets/create_key.py
iam/cloud-client/snippets/delete_key.py
iam/cloud-client/snippets/list_keys.py
iam/cloud-client/snippets/test_service_account_key.py

feat: write sample for creating key for service account

---

documentai/snippets/handle_response_sample.py

fix: Spelling error `available`

---

generative_ai/rag.py
generative_ai/rag_test.py
generative_ai/requirements.txt

samples(vertex-ai): Add missing parameter for RAG Upload File

---

generative_ai/gemini_guide_example.py

Fixes b/338025701
Remove redundant TODOs for the SDK installation.
SDK installation is already covered by public docs.

refactor(generative-ai): Remove redundant TODOs

---

generative_ai/embedding_model_tuning.py
generative_ai/embedding_model_tuning_test.py
generative_ai/requirements.txt

Use tune_model method on TextEmbeddingModel class.

---

generative_ai/gemini_chat_example.py
generative_ai/gemini_count_token_example.py
generative_ai/gemini_grounding_example.py
generative_ai/gemini_guide_example.py
generative_ai/gemini_multi_image_example.py
generative_ai/gemini_pro_basic_example.py
generative_ai/gemini_pro_config_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_single_turn_video_example.py
generative_ai/test_gemini_examples.py

Gemini sample style updates:
- add comment to update product_id
- set default location to "us-central1"
- update tests

refactor(generative_ai): update gemini sample to use specific location and add developer TODOs

---

generative_ai/embedding.py
generative_ai/embedding_test.py

feat: override the 003 model code sample to 004 models.

---

iam/cloud-client/snippets/service_account_get_policy.py
iam/cloud-client/snippets/service_account_rename.py
iam/cloud-client/snippets/service_account_set_policy.py
iam/cloud-client/snippets/test_service_account.py

feat: service account manipulations samples

---

generative_ai/gemini_video_audio.py

fix: indent error

---

generative_ai/gemini_text_input_example.py

feat: update text-only input sample to use a generic review

---

generative_ai/gemini_rapid_evaluation.py
generative_ai/gemini_rapid_evaluation_test.py

samples(generative_ai): Update Rapid Eval Sample to use Vertex AI SDK

---

bigquery-connection/snippets/create_mysql_connection.py
bigquery-connection/snippets/create_mysql_connection_test.py

Fixes https://github.com/GoogleCloudPlatform/python-docs-samples/issues/11720
- [N/A] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [N/A] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [N/A] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [N/A] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [N/A] This …

docs(bigquery-connection): supply a manual connection_id to assist with cleanup

---

iam/cloud-client/snippets/conftest.py

fix: leverage single pre-created role in tests

---

iam/cloud-client/snippets/get_policy.py
iam/cloud-client/snippets/modify_policy_add_member.py
iam/cloud-client/snippets/modify_policy_remove_member.py
iam/cloud-client/snippets/requirements-test.txt
iam/cloud-client/snippets/set_policy.py
iam/cloud-client/snippets/test_project_policies.py
iam/cloud-client/snippets/test_service_account_key.py

[Fix] Adding retries for flaky tests

---

eventarc/generic/Dockerfile
eventarc/pubsub/Dockerfile

Removes unused region tags: 
* eventarc_generic_dockerfile
* eventarc_pubsub_dockerfile

fix: remove unused region tags

---

generative_ai/function_calling.py
generative_ai/gemini_all_modalities.py
generative_ai/gemini_audio.py
generative_ai/gemini_pdf_example.py
generative_ai/gemini_system_instruction.py
generative_ai/gemini_video_audio.py

Gemini 1.5 Flash model update 1

feat: Gemini 1.5 Flash updates

---

iam/cloud-client/snippets/quickstart.py
iam/cloud-client/snippets/quickstart_test.py
iam/cloud-client/snippets/test_project_policies.py
iam/cloud-client/snippets/test_service_account_key.py

feat: added quickstart sample

---

generative_ai/function_calling.py
generative_ai/gemini_all_modalities.py
generative_ai/gemini_audio.py
generative_ai/gemini_count_token_example.py
generative_ai/gemini_pdf_example.py
generative_ai/gemini_system_instruction.py
generative_ai/gemini_tuning_test.py
generative_ai/gemini_video_audio.py
generative_ai/inference/inference_api_test.py

Update Gemini Models to use flash
https://blog.google/technology/ai/google-gemini-update-flash-ai-assistant-io-2024/

feat(generative_ai): update gemini model to use flash model

---

generative_ai/function_calling.py
generative_ai/gemini_all_modalities.py
generative_ai/gemini_audio.py
generative_ai/gemini_count_token_example.py
generative_ai/gemini_pdf_example.py
generative_ai/gemini_system_instruction.py
generative_ai/gemini_video_audio.py

Clearing unnecessary code comment.
Link provided should have information on related models with model number.

docs(generative_ai): clearing comments

---

speech/microphone/transcribe_streaming_infinite.py
speech/microphone/transcribe_streaming_infinite_test.py
speech/microphone/transcribe_streaming_mic_test.py

feat: tests added

---

dialogflow/detect_intent_stream.py

fix: closeSend example for python

---

memorystore/memcache/noxfile_config.py
memorystore/memcache/quickstart.py
memorystore/memcache/quickstart_test.py
memorystore/memcache/requirement-test.txt
memorystore/memcache/requirement.txt

Feat: Memcached samples

---

generative_ai/embedding_model_tuning.py
generative_ai/test_gemini_examples.py

fix: spelling and update comment test_gemini_examples.py

---

generative_ai/summarization.py
generative_ai/summarization_test.py

Fixes b/341837104
- set  default temperature 
- set default location
- fix incorrect prompt text indentation

fix(generative-ai): temperature is not defined in the sample

---

generative_ai/gemini_multi_image_example.py
generative_ai/gemini_pro_basic_example.py
generative_ai/gemini_single_turn_video_example.py

Fixes 
- Update the Gemini 1.0 vision model with the 1.5 Flash model.
- [x ] Please **merge** this PR for me once it is approved

feat(generative-ai): Update Gemini model versions

---

cdn/snippets.py
cdn/snippets_test.py

No code changes. Update region tags to include imports.

style(cdn): update snippets.py code format.

---

container/snippets/create_cluster.py
container/snippets/create_cluster_test.py

Fixes #10651 
Added additional configurations, which were requested in the issue. However some of them are not specific to GKE.
After cluster is being created the following actions are available as kubernetes documentation states:
- Create a deployment (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)
- Create a cronjob (https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)
- Create a new job (https://kubernetes.io/docs/concepts/workloads/controllers/job/)

fix: added additional configurations with description

---

generative_ai/anthropic_claude_3_tool_use.py
generative_ai/anthropic_claude_3_tool_use_test.py

Fixes #b343808667
- [s] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample

Add tool use sample for Claude model

---

generative_ai/chat_completions/chat_completions_function_calling_basic.py
generative_ai/chat_completions/chat_completions_function_calling_config.py
generative_ai/chat_completions/chat_completions_test.py

Fixes b/344536628
- Function calling basic 
- Function calling with configuration

feat(generative-ai): Add function calling examples for Chat Completions API

---

generative_ai/chat_completions/chat_completions_function_calling_basic.py
generative_ai/chat_completions/chat_completions_function_calling_config.py
generative_ai/chat_completions/chat_completions_non_streaming_image.py
generative_ai/chat_completions/chat_completions_non_streaming_text.py
generative_ai/chat_completions/chat_completions_streaming_image.py
generative_ai/chat_completions/chat_completions_streaming_text.py

…samples
refactor(generative-ai): Change region tags for chat completions api
completion > completions

refactor(generative-ai): Change region tags for chat completions api

---

generative_ai/gemini_guide_example.py
generative_ai/gemini_text_input_example.py

feat: update quickstart samples to use the Gemini Flash model

---

speech/microphone/requirements.txt
speech/microphone/transcribe_streaming_infinite_v2.py
speech/microphone/transcribe_streaming_infinite_v2_test.py

Fixes #11596
This PR provides an example of Infinite Streaming with the Google Speech-to-Text API v2.

add STT v2 API infinite streaming example Issue ##11596

---

functions/bigtable/main_async.py
functions/bigtable/main_async_test.py
functions/bigtable/requirements.txt

Asyncio sample

---

compute/client_library/recipes/instances/ip_address/assign_static_external_ip_to_new_vm.py
compute/client_library/snippets/instances/ip_address/assign_static_external_ip_to_new_vm.py

Replacing the region tag name, as the previous one was incorrect and colliding with existing one.

fix(compute): renaming region name

---

run/helloworld/Dockerfile

Remove duplicate region tag

---

discoveryengine/create_data_store_sample.py
discoveryengine/data_store_sample_test.py
discoveryengine/delete_data_store_sample.py
discoveryengine/requirements.txt

Create and Delete Data Store Samples for Vertex AI Search
https://cloud.google.com/generative-ai-app-builder/docs/create-data-store-es#website

samples(discoveryengine): Add Create/Delete Data Store Samples

---

generative_ai/context_caching/context_caching_test.py
generative_ai/context_caching/create_context_cache.py
generative_ai/gemini_rapid_evaluation_test.py
generative_ai/gemini_reasoning_engine_test.py
generative_ai/requirements.txt

Fixes b346529113
Add context caching samples:
- Create context cache

feat(generative-ai): Add context caching samples (1)

---

generative_ai/context_caching/context_caching_test.py
generative_ai/context_caching/delete_context_cache.py
generative_ai/context_caching/get_context_cache.py
generative_ai/context_caching/update_context_cache.py
generative_ai/context_caching/use_context_cache.py

Fixes b346529113
Add context caching samples part 2:
- use
- get
- update
- delete
Part 1 is in #11871

feat(generative-ai): Add context caching samples (2)

---

generative_ai/controlled_generation/controlled_generation_test.py
generative_ai/controlled_generation/response_mime_type.py
generative_ai/controlled_generation/response_schema.py

Fixes b348169182
Add controlled generation samples
- response_mime_type (for Flash)
- response_schema (for Pro)

feat(generative-ai): Add controlled generation samples

---

discoveryengine/create_engine_sample.py
discoveryengine/delete_engine_sample.py
discoveryengine/engine_sample_test.py
discoveryengine/get_engine_sample.py
discoveryengine/list_engines_sample.py
discoveryengine/search_sample.py

Add Engine methods Samples
For this page in docs: https://cloud.google.com/generative-ai-app-builder/docs/create-engine-es

samples(discoveryengine): Add Create, List, Get, Delete Engine Samples

---

generative_ai/controlled_generation/controlled_generation_test.py
generative_ai/controlled_generation/response_mime_type.py
generative_ai/controlled_generation/response_schema.py

Fixes b348169182
Add more controlled generation examples for the use of response_schema.

feat(generative-ai): Add more controlled generation examples

---

discoveryengine/site_search_engine_sample.py
discoveryengine/site_search_engine_sample_test.py

For page https://cloud.google.com/generative-ai-app-builder/docs/create-data-store-es

samples(discoveryengine): Add Website Import

---

appengine/standard/mailjet/app.yaml

remove unused env_variables region tag

---

jobs/v3/api_client/commute_search_sample.py

fix: Adding region tag with product prefix

---

jobs/v3/api_client/base_job_sample.py
jobs/v3/api_client/commute_search_sample.py

chore: add job prefix to job sample

---

kubernetes_engine/django_tutorial/polls.yaml

Internal: b/347826204
- [x ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#tes …

Adding container region tag

---

monitoring/snippets/v3/cloud-client/quickstart.py

chore: fix a typo in monitoring/snippets/v3/cloud-client/quickstart.py

---

kubernetes_engine/django_tutorial/polls.yaml

Internal: b/347826204
- [ x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#tes …

Removing old 'service' region tag.

---

compute/api/create_instance.py

Add compute_create_instance region tag

---

appengine/standard/firebase/firetactoe/static/main.js

chore(appengine): remove region tag: add_listener

---

compute/api/create_instance.py

Remove old create_instance region tag

---

batch/create/create_gpu_with_script_no_mounting.py
batch/create/create_with_gpu_no_mounting.py
batch/tests/test_basics.py
batch/tests/test_bucket.py
batch/tests/test_template.py

feat: create gpu job sample

---

batch/create/create_with_service_account.py
batch/tests/test_basics.py

feat: batch create job with service account

---

generative_ai/controlled_generation/response_schema.py
generative_ai/rag.py

The default model response is a bit confusing since some fields aren't being included (b/349685260).

Updated forecast sample

---

jobs/v3/api_client/quickstart.py

Add new region tag as part of migration (quickstart -> job_search_quick_start_python)
Internal: b/347825842

Chore: Add new region tag

---

jobs/v3/api_client/quickstart.py

Change region tag to match naming convention of other languages.
job_search_quick_start_python -> job_search_quick_start
Internal: b/347825842

Chore: Update region tag

---

batch/create/create_with_ssd.py
batch/tests/test_basics.py

feat: create batch with local ssd

---

jobs/v3/api_client/commute_search_sample.py

/removed old region tag commute_search
Fixes b/347825771

fix: removed old region tag

---

jobs/v3/api_client/base_job_sample.py

chore: remove get_job region tag from base_job_sample.py

---

datastore/cloud-ndb/quickstart.py

chore: removes ndb_context_usage region tags

---

generative_ai/gemini_tuning.py
generative_ai/gemini_tuning_test.py

fix: Gemini tuning samples don't support 1.5 Flash

---

batch/create/create_with_persistent_disk.py
batch/tests/test_basics.py

feat: create job with persistent disk sample

---

generative_ai/function_calling.py
generative_ai/gemini_all_modalities.py
generative_ai/gemini_audio.py
generative_ai/gemini_chat_example.py
generative_ai/gemini_count_token_example.py
generative_ai/gemini_grounding_example.py
generative_ai/gemini_guide_example.py
generative_ai/gemini_multi_image_example.py
generative_ai/gemini_pdf_example.py
generative_ai/gemini_pro_basic_example.py
generative_ai/gemini_pro_config_example.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_single_turn_video_example.py
generative_ai/gemini_text_input_example.py
generative_ai/gemini_video_audio.py

Instead of using `GenerativeModel(model_name="gemini...")` using `GenerativeModel("gemini-1.5-flash-001")`. `model_name` is the default expected argument and there is not need to explicitly mention it.
Fixes [b350891009](b/350891009)

refactor(generative_ai): update gemini code samples

---

.github/CODEOWNERS
managedkafka/snippets/clusters/clusters_test.py
managedkafka/snippets/clusters/create_cluster.py
managedkafka/snippets/clusters/delete_cluster.py
managedkafka/snippets/clusters/get_cluster.py
managedkafka/snippets/clusters/list_clusters.py
managedkafka/snippets/clusters/update_cluster.py
managedkafka/snippets/consumergroups/consumer_groups_test.py
managedkafka/snippets/consumergroups/delete_consumer_group.py
managedkafka/snippets/consumergroups/get_consumer_group.py
managedkafka/snippets/consumergroups/list_consumer_groups.py
managedkafka/snippets/consumergroups/update_consumer_group.py
managedkafka/snippets/requirements.txt
managedkafka/snippets/topics/create_topic.py
managedkafka/snippets/topics/delete_topic.py
managedkafka/snippets/topics/get_topic.py
managedkafka/snippets/topics/list_topics.py
managedkafka/snippets/topics/topics_test.py
managedkafka/snippets/topics/update_topic.py

- [n/a] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [n/a] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)

Managed kafka code samples

---

discoveryengine/create_data_store_sample.py
discoveryengine/documents_sample_test.py
discoveryengine/import_documents_sample.py

- https://cloud.google.com/generative-ai-app-builder/docs/create-data-store-es

samples(discoveryengine): Add Import Documents Samples for Google Cloud Sources

---

generative_ai/chat_completions/chat_completions_credentials_refresher.py
generative_ai/chat_completions/chat_completions_test.py

Add chat completions credentials refresher code sample

---

appengine/flexible_python37_and_earlier/tasks/snippets.py

Fixes b/257989818
Snippet tracker tool is unable to disambiguate between multiple implementations of Python region tags
- [x ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [x ] Please **merge** this PR for me once it is approved

docs: Remove duplicate region tags

---

batch/create/create_with_custom_status_events.py
batch/requirements.txt
batch/tests/test_basics.py

- Added `create_with_custom_status_events.py` new script to create jobs with custom events to describe job's runnables.
- Modified `test_basics.py` to include tests for creating job with custom status events

feat: Batch create job with custom status events sample

---

generative_ai/gemini_tuning.py

Add adapter_size in the advanced example

---

generative_ai/imagen/generate_image.py

This change updates the generate image code sample to use the latest Imagen 3 model.

chore: update imagen model to latest version

---

video/stitcher/create_vod_config.py
video/stitcher/delete_vod_config.py
video/stitcher/get_vod_config.py
video/stitcher/list_vod_configs.py
video/stitcher/requirements.txt
video/stitcher/update_vod_config.py
video/stitcher/utils.py
video/stitcher/vod_config_test.py
video/stitcher/vod_session_test.py

docs(samples): add samples for VOD config

---

generative_ai/anthropic_claude_3_streaming.py
generative_ai/anthropic_claude_3_tool_use.py
generative_ai/anthropic_claude_3_unary.py
generative_ai/chat.py
generative_ai/code_chat.py
generative_ai/code_completion_function.py
generative_ai/code_generation_function.py
generative_ai/distillation.py
generative_ai/embedding.py
generative_ai/embedding_model_tuning.py
generative_ai/evaluate_model.py
generative_ai/grounding.py
generative_ai/ideation.py
generative_ai/list_tuned_models.py
generative_ai/multimodal_embedding_image.py
generative_ai/multimodal_embedding_image_video_text.py
generative_ai/multimodal_embedding_video.py
generative_ai/streaming_text.py
generative_ai/tune_code_generation_model.py
generative_ai/tuning.py

Preferred prefix for region tags is `generativeaionvertexai_`.

chore: cleanup unused region tags

---

compute/client_library/requirements-test.txt
compute/client_library/requirements.txt

docs(compute): Updating packages

---

generative_ai/embedding_batch.py
generative_ai/embedding_batch_test.py

Add Batch Text Embeddings Sample for docs page https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/batch-prediction-genai-embeddings

samples(generative-ai): Add Batch Embeddings Sample

---

discoveryengine/documents_sample_test.py
discoveryengine/import_documents_sample.py
discoveryengine/requirements.txt

To be added to https://cloud.google.com/generative-ai-app-builder/docs/create-data-store-es

samples(discoveryengine): Add AlloyDB Import Sample

---

.github/CODEOWNERS

feat: added secret manager team in codeowners

---

secretmanager/snippets/create_secret_with_labels.py
secretmanager/snippets/create_update_secret_label.py
secretmanager/snippets/delete_secret_label.py
secretmanager/snippets/list_secret_labels.py
secretmanager/snippets/snippets_test.py
secretmanager/snippets/view_secret_labels.py

feat: added Samples for labels

---

jobs/v3/api_client/custom_attribute_sample.py

fix(jobs): updating region_tag with product prefix

---

cloud_tasks/http_queues/send_task_to_http_queue.py

Per b/357452986
Fixes b/357452986
- [ x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ x] Please **merge** this PR for me once it is approved

docs: Fix comment

---

speech/snippets/transcribe_batch_dynamic_batching_v2.py
speech/snippets/transcribe_batch_dynamic_batching_v2_test.py
speech/snippets/transcribe_batch_gcs_input_gcs_output_v2.py
speech/snippets/transcribe_batch_gcs_input_gcs_output_v2_test.py
speech/snippets/transcribe_batch_gcs_input_inline_output_v2.py
speech/snippets/transcribe_batch_gcs_input_inline_output_v2_test.py
speech/snippets/transcribe_batch_multiple_files_v2.py
speech/snippets/transcribe_batch_multiple_files_v2_test.py
speech/snippets/transcribe_chirp_auto_detect_language.py
speech/snippets/transcribe_chirp_auto_detect_language_test.py

Samples placed here:
1. transcribe_batch_dynamic_batching_v2.py
2. transcribe_batch_gcs_input_gcs_output_v2.py
3. transcribe_batch_gcs_input_inline_output_v2.py
4. transcribe_batch_multiple_files_v2.py
5. transcribe_chirp_auto_detect_language.py

Simplified 5 speech samples (set-1)

---

generative_ai/gemini_safety_config_example.py

Removed GenerationConfig settings that are unrelated to safety

---

discoveryengine/create_data_store_sample.py
discoveryengine/create_engine_sample.py
discoveryengine/data_store_sample_test.py
discoveryengine/documents_sample_test.py
discoveryengine/get_data_store_sample.py
discoveryengine/import_documents_sample.py
discoveryengine/list_data_stores_sample.py
discoveryengine/purge_documents_sample.py
discoveryengine/requirements.txt
discoveryengine/site_search_engine_sample.py
documentai/snippets/batch_process_documents_sample.py
documentai/snippets/evaluate_processor_version_sample.py

- Change default behavior for GCS Import to be Unstructured PDFs (Users reported confusion)
- Add get/list data store samples
- Add purge data store sample

samples(discoveryengine): Updates to VAIS Data Store Samples

---

webrisk/snippets/submit_uri.py
webrisk/snippets/test_basic_samples.py

Fix: Changes Submission API Code Sample to use LRO id.

---

generative_ai/chat_completions/chat_completions_credentials_refresher.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_tuning.py
generative_ai/ideation.py
generative_ai/inference/non_stream_multimodality_basic.py
generative_ai/inference/non_stream_text_basic.py
generative_ai/inference/stream_text_basic.py
generative_ai/multimodal_embedding_image_video_text.py
generative_ai/multimodal_embedding_video.py
generative_ai/tune_code_generation_model.py
generative_ai/tune_code_generation_model_test.py
generative_ai/tuning.py

* **generativeaionvertexai_tuning_basic**
+ Put `LOCATION` variable
* **generativeaionvertexai_tuning_advanced**
+ Put `LOCATION` variable
* **generativeaionvertexai_get_tuning_job**
+ Here we have [hidden variable](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/a1cd10e287a60edd811883f20bc67c4b436f34cb/generative_ai/gemini_tuning.py#L98) `tuning_job_id = "4982013113894174720"` in `generative_ai/gemini_tuning.py`. Should we add some comments?
* **enerativeaionvertexai_cancel_tuning_job**
+ Here we have [hidden variable](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/a1cd10e287a60edd811883f20bc67c4b436f34cb/generative_ai/gemini_tuning.py#L134) `tuning_job_id = "4982013113894174720"` in `generative_ai/gemini_tuning.py`. Should we add some comments?
* …

refactor(generative_ai): Reduced hidden variables and refactored code

---

speech/snippets/transcribe_async_gcs_test.py
speech/snippets/transcribe_chirp.py
speech/snippets/transcribe_chirp_test.py
speech/snippets/transcribe_context_classes.py
speech/snippets/transcribe_diarization_gcs_beta.py
speech/snippets/transcribe_enhanced_model.py
speech/snippets/transcribe_enhanced_model_test.py
speech/snippets/transcribe_multilanguage_gcs_beta.py
speech/snippets/transcribe_multilanguage_gcs_beta_test.py

Simplified speech samples (set-2)

---

generative_ai/anthropic_claude_3_streaming.py
generative_ai/anthropic_claude_3_streaming_test.py
generative_ai/anthropic_claude_3_tool_use.py
generative_ai/anthropic_claude_3_tool_use_test.py
generative_ai/anthropic_claude_3_unary.py
generative_ai/anthropic_claude_3_unary_test.py
generative_ai/chat.py
generative_ai/chat_completions/chat_completions_credentials_refresher.py
generative_ai/code_chat.py
generative_ai/code_chat_test.py
generative_ai/code_generation_function.py
generative_ai/code_generation_function_test.py
generative_ai/code_generation_unittest.py
generative_ai/code_generation_unittest_test.py
generative_ai/distillation.py
generative_ai/distillation_test.py
generative_ai/gemini_safety_config_example.py

| File 	| Comments 	|
|---	|---	|
| anthropic_claude_3_streaming.py 	| Updated PROJECT_ID variable. Hadrcode Location "us-east5" 	|
| anthropic_claude_3_tool_use.py 	| Updated PROJECT_ID variable. Hadrcode Location "us-east5" 	|
| anthropic_claude_3_unary.py 	| Updated PROJECT_ID variable. Hadrcode Location "us-east5" 	|
| chat.py 	| Just added if name == main 	|
| code_chat.py 	| Remove the temperature parameter 	|
| code_generation_function.py 	| Remove the temperature parameter 	|
| code_generation_unittest.py 	| Remove the temperature parameter 	|
| distillation.py 	| Made refactoring. Remove useless parametres. Update docstring 	|

refactor(generative_ai): Reduced hidden variables and refactored code (set-1)

---

generative_ai/multimodal_embedding_image.py
generative_ai/multimodal_embedding_image_video_text.py
generative_ai/multimodal_embedding_video.py
generative_ai/rag.py
generative_ai/rag_test.py
generative_ai/sentiment_analysis.py
generative_ai/sentiment_analysis_test.py
generative_ai/streaming_chat.py
generative_ai/streaming_chat_test.py
generative_ai/streaming_code.py
generative_ai/streaming_code_test.py
generative_ai/streaming_codechat.py
generative_ai/streaming_codechat_test.py
generative_ai/streaming_text.py
generative_ai/streaming_text_test.py
generative_ai/summarization.py
generative_ai/summarization_test.py
generative_ai/tune_code_generation_model.py
generative_ai/tune_code_generation_model_test.py
generative_ai/tuning.py

Refactored GenAI Samples. Removed arguments and added/clarified comments. 
**Major changes:**
`tuning.py` -> Removed `credentials` variable. Using credentials is optional because the Google Cloud SDK and Python libraries use the default credentials configured in your environment. 

refactor(generative_ai): (set-4) Refactored GenAI Samples

---

generative_ai/controlled_generation/controlled_generation_test.py
generative_ai/controlled_generation/response_schema.py

update controlled generation
https://b.corp.google.com/issues/355233528

feat(generativeai): update controlled generation

---

generative_ai/gemini_reasoning_engine.py

adding cloud pickle in requirements 

---

secretmanager/snippets/regional_samples/create_regional_secret.py
secretmanager/snippets/regional_samples/delete_regional_secret.py
secretmanager/snippets/regional_samples/get_regional_secret.py
secretmanager/snippets/regional_samples/regional_quickstart.py
secretmanager/snippets/regional_samples/snippets_test.py
secretmanager/snippets/regional_samples/update_regional_secret.py
secretmanager/snippets/requirements.txt

fix:added regional samples for SM

---

secretmanager/snippets/regional_samples/access_regional_secret_version.py
secretmanager/snippets/regional_samples/add_regional_secret_version.py
secretmanager/snippets/regional_samples/create_regional_secret.py
secretmanager/snippets/regional_samples/delete_regional_secret.py
secretmanager/snippets/regional_samples/destroy_regional_secret_version.py
secretmanager/snippets/regional_samples/disable_regional_secret_version.py
secretmanager/snippets/regional_samples/enable_regional_secret_version.py
secretmanager/snippets/regional_samples/get_regional_secret.py
secretmanager/snippets/regional_samples/get_regional_secret_version.py
secretmanager/snippets/regional_samples/regional_quickstart.py
secretmanager/snippets/regional_samples/snippets_test.py
secretmanager/snippets/regional_samples/update_regional_secret.py

Regional samples 2

---

secretmanager/snippets/regional_samples/access_regional_secret_version.py
secretmanager/snippets/regional_samples/add_regional_secret_version.py
secretmanager/snippets/regional_samples/create_regional_secret.py
secretmanager/snippets/regional_samples/delete_regional_secret.py
secretmanager/snippets/regional_samples/delete_regional_secret_with_etag.py
secretmanager/snippets/regional_samples/destroy_regional_secret_version.py
secretmanager/snippets/regional_samples/destroy_regional_secret_version_with_etag.py
secretmanager/snippets/regional_samples/disable_regional_secret_version.py
secretmanager/snippets/regional_samples/disable_regional_secret_version_with_etag.py
secretmanager/snippets/regional_samples/enable_regional_secret_version.py
secretmanager/snippets/regional_samples/enable_regional_secret_version_with_etag.py
secretmanager/snippets/regional_samples/get_regional_secret.py
secretmanager/snippets/regional_samples/get_regional_secret_version.py
secretmanager/snippets/regional_samples/regional_quickstart.py
secretmanager/snippets/regional_samples/snippets_test.py
secretmanager/snippets/regional_samples/update_regional_secret.py
secretmanager/snippets/regional_samples/update_regional_secret_with_etag.py

Regional samples 3

---

generative_ai/embedding_preview.py
generative_ai/embedding_test.py

fix: Text-Embedding Model Serving demo.

---

speech/snippets/transcribe.py
speech/snippets/transcribe_multichannel.py
speech/snippets/transcribe_multichannel_v2.py
speech/snippets/transcribe_multichannel_v2_test.py
speech/snippets/transcribe_multiple_languages_v2.py
speech/snippets/transcribe_multiple_languages_v2_test.py
speech/snippets/transcribe_override_recognizer.py
speech/snippets/transcribe_override_recognizer_test.py
speech/snippets/transcribe_profanity_filter_v2.py
speech/snippets/transcribe_profanity_filter_v2_test.py
speech/snippets/transcribe_reuse_recognizer.py
speech/snippets/transcribe_reuse_recognizer_test.py

Simplified speech samples (set-4)

---

generative_ai/inference/stream_multimodality_basic.py
generative_ai/inference/stream_text_basic.py

Adding "TO DO" for variables

---

generative_ai/code_generation_unittest_test.py
generative_ai/context_caching/context_caching_test.py
generative_ai/context_caching/create_context_cache.py
generative_ai/controlled_generation/response_schema.py
generative_ai/embedding_preview.py
generative_ai/gemini_rapid_evaluation.py
generative_ai/requirements.txt

For context caching - create code samples, updating the sample arguments to use `display_name`. This is a newly added SDK feature.
Fixes: [b/357634471](http://b/357634471), [b/362459779](http://b/362459779)
A few lint updates are added by Owlbot.

chore(generativai):  Update create code samples to include `display_name`

---

generative_ai/controlled_generation/response_schema.py
generative_ai/gemini_pdf_example.py
generative_ai/gemini_pro_basic_example.py
generative_ai/gemini_pro_config_example.py
generative_ai/gemini_rapid_evaluation.py
generative_ai/gemini_safety_config_example.py
generative_ai/gemini_single_turn_video_example.py
generative_ai/gemini_system_instruction.py
generative_ai/gemini_text_input_example.py
generative_ai/list_tuned_code_generation_models.py
generative_ai/list_tuned_models.py

* update examples for controlled generation
* add new eval metric to eval example
* for eligible snippets add conditional statment to run the snippets in CLI
Fixes b/362459779 - comment4

chore(generativeai): multiple minor changes

---

batch/create/create_with_specific_network.py
batch/tests/test_basics.py

feat: Create Batch job with custom network sample

---

secretmanager/snippets/regional_samples/iam_grant_access_with_regional_secret.py
secretmanager/snippets/regional_samples/iam_revoke_access_with_regional_secret.py
secretmanager/snippets/regional_samples/snippets_test.py

fix:regional samples for SM

---

generative_ai/gemini_rapid_evaluation.py
generative_ai/rag.py

fix(generative-ai): Update comment in RAG API samples to specify optional

---

generative_ai/gemini_grounding_example.py
generative_ai/gemini_rapid_evaluation.py
generative_ai/requirements.txt
generative_ai/test_gemini_examples.py

- https://github.com/googleapis/python-aiplatform/releases/tag/v1.64.0

docs(samples): Update Vertex AI Gemini Grounding with new syntax from v1.64.0

---

appengine/flexible/django_cloudsql/requirements.txt
appengine/flexible/hello_world_django/requirements.txt
appengine/flexible_python37_and_earlier/django_cloudsql/requirements.txt
appengine/flexible_python37_and_earlier/hello_world_django/requirements.txt
appengine/standard_python3/bundled-services/blobstore/django/requirements.txt
appengine/standard_python3/bundled-services/deferred/django/requirements.txt
appengine/standard_python3/bundled-services/mail/django/requirements.txt
appengine/standard_python3/django/requirements.txt
kubernetes_engine/django_tutorial/requirements.txt
run/django/requirements.txt

Replaces #12555 
Updates Django to latest patch release within the context of the supplied `python_version`.

chore(deps): update django

---

batch/create/create_with_allocation_policy_labels.py
batch/create/create_with_job_labels.py
batch/create/create_with_runnables_labels.py
batch/tests/test_basics.py

feat: Batch created job with custom labels. 3 new samples

---

secretmanager/snippets/regional_samples/get_regional_secret_version.py
secretmanager/snippets/regional_samples/iam_grant_access_with_regional_secret.py
secretmanager/snippets/regional_samples/iam_revoke_access_with_regional_secret.py
secretmanager/snippets/regional_samples/list_regional_secret_versions.py
secretmanager/snippets/regional_samples/list_regional_secret_versions_with_filter.py
secretmanager/snippets/regional_samples/list_regional_secrets.py
secretmanager/snippets/regional_samples/list_regional_secrets_with_filter.py
secretmanager/snippets/regional_samples/snippets_test.py

fix(secretmanager): add new regional samples

---

storage/cost-analysis/storage_soft_delete_relative_cost_analyzer.py

Fixing run time error with return type

soft-delete-cost-analysis: fixing return type

---

generative_ai/extensions/create_example.py
generative_ai/extensions/delete_example.py
generative_ai/extensions/execute_example.py
generative_ai/extensions/extensions_test.py
generative_ai/extensions/get_example.py
generative_ai/extensions/list_example.py
generative_ai/gemini_extensions.py
generative_ai/gemini_extensions_test.py

|  Region Tag	| Old file | New File  	| 
|---					|---			|---				|
|		generativeaionvertexai_delete_extension		|	gemini_extensions.py	|	delete_example.py	|
|		generativeaionvertexai_create_extension		|	gemini_extensions.py	|	create_example.py	|
|		generativeaionvertexai_execute_extension		|	gemini_extensions.py	|	execute_example.py	|
|		generativeaionvertexai_get_extension		|	gemini_extensions.py	|	get_example.py	|
|		generativeaionvertexai_list_extensions		|	gemini_extensions.py	|	list_example.py	|
❗**Files need to be deleted after approval:**
`generative_ai/gemini_extensions.py`
`generative_ai/gemini_extensions_test.py`

refactor: (GenAI) Reorganized Extensions Samples (Group A)

---

generative_ai/controlled_generation/controlled_generation_test.py
generative_ai/controlled_generation/example_01.py
generative_ai/controlled_generation/example_02.py
generative_ai/controlled_generation/example_03.py
generative_ai/controlled_generation/example_04.py
generative_ai/controlled_generation/example_05.py
generative_ai/controlled_generation/example_06.py
generative_ai/controlled_generation/example_07.py
generative_ai/controlled_generation/response_mime_type.py
generative_ai/controlled_generation/response_schema.py

Reorganized Controlled Generation Samples.
1. Moved each `generate_content` function with region tags into separate files.
2. Rewrote tests
|   Region Tag	| Old file   	| New File  	| 
|---	|---	|---	|
|   generativeaionvertexai_gemini_controlled_generation_response_schema	|   response_schema.py	|   example_01.py	| 
|   generativeaionvertexai_gemini_controlled_generation_response_schema_2	|   response_schema.py	|   example_02.py	|
|   generativeaionvertexai_gemini_controlled_generation_response_schema_3	|   response_schema.py	|   example_03.py	| 
|   generativeaionvertexai_gemini_controlled_generation_response_schema_4	|   response_schema.py	|   example_04.py	| 
|   generativeaionvertexai_gemini_controlled_generation_response_mime_type	|   response_mime_type.py	|   example_05.py	|
| …

refactor: (GenAI) Reorganized Controlled Generation Samples (Group A)

---

generative_ai/classify_news_items.py
generative_ai/context_caching/context_caching_test.py
generative_ai/context_caching/create_context_cache.py
generative_ai/context_caching/delete_context_cache.py
generative_ai/context_caching/get_context_cache.py
generative_ai/context_caching/update_context_cache.py
generative_ai/context_caching/use_context_cache.py

I have modified the following files:
- `create_context_cache.py`
- `delete_context_cache.py`
- `get_context_cache.py`
- `update_context_cache.py`
- `use_context_cache.py`
❓However, as a developer and user, I can not find a single file `list_context_cache.py`
❗I have begun developing this file, but I have encountered an issue: the method required for listing context caches is not yet implemented and cannot be used. I have detailed the problem in the attached [document](https://docs.google.com/document/d/1AvNZYbIhrxO414CmPFRbyL24f-3fpncZQOOaaGy-Kcg/edit?usp=sharing).
Proposed region_tag: `generativeaionvertexai_gemini_list_context_cache`
Could you please review the issue and prioritize the implementation of this method? Having this method available would greatly facilitate the development …

refactor: (GenAI) Improved Context Cache Samples (Group A)

---

composer/tools/composer_dags.py

updates to list manipulation to ignore the header

---

speech/snippets/transcribe_feature_in_recognizer.py
speech/snippets/transcribe_feature_in_recognizer_test.py
speech/snippets/transcribe_file_v2.py
speech/snippets/transcribe_file_v2_test.py
speech/snippets/transcribe_gcs_v2.py
speech/snippets/transcribe_gcs_v2_test.py
speech/snippets/transcribe_model_selection.py
speech/snippets/transcribe_model_selection_test.py
speech/snippets/transcribe_model_selection_v2.py
speech/snippets/transcribe_model_selection_v2_test.py
speech/snippets/transcribe_multichannel_v2_test.py

Simplified next set of Speech Samples (set-3)

---

generative_ai/system_instructions/system_instructions_example.py
generative_ai/system_instructions/system_instructions_example_test.py

Created a new folder: `/generative_ai/system_instructions/`
| Region_tag                                            | New file                          |
|-------------------------------------------------------|-----------------------------------|
| generativeaionvertexai_gemini_system_instruction  | system_instructions_example.py         |
**❗Actions after approval:**
- Delete file `/generative_ai/gemini_system_instruction.py`
- Delete [test_set_system_instruction](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/302a01cefced5764cf271a40443bb0173d3f29f3/generative_ai/test_gemini_examples.py#L165-L167) test in `/generative_ai/test_gemini_examples.py`

refactor: (GenAI) Reorganized System Instructions Sample (Group C)

---

generative_ai/safety/safety_config_example.py
generative_ai/safety/safety_config_example_test.py

Created new folder: `/generative_ai/safety`
| Region_tag                                    | New file                      |
|-----------------------------------------------|-------------------------------|
| generativeaionvertexai_gemini_safety_settings    | safety_config_example.py    |
❗**Actions after approval:**
Delete following file: `/generative_ai/gemini_safety_config_example.py`
Delete [following test](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/1e214f288dc6bc5b0964d8bb03938f9d791c6218/generative_ai/test_gemini_examples.py#L96C1-L100C1) in /generative_ai/test_gemini_examples.py

refactor: (GenAI) Reorganized Safety Sample (Group С)   

---

generative_ai/chat_completions/chat_completions_function_calling_basic.py
generative_ai/chat_completions/chat_completions_function_calling_config.py
generative_ai/chat_completions/chat_completions_test.py
generative_ai/function_calling.py
generative_ai/function_calling/advanced_example.py
generative_ai/function_calling/basic_example.py
generative_ai/function_calling/chat_example.py
generative_ai/function_calling/chat_function_calling_basic.py
generative_ai/function_calling/chat_function_calling_config.py
generative_ai/function_calling/chat_function_calling_test.py
generative_ai/function_calling/examples_function_calling_test.py
generative_ai/function_calling/function_calling_test.py
generative_ai/function_calling_chat.py
generative_ai/function_calling_chat_test.py
generative_ai/function_calling_test.py

| Region_tag                                                   | Old file                                                | New file                   |
|--------------------------------|----------------------------------|----------------|
| generativeaionvertexai_gemini_function_calling_chat                    | function_calling_chat.py                                     | chat_example.py                 |
| generativeaionvertexai_gemini_function_calling_advanced                | function_calling.py                                          | advanced_example.py             |
| generativeaionvertexai_gemini_function_calling                         | function_calling.py                                          | basic_example.py                |
| …

refactor: (GenAI) Reorganized Function calling Samples (Group A) 

---

generative_ai/batch_predict/gemini_batch_predict.py
generative_ai/batch_predict/test_batch_predict.py

adding batch gemini predict sample

---

appengine/standard_python3/hello_world/app.yaml

updating to python 312 for the basic hello world

chore(gae): update hello world to the latest python runtime

---

securitycenter/snippets_v2/mute_findings_v2.py
securitycenter/snippets_v2/mute_findings_v2_test.py
securitycenter/snippets_v2/noxfile_config.py
securitycenter/snippets_v2/requirements.txt
securitycenter/snippets_v2/snippets_bigquery_export_v2.py
securitycenter/snippets_v2/snippets_bigquery_export_v2_test.py
securitycenter/snippets_v2/snippets_findings_v2.py
securitycenter/snippets_v2/snippets_findings_v2_test.py
securitycenter/snippets_v2/snippets_mute_config_v2.py
securitycenter/snippets_v2/snippets_mute_config_v2_test.py
securitycenter/snippets_v2/snippets_notification_configs_v2.py
securitycenter/snippets_v2/snippets_notification_v2_test.py
securitycenter/snippets_v2/snippets_security_marks_v2.py
securitycenter/snippets_v2/snippets_security_marks_v2_test.py

This is the Lint changes PR that needs to be merged prior to the #12609 as per the chat [conversation](https://chat.google.com/room/AAAAryfZp6g/7iWQzVWqJxg/7iWQzVWqJxg?cls=10). 

Lint changes PR 

---

generative_ai/extensions/extensions_test.py
generative_ai/extensions/list_example.py

feat(generative_ai): minor code update to extensions list sample

---

dataflow/flex-templates/pipeline_with_dependencies/README.md

Remove an extraneous command from README.md

---

secretmanager/snippets/regional_samples/create_regional_secret_with_labels.py
secretmanager/snippets/regional_samples/create_update_regional_secret_label.py
secretmanager/snippets/regional_samples/delete_regional_secret_label.py
secretmanager/snippets/regional_samples/edit_regional_secret_label.py
secretmanager/snippets/regional_samples/get_regional_secret.py
secretmanager/snippets/regional_samples/snippets_test.py
secretmanager/snippets/regional_samples/view_regional_secret_labels.py
secretmanager/snippets/view_secret_labels.py

feat:added samples for labels, regional SM

---

generative_ai/model_garden/claude_3_streaming_example.py
generative_ai/model_garden/test_model_garden_examples.py

claude_3_streaming_example was temporarily uncomment due to long delays in tests.
Fixes: [b/374363762](http://b/374363762)

feat(generative-ai): update claude_3_streaming_example.py

---

generative_ai/batch_predict/gemini_batch_predict_gcs.py
generative_ai/batch_predict/noxfile_config.py
generative_ai/batch_predict/test_batch_predict_examples.py

feat(generative-ai): Update to gemini_batch_predict gcs specific

---

generative_ai/README.md
generative_ai/template_folder/advanced_example.py
generative_ai/template_folder/noxfile_config.py
generative_ai/template_folder/requirements-test.txt
generative_ai/template_folder/requirements.txt
generative_ai/template_folder/simple_example.py
generative_ai/template_folder/test_template_folder_examples.py

All readme pages for Generative_AI folder along with a style guide & example folder template.
I'm also working on a new `StyleGuide` and `NamingFormats` for GenAI code samples. Publishing these changes first.

docs: Generative ai docs

---

generative_ai/batch_predict/gemini_batch_predict_gcs.py
generative_ai/batch_predict/requirements.txt

Fixes b/376144913: Allow BatchPredictionJob in GA namespace, i.e., from vertexai.batch_prediction import BatchPredictionJob

feat: from vertexai.batch_prediction import BatchPredictionJob

---

generative_ai/batch_predict/gemini_batch_predict_bigquery.py
generative_ai/batch_predict/gemini_batch_predict_gcs.py

feat(genai): Updates to comments

---

generative_ai/context_caching/list_context_caches.py
generative_ai/context_caching/test_context_caching.py

Fixes a small typo in the function name

fix: typo in list_context_caches function name

---

discoveryengine/answer_query_sample.py

docs(samples): VAIS Answer - Add comment describing that all options are included by default

---

generative_ai/model_garden/claude_3_streaming_example.py
generative_ai/model_garden/claude_3_tool_example.py
generative_ai/model_garden/claude_3_unary_example.py

feat: add support for claude-3-5-sonnet-v2@20241022

---

generative_ai/understand_audio/requirements.txt
generative_ai/understand_audio/transcription_example.py

Fixes [b_367786718](http://b/367786718)

feat(generative-ai): Update audio example to use audio_timestamp config

---

managedkafka/snippets/clusters/create_cluster.py

Fix: network_configs assignment

---

dataplex/snippets/create_entry_group.py
dataplex/snippets/create_entry_type.py
dataplex/snippets/delete_entry_group.py
dataplex/snippets/delete_entry_type.py
dataplex/snippets/entry_group_test.py
dataplex/snippets/entry_type_test.py
dataplex/snippets/get_entry_group.py
dataplex/snippets/get_entry_type.py
dataplex/snippets/list_entry_groups.py
dataplex/snippets/list_entry_types.py
dataplex/snippets/noxfile_config.py
dataplex/snippets/update_entry_group.py
dataplex/snippets/update_entry_type.py

feat(dataplex): add code samples for Entry Types and Groups

---

generative_ai/batch_predict/batch_code_predict.py
generative_ai/batch_predict/batch_text_predict.py

Renamed 2 region_tags in GenAI folder in accordance with standards and general regulations
`aiplatform_batch_code_predict` -> `generativeaionvertexai_batch_code_predict`
`aiplatform_batch_text_predict` -> `generativeaionvertexai_batch_text_predict`

Renamed 2 region tags

---

dataplex/snippets/create_entry.py
dataplex/snippets/delete_entry.py
dataplex/snippets/entry_test.py
dataplex/snippets/get_entry.py
dataplex/snippets/list_entries.py
dataplex/snippets/lookup_entry.py
dataplex/snippets/update_entry.py

feat(dataplex): add code samples for Entries

---

texttospeech/snippets/requirements.txt
texttospeech/snippets/synthesize_speech_multiple_speakers.py
texttospeech/snippets/synthesize_speech_multiple_speakers_test.py

- https://cloud.google.com/text-to-speech/docs/create-dialogue-with-multispeakers

feat(texttospeech): Create sample for Synthesize speech multiple speakers

---

dataplex/snippets/search_entries.py
dataplex/snippets/search_entries_test.py

feat(dataplex): add code samples for Search Entries

---

dataplex/snippets/create_aspect_type.py
dataplex/snippets/create_entry_group.py
dataplex/snippets/create_entry_type.py
dataplex/snippets/delete_aspect_type.py
dataplex/snippets/delete_entry_group.py
dataplex/snippets/delete_entry_type.py
dataplex/snippets/get_aspect_type.py
dataplex/snippets/get_entry_group.py
dataplex/snippets/get_entry_type.py
dataplex/snippets/list_aspect_types.py
dataplex/snippets/list_entry_groups.py
dataplex/snippets/list_entry_types.py
dataplex/snippets/update_aspect_type.py
dataplex/snippets/update_entry_group.py
dataplex/snippets/update_entry_type.py

feat(dataplex): change method comments into docstrings

---

discoveryengine/requirements.txt
discoveryengine/search_lite_sample.py
discoveryengine/search_lite_sample_test.py
discoveryengine/search_sample.py
discoveryengine/search_sample_test.py

https://cloud.google.com/generative-ai-app-builder/docs/preview-search-results#web-api-key

docs(samples): Added Vertex AI Search "lite" method sample

---

discoveryengine/search_sample.py
discoveryengine/train_custom_model_sample.py
discoveryengine/train_custom_model_sample_test.py
discoveryengine/update_serving_config_sample.py
discoveryengine/update_serving_config_sample_test.py

https://cloud.google.com/generative-ai-app-builder/docs/tune-search

docs(discoveryengine): Add Search Tuning Samples

---

jobs/v3/api_client/auto_complete_sample.py

chore(job): migrate region step 1 - add new region job_auto_complete_job_title

---

dataflow/flex-templates/getting_started/requirements.txt

Replaces #12798 
Fixes #12797 

chore(dataflow): bump version to resolve dependency error

---

generative_ai/model_tuning/supervised_advanced_example.py

Update supervised_advanced_example.py to support byosa and cmek

---

jobs/v3/api_client/auto_complete_sample.py
jobs/v3/api_client/base_company_sample.py
jobs/v3/api_client/base_job_sample.py
jobs/v3/api_client/batch_operation_sample.py
jobs/v3/api_client/commute_search_sample.py
jobs/v3/api_client/custom_attribute_sample.py

Impacted files:
auto_complete_sample.py
base_company_sample.py
base_job_sample.py
batch_operation_sample.py
commute_search_sample.py
custom_attribute_sample.py
b/347825711
b/347350180
b/347350613
b/347350711
b/347826174
b/347825723
b/347825628
b/347825736
b/347350260
b/347350552
b/347350248
b/347350398

chore(job): migrate regions part 1 and delete region tag 'instantiate' for jobs/v3/api_client/

---

datastore/cloud-ndb/django_middleware.py

chore(datastore): migrate region step 1 - add new region datastore_ndb_django_middleware

---

endpoints/kubernetes/k8s-grpc-bookstore.yaml

chore(endpoints): add region tag endpoints_secret_1

---

kubernetes_engine/django_tutorial/polls.yaml

Fixes [b/347826199](http://b/347826199)

chore(gke): migrate region step 1 - update region kubernetes_deployment to gke_kubernetes_deployment

---

endpoints/kubernetes/k8s-grpc-bookstore.yaml

chore(endpoints): remove old region tag secrets-1

---

endpoints/getting-started/openapi-appengine.yaml

chore(endpoints): migrate regions in endpoints/getting-started/openapi-appengine.yaml

---

documentai/snippets/process_document_sample.py

chore(documentai): delete sample documentai_process_document_processor_version

---

jobs/v3/api_client/base_company_sample.py
jobs/v3/api_client/custom_attribute_sample.py

base_company_sample.py
b/347825736
b/347350613
b/347350711
b/347825723
b/347825736
b/347350260
custom_attribute_sample.py
b/347825777

chore(job): migrate regions step 3 - remove regions in base_company_sample.py & custom_attribute_sample.py

---

appengine/standard/iap/js/poll.js

- [X ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ X] Please **merge** this PR for me once it is approved

Update poll.js to include XML Header in fetch request

---

jobs/v3/api_client/histogram_sample.py
jobs/v3/api_client/quickstart.py

chore(job): fix regions in jobs/v3/api_client/ histogram_sample.py & quickstart.py

---

endpoints/getting-started/openapi-appengine.yaml

Fixes Internal: b/347826154
Follow-up of #13015

chore(endpoints): migration step 3 - remove old regions in openapi-appengine.yaml

---

appengine/standard/migration/ndb/redis_cache/main.py
appengine/standard/migration/ndb/redis_cache/requirements-test.txt

chore(gae): rename regions in migration/ndb/redis_cache/main.py

---

appengine/standard/images/api/blobstore.py
appengine/standard/images/api/main.py

chrore(gae): fix region tags for images thumbnailer in appengine/standard/images/api/

---

compute/encryption/generate_wrapped_rsa_key.py

Fixes Internal: b/389690705
Follow-up of b/280881053 & #10118

chore(compute): delete region 'all' in generate_wrapped_rsa_key.py

---

compute/metadata/main.py
compute/metadata/vm_identity.py
compute/metadata/vm_identity_test.py

chore(compute): migrate region tags step 1 in metadata (watch maintenance notices)

---

datalabeling/README.md

these samples were moved temporarily to the API repo and then moved back and the README didn't get updated.

fix: remove incorrect information for datalabeling/README.md

---

appengine/standard/ndb/overview/main.py
appengine/standard/ndb/overview/requirements-test.txt

chore(gae): migrate region tags step 1 - at standard/ndb/overview/main.py

---

appengine/standard/ndb/overview/main.py

chore(gae): migrate region tags step 3 - at standard/ndb/overview/main.py 

---

compute/metadata/main.py

chore(compute): migrate regions step 3 - delete old region tags from metadata/main.py

---

monitoring/api/v3/api-client/list_resources.py

chore(monitoring): delete region tag 'all' from monitoring/api/v3/api-client/list_resources.py

---

genai/template_folder/requirements.txt
generative_ai/batch_predict/requirements.txt
generative_ai/chat_completions/requirements.txt
generative_ai/context_caching/requirements.txt
generative_ai/controlled_generation/requirements.txt
generative_ai/embeddings/requirements.txt
generative_ai/evaluation/requirements.txt
generative_ai/extensions/requirements.txt
generative_ai/function_calling/requirements.txt
generative_ai/grounding/requirements.txt
generative_ai/image/requirements.txt
generative_ai/image_generation/requirements.txt
generative_ai/inference/requirements.txt
generative_ai/model_garden/requirements.txt
generative_ai/model_tuning/requirements.txt
generative_ai/openai/requirements.txt
generative_ai/prompts/requirements.txt
generative_ai/reasoning_engine/requirements.txt
generative_ai/safety/requirements.txt
generative_ai/system_instructions/requirements.txt
generative_ai/template_folder/requirements.txt
generative_ai/text_generation/requirements.txt
generative_ai/text_models/requirements.txt
generative_ai/token_count/requirements.txt
generative_ai/understand_audio/requirements.txt
generative_ai/understand_docs/requirements.txt
generative_ai/understand_video/requirements.txt
generative_ai/video/requirements.txt

chore(deps): update dependencies langchain-google-vertexai

---

generative_ai/grounding/requirements-test.txt
generative_ai/grounding/requirements.txt
generative_ai/grounding/web_example.py

Update for https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/ground-gemini#ground-to-search

docs(generative_ai): Update Grounding with Google Search sample to include dynamic retrieval

---

secretmanager/snippets/requirements.txt

See original issue https://github.com/googleapis/google-cloud-python/issues/13350 which has been addressed as of [proto-plus v1.26.0](https://github.com/googleapis/proto-plus-python/releases/tag/v1.26.0)

chore(deps): update protobuf in secretmanager/snippets/requirements.txt

---

run/django/cloudmigrate.yaml
run/hello-broken/Dockerfile
run/helloworld/Dockerfile
run/image-processing/Dockerfile

b/347349699
b/347350333
Follow-up of #4951

chore(cloudrun): migrate region tags for dockerfiles and yaml from run folder - part 1

---

generative_ai/chat_completions/chat_completions_authentication.py
generative_ai/chat_completions/chat_completions_credentials_refresher.py
generative_ai/chat_completions/chat_completions_non_streaming_image.py
generative_ai/chat_completions/chat_completions_non_streaming_text.py
generative_ai/chat_completions/chat_completions_non_streaming_text_self_deployed.py
generative_ai/chat_completions/chat_completions_streaming_image.py
generative_ai/chat_completions/chat_completions_streaming_text.py
generative_ai/chat_completions/chat_completions_streaming_text_self_deployed.py
generative_ai/chat_completions/chat_completions_test.py
generative_ai/chat_completions/requirements-test.txt
generative_ai/chat_completions/requirements.txt

- Fix imports (tests were failing)
- Add authentication sample
- Combine credentials refresher region tags
- Add samples for self-hosted models

docs(generative_ai): Update Chat Completions API samples

---

genai/express_mode/api_key_example.py
genai/express_mode/api_key_example_test.py
genai/express_mode/noxfile_config.py
genai/express_mode/requirements-test.txt
genai/express_mode/requirements.txt

New Sample for Gen AI SDK
https://cloud.google.com/vertex-ai/generative-ai/docs/start/express-mode/overview

docs(gen_ai): Add Vertex AI Express Mode Sample for Google Gen AI SDK

---

gemma2/gemma2_predict_gpu.py
gemma2/gemma2_predict_tpu.py
gemma2/gemma2_test.py

Copyright header - fixing the spell check. No code changes.

docs(gemma2): spell check fix

---

run/django/cloudmigrate.yaml
run/hello-broken/Dockerfile
run/helloworld/Dockerfile
run/image-processing/Dockerfile

b/347349699
b/347350333
Follow-up of #13095

chore(cloudrun): migrate region tags for dockerfiles and yaml from run folder - part 1 - step 3

---

generative_ai/image_generation/generate_image.py

Update code sample to latest Imagen model

feat: Imagen model update

---

appengine/flexible/README.md

docs(gae): [flexible] fix link to Python 3.7 code samples in README

---

appengine/standard/firebase/firenotes/backend/main.py
appengine/standard/firebase/firenotes/frontend/main.js
appengine/standard/firebase/firetactoe/firetactoe.py
appengine/standard/firebase/firetactoe/rest_api.py
appengine/standard/firebase/firetactoe/static/main.js

chore(gae): delete unused and add new region tags in 'standard/firebase' folder

---

appengine/standard_python3/pubsub/app.yaml
appengine/standard_python3/pubsub/main.py

chore(gae): fix region tags in standard_python3/pubsub/

---

appengine/standard_python3/pubsub/app.yaml
appengine/standard_python3/pubsub/main.py

chore(gae): delete old region tags in standard_python3/pubsub/

---

genai/text_generation/textgen_with_youtube_video.py

Fixes example response for the [textgen_with_youtube_video.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/genai/text_generation/textgen_with_youtube_video.py).
The example response in this sample was likely obtained from a different prompt or video (e.g., from the "_Write an advertising jingle ..._" example prompt).
The [source YT video](https://www.youtube.com/watch?v=3KtWfp0UopM) is about Google's "25 Years in Search", while the example response talks about a "_Lunchtime_" and "_Delicious Meals_".

fix(genai): fix example response to match model response

---

genai/controlled_generation/ctrlgen_with_enum_class_schema.py
genai/controlled_generation/ctrlgen_with_resp_schema.py
genai/controlled_generation/requirements.txt
genai/controlled_generation/test_controlled_generation_samples.py

- CtrlGen with Enum Class
- CtrlGen with Resp Schema
Added requirements.txt

feat(genai): Add new Controlled Generation samples

---

genai/live/live_with_txt.py
genai/live/noxfile_config.py
genai/live/requirements-test.txt
genai/live/requirements.txt
genai/live/test_live_samples.py

https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal-live-api

feat(genai): Add Sample for Multimodal Live API

---

generative_ai/chat_completions/chat_completions_credentials_refresher.py
generative_ai/chat_completions/chat_completions_non_streaming_image.py
generative_ai/chat_completions/chat_completions_non_streaming_text.py
generative_ai/chat_completions/chat_completions_streaming_image.py
generative_ai/chat_completions/chat_completions_streaming_text.py
generative_ai/chat_completions/requirements.txt

Update Chat Completions Samples to Gemini 2.0 Flash GA

chore(generative-ai): Update Chat Completions Samples to Gemini 2.0 Flash GA

---

genai/text_generation/test_text_generation.py
genai/text_generation/textgen_with_pdf.py

- Changed to a basic Doc Summarization example instead of reading code from PDF.

feat(genai): Update Text Generation with PDF Sample

---

datacatalog/README.md

chore(datacatalog): add information about deprecation of Data Catalog

---

genai/embeddings/embed_content_text.py
genai/embeddings/embeddings_docretrieval_with_txt.py
genai/embeddings/noxfile_config.py
genai/embeddings/requirements-test.txt
genai/embeddings/requirements.txt
genai/embeddings/test_embeddings_examples.py

https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings

docs(genai): Text Embedding Sample for Gen AI SDK

---

genai/bounding_box/boundingbox_with_txt_img.py
genai/bounding_box/noxfile_config.py
genai/bounding_box/requirements-test.txt
genai/bounding_box/requirements.txt
genai/bounding_box/test_bounding_box_examples.py

https://cloud.google.com/vertex-ai/generative-ai/docs/bounding-box-detection

docs(genai): Add Bounding Box Sample for Gen AI SDK

---

datastore/cloud-ndb/django_middleware.py

chore(datastore): migrate region tag step 3 - delete region tag 'ndb_django_middleware'

---

appengine/standard/modules/main.py

chore(gae): rename and delete region tags in standard/modules

---

appengine/standard/ndb/async/shopping_cart.py
appengine/standard/ndb/properties/snippets.py
appengine/standard/ndb/queries/snippets.py
appengine/standard/ndb/transactions/main.py
appengine/standard/ndb/transactions/requirements-test.txt

chore(gae): rename and delete region tags in standard/ndb/

---

genai/text_generation/requirements.txt
genai/text_generation/textgen_chat_with_txt.py
genai/tools/requirements.txt
genai/tools/tools_code_exec_with_txt.py
genai/tools/tools_code_exec_with_txt_local_img.py

https://github.com/googleapis/python-genai/releases/tag/v1.3.0
Update `genai/text_generation/textgen_chat_with_txt.py` to use `UserContent` and `ModelContent`
Update `genai/tools/tools_code_exec_with_txt.py` and `genai/tools/tools_code_exec_with_txt_local_img.py` to use `response.executable_code` and `response.code_execution_result`

chore(genai): Update Chat and Code Exec Samples for 1.3.0 SDK Update

---

genai/video_generation/noxfile_config.py
genai/video_generation/requirements-test.txt
genai/video_generation/requirements.txt
genai/video_generation/test_video_generation_examples.py
genai/video_generation/videogen_with_txt.py

https://cloud.google.com/vertex-ai/generative-ai/docs/video/generate-videos

docs(genai): Add Veo Generation Sample

---

genai/provisioned_throughput/noxfile_config.py
genai/provisioned_throughput/provisioned_throughput_with_txt.py
genai/provisioned_throughput/provisionedthroughput_with_txt.py
genai/provisioned_throughput/requirements-test.txt
genai/provisioned_throughput/requirements.txt
genai/provisioned_throughput/test_provisioned_throughput_examples.py
generative_ai/provisioned_throughput/noxfile_config.py
generative_ai/provisioned_throughput/provisioned_throughput_with_txt.py
generative_ai/provisioned_throughput/requirements-test.txt
generative_ai/provisioned_throughput/requirements.txt
generative_ai/provisioned_throughput/test_provisioned_throughput_examples.py

https://cloud.google.com/vertex-ai/generative-ai/docs/use-provisioned-throughput

docs(genai): Add Provisioned Throughput samples for Gen AI SDK and Vertex AI SDK

---

.github/CODEOWNERS

Fixes errors in CODEOWNERS file. Also misc lint
Uses cloud-samples-infra in lieu of another temporary owner.

fix: update CODEOWNER for practice-folder

---

generative_ai/model_tuning/supervised_advanced_example.py
generative_ai/model_tuning/supervised_example.py

Update tuning examples model version to use gemini-2.0

update model version to 2.0

---

genai/video_generation/requirements.txt
genai/video_generation/test_video_generation_examples.py
genai/video_generation/videogen_with_img.py

New genai Veo sample showing how to generate videos from an image input

feat: Veo sample with image input

---

videointelligence/samples/analyze/beta_snippets.py
videointelligence/samples/analyze/beta_snippets_test.py

b/345843794
video_detect_text_beta
b/345843264
video_detect_text_gcs_beta
b/345843431
video_speech_transcription_gcs_beta
Skip failing tests in `beta_snippets_tests.py` to allow Kokoro CI to pass (see b/330632499)

chore(video): delete samples in beta_snippets.py

---

people-and-planet-ai/geospatial-classification/README.ipynb
people-and-planet-ai/geospatial-classification/e2e_test.py

Updates the accelerator away from no longer supported [K80](https://cloud.google.com/compute/docs/eol/k80-eol)
Fixes #13233 
Address build issues in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12827, 
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12572

fix(ppai): update accelorator, eos

---

functions/ocr/app/main.py
functions/ocr/app/noxfile_config.py
functions/ocr/app/requirements.txt

Fixes Internal: b/347350339
- Delete unused region tag 'message_validation_helper'
- Update dependencies to support Python 3.12+
- Update `noxfile_config.py` to allow testing on Python 3.9+
- Update code style and remove unneeded spacing

chore(functions): delete region tag and update sample for Python 3.9+

---

appengine/standard/endpoints-frameworks-v2/echo/app.yaml

chore(gae): delete invalid region tag 'env_vars'

---

genai/text_generation/thinking_textgen_with_txt.py

Update thinking model to use latest model name.

feat(genai): update thinking model name

---

genai/tools/test_tools_examples.py
genai/tools/tools_vais_with_txt.py

docs(genai): Add Grounding Sample for Vertex AI Search

---

.github/CODEOWNERS
.github/auto-label.yaml

Follow-up of [PR 13281](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/13281#issuecomment-2770011165)

chore(dns): remove entries in 'CODEOWNERS' and 'auto-label.yaml' for 'dns' product

---

genai/count_tokens/counttoken_compute_with_txt.py
genai/count_tokens/counttoken_resp_with_txt.py
genai/count_tokens/counttoken_with_txt.py
genai/count_tokens/counttoken_with_txt_vid.py

Remove duplicate/un-used region tags
Cleanup - b/413014256 (docs are also being updated to remove references these old region tags)

docs: region tags clean-up

---

discoveryengine/cancel_operation_sample.py
discoveryengine/operations_sample_test.py
discoveryengine/requirements.txt

https://cloud.google.com/generative-ai-app-builder/docs/long-running-operations

docs(discoveryengine): Add Cancel Operation Sample

---

genai/image_generation/imggen_mmflash_edit_img_with_txt_img.py
genai/image_generation/imggen_mmflash_txt_and_img_with_txt.py
genai/image_generation/imggen_mmflash_with_txt.py
genai/image_generation/noxfile_config.py
genai/image_generation/test_image_generation.py

feat(image-generation): Image generation using Gemini Flash

---

genai/image_generation/imggen_with_txt.py
genai/image_generation/test_image_generation.py

Create a new Imagen image generation sample with the Gen AI SDK

feat(genai): Add new sample for image gen

---

appengine/standard_python3/building-an-app/building-an-app-1/app.yaml
appengine/standard_python3/building-an-app/building-an-app-1/main.py

Update code samples to point to the latest python version (3.13)

Update code samples to point to the latest python version (3.13)

---

genai/thinking/noxfile_config.py
genai/thinking/requirements-test.txt
genai/thinking/requirements.txt
genai/thinking/test_thinking_examples.py
genai/thinking/thinking_budget_with_txt.py
genai/thinking/thinking_includethoughts_with_txt.py
genai/thinking/thinking_with_txt.py

- Created a new folder for thinking models
- Add new thinking_budget example
- Add new thinking include_thoughts example

feat(genai): Add thinking feature examples

---

genai/video_generation/videogen_with_img.py
genai/video_generation/videogen_with_txt.py

feat(genai): video model version update

---

generative_ai/embeddings/batch_example.py

Revert the change in generative_ai/embeddings/batch_example.py from https://github.com/GoogleCloudPlatform/python-docs-samples/pull/13388 because gemini-embedding-001 doesn't support batch_predict at the moment.

fix: Revert the change in generative_ai/embeddings/batch_example.py

---

genai/image_generation/imggen_with_txt.py

feat: update Imagen model version

---

run/mcp-server/.dockerignore
run/mcp-server/Dockerfile
run/mcp-server/README.md
run/mcp-server/pyproject.toml
run/mcp-server/server.py
run/mcp-server/test_server.py
run/mcp-server/uv.lock

Simple remote MCP server sample deployed to Cloud Run 🚀 ☁️ 
This accompanies a blog that will go live in the next day or two.

feat(run): add FastMCP MCP server sample

---

genai/tuning/tuning_job_create.py
genai/tuning/tuning_with_checkpoints_create.py

feat(genai): update tuning gemini 2.5 flash base model name

---

dataproc/snippets/submit_spark_job_to_driver_node_group_cluster.py
dataproc/snippets/submit_spark_job_to_driver_node_group_cluster_test.py

feat(dataproc): Add Spark Job to Cluster sample

---

dataproc/snippets/submit_spark_job_to_driver_node_group_cluster.py
dataproc/snippets/submit_spark_job_to_driver_node_group_cluster_test.py

Fixes #13459 #13423
This PR merges the approved changes into main.

feat(dataproc): Add Spark Job to Cluster sample (#13459)

---

alloydb/notebooks/embeddings_batch_processing.ipynb

chore: fix typo

---

genai/video_generation/test_video_generation_examples.py
genai/video_generation/videogen_with_first_last_frame.py
genai/video_generation/videogen_with_no_rewrite.py
genai/video_generation/videogen_with_vid.py

Add new genai code samples for veo 2 advanced control features

feat: veo samples for advanced control features

---

genai/batch_prediction/get_batch_job.py
genai/batch_prediction/get_batchprediction_job.py
genai/batch_prediction/test_batch_prediction_examples.py

Adds get_batch_job.py code sample.
Internal: b/432138567

feat(batch predition): Adds get_batch_prediction_job.py code sample

---

genai/video_generation/requirements.txt
genai/video_generation/videogen_with_img.py
genai/video_generation/videogen_with_txt.py

feat: update veo3 model version

---

genai/image_generation/imggen_with_txt.py

feat(genai): update Imagen 4 model

---

genai/image_generation/imggen_mmflash_edit_img_with_txt_img.py
genai/image_generation/imggen_mmflash_locale_aware_with_txt.py
genai/image_generation/imggen_mmflash_multiple_imgs_with_txt.py
genai/image_generation/imggen_mmflash_txt_and_img_with_txt.py
genai/image_generation/imggen_mmflash_with_txt.py
genai/image_generation/imggen_virtual_try_on_with_txt_img.py
genai/image_generation/test_image_generation.py
genai/image_generation/test_image_generation_mmflash.py

Update samples to latest Gemini Flash 2.0

feat(genai): Update samples to use Gemini 2.5 Flash MM

---

discoveryengine/standalone_apis_sample.py
discoveryengine/standalone_apis_sample_test.py

Reverts GoogleCloudPlatform/python-docs-samples#13244
Fixes b/415349583

revert: "docs: Remove Grounded Generation Samples"
